#
# Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
# Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
# "Sonatype" is a trademark of Sonatype, Inc.
#
# MTIQ Docker image:
# - To build locally:
# docker build --build-arg IQ_SERVER_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate \
# -Dexpression=project.version -q -DforceStdout) --tag sonatype.repo.sonatype.app/docker-all/mtiq/server:local-dev --file ./Dockerfile.fips .
#
# - To run locally:
# (Note: container must have access to your Postgres DB. This can be achieved by specifying a DB host of
# docker.for.mac.localhost (Docker Desktop) in your config, or specifying a Docker network with --net that both containers (this and Postgres) can use):
# docker run --rm -it -v /path/to/your/docker/config.yml:/etc/mtiq-server/config.yaml -p 8070:8070 -e "IS_MTIQ_BATCH=true" \
# -e "NXIQ_ENABLE_SSO_ONLY=false" -e "USING_DEFAULT_ENCRYPTION_KEY_STORE=true" -e "DELETE_BUILT_IN_ADMIN=false" \
# -e "NXIQ_ENABLE_LOCAL_JWK_PROVIDER=true" -e "FIPS_MODE_ENABLED=true" -e "AWS_REGION=us-east-1" sonatype.repo.sonatype.app/docker-all/mtiq/server:local-dev

ARG SONATYPE_PRIVATE_REGISTRY=sonatype.repo.sonatype.app/docker-all

FROM $SONATYPE_PRIVATE_REGISTRY/chainguard/wolfi-base AS builder

ARG IQ_SERVER_VERSION

# Prepare os dependencies to be copied to runtime stage
COPY ./package-copy.sh /tmp/
RUN /tmp/package-copy.sh curl tini jemalloc

RUN touch /tmp/empty.log \
  && mkdir -p /sonatype-work

# Include JNI lib (Copy to path that will end up in /usr/lib in final stage)
COPY target/libjemalloc-jni.so /tmp/package-content/usr/lib/libjemalloc-jni.so

# Include MTIQ server jar
COPY target/nexus-mtiq-server.jar /opt/sonatype/nexus-iq-server/nexus-mtiq-server.jar

############################
# Final stage
############################

FROM $SONATYPE_PRIVATE_REGISTRY/sonatype-infosec/jdk-fips:openjdk-17

# Copy prepared os dependencies content to its destination
COPY --from=builder /tmp/package-content /

# Copy assembly from builder (includes libjemalloc-jni.so)
COPY --from=builder --chown=65532:65532 /opt/sonatype/nexus-iq-server /opt/sonatype/nexus-iq-server

# Copy empty log file into clm-server log location
COPY --from=builder --chown=65532:65532 /tmp/empty.log /var/log/nexus-iq-server/clm-server.log.

# Copy SONATYPE_WORK from builder
COPY --from=builder --chown=65532:65532 /sonatype-work /sonatype-work

# This is where we will store persistent data
VOLUME /sonatype-work

# Expose the ports
EXPOSE 8070
EXPOSE 8071

WORKDIR /opt/sonatype/nexus-iq-server

# jemalloc profiling variables
ENV LD_PRELOAD="libjemalloc.so.2"
ENV MALLOC_CONF="prof:true,prof_active:false"

ENV JDK_JAVA_OPTIONS="${JDK_JAVA_OPTIONS} \
  -Dgit.without.shell=true \
  -Djava.util.prefs.userRoot=/sonatype-work/javaprefs \
  -Djava.library.path=/opt/sonatype/nexus-iq-server \
  -XX:+AlwaysPreTouch -XX:+CrashOnOutOfMemoryError -XshowSettings:vm"

LABEL vendor=Sonatype \
  maintainer="MTIQ Team <mtiq-dev@sonatype.com>" \
  com.sonatype.name="MTIQ Server Docker Image"

ENTRYPOINT ["tini", "--", "java", "-jar", "/opt/sonatype/nexus-iq-server/nexus-mtiq-server.jar"]

CMD ["server", "/etc/mtiq-server/config.yaml"]
