<!--

    Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
    Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
    "Sonatype" is a trademark of Sonatype, Inc.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sonatype.insight.brain</groupId>
    <artifactId>insight-brain</artifactId>
    <version>1.23.0-01</version>
  </parent>

  <artifactId>insight-brain-service</artifactId>
  <name>Insight Brain Service</name>

  <properties>
    <node.version>v0.12.4</node.version>
    <npm.version>2.13.2</npm.version>
    <freemarker.version>2.3.19</freemarker.version>
    <wro4j.version>1.8.0</wro4j.version>
    <licensing.version>1.4</licensing.version>
    <angularjs.version>1.4.8</angularjs.version>
    <jasmine.version>1.3.1.4</jasmine.version>
    <saga.version>1.5.2</saga.version>
    <jasmine.brain.id>test-brain-assets</jasmine.brain.id>
    <jasmine.cip.id>test-cip-assets</jasmine.cip.id>
    <jasmine.audit.id>test-audit-assets</jasmine.audit.id>
    <jasmine.version.graph.id>test-version-graph-assets</jasmine.version.graph.id>
    <jasmine.view.details.id>test-view-details-assets</jasmine.view.details.id>
    <grunt.task>build</grunt.task>
    <wro4j.brain.resources>${project.build.directory}/generated/assets/</wro4j.brain.resources>
    <wro4j.minimize>true</wro4j.minimize>
    <angular.debug>false</angular.debug>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </dependency>

    <dependency>
      <groupId>org.sonatype.sisu</groupId>
      <artifactId>sisu-guice</artifactId>
    </dependency>
    <dependency>
      <groupId>org.sonatype.sisu.inject</groupId>
      <artifactId>guice-multibindings</artifactId>
    </dependency>
    <dependency>
      <groupId>org.eclipse.sisu</groupId>
      <artifactId>org.eclipse.sisu.inject</artifactId>
      <exclusions>
        <exclusion>
          <!-- using aop version instead -->
          <groupId>org.sonatype.sisu</groupId>
          <artifactId>sisu-guice</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>javax.inject</groupId>
      <artifactId>javax.inject</artifactId>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-data</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-data</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-json-store</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-common</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-model</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-model-io</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-archive</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-client-utils</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.portal</groupId>
      <artifactId>insight-portal-mail</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.portal</groupId>
      <artifactId>insight-error-handling</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.portal</groupId>
      <artifactId>insight-jaxrs-utils</artifactId>
    </dependency>

    <dependency>
      <groupId>org.freemarker</groupId>
      <artifactId>freemarker</artifactId>
      <version>${freemarker.version}</version>
    </dependency>

    <!-- Dependencies for drools -->
    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>knowledge-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>drools-core</artifactId>
      <version>${drools.version}</version>
    </dependency>
    <dependency>
      <groupId>org.drools</groupId>
      <artifactId>drools-compiler</artifactId>
      <version>${drools.version}</version>
    </dependency>

    <dependency>
      <groupId>com.yammer.dropwizard</groupId>
      <artifactId>dropwizard-core</artifactId>
      <version>${dropwizard.version}</version>
      <exclusions>
        <exclusion>
          <!-- Conflicts with org.ow2.asm:asm-*:4.x used by enhanced matching. -->
          <groupId>asm</groupId>
          <artifactId>asm</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-utils</artifactId>
    </dependency>

    <dependency>
      <groupId>org.eclipse.birt.runtime</groupId>
      <artifactId>org.eclipse.birt.runtime</artifactId>
      <version>3.7.2.v20120214-1408</version>
      <exclusions>
        <exclusion>
          <groupId>commons-cli</groupId>
          <artifactId>commons-cli</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.milyn</groupId>
          <artifactId>flute</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime.3_7_1</groupId>
          <artifactId>org.apache.batik.pdf</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime.3_7_1</groupId>
          <artifactId>org.apache.commons.codec</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime.3_7_1</groupId>
          <artifactId>derby</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime.3_7_1</groupId>
          <artifactId>javax.wsdl</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime.3_7_1</groupId>
          <artifactId>org.apache.batik.util.gui</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime.3_7_1</groupId>
          <artifactId>org.eclipse.osgi.services</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime.3_7_1</groupId>
          <artifactId>org.eclipse.update.configurator</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime.3_7_1</groupId>
          <artifactId>org.eclipse.core.expressions</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime.3_7_1</groupId>
          <artifactId>org.eclipse.core.filesystem</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.core.resources</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.emf</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.emf.ecore.change</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.connectivity</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.connectivity.apache.derby</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.connectivity.apache.derby.dbdefinition</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.connectivity.oda.consumer</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.connectivity.oda.design</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.connectivity.oda.flatfile</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.connectivity.oda.profile</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.connectivity.dbdefinition.genericJDBC</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.connectivity.db.generic</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.connectivity.sqm.core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.connectivity.console.profile</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.hsqldb</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.hsqldb.dbdefinition</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.ibm.informix</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.ibm.informix.dbdefinition</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.ibm.db2.luw</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.ibm.db2.luw.dbdefinition</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.oda.ws</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.oda.xml</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.msft.sqlserver</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.msft.sqlserver.dbdefinition</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime.3_7_1</groupId>
          <artifactId>org.eclipse.datatools.enablement.mysql</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.mysql.dbdefinition</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.oracle</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.oracle.dbdefinition</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.postgresql</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.enablement.postgresql.dbdefinition</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.modelbase.dbdefinition</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.modelbase.derby</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.modelbase.sql</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.eclipse.birt.runtime</groupId>
          <artifactId>org.eclipse.datatools.modelbase.sql.query</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.hamcrest</groupId>
      <artifactId>hamcrest-library</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jvnet.mock-javamail</groupId>
      <artifactId>mock-javamail</artifactId>
      <version>1.9</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.yammer.dropwizard</groupId>
      <artifactId>dropwizard-testing</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>hds-mock-server</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.portal</groupId>
      <artifactId>insight-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.portal</groupId>
      <artifactId>insight-jaxrs-testing</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.clm</groupId>
      <artifactId>com.sonatype.clm.dto.model</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sun.jersey.contribs</groupId>
      <artifactId>jersey-multipart</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.licensing</groupId>
      <artifactId>license-bundle</artifactId>
      <version>${licensing.version}</version>
    </dependency>
    <dependency>
      <groupId>org.sonatype.aether</groupId>
      <artifactId>aether-util</artifactId>
    </dependency>

    <dependency>
      <groupId>org.apache.shiro</groupId>
      <artifactId>shiro-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.shiro</groupId>
      <artifactId>shiro-guice</artifactId>
      <exclusions>
        <exclusion>
          <!-- using sisu guice instead -->
          <groupId>com.google.inject</groupId>
          <artifactId>guice</artifactId>
        </exclusion>
        <exclusion>
          <!-- using sisu multibindings instead -->
          <groupId>com.google.inject.extensions</groupId>
          <artifactId>guice-multibindings</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <dependency>
      <groupId>com.sonatype.insight.portal</groupId>
      <artifactId>insight-license-model</artifactId>
    </dependency>

    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-ldap</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-ldap</artifactId>
      <classifier>tests</classifier>
    </dependency>
    <dependency>
      <groupId>org.apache.directory.server</groupId>
      <artifactId>apacheds-core-integ</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-math3</artifactId>
      <version>3.3</version>
    </dependency>
  </dependencies>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
      </resource>
      <resource>
        <directory>${project.build.directory}/generated</directory>
      </resource>
      <resource>
        <directory>src/main/filtered-resources</directory>
        <filtering>true</filtering>
      </resource>
      <resource>
        <directory>src/main/brain-client</directory>
        <filtering>true</filtering>
        <targetPath>${project.build.outputDirectory}/assets/policy/js/</targetPath>
      </resource>
      <resource>
        <directory>src/main/brain-client</directory>
        <filtering>true</filtering>
        <targetPath>${project.build.outputDirectory}/assets/assets/js/</targetPath>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.sonatype.plugins</groupId>
        <artifactId>sisu-maven-plugin</artifactId>
        <!-- Use 1.1 because: https://github.com/sonatype/insight-brain/commit/63133339 -->
        <version>1.1</version><!--$NO-MVN-MAN-VER$-->
        <executions>
          <execution>
            <id>index-service</id>
            <phase>process-classes</phase>
            <goals>
              <goal>index</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <argLine>-XX:MaxPermSize=144m</argLine>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.github.klieber</groupId>
        <artifactId>phantomjs-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>com.github.searls</groupId>
        <artifactId>jasmine-maven-plugin</artifactId>
        <version>${jasmine.version}</version>
        <extensions>true</extensions>
        <!-- Only the last execution of this plugin is subject to collection of coverage information, unfortunately. -->
        <executions>
          <execution>
            <id>${jasmine.cip.id}</id>
            <phase>test</phase>
            <goals>
              <goal>test</goal>
            </goals>
            <configuration>
              <preloadSources>
                <source>resources/assets/cip/cip-test-util.js</source>
                <include>frontend/lib/jquery/jquery.js</include>
                <include>frontend/lib/bootstrap/bootstrap-2.3.1.min.js</include>
                <include>frontend/lib/angular/angular.js</include>
                <include>frontend/lib/angular-${angularjs.version}/angular-route.js</include>
                <include>frontend/lib/angular-${angularjs.version}/angular-sanitize.js</include>
                <include>frontend/lib/angular-vs-repeat/src/angular-vs-repeat.js</include>
                <include>frontend/lib/angular-ui-router-0.2.15.min.js</include>
                <include>wro4j/cip/cip-loader.js</include>
              </preloadSources>
              <sourceIncludes>
                <include>brain-client/*.js</include>
                <include>wro4j/cip/**/*module.js</include>
                <include>wro4j/cip/*.js</include>
                <include>wro4j/cip/**/*.js</include>
                <include>wro4j/audit-report/cip/cip.vulnerability.editor/*module.js</include>
                <include>wro4j/audit-report/cip/cip.vulnerability.editor/*.js</include>
                <include>wro4j/audit-report/cip/vulnerability.details/*module.js</include>
                <include>wro4j/audit-report/cip/vulnerability.details/*.js</include>
                <include>frontend/utility/directives/utility.directives.module.js</include>
                <include>frontend/utility/directives/load.wrapper.directive.js</include>
                <include>frontend/utility/services/utility.services.module.js</include>
                <include>frontend/utility/services/unauthenticated.request.queue.service.js</include>
                <include>frontend/utility/services/login.modal.controller.js</include>
                <include>frontend/utility/services/login.modal.service.js</include>
                <include>frontend/util/AngularCommon.js</include>
                <include>frontend/util/CLMAppLocation.js</include>
                <include>frontend/util/CLMLocation.js</include>
                <include>frontend/util/HttpInterceptors.js</include>
                <include>frontend/lib/ui-bootstrap-tpls-0.13.4.min.js</include>
                <include>frontend/lib/datepicker/bootstrap-datepicker.js</include>
              </sourceIncludes>
              <sourceExcludes>
                <exclude>frontend/lib/bootstrap-sass-official/**/*.js</exclude>
              </sourceExcludes>
              <specIncludes>
                <include>frontend/SpecUtil.js</include>
                <include>frontend/**/lib/*.js</include>
                <include>frontend/**/*MockData.js</include>
                <include>resources/assets/cip/**/*.js</include>
                <include>resources/assets/**/cip*.js</include>
                <include>resources/assets/**/CIP*.js</include>
                <include>resources/assets/brain-client/*.js</include>
              </specIncludes>
              <junitXmlReportFileName>TEST-cip.xml</junitXmlReportFileName>
            </configuration>
          </execution>
          <execution>
            <id>${jasmine.audit.id}</id>
            <phase>test</phase>
            <goals>
              <goal>test</goal>
            </goals>
            <configuration>
              <preloadSources>
                <source>resources/assets/cip/cip-test-util.js</source>
                <include>frontend/lib/jquery/jquery.js</include>
                <include>frontend/lib/bootstrap/bootstrap-2.3.1.min.js</include>
                <include>frontend/lib/angular/angular.js</include>
                <include>frontend/lib/angular-${angularjs.version}/angular-route.js</include>
                <include>frontend/lib/angular-${angularjs.version}/angular-sanitize.js</include>
                <include>frontend/lib/angular-vs-repeat/src/angular-vs-repeat.js</include>
                <include>frontend/lib/angular-ui-router-0.2.15.min.js</include>
                <include>wro4j/cip/cip-loader.js</include>
              </preloadSources>
              <sourceIncludes>
                <include>brain-client/*.js</include>
                <include>wro4j/cip/**/*module.js</include>
                <include>wro4j/cip/**/*.js</include>
                <include>wro4j/version-graph/**/*app.js</include>
                <include>wro4j/version-graph/**/*module.js</include>
                <include>wro4j/version-graph/**/*.js</include>
                <include>wro4j/audit-report/**/*module.js</include>
                <include>wro4j/audit-report/**/*.js</include>
                <include>frontend/utility/directives/utility.directives.module.js</include>
                <include>frontend/utility/directives/load.wrapper.directive.js</include>
                <include>frontend/utility/services/utility.services.module.js</include>
                <include>frontend/utility/services/unauthenticated.request.queue.service.js</include>
                <include>frontend/utility/services/login.modal.controller.js</include>
                <include>frontend/utility/services/login.modal.service.js</include>
                <include>frontend/util/AngularCommon.js</include>
                <include>frontend/util/CLMAppLocation.js</include>
                <include>frontend/util/CLMLocation.js</include>
                <include>frontend/util/HttpInterceptors.js</include>
                <include>frontend/lib/ui-bootstrap-tpls-0.13.4.min.js</include>
                <include>frontend/lib/datepicker/bootstrap-datepicker.js</include>
              </sourceIncludes>
              <sourceExcludes>
                <exclude>frontend/lib/bootstrap-sass-official/**/*.js</exclude>
              </sourceExcludes>
              <specIncludes>
                <include>frontend/SpecUtil.js</include>
                <include>frontend/**/lib/*.js</include>
                <include>frontend/**/*MockData.js</include>
                <include>resources/assets/audit-report/*.js</include>
              </specIncludes>
              <junitXmlReportFileName>TEST-audit.xml</junitXmlReportFileName>
            </configuration>
          </execution>
          <execution>
            <id>${jasmine.brain.id}</id>
            <phase>test</phase>
            <goals>
              <goal>test</goal>
            </goals>
            <configuration>
              <preloadSources>
                <source>frontend/lib/jquery/jquery.js</source>
                <source>frontend/lib/bootstrap/bootstrap-2.3.1.min.js</source>
                <source>frontend/lib/angular/angular.js</source>
                <source>frontend/lib/angular-${angularjs.version}/angular-aria.js</source>
                <source>frontend/lib/angular-${angularjs.version}/angular-cookies.js</source>
                <source>frontend/lib/angular-${angularjs.version}/angular-route.js</source>
                <source>frontend/lib/angular-${angularjs.version}/angular-sanitize.js</source>
                <source>frontend/lib/angular-ui-router-0.2.15.min.js</source>
                <source>frontend/lib/angular-ui-utils-0.0.3.js</source>
                <source>frontend/lib/angular-vs-repeat/src/angular-vs-repeat.js</source>
                <source>frontend/lib/ui-bootstrap-tpls-0.13.4.min.js</source>
                <source>frontend/lib/X-editable/xeditable-0.1.8.min.js</source>
                <source>frontend/lib/ngUpload/ng-upload.js</source>
                <source>frontend/lib/d3/d3.js</source>
                <source>frontend/lib/fuse.js/src/fuse.js</source>
                <source>frontend/SpecUtil.js</source>
              </preloadSources>
              <sourceIncludes>
                <include>frontend/**/*.module.js</include>
                <include>frontend/**/*Module.js</include>
                <include>frontend/**/*.js</include>
              </sourceIncludes>
              <sourceExcludes>
                <exclude>frontend/lib/**/*.js</exclude>
                <exclude>frontend/brain-client/*.js</exclude>
                <exclude>frontend/version-graph/*.js</exclude>
                <exclude>frontend/cip/*.js</exclude>
                <exclude>frontend/policy/js/*.js</exclude>
              </sourceExcludes>
              <specIncludes>
                <include>frontend/**/*utils.js</include>
                <include>frontend/**/lib/*.js</include>
                <include>frontend/**/*MockData.js</include>
                <include>frontend/**/*.mock.data.js</include>
                <include>frontend/**/*-spec.js</include>
                <include>frontend/**/*.spec.js</include>
                <include>frontend/**/*Spec.js</include>
              </specIncludes>
              <specExcludes>
                <exclude>frontend/**/cip*.js</exclude>
                <exclude>frontend/**/CIP*.js</exclude>
                <exclude>frontend/brain-client/**/*.js</exclude>
                <exclude>frontend/version-graph/**/*.js</exclude>
              </specExcludes>
              <junitXmlReportFileName>TEST-server-new.xml</junitXmlReportFileName>
            </configuration>
          </execution>
          <execution>
            <id>${jasmine.version.graph.id}</id>
            <phase>test</phase>
            <goals>
              <goal>test</goal>
            </goals>
            <configuration>
              <sourceIncludes>
                <include>frontend/lib/jquery/jquery.js</include>
                <include>frontend/lib/angular/angular.js</include>
                <include>frontend/lib/angular-${angularjs.version}/angular-route.js</include>
                <include>brain-client/*.js</include>
                <include>wro4j/version-graph/protovis.min.js</include>
                <include>wro4j/version-graph/appcheck.js</include>
                <include>wro4j/version-graph/**/*.module.js</include>
                <include>wro4j/version-graph/**/*.app.js</include>
                <include>wro4j/version-graph/app/*.js</include>
                <include>wro4j/version-graph/version.graph/*.js</include>
                <include>frontend/ComponentDisplayModule.js</include>
              </sourceIncludes>
              <sourceExcludes>
                <exclude>wro4j/cip/**/*.js</exclude>
              </sourceExcludes>
              <specIncludes>
                <include>frontend/**/lib/*.js</include>
                <include>resources/assets/version-graph/VersionGraphSpec.js</include>
              </specIncludes>
            </configuration>
          </execution>
          <execution>
            <id>${jasmine.view.details.id}</id>
            <phase>test</phase>
            <goals>
              <goal>test</goal>
            </goals>
            <configuration>
              <sourceIncludes>
                <include>frontend/lib/jquery/jquery.js</include>
                <include>frontend/lib/angular/angular.js</include>
                <include>frontend/lib/angular-${angularjs.version}/angular-route.js</include>
                <include>brain-client/*.js</include>
                <include>wro4j/version-graph/viewdetails.js</include>
              </sourceIncludes>
              <specIncludes>
                <include>frontend/**/lib/*.js</include>
                <include>resources/assets/version-graph/ViewDetailsSpec.js</include>
              </specIncludes>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <jasmineTargetDir>${project.build.directory}${file.separator}jasmine-reports</jasmineTargetDir>
          <jsSrcDir>${project.basedir}/src/main</jsSrcDir>
          <jsTestSrcDir>${project.basedir}/src/test</jsTestSrcDir>
          <keepServerAlive>true</keepServerAlive>
          <webDriverClassName>org.openqa.selenium.phantomjs.PhantomJSDriver</webDriverClassName>
          <webDriverCapabilities>
            <capability>
              <name>phantomjs.binary.path</name>
              <value>${phantomjs.binary}</value>
            </capability>
          </webDriverCapabilities>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.github.timurstrekalov</groupId>
        <artifactId>saga-maven-plugin</artifactId>
        <version>${saga.version}</version>
        <executions>
          <execution>
            <id>jasmine-coverage</id>
            <phase>test</phase>
            <goals>
              <goal>coverage</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <baseDir>http://localhost:${jasmine.serverPort}</baseDir>
          <backgroundJavaScriptTimeout>1000</backgroundJavaScriptTimeout>
          <outputDir>${project.build.directory}/coverage</outputDir>
          <sortBy>file</sortBy>
          <noInstrumentPatterns>
            <pattern>.*/SpecUtil\.js</pattern>
            <pattern>.*/lib/.*\.js</pattern>
            <pattern>.*/.*MockData\.js</pattern>
            <pattern>.*/.*-spec\.js</pattern>
            <pattern>.*/.*Spec\.js</pattern>
          </noInstrumentPatterns>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <shadedArtifactAttached>true</shadedArtifactAttached>
              <shadedClassifierName>server</shadedClassifierName>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                    <exclude>META-INF/maven/**</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>*:org.eclipse.sisu.inject</artifact>
                  <excludes>
                    <!-- avoid conflict with same resource from BIRT -->
                    <exclude>plugin.xml</exclude>
                  </excludes>
                </filter>
                <filter>
                  <artifact>*:org.eclipse.birt.runtime</artifact>
                  <includes>
                    <include>*.xml</include>
                    <include>org/eclipse/**</include>
                    <include>javax/**</include>
                  </includes>
                </filter>
              </filters>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>com.sonatype.insight.brain.service.InsightBrainService</mainClass>
                  <manifestEntries>
                    <!-- Required by BIRT to discover the extensions we have shaded in -->
                    <Bundle-SymbolicName>${project.groupId}.server</Bundle-SymbolicName>
                  </manifestEntries>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/NOTICE</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/NOTICE.txt</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/LICENSE</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/LICENSE.txt</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/insight/configuration.properties</resource>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <version>1.0</version>
        <executions>
          <execution>
            <id>install-node-and-npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
              <nodeVersion>${node.version}</nodeVersion>
              <npmVersion>${npm.version}</npmVersion>
            </configuration>
          </execution>
          <execution>
            <id>npm-install</id>
            <goals>
              <goal>npm</goal>
            </goals>
          </execution>
          <execution>
            <id>bower-install</id>
            <goals>
              <goal>bower</goal>
            </goals>
          </execution>
          <execution>
            <id>grunt-build</id>
            <goals>
              <goal>grunt</goal>
            </goals>
            <configuration>
              <srcdir>${basedir}/src/main/frontend</srcdir>
              <arguments>${grunt.task}</arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>ro.isdc.wro4j</groupId>
        <artifactId>wro4j-maven-plugin</artifactId>
        <version>${wro4j.version}</version>
        <executions>
          <execution>
            <id>external-libraries</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <targetGroups>external</targetGroups>
              <jsDestinationFolder>${wro4j.brain.resources}assets/js/</jsDestinationFolder>
            </configuration>
          </execution>
          <execution>
            <id>cip-loader</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <targetGroups>cip-loader</targetGroups>
              <cssDestinationFolder>${wro4j.brain.resources}policy/css/</cssDestinationFolder>
              <jsDestinationFolder>${wro4j.brain.resources}policy/js/</jsDestinationFolder>
            </configuration>
          </execution>
          <execution>
            <id>css-cip</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <targetGroups>cip</targetGroups>
              <cssDestinationFolder>${wro4j.brain.resources}cip/</cssDestinationFolder>
              <jsDestinationFolder>${wro4j.brain.resources}cip/</jsDestinationFolder>
            </configuration>
          </execution>
          <execution>
            <id>version-graph</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <targetGroups>version.graph.app,viewdetails</targetGroups>
              <cssDestinationFolder>${wro4j.brain.resources}version-graph/</cssDestinationFolder>
              <jsDestinationFolder>${wro4j.brain.resources}version-graph/</jsDestinationFolder>
            </configuration>
          </execution>
          <execution>
            <id>audit-report</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <targetGroups>audit-report</targetGroups>
              <cssDestinationFolder>${wro4j.brain.resources}audit-report/</cssDestinationFolder>
              <jsDestinationFolder>${wro4j.brain.resources}audit-report/</jsDestinationFolder>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <minimize>${wro4j.minimize}</minimize>
          <wroFile>${basedir}/wro.xml</wroFile>
          <parallelProcessing>true</parallelProcessing>
          <extraConfigFile>${basedir}/wro.properties</extraConfigFile>
          <wroManagerFactory>ro.isdc.wro.maven.plugin.manager.factory.ConfigurableWroManagerFactory</wroManagerFactory>
          <ignoreMissingResources>false</ignoreMissingResources>
          <contextFolder>${basedir}/src/main/</contextFolder>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>test-jar</goal>
            </goals>
            <configuration>
              <includes>
                <include>**/PortAllocator*</include>
                <include>**/AbstractBrainServiceTest*</include>
                <include>**/InsightMockServerRule*</include>
                <include>**/TestInsightBrainService*</include>
                <include>**/TestInsightBrainServiceRule*</include>
                <include>**/TestCLMServer*</include>
                <include>**/AbstractResourceTest*</include>
                <include>**/TestLicenseFingerprinter*</include>
                <include>**/TestProductLicenseManager*</include>
                <include>**/productlicense/license.lic</include>
                <include>**/SlowMoFilter*</include>
                <include>**/TemporaryEntity*</include>
                <include>**/HttpRequest*</include>
                <include>**/HttpResponse*</include>
              </includes>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>

    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.eclipse.m2e</groupId>
          <artifactId>lifecycle-mapping</artifactId>
          <version>1.0.0</version>
          <configuration>
            <lifecycleMappingMetadata>
              <pluginExecutions>
                <pluginExecution>
                  <pluginExecutionFilter>
                    <groupId>com.github.searls</groupId>
                    <artifactId>jasmine-maven-plugin</artifactId>
                    <versionRange>[1.2.0.0,)</versionRange>
                    <goals>
                      <goal>test</goal>
                      <goal>testResources</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <ignore />
                  </action>
                </pluginExecution>
                <pluginExecution>
                  <pluginExecutionFilter>
                    <groupId>org.sonatype.plugins</groupId>
                    <artifactId>sisu-maven-plugin</artifactId>
                    <versionRange>[1.0,)</versionRange>
                    <goals>
                      <goal>index</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <ignore />
                  </action>
                </pluginExecution>
                <pluginExecution>
                  <pluginExecutionFilter>
                    <groupId>com.github.klieber</groupId>
                    <artifactId>phantomjs-maven-plugin</artifactId>
                    <versionRange>[0.1,)</versionRange>
                    <goals>
                      <goal>install</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <ignore />
                  </action>
                </pluginExecution>
                <pluginExecution>
                  <pluginExecutionFilter>
                   <groupId>com.github.eirslett</groupId>
                    <artifactId>frontend-maven-plugin</artifactId>
                    <versionRange>[0,)</versionRange>
                    <goals>
                      <goal>bower</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <ignore />
                  </action>
                </pluginExecution>
              </pluginExecutions>
            </lifecycleMappingMetadata>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <profiles>
    <!--
      To execute just the Jasmine tests run mvn phantomjs:install jasmine:test -P <test profile>
      E.g. mvn phantomjs:install jasmine:test -P test-brain
    -->
    <profile>
      <id>test-cip</id>
      <properties>
        <jasmine.cip.id>default-cli</jasmine.cip.id>
      </properties>
    </profile>
    <profile>
      <id>test-audit</id>
      <properties>
        <jasmine.audit.id>default-cli</jasmine.audit.id>
      </properties>
    </profile>
    <profile>
      <id>test-brain</id>
      <properties>
        <jasmine.brain.id>default-cli</jasmine.brain.id>
      </properties>
    </profile>
    <profile>
      <id>test-version-graph</id>
      <properties>
        <jasmine.version.graph.id>default-cli</jasmine.version.graph.id>
      </properties>
    </profile>
    <profile>
      <id>test-view-details</id>
      <properties>
        <jasmine.view.details.id>default-cli</jasmine.view.details.id>
      </properties>
    </profile>
    <profile>
      <id>m2e</id>
      <activation>
        <property>
          <name>m2e.version</name>
        </property>
      </activation>
      <properties>
        <angular.debug>true</angular.debug>
        <grunt.task>m2e</grunt.task>
        <wro4j.minimize>false</wro4j.minimize>
        <wro4j.brain.resources>${project.build.directory}/classes/assets/</wro4j.brain.resources>
      </properties>
    </profile>
    <profile>
      <id>idea</id>
      <properties>
        <wro4j.minimize>false</wro4j.minimize>
      </properties>
    </profile>
    <profile>
      <id>obfuscate</id>
      <activation>
        <property>
          <name>!skip-obfuscate</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.wvengen</groupId>
            <artifactId>proguard-maven-plugin</artifactId>
            <configuration>
              <injar>${project.build.finalName}-server.jar</injar>
              <includeDependency>false</includeDependency>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>seed-map</id>
                <phase>package</phase>
                <goals>
                  <goal>attach-artifact</goal>
                </goals>
                <configuration>
                  <artifacts>
                    <artifact>
                      <file>${project.build.directory}/proguard_seeds.txt</file>
                      <classifier>seeds</classifier>
                      <type>txt</type>
                    </artifact>
                    <artifact>
                      <file>${project.build.directory}/proguard_map.txt</file>
                      <classifier>map</classifier>
                      <type>txt</type>
                    </artifact>
                  </artifacts>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>test-only-properties</id>
      <activation>
        <property>
          <name>!build.number</name>
        </property>
      </activation>
      <properties>
        <build.number>build-number</build.number>
      </properties>
    </profile>
    <profile>
      <id>clean-node</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-clean-plugin</artifactId>
            <configuration>
              <filesets>
                <fileset>
                  <directory>node</directory>
                </fileset>
                <fileset>
                  <directory>node_modules</directory>
                </fileset>
              </filesets>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
