-repackageclasses zz

-dontusemixedcaseclassnames

-dontoptimize
-dontshrink
-dontnote

-dontwarn ch.qos.logback.**
-dontwarn com.google.**
-dontwarn com.fasterxml.**
-dontwarn com.sun.**
-dontwarn com.thoughtworks.xstream.**
-dontwarn de.schlichtherle.**
-dontwarn freemarker.**
-dontwarn javax.**
-dontwarn org.**

# exclude anything not directly related to scanning from obfuscation
-keep class !com.sonatype.insight.scan.**,!org.objectweb.** { *; }

# DTOs used by XStream to build the scan report XML
-keepclassmembers public class com.sonatype.insight.scan.model.* { *; }

-renamesourcefileattribute SourceFile
-keepattributes *Annotation*,Exceptions,InnerClasses,EnclosingMethod,Signature,SourceFile,LineNumberTable

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

