/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
package com.sonatype.insight.brain.service.modules;

import com.sonatype.insight.brain.AsyncEventBusProvider;
import com.sonatype.insight.brain.api.v2.service.ApiConfigurationService;
import com.sonatype.insight.brain.artifactory.ArtifactoryClientFactory;
import com.sonatype.insight.brain.audit.AuditFilter;
import com.sonatype.insight.brain.audit.AuditRecorder;
import com.sonatype.insight.brain.audit.AuditService;
import com.sonatype.insight.brain.audit.AuditSessionListener;
import com.sonatype.insight.brain.audit.DefaultAuditLogFilesProvider;
import com.sonatype.insight.brain.aws.credentials.DefaultInsightAwsCredentialProvider;
import com.sonatype.insight.brain.aws.s3.S3AsyncClientProvider;
import com.sonatype.insight.brain.aws.s3.S3ClientProvider;
import com.sonatype.insight.brain.backup.DbBackupTask;
import com.sonatype.insight.brain.callflow.ComponentReachabilityService;
import com.sonatype.insight.brain.callflow.PolicyViolationReachabilityService;
import com.sonatype.insight.brain.concurrent.PerpetualLockManager;
import com.sonatype.insight.brain.configuration.AutomaticApplicationsConfigurationService;
import com.sonatype.insight.brain.configuration.AutomaticSourceControlConfigurationService;
import com.sonatype.insight.brain.configuration.SystemNoticeService;
import com.sonatype.insight.brain.configuration.ldap.LdapRealm;
import com.sonatype.insight.brain.configuration.ldap.LdapService;
import com.sonatype.insight.brain.configuration.saml.SamlConfigurationService;
import com.sonatype.insight.brain.container.images.ContainerImageReportService;
import com.sonatype.insight.brain.cpematching.CpeMatchingConfigurationService;
import com.sonatype.insight.brain.dataaccess.search.DefaultSearchIndexManager;
import com.sonatype.insight.brain.dataaccess.search.SearchIndexManager;
import com.sonatype.insight.brain.developer.integrationdashboard.ApplicationCountHistoryService;
import com.sonatype.insight.brain.developer.integrationdashboard.DeveloperEnablementService;
import com.sonatype.insight.brain.developer.integrationdashboard.IntegrationService;
import com.sonatype.insight.brain.developer.integrationdashboard.ScmStatService;
import com.sonatype.insight.brain.development.prioritization.DevelopmentPrioritiesReportService;
import com.sonatype.insight.brain.development.prioritization.DevelopmentPrioritiesService;
import com.sonatype.insight.brain.development.prioritization.DevelopmentPrioritiesUtilsService;
import com.sonatype.insight.brain.development.prioritization.DevelopmentPrioritizationRemediationService;
import com.sonatype.insight.brain.enterprise.reporting.EnterpriseReportingService;
import com.sonatype.insight.brain.eventbus.AsyncEventBus;
import com.sonatype.insight.brain.filter.ThrowableHandler;
import com.sonatype.insight.brain.filter.UserFilterPruner;
import com.sonatype.insight.brain.filter.UserFilterService;
import com.sonatype.insight.brain.firewall.FirewallRedirectFilter;
import com.sonatype.insight.brain.innersource.InnerSourceService;
import com.sonatype.insight.brain.jaxrs.CSVMessageBodyWriter;
import com.sonatype.insight.brain.jira.JiraClientFactory;
import com.sonatype.insight.brain.jira.JiraPolicyAlertNotifier;
import com.sonatype.insight.brain.jira.JiraService;
import com.sonatype.insight.brain.label.ComponentLabelService;
import com.sonatype.insight.brain.label.LabelService;
import com.sonatype.insight.brain.labs.LabsService;
import com.sonatype.insight.brain.landing.IndexCacheControlFilter;
import com.sonatype.insight.brain.landing.LandingService;
import com.sonatype.insight.brain.license.DefaultLicenseNameProvider;
import com.sonatype.insight.brain.license.LicenseNameProvider;
import com.sonatype.insight.brain.license.LicenseOverrideService;
import com.sonatype.insight.brain.license.LicenseThreatGroupService;
import com.sonatype.insight.brain.malware.defense.MalwareDefenseTelemetryMetrics;
import com.sonatype.insight.brain.malware.defense.changedetection.ComponentChangeDetectionProcessor;
import com.sonatype.insight.brain.malware.defense.changedetection.ComponentChangeDetectionTask;
import com.sonatype.insight.brain.metrics.PolicyEvaluateServiceMetrics;
import com.sonatype.insight.brain.owner.OwnerService;
import com.sonatype.insight.brain.product.license.CLMFeature;
import com.sonatype.insight.brain.product.license.CLMLicenseManager;
import com.sonatype.insight.brain.product.license.DatabasePreferencesFactory;
import com.sonatype.insight.brain.product.license.FirewallFeature;
import com.sonatype.insight.brain.product.license.FirewallReleaseIntegrityLicenseListener;
import com.sonatype.insight.brain.product.license.LicenseAwareContainerDynamicFeature;
import com.sonatype.insight.brain.product.license.LicensedConditionTypesListener;
import com.sonatype.insight.brain.product.license.ProductLicenseDetailsCache;
import com.sonatype.insight.brain.product.license.ProductLicenseService;
import com.sonatype.insight.brain.product.notifications.HdsProductNotificationService;
import com.sonatype.insight.brain.product.notifications.ProductNotificationService;
import com.sonatype.insight.brain.proprietary.ProprietaryConfigService;
import com.sonatype.insight.brain.releasegraph.ReleaseGraphCacheLoader;
import com.sonatype.insight.brain.releasegraph.ReleaseGraphCacheProvider;
import com.sonatype.insight.brain.releasegraph.ReleaseGraphService;
import com.sonatype.insight.brain.releasegraph.ReleaseGraphTask;
import com.sonatype.insight.brain.releasegraph.ReportItemCacheLoader;
import com.sonatype.insight.brain.report.ApplicationReportPersistenceService;
import com.sonatype.insight.brain.report.ApplicationReportPersistenceServiceProvider;
import com.sonatype.insight.brain.report.FileApplicationReportPersistenceService;
import com.sonatype.insight.brain.report.HybridApplicationReportPersistenceService;
import com.sonatype.insight.brain.report.ReportDataReader;
import com.sonatype.insight.brain.report.ReportDataStore;
import com.sonatype.insight.brain.report.ReportDiskSaver;
import com.sonatype.insight.brain.report.ReportPurger;
import com.sonatype.insight.brain.report.ReportService;
import com.sonatype.insight.brain.report.RepositoryMatcher;
import com.sonatype.insight.brain.report.S3ApplicationReportPersistenceService;
import com.sonatype.insight.brain.report.pdf.PdfGeneratorService;
import com.sonatype.insight.brain.roi.RoiConfigurationService;
import com.sonatype.insight.brain.sbom.PendingSbomMetadataCleaner;
import com.sonatype.insight.brain.sbom.SbomResultsMerger;
import com.sonatype.insight.brain.sbom.applications.SbomApplicationsService;
import com.sonatype.insight.brain.sbom.components.SbomComponentsService;
import com.sonatype.insight.brain.sbom.dashboard.SbomDashboardService;
import com.sonatype.insight.brain.sbom.datastore.FileSbomPersistenceService;
import com.sonatype.insight.brain.sbom.datastore.HybridSbomPersistenceService;
import com.sonatype.insight.brain.sbom.datastore.S3SbomPersistenceService;
import com.sonatype.insight.brain.sbom.datastore.SbomPersistenceService;
import com.sonatype.insight.brain.sbom.datastore.SbomPersistenceServiceProvider;
import com.sonatype.insight.brain.sbom.export.CycloneDxToCycloneDxExporter;
import com.sonatype.insight.brain.sbom.export.CycloneDxToPdfExporter;
import com.sonatype.insight.brain.sbom.export.CycloneDxToSpdxExporter;
import com.sonatype.insight.brain.sbom.export.SbomExporterProvider;
import com.sonatype.insight.brain.sbom.export.SpdxToCycloneDxExporter;
import com.sonatype.insight.brain.sbom.export.SpdxToPdfExporter;
import com.sonatype.insight.brain.sbom.export.SpdxToSpdxExporter;
import com.sonatype.insight.brain.sbom.ingestion.SbomImportService;
import com.sonatype.insight.brain.sbom.ingestion.SbomScanEvaluator;
import com.sonatype.insight.brain.sbom.license.ThirdPartyComponentLicenseResolutionService;
import com.sonatype.insight.brain.sbom.policy.SbomPolicyService;
import com.sonatype.insight.brain.sbom.utils.SbomFileDetector;
import com.sonatype.insight.brain.sbom.utils.SbomMetadataUtils;
import com.sonatype.insight.brain.sbom.vulnerabilityanalysis.VulnerabilityAnalysisReferenceDataService;
import com.sonatype.insight.brain.scale.HeartbeatPartitionManager;
import com.sonatype.insight.brain.scan.PersistedScanTicketCleaner;
import com.sonatype.insight.brain.scan.ScanService;
import com.sonatype.insight.brain.scan.Scanner;
import com.sonatype.insight.brain.scan.datastore.FileScanPersistenceService;
import com.sonatype.insight.brain.scan.datastore.HybridScanPersistenceService;
import com.sonatype.insight.brain.scan.datastore.S3ScanPersistenceService;
import com.sonatype.insight.brain.scan.datastore.ScanPersistenceService;
import com.sonatype.insight.brain.scan.datastore.ScanPersistenceServiceProvider;
import com.sonatype.insight.brain.scan.matcher.firewall.NpmPathnameParser;
import com.sonatype.insight.brain.scan.matcher.firewall.RepositoryPathnameParser;
import com.sonatype.insight.brain.scheduler.GuiceAwareJobFactory;
import com.sonatype.insight.brain.scheduler.QuartzJobSchedulingService;
import com.sonatype.insight.brain.scheduler.QuartzTriggerListener;
import com.sonatype.insight.brain.search.AdvancedSearchService;
import com.sonatype.insight.brain.search.ConversionHelper;
import com.sonatype.insight.brain.search.SuggestionIndexCleaner;
import com.sonatype.insight.brain.search.export.LifecycleSearchRowFactory;
import com.sonatype.insight.brain.search.export.SbomSearchRowFactory;
import com.sonatype.insight.brain.search.index.IndexCreationScheduler;
import com.sonatype.insight.brain.search.index.IndexService;
import com.sonatype.insight.brain.search.index.VulnerabilityDescriptionFetcher;
import com.sonatype.insight.brain.search.lucene.DocumentBuilderHelper;
import com.sonatype.insight.brain.search.lucene.LuceneComponents;
import com.sonatype.insight.brain.search.query.SearchService;
import com.sonatype.insight.brain.security.CipherFactory;
import com.sonatype.insight.brain.service.BaseUrl;
import com.sonatype.insight.brain.service.BaseUrlFilter;
import com.sonatype.insight.brain.service.BaseUrlProvider;
import com.sonatype.insight.brain.service.Configuration;
import com.sonatype.insight.brain.service.CopyStorageService;
import com.sonatype.insight.brain.service.CspFrameHeaderFilter;
import com.sonatype.insight.brain.service.CopyStorageTask;
import com.sonatype.insight.brain.service.ErrorResponseGenerator;
import com.sonatype.insight.brain.service.ExternalTelemetryService;
import com.sonatype.insight.brain.service.ServerHeaderFilter;
import com.sonatype.insight.brain.service.InsightProxy;
import com.sonatype.insight.brain.service.InsightWork;
import com.sonatype.insight.brain.service.ShiroSessionTimeoutHandler;
import com.sonatype.insight.brain.shutdown.ShutdownHandler;
import com.sonatype.insight.brain.shutdown.ShutdownTask;
import com.sonatype.insight.brain.solution.SolutionResolver;
import com.sonatype.insight.brain.solution.SolutionUrlResolver;
import com.sonatype.insight.brain.sourcecontrol.SourceControlDataService;
import com.sonatype.insight.brain.sourcecontrol.SourceControlLoadBalancer;
import com.sonatype.insight.brain.sourcecontrol.SourceControlPullRequestService;
import com.sonatype.insight.brain.sourcecontrol.SourceControlRepositoryUtils;
import com.sonatype.insight.brain.sourcecontrol.SourceControlUtils;
import com.sonatype.insight.brain.successmetrics.PolicyViolationAggregationService;
import com.sonatype.insight.brain.successmetrics.SuccessMetricsPurger;
import com.sonatype.insight.brain.successmetrics.SuccessMetricsReportDataService;
import com.sonatype.insight.brain.successmetrics.SuccessMetricsReportService;
import com.sonatype.insight.brain.successmetrics.SuccessMetricsService;
import com.sonatype.insight.brain.support.FeaturePropertiesInfo;
import com.sonatype.insight.brain.support.JmxInfo;
import com.sonatype.insight.brain.support.SupportService;
import com.sonatype.insight.brain.tag.TagService;
import com.sonatype.insight.brain.thirdparty.DuplicateAwareThirdPartyFileCoordinatePersister;
import com.sonatype.insight.brain.thirdparty.ThirdPartyComponentDAO;
import com.sonatype.insight.brain.thirdparty.ThirdPartyDataService;
import com.sonatype.insight.brain.thirdparty.ThirdPartyPersistenceService;
import com.sonatype.insight.brain.thirdparty.ThirdPartyResultHandlerFactory;
import com.sonatype.insight.brain.thirdparty.ThirdPartyScanResultsProcessor;
import com.sonatype.insight.brain.utils.IdUtils;
import com.sonatype.insight.brain.utils.NgUploadResponseGenerator;
import com.sonatype.insight.brain.vulnerability.SecurityVulnerabilityDataService;
import com.sonatype.insight.brain.vulnerability.SecurityVulnerabilityOverrideService;
import com.sonatype.insight.brain.webhook.ApplicationEvaluationEventService;
import com.sonatype.insight.brain.webhook.LicenseOverrideEventService;
import com.sonatype.insight.brain.webhook.ManagementEventService;
import com.sonatype.insight.brain.webhook.OrganizationApplicationManagementEventService;
import com.sonatype.insight.brain.webhook.OwnerDTOUtil;
import com.sonatype.insight.brain.webhook.PolicyAlertEventService;
import com.sonatype.insight.brain.webhook.RequestPolicyWaiverEventService;
import com.sonatype.insight.brain.webhook.SecurityVulnerabilityOverrideEventService;
import com.sonatype.insight.brain.webhook.WebhookClientUtil;
import com.sonatype.insight.brain.webhook.WebhookDispatcher;
import com.sonatype.insight.brain.zscaler.ApiZScalerConfigurationService;
import com.sonatype.insight.brain.zscaler.ApiZScalerService;
import com.sonatype.insight.brain.zscaler.HDSMaliciousUrlFetcher;
import com.sonatype.insight.brain.zscaler.ZScalerClient;
import com.sonatype.insight.brain.zscaler.ZScalerConfigTelemetryCollector;
import com.sonatype.insight.brain.zscaler.ZScalerMaliciousUrlFetcher;
import com.sonatype.insight.brain.zscaler.ZScalerMetricsTelemetryCollector;
import com.sonatype.insight.brain.zscaler.ZScalerUpdater;
import com.sonatype.insight.brain.common.io.FileCleaner;
import com.sonatype.insight.brain.security.PasswordHandler;
import com.sonatype.insight.brain.telemetry.TelemetryUtils;
import com.sonatype.insight.brain.tenancy.TenantUtil;
import com.sonatype.insight.brain.api.v2.service.ApiComponentChangeDetectionService;
import com.sonatype.insight.brain.api.v2.service.ApiComponentDetailsServiceV2;
import com.sonatype.insight.brain.api.v2.service.ApiArtifactoryConnectionService;
import com.sonatype.insight.brain.api.v2.service.ApiComponentRemediationService;
import com.sonatype.insight.brain.api.v2.service.ApiReportDataServiceV2;
import com.sonatype.insight.brain.dataaccess.component.ComponentLoaderFactory;
import com.sonatype.insight.brain.dataaccess.configuration.saml.SamlConfigurationAdapter;
import com.sonatype.insight.brain.support.ConfigurationInfo;
import com.sonatype.insight.brain.support.SourceControlConfigurationInfo;
import com.sonatype.insight.brain.report.ReportDownloader;
import com.sonatype.insight.jaxrs.error.JaxRsExceptionMapper;
import org.apache.shiro.guice.web.GuiceShiroFilter;
import org.apache.shiro.web.config.ShiroFilterConfiguration;
import org.sonatype.plexus.components.cipher.PlexusCipher;

import com.google.inject.AbstractModule;
import com.google.inject.Provides;
import com.google.inject.Singleton;
import com.google.inject.name.Named;
import software.amazon.awssdk.services.s3.S3AsyncClient;

/**
 * Guice module providing explicit bindings for CoreService components. This replaces Sisu's automatic @Named component
 * discovery.
 */
public class CoreServiceModule
    extends AbstractModule
{
  @Override
  protected void configure() {
    // Utility classes used across many modules
    bind(FileCleaner.class);
    bind(PasswordHandler.class);
    bind(TelemetryUtils.class);
    bind(TenantUtil.class);

    // Additional core service bindings for requireExplicitBindings
    bind(ApiComponentChangeDetectionService.class);
    bind(ApiComponentDetailsServiceV2.class);
    bind(ApiArtifactoryConnectionService.class);
    bind(ApiComponentRemediationService.class);
    bind(ApiReportDataServiceV2.class);
    bind(ComponentLoaderFactory.class);
    bind(SamlConfigurationAdapter.class);
    bind(ConfigurationInfo.class);
    bind(SourceControlConfigurationInfo.class);
    bind(ReportDownloader.class);
    bind(JaxRsExceptionMapper.class);

    // Additional bindings needed at runtime
    bind(com.sonatype.insight.brain.scan.ScanTask.class);
    bind(com.sonatype.insight.brain.developer.integrationdashboard.CIEvaluationStatService.class);
    bind(com.sonatype.insight.brain.developer.integrationdashboard.DateTimeService.class);
    bind(com.sonatype.insight.brain.support.DbData.class);
    bind(com.sonatype.insight.brain.support.DbDiagnostics.class);
    bind(com.sonatype.insight.brain.support.SystemInfo.class);
    bind(com.sonatype.insight.jaxrs.error.JavaLangErrorHandler.class);

    // External scan dependency bindings
    bind(com.sonatype.insight.scan.anon.Anonymizer.class);

    bind(AdvancedSearchService.class);
    bind(ApiConfigurationService.class).in(Singleton.class);
    bind(ApiZScalerConfigurationService.class).in(Singleton.class);
    bind(ApiZScalerService.class).in(Singleton.class);
    bind(ApplicationCountHistoryService.class);
    bind(ApplicationEvaluationEventService.class);
    bind(ApplicationReportPersistenceService.class).toProvider(ApplicationReportPersistenceServiceProvider.class);
    bind(ApplicationReportPersistenceServiceProvider.class);
    bind(ArtifactoryClientFactory.class);
    bind(AsyncEventBusProvider.class);
    bind(AsyncEventBus.class).toProvider(AsyncEventBusProvider.class);
    bind(AuditFilter.class);
    bind(AuditRecorder.class);
    bind(AuditService.class);
    bind(AuditSessionListener.class);
    bind(AutomaticApplicationsConfigurationService.class);
    bind(AutomaticSourceControlConfigurationService.class);
    bind(BaseUrl.class);
    bind(BaseUrlProvider.class).to(Configuration.class);
    bind(CLMFeature.class);
    bind(CLMLicenseManager.class);
    bind(CSVMessageBodyWriter.class);
    bind(ComponentChangeDetectionProcessor.class);
    bind(ComponentChangeDetectionTask.class);
    bind(ComponentLabelService.class);
    bind(ComponentReachabilityService.class);
    bind(Configuration.class);
    bind(ContainerImageReportService.class);
    bind(ConversionHelper.class);
    bind(CopyStorageService.class);
    bind(CopyStorageTask.class);
    bind(CpeMatchingConfigurationService.class);
    bind(CycloneDxToCycloneDxExporter.class);
    bind(CycloneDxToPdfExporter.class);
    bind(CycloneDxToSpdxExporter.class);
    bind(DatabasePreferencesFactory.class);
    bind(DbBackupTask.class);
    bind(DefaultAuditLogFilesProvider.class);
    bind(DefaultInsightAwsCredentialProvider.class);
    bind(DefaultLicenseNameProvider.class);
    bind(DeveloperEnablementService.class);
    bind(DevelopmentPrioritiesReportService.class);
    bind(DevelopmentPrioritiesService.class);
    bind(DevelopmentPrioritiesUtilsService.class);
    bind(DevelopmentPrioritizationRemediationService.class);
    bind(DocumentBuilderHelper.class);
    bind(DuplicateAwareThirdPartyFileCoordinatePersister.class);
    bind(EnterpriseReportingService.class);
    bind(ErrorResponseGenerator.class);
    bind(ExternalTelemetryService.class);
    bind(BaseUrlFilter.class);
    bind(CspFrameHeaderFilter.class);
    bind(FirewallRedirectFilter.class);
    bind(GuiceShiroFilter.class);
    bind(IndexCacheControlFilter.class);
    bind(ServerHeaderFilter.class);
    bind(ShiroFilterConfiguration.class);
    bind(FeaturePropertiesInfo.class);
    bind(FileApplicationReportPersistenceService.class);
    bind(FileSbomPersistenceService.class);
    bind(FileScanPersistenceService.class);
    bind(FirewallFeature.class);
    bind(FirewallReleaseIntegrityLicenseListener.class);
    bind(HDSMaliciousUrlFetcher.class);
    bind(HdsProductNotificationService.class);
    bind(HeartbeatPartitionManager.class);
    bind(HybridApplicationReportPersistenceService.class);
    bind(HybridSbomPersistenceService.class);
    bind(HybridScanPersistenceService.class);
    bind(IdUtils.class);
    bind(IndexCreationScheduler.class);
    bind(IndexService.class);
    bind(InnerSourceService.class);
    bind(InsightProxy.class);
    bind(InsightWork.class);
    bind(IntegrationService.class);
    bind(JiraClientFactory.class);
    bind(JiraPolicyAlertNotifier.class);
    bind(JiraService.class);
    bind(JmxInfo.class);
    bind(LabelService.class);
    bind(LabsService.class);
    bind(LandingService.class);
    bind(LdapRealm.class);
    bind(LdapService.class);
    bind(LicenseAwareContainerDynamicFeature.class);
    bind(LicenseNameProvider.class).to(DefaultLicenseNameProvider.class);
    bind(LicenseOverrideEventService.class);
    bind(LicenseOverrideService.class);
    bind(LicenseThreatGroupService.class);
    bind(LicensedConditionTypesListener.class);
    bind(LifecycleSearchRowFactory.class);
    bind(LuceneComponents.class);
    bind(MalwareDefenseTelemetryMetrics.class);
    bind(ManagementEventService.class);
    bind(NgUploadResponseGenerator.class);
    bind(NpmPathnameParser.class);
    bind(OrganizationApplicationManagementEventService.class);
    bind(OwnerDTOUtil.class);
    bind(OwnerService.class);
    bind(PdfGeneratorService.class);
    bind(PendingSbomMetadataCleaner.class);
    bind(PerpetualLockManager.class);
    bind(PersistedScanTicketCleaner.class);
    bind(PolicyAlertEventService.class);
    bind(PolicyEvaluateServiceMetrics.class);
    bind(PolicyViolationAggregationService.class);
    bind(PolicyViolationReachabilityService.class);
    bind(ProductLicenseDetailsCache.class);
    bind(ProductLicenseService.class);
    bind(ProductNotificationService.class);
    bind(ProprietaryConfigService.class);
    bind(QuartzJobSchedulingService.class);
    bind(QuartzTriggerListener.class);
    bind(ReleaseGraphCacheLoader.class);
    bind(ReleaseGraphCacheProvider.class);
    bind(ReleaseGraphService.class);
    bind(ReleaseGraphTask.class);
    bind(ReportDataReader.class);
    bind(ReportDataStore.class);
    bind(ReportDiskSaver.class);
    bind(ReportItemCacheLoader.class);
    bind(ReportPurger.class);
    bind(ReportService.class);
    bind(RepositoryMatcher.class);
    bind(RepositoryPathnameParser.class);
    bind(RequestPolicyWaiverEventService.class);
    bind(RoiConfigurationService.class);
    bind(S3AsyncClient.class).toProvider(S3AsyncClientProvider.class);
    bind(S3AsyncClientProvider.class);
    bind(S3ApplicationReportPersistenceService.class);
    bind(S3ClientProvider.class);
    bind(S3SbomPersistenceService.class);
    bind(S3ScanPersistenceService.class);
    bind(SamlConfigurationService.class);
    bind(SbomApplicationsService.class);
    bind(SbomComponentsService.class);
    bind(SbomDashboardService.class);
    bind(SbomExporterProvider.class);
    bind(SbomFileDetector.class);
    bind(SbomImportService.class);
    bind(SbomMetadataUtils.class);
    bind(SbomPersistenceService.class).toProvider(SbomPersistenceServiceProvider.class);
    bind(SbomPersistenceServiceProvider.class);
    bind(SbomPolicyService.class);
    bind(SbomResultsMerger.class);
    bind(SbomScanEvaluator.class);
    bind(SbomSearchRowFactory.class);
    bind(ScanPersistenceService.class).toProvider(ScanPersistenceServiceProvider.class);
    bind(ScanPersistenceServiceProvider.class);
    bind(ScanService.class);
    bind(Scanner.class);
    bind(ScmStatService.class);
    bind(SearchIndexManager.class).to(DefaultSearchIndexManager.class);
    bind(SearchService.class);
    bind(SecurityVulnerabilityDataService.class);
    bind(SecurityVulnerabilityOverrideEventService.class);
    bind(SecurityVulnerabilityOverrideService.class);
    bind(ShiroSessionTimeoutHandler.class);
    bind(ShutdownHandler.class);
    bind(ShutdownTask.class);
    bind(GuiceAwareJobFactory.class);
    bind(SolutionResolver.class);
    bind(SolutionUrlResolver.class);
    bind(SourceControlDataService.class);
    bind(SourceControlLoadBalancer.class);
    bind(SourceControlPullRequestService.class);
    bind(SourceControlRepositoryUtils.class);
    bind(SourceControlUtils.class);
    bind(SpdxToCycloneDxExporter.class);
    bind(SpdxToPdfExporter.class);
    bind(SpdxToSpdxExporter.class);
    bind(SuccessMetricsPurger.class);
    bind(SuccessMetricsReportDataService.class);
    bind(SuccessMetricsReportService.class);
    bind(SuccessMetricsService.class);
    bind(SuggestionIndexCleaner.class);
    bind(SupportService.class);
    bind(SystemNoticeService.class);
    bind(TagService.class);
    bind(ThirdPartyComponentDAO.class);
    bind(ThirdPartyComponentLicenseResolutionService.class);
    bind(ThirdPartyDataService.class);
    bind(ThirdPartyPersistenceService.class);
    bind(ThirdPartyResultHandlerFactory.class);
    bind(ThirdPartyScanResultsProcessor.class);
    bind(ThrowableHandler.class);
    bind(UserFilterPruner.class);
    bind(UserFilterService.class);
    bind(VulnerabilityAnalysisReferenceDataService.class);
    bind(VulnerabilityDescriptionFetcher.class);
    bind(WebhookClientUtil.class);
    bind(WebhookDispatcher.class);
    bind(ZScalerClient.class);
    bind(ZScalerConfigTelemetryCollector.class);
    bind(ZScalerMaliciousUrlFetcher.class).to(HDSMaliciousUrlFetcher.class);
    bind(ZScalerMetricsTelemetryCollector.class);
    bind(ZScalerUpdater.class);

    // Additional interface bindings needed for Guice migration
    bind(org.quartz.spi.JobFactory.class).to(GuiceAwareJobFactory.class);
    bind(software.amazon.awssdk.services.s3.S3Client.class).toProvider(S3ClientProvider.class);
    bind(PlexusCipher.class).toInstance(CipherFactory.createCipher());
  }

  @Provides
  @Singleton
  @Named("${scheduler.name:-QuartzScheduler}")
  public String provideSchedulerName() {
    return "QuartzScheduler";
  }
}
