/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */

import { initialState as initInputState } from '@sonatype/react-shared-components/components/NxTextInput/stateHelpers';
import {
  REACT_APP_REPORT_LOAD_METADATA_FULFILLED,
  REACT_APP_REPORT_LOAD_METADATA_FAILED,
  REACT_APP_REPORT_LOAD_METADATA_REQUESTED
} from './reportActions';
import { createReducerFromActionMap } from '../../util/reduxUtil';

const initialState = Object.freeze({
  loading: false,
  loadError: null, // should be an error object generated by axios when not null,
  metadataDetails: null,
  inputState: Object.freeze(initInputState(''))
});

/**
 * Maps ActionTypes to Reducer functions
 */
const reducerActionMap = {
  [REACT_APP_REPORT_LOAD_METADATA_REQUESTED]: setMetadataLoading,
  [REACT_APP_REPORT_LOAD_METADATA_FULFILLED]: setMetadataDetails,
  [REACT_APP_REPORT_LOAD_METADATA_FAILED]: setLoadError
};

function setMetadataLoading(payload, state) {
  return {
    ...state,
    loading: true,
    loadError: null,
    metadataDetails: null
  };
}

function setMetadataDetails(metadataDetails, state) {
  return {
    ...state,
    metadataDetails,
    loading: false,
    loadError: null
  };
}

function setLoadError(loadError, state) {
  return {
    ...state,
    loadError,
    loading: false
  };
}
/**
 * Main reducer function for this file.
 * Looks up the action by type and then executes using the payload and the state.
 */
const reportReducer = createReducerFromActionMap(reducerActionMap, initialState);
export default reportReducer;
