
-repackageclasses zz

-dontusemixedcaseclassnames

-dontoptimize
-dontshrink
-dontnote

-dontwarn ch.qos.logback.**
-dontwarn com.google.**
-dontwarn com.thoughtworks.xstream.**
-dontwarn de.schlichtherle.**
-dontwarn javax.enterprise.**
-dontwarn org.apache.**
-dontwarn org.sonatype.guice.**

# 3rd party stuff excluded from obfuscation
-keep class !com.sonatype.insight.**,!org.objectweb.** { *; }

# CLI entry
-keep public class com.sonatype.insight.scan.cli.PolicyEvaluatorCli { *; }

# Logging support
-keep public class com.sonatype.insight.scan.cli.MarkerFilter { *; }

# DTOs used by XStream to build the scan report XML
-keepclassmembers public class com.sonatype.insight.scan.model.* { *; }

# DTO used to parse the JSON response from the server
-keepclassmembers public class com.sonatype.clm.dto.model.** { *; }

-renamesourcefileattribute SourceFile
-keepattributes *Annotation*,Exceptions,InnerClasses,EnclosingMethod,Signature,SourceFile,LineNumberTable

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

