/*
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/oss/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
*/
(function(){function u(e,a,c){c=$.extend({},w,c);var d=2*c.fontSize,g=a.length*c.fontSize*.6,f=c.height/2-d/2,p=c.leftPadding+(c.width-c.leftPadding-c.rightPadding-g)/2;e.add(pv.Bar).top(f).left(p).lineWidth(0).height(d).width(g).strokeStyle("#cee8fb").fillStyle("#cee8fb");e.add(pv.Dot).top(f+d/2).left(p).radius(d/2).lineWidth(0).strokeStyle("#cee8fb").fillStyle("#cee8fb");e.add(pv.Dot).top(f+d/2).left(p+g).radius(d/2).lineWidth(0).strokeStyle("#cee8fb").fillStyle("#cee8fb");e.add(pv.Label).top(f+
d/2).left(p+g/2).width(g).font("normal "+(c.fontSize+1)+"px arial").textAlign("center").textBaseline("middle").text(a)}var v,x={height:50,width:50,lineWidth:1.5,innerRadius:9,outerRadius:21,outerRadiusStep:0,showLabels:!1,fillColors:["#FDDD03","#8DC63E"],strokeColors:["#3A983F"],textColors:["white"]},y={height:193,width:235,innerRadius:30,outerRadius:60,outerRadiusStep:7,fontSize:16,showLabels:!0,lineWidth:1},z={width:267,height:183,fontSize:9},w={fontSize:9,leftPadding:0,rightPadding:0};v=function(){function e(b){if("number"===
typeof b){if(8<=b)return 0;if(4<=b)return 1;if(0<b)return 2;if(0===b)return 3}else if("string"===typeof b){if("COPYLEFT"===b)return 0;if("NOT-PROVIDED"===b||"NON-STANDARD"===b)return 1;if("WEAKCOPYLEFT"===b)return 2;if("LIBERAL"===b)return 3}return 4}function a(b){var m={versions:[],versionPopularity:[],majorRevIndices:[],conflictVersions:[],effectiveLicenses:[],securityLevels:[[],[],[]]};$.each(b.versions,function(a,c){var d=!1,l=!1,h=!1;m.versions.push(c.version);m.versionPopularity.push(c.popularity||
c.relativePopularity||0);b.version===c.version&&(m.currentVersionIndex=a);c.majorRevisionStep&&m.majorRevIndices.push(a);m.effectiveLicenses.push(e(c.effectiveLicenseThreat||c.licenseThreatLevel));c.securityThreats?(-1!==$.inArray("Critical",c.securityThreats)&&m.securityLevels[0].push(a),-1!==$.inArray("Severe",c.securityThreats)&&m.securityLevels[1].push(a),-1!==$.inArray("Moderate",c.securityThreats)&&m.securityLevels[2].push(a)):c.securityVulnerabilities&&0<c.securityVulnerabilities.length&&($.each(c.securityVulnerabilities,
function(b,m){var a=e(m.severity);d=d||0===a;l=l||1===a;h=h||2<=a}),d&&m.securityLevels[0].push(a),l&&m.securityLevels[1].push(a),h&&m.securityLevels[2].push(a))});return m}function c(b){return function(m){return(b.barGap+b.barWidth)*m+b.barGap}}function d(b,m,a,c){var d=!1,e=!1,h=0,g=function(b){var a=m.transform().translate(b,0);b=h+b;10>b&&-10<c.width-c.contentWidth+b?(h=b,m.transform(a).render()):e=d=!1},f=function(){d&&(g(10),setTimeout(f,100))},k=function(){e&&(g(-10),setTimeout(k,100))};a.add(pv.Dot).left(c.contentWidth-
7).top(15+c.height/2).fillStyle("#f7fbfe").strokeStyle("#575757").angle(-Math.PI/2).shape("triangle").lineWidth(1).size(30).cursor("pointer").events("all").event("mouseover",function(){this.fillStyle("#575757").render()}).event("mouseout",function(){this.fillStyle("#f7fbfe").render();e=!1}).event("mousedown",function(){e=!0;setTimeout(k,0)}).event("mouseup",function(){e=!1});a.add(pv.Dot).left(7).top(15+c.height/2).fillStyle("#f7fbfe").strokeStyle("#575757").angle(Math.PI/2).shape("triangle").lineWidth(1).size(30).cursor("pointer").event("all").events("all").event("mouseover",
function(){this.fillStyle("#575757").render()}).event("mouseout",function(){this.fillStyle("#f7fbfe").render();d=!1}).event("mousedown",function(){d=!0;setTimeout(f,0)}).event("mouseup",function(){d=!1});return g}function g(b,a){var d=b.add(pv.Panel).def("i",-1),e=d.add(pv.Bar),h=e.anchor("bottom").add(pv.Label).visible(!1).textBaseline("top"),g=c(a),f=null;e.data(a.data.versions).width(a.spacer-1).left(function(){return a.left+g(this.index)-1}).top(a.topPadding).height(t.partialDisplay?a.height:
a.height-20).lineWidth(0).strokeStyle("#f7fbfe").fillStyle("transparent").events("all").event("mouseover",function(){d.i(this.index);this.render();h.visible(function(b){return d.i()===this.index}).textAlign(0===this.index?"left":this.index===a.data.versions.length-1?"right":"center").render()}).event("mouseout",function(){d.i(-1);this.render();h.visible(!1).render()}).fillStyle(function(b){return d.i()===this.index?pv.color("rgba(153, 204, 255, 0.5)"):this.index===f?pv.color("rgba(10, 10, 10, 0.15)"):
"transparent"}).strokeStyle(function(b){return this.index===f?pv.color("rgba(10, 10, 10, 0.5)"):pv.color("rgba(255, 255, 255,0.1)")}).lineWidth(1);a.selectable&&(f=a.data.currentVersionIndex,e.event("click",function(){a.versionClick(this.data());f=this.index;this.render()}),e.event("dblclick",function(){a.versionDblClick(this.data())}))}function f(b,a){var d=a.data,e=1,h=d.versionPopularity.length,g=c(a),f=b.add(pv.Panel),k=a.barHeight-3;f.width(a.width).height(a.barHeight).top(a.top).left(a.left);
$.each(d.versionPopularity,function(b,a){e=Math.max(e,a)});e=1/e;$.each(d.majorRevIndices,function(b,a){if(a>d.currentVersionIndex)return h=a,!1});f.add(pv.Bar).data(d.versionPopularity).width(a.barWidth).left(function(){return g(this.index)}).height(function(b){return k*b*e+3}).bottom(0).fillStyle(function(b){return this.index<d.currentVersionIndex?"#a8a9ad":this.index>=h?"#6d97d0":this.index===d.currentVersionIndex?"#58585a":"#8bc73e"});f.add(pv.Rule).width(a.contentActualWidth+a.barGap).bottom(0).left(0).strokeStyle("#949599");
a.top+=a.barHeight+a.spacer;return b}function p(b,a){b.add(pv.Panel).width(a.width).top(a.top).height(a.spacer).left(3).add(pv.Bar).top(1).data(a.vGridLines).width(a.barWidth+a.barGap-1.5).height(a.barWidth+a.barGap-1.5).left(function(){return this.data()-2}).fillStyle("#edf1f4")}function n(b,a){b.add(pv.Panel).width(a.width).top(a.top).height(a.spacer).left(a.left).add(pv.Bar).top(a.barGap/2).data(a.data.effectiveLicenses).width(a.barWidth).height(a.barWidth).left(function(){return c(a)(this.index)}).fillStyle(function(b){switch(b){case 0:return"#bc012f";
case 1:return"#f4861d";case 2:return"#f5c648";case 3:return"#006bbf";default:return"#9D9D9D"}}).strokeStyle(function(b){switch(b){case 0:return"#bc012f";case 1:return"#f4861d";case 2:return"#f5c648";case 3:return"#006bbf";default:return"#9D9D9D"}});a.top+=2*a.spacer;return b}function r(b,a){$.each(a.data.securityLevels,function(d,e){var h=b.add(pv.Panel).width(a.width).top(a.top).height(a.spacer).left(a.left),f="#575757",g="#9D9D9D";switch(d){case 0:f=g="#bc012f";break;case 1:f=g="#f4861d";break;
case 2:f=g="#f5c648"}h.add(pv.Dot).data(e).left(function(b){return a.barWidth/2+c(a)(b)+1}).radius(a.barWidth/2-.5).fillStyle(g).strokeStyle(f).angle(-Math.PI/2).shape("triangle");a.top+=a.spacer});return b}function h(b){var a=[],c=$("#aiVersionChartContainer"),e,h,l,q;b=$.extend({},t,b);if(0!==c.length){$.each(k,function(a,c){b[a]=c.call(k,b)});c.height(b.actualHeight);c=(new pv.Panel).canvas("aiVersionChartLabels").height(b.actualHeight).width(b.labelWidth).fillStyle("#f7fbfe").strokeStyle("#f7fbfe");
l=(new pv.Panel).canvas("aiVersionChartViz").overflow("hidden").height(b.actualHeight).width(b.contentWidth).fillStyle("#f7fbfe").strokeStyle("#f7fbfe");b.panning&&(e=l,l=e.add(pv.Panel).overflow("hidden").height(b.actualHeight).width(b.contentWidth-30).fillStyle("#f7fbfe").strokeStyle("#f7fbfe").left(15));for(q=0;q<=b.spacer*b.contentRows;q+=b.spacer)a.push(q);l.add(pv.Rule).data(a).left(0).width(b.width).top(function(a){return a+b.topPadding}).height(1).strokeStyle("#dee6f3").strokeDasharray("1 1");
b.vGridLines=[0];for(q=(b.width/2-1)%b.spacer-b.spacer/2-.5;q<b.width;q+=b.spacer)b.vGridLines.push(q);l.add(pv.Rule).data(b.vGridLines).left(function(a){return a}).height(b.height-b.topPadding).top(b.top).strokeStyle("#dee6f3").strokeDasharray("1 1");$.each(b.partialDisplay?[]:[5,7,8,9],function(a,c){p(l,$.extend({},b,{top:b.top+(c-1)*b.spacer}))});0!==b.versionCount&&(l.add(pv.Rule).left(b.width/2-1).top(b.topPadding).height(b.height-b.topPadding).strokeStyle("#949599"),l.add(pv.Label).left(b.width/
2-70).top(15).textAlign("center").text("Older"),l.add(pv.Label).left(b.width/2).top(15).textAlign("center").text("This Version"),l.add(pv.Label).left(b.width/2+70).top(15).textAlign("center").text("Newer"));c.add(pv.Label).left(0).top(b.top+b.labelTop).textAlign("left").text("Popularity");b.top+=1;f(l,b);b.partialDisplay||(c.add(pv.Label).left(0).top(b.top+10).textAlign("left").text("License Risk"),n(l,b),c.add(pv.Label).left(0).top(b.top+10).textAlign("left").text("Security Alerts"),r(l,b));0===
b.versionCount?(u(l,"No Data",{width:b.contentWidth,height:b.actualHeight}),c.render(),l.render()):(g(l,b),b.panning&&(h=d(c,l,e,b),b.contentWidth-=15),c.render(),l.render(),b.panning&&h(-(b.width/2-b.contentWidth+b.contentWidth/2)))}}var t={partialDisplay:!1,selectable:!1,barGap:3,barWidth:8,contentWidth:375,labelTop:14,labelWidth:100,topPadding:20,vizPadding:6,versionClick:$.noop,versionDblClick:$.noop},k={actualHeight:function(a){return this.height(a)+11+this.bottomPadding(a)},barHeight:function(a){return 3*
(a.barWidth+a.barGap)-1},height:function(a){return a.topPadding+this.contentRows(a)*(a.barWidth+a.barGap)+1},contentRows:function(a){return a.partialDisplay?4:10},bottomPadding:function(a){return a.partialDisplay?20:0},versionCount:function(a){return a.data.versions?a.data.versions.length:0},contentActualWidth:function(a){return(a.barWidth+a.barGap)*this.versionCount(a)},width:function(a){var c=a.data.currentVersionIndex;return 0<c?Math.max(a.contentWidth,2*((a.barWidth+a.barGap)*(Math.max(c,a.data.versions.length-
c)+1)-a.barGap)):a.contentWidth},panning:function(a){return this.width(a)>a.contentWidth},left:function(a){var c=a.data.currentVersionIndex;return 0>c?0:this.width(a)/2-(c*(a.barWidth+a.barGap)+a.barWidth/2+a.barWidth/2)},spacer:function(a){return a.barGap+a.barWidth},top:function(a){return a.topPadding}};return function(b){b.data=a(b.data);h(b)}}();$.extend(!0,window,{HealthCheck:{getAge:function(e,a){var c,d;c=(a?a.getTime():(new Date).getTime())-e.getTime();if(31104E6<c)c/=31104E6,d="year";else if(2592E6<
c)c/=2592E6,d="month";else if(864E5<c)c/=864E5,d="day";else if(36E5<c)c/=36E5,d="hour";else if(6E4<c)c/=6E4,d="minute";else return"some seconds";c=Math.floor(c);1<c&&(d+="s");return c+" "+d},artifactsChart:function(e,a){a=$.extend({},x,a);a.visTop=a.height/2;a.visLeft=a.width/2;a.h=a.height;a.w=a.width;this.donutChart([e,1-e],a)},licenseChart:function(e,a){a=$.extend({},y,a);if(0!==Math.max.apply(null,e))a.h=a.height,a.w=a.width,a.visTop=a.h/2+5,a.visLeft=a.w/2-3.5,a.fillColors=3===e.length?["#bc012f",
"#f5c648","#006bbf"]:["#bc012f","#f4861d","#f5c648","#006bbf"],a.strokeColors=3===e.length?["#bc012f","#f5c648","#006bbf"]:["#bc012f","#f4861d","#f5c648","#006bbf"],a.textColors=3===e.length?["#9d0c11","#83740d","white"]:["#9d0c11","#f4861d","#83740d","white"],this.donutChart(e,a);else{var c=(new pv.Panel).width(a.width).height(a.height);null!=a.element&&c.canvas(a.element);u(c,"No Licenses Found",{height:a.height,width:a.width});c.render()}},donutChart:function(e,a){var c=0,d=[],g=[],f=[],p=[],n=
-1,r=0,h,t,k,b;for(k=0;k<e.length;k++)0<e[k]&&(c+=e[k],d.push(e[k]),g.push(a.fillColors[k%a.fillColors.length]),f.push(a.strokeColors[k%a.strokeColors.length]),p.push(a.textColors[k%a.textColors.length]));t=d.length-1;for(k=0;k<d.length;k++){if(0>n||d[k]>=d[n])n=k;b=.01*c-d[k];0<b&&(d[k]=.01*c,r+=b)}d[n]-=r;n=(new pv.Panel).width(a.w).height(a.h);null!=a.element&&n.canvas(a.element);h=n.add(pv.Wedge).data(d).left(a.visLeft).top(a.visTop).outerRadius(function(){return a.outerRadius+(t-this.index)*
a.outerRadiusStep}).innerRadius(a.innerRadius).angle(function(a){return a/c*2*Math.PI}).fillStyle(pv.colors(g).by(function(){return this.index})).lineWidth(function(b){return 0<b?a.lineWidth:0}).strokeStyle(pv.colors(f).by(function(){return this.index}));a.showLabels&&h.add(pv.Label).left(function(){return 1===this.index&&.61>h.angle()?a.visLeft+(this.innerRadius()-5)*Math.cos(h.midAngle()):a.visLeft+(this.outerRadius()+3)*Math.cos(h.midAngle())}).top(function(){return 1===this.index&&.61>h.angle()?
a.visTop+(this.innerRadius()-5)*Math.sin(h.midAngle()):a.visTop+(this.outerRadius()+3)*Math.sin(h.midAngle())}).font("bold "+a.fontSize+"px arial").text(function(a){return 0===a||this.index===d.length-1?"":Math.round(a/c*100)+"%"}).textStyle(pv.colors(p).by(function(){return this.index})).textAlign(function(){var a=0>h.midAngle()?2*Math.PI+h.midAngle():h.midAngle();return 2===this.index&&a>1.5*Math.PI?"left":.31>Math.abs(a%Math.PI-Math.PI/2)?"center":1===this.index&&.61>h.angle()?a>Math.PI/2&&a<1.5*
Math.PI?"left":"right":a>Math.PI/2&&a<1.5*Math.PI?"right":"left"}).textBaseline(function(){var a=0>h.midAngle()?2*Math.PI+h.midAngle():h.midAngle();return.31>Math.abs((a+Math.PI/2)%Math.PI-Math.PI/2)?"middle":1===this.index&&.61>h.angle()?a>Math.PI?"top":"bottom":a>Math.PI?"bottom":"top"});n.render()},barChart:function(e,a){a=$.extend({},z,a);var c=e[0],d=0,g=2*a.fontSize,f=5*a.fontSize,p=pv.Scale.ordinal(pv.range(e.length)).splitBanded(0,a.height-g,.6),n,r,h;for(n=1;n<e.length;n++)c=Math.max(c,e[n]);
n=0===c;d=function(){var a=[1,2,5,10,20,25,50,100,200,250,500,1E3,2E3,2500,5E3],d=[9,9,9,9,8,8,8,8,6,6,6,5,5,4,4],b;for(b=0;b<a.length;b++)if(c/a[b]<=d[b])return a[b];return a[a.length-1]}();c=0===c%d?c+d:Math.ceil(c/d)*d;r=pv.Scale.linear(0,c).range(0,a.width-f-10);h=(new pv.Panel).width(a.width).height(a.height);null!=a.element&&h.canvas(a.element);h.add(pv.Panel).width(a.width-f).height(a.height-g-5).top(g+5).left(f).fillStyle("#f7fbfe").strokeStyle("#F2F5F8");h.add(pv.Label).text("Threat").top(a.fontSize-
1).left(a.fontSize/2).font("normal "+a.fontSize+"px arial").textStyle("#575757").events("all").event("mouseover",pv.Behavior.tipsy({fade:!0,gravity:"w",html:!0,opacity:1,offset:35,title:function(){return"Sonatype utilizes the base score from the Common Vulnerability Scoring System, version 2."}})).textAlign("left").textBaseline("middle");h.add(pv.Label).text("Level").top(2*a.fontSize-1).left(a.fontSize/2+3).font("normal "+a.fontSize+"px arial").textStyle("#575757").textAlign("left").textBaseline("middle");
h.add(pv.Bar).data(e).top(function(){return g+p(this.index)}).text(function(a){return a}).event("mouseover",pv.Behavior.tipsy({fade:!0,gravity:"w",html:!0,opacity:1})).height(p.range().band).left(f).width(r).fillStyle(function(a){a=10-this.index;return 6<a?"rgb(188,1,47)":3<a?"rgb(244,134,29)":"rgb(254,198,72)"}).anchor("left").add(pv.Label).textAlign("center").left(f/2).width(f).font("normal "+a.fontSize+"px arial").textStyle("#575757").strokeStyle("#575757").text(function(){return 10-this.index});
d=pv.range(0,c+d,d);h.add(pv.Rule).data(d).top(g+5).left(function(a){return f+r(a)}).strokeStyle("#f1f4f9").add(pv.Rule).top(g).height(5).strokeStyle("#575757").anchor("top").add(pv.Label).text(r.tickFormat).font("normal "+a.fontSize+"px arial").textStyle("#575757");n&&u(h,"No Vulnerabilities Found",{width:a.width,height:a.height,rightPadding:10,leftPadding:f});h.render()},punchCard:function(e,a){e=e||[];a=a||{};var c=[],d=-1,g,f,p;if(5<e.length)for(c=e.splice(5,e.length-5),g=0;g<c.length;g++)for(f=
0;f<c[g].length;f++)e[4][f]+=c[g][f];$.each(e,function(a,c){$.each(c,function(a,c){d=Math.max(d,c)})});f=(new pv.Panel).width(107).height(180);null!=a.element&&f.canvas(a.element);f.add(pv.Label).text("Dependency Depth").right(0).top(3).font("9px arial").textStyle("#575757").textAlign("right").textBaseline("top");for(g=0;5>g;g++)f.add(pv.Label).text(4<=g&&0<c.length?"5+":g+1).font("9px arial").textStyle("#575757").left(3).top(36+32*g).textBaseline("middle");p=f.add(pv.Panel).bottom(0).right(0).width(87).height(160).strokeStyle("#eef2fb").fillStyle("#f7fbfe");
for(g=1;5>g;g++)p.add(pv.Rule).strokeStyle("#eef2fb").top(32*g);$.each(e,function(a,c){$.each(c,function(c,e){0<e&&p.add(pv.Dot).data([e]).left(function(a){return 16+28*c}).top(16+32*a).size(function(a){return a/d*144}).fillStyle(function(a){return 0===c?"#bc012f":1===c?"#f4861d":"#f5c648"}).strokeStyle(function(a){return 0===c?"#bc012f":1===c?"#f4861d":"#f5c648"})})});0===e.length&&u(p,"No Components",{height:160,width:87});f.render()}},Insight:{ComponentInformation:v}})})();