/*
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2012-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
*/
(function(){function d(b){var a=this;this.options=$.extend(!0,{},f,b);this.node=$("\x3cdiv id\x3d'informationPanel' class\x3d'informationPanel fullBorderedTable'\x3e\x3cdiv style\x3d'width:99%; padding-top: 5px; padding-left: 0.5%; padding-right: 0.5%;'\x3e\x3ca class\x3d'close'\x3e\x26times;\x3c/a\x3e\x3cul class\x3d'nav nav-tabs' style\x3d'margin-bottom:0px; !important'\x3e\x3c/ul\x3e\x3cdiv class\x3d'tab-content' style\x3d'overflow:hidden'\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");$(".close",this.node).click(function(){a.hide()});
this.plugins=[];Insight.InformationPanelPlugins.sort(function(c,a){return c.prototype.priority-a.prototype.priority});$.each(Insight.InformationPanelPlugins,function(c,e){var b=$('\x3cli data-info-plugin\x3d"'+c+'" class\x3d"tm-cip-nav-'+e.name+'"\x3e\x3ca data-target\x3d"infoPanel'+c+'" data-toggle\x3d"tab"\x3e\x3c/a\x3e\x3c/li\x3e'),g=$('\x3cdiv class\x3d"tab-pane" id\x3d"infoPanel'+c+'" class\x3d"tm-cip-content-'+e.name+'"\x3e\x3c/div\x3e');$("ul.nav",a.node).append(b);$("div.tab-content",a.node).append(g);
a.plugins.push(new e(g,a.options))});$('a[data-toggle\x3d"tab"]',this.node).on("show",function(c){var b;null!==c.relatedTarget&&(b=$(c.relatedTarget.parentNode).data("info-plugin"),a.plugins[b].destroy(),$("#"+$(c.relatedTarget).data("target"),a.node).hide());null!==c.target&&(b=$(c.target.parentNode).data("info-plugin"),c=$("#"+$(c.target).data("target"),a.node),c.show(),a.plugins[b].create(c,a.node))})}function h(b){b=b||{};this.priority=b.priority||512}var f={byHash:!1};d.prototype.destroy=function(){this.cleanPlugins()};
d.prototype.hide=function(){this.node.detach();this.grid.removeCellCssStyles("popout");this.cleanPlugins()};d.prototype.init=function(b){var a=this;this.grid=b;b.onClick.subscribe(function(){a.gridClickedFn.apply(a,arguments)});b.getData().onRowCountChanged.subscribe(function(){a.hide()});b.getData().onRowsChanged.subscribe(function(){a.rowChangedFn.apply(a,arguments)});$.each(this.plugins,function(c,a){a.setGrid(b)})};d.prototype.cleanPlugins=function(){$.each(this.plugins,function(b,a){a.destroy()})};
d.prototype.gridClickedFn=function(b,a){var c=this;"INPUT"!==b.target.tagName&&0===$(b.target).children("input:first").length&&(Insight.util.isNotNullOrUndefined(c.timer)?(clearTimeout(c.timer),c.timer=null):c.timer=setTimeout(function(){c.timer=null;$.each(c.plugins,function(b,k){k.setItem(c.grid.getDataItem(a.row))});c.toggle(b,a)},250))};d.prototype.getItem=function(){return this.grid.getDataItem(this.currentRow)};d.prototype.updatePanel=function(){var b=this,a=null;$.each(this.plugins,function(c,
a){var k=$("li[data-info-plugin\x3d"+c+"]",b.node);a.isVisible()?(k.show(),$("a",k).text(a.getTitle())):(k.hide(),$("#infoPanel"+c,b.node).hide(),k.hasClass("active")&&(k.removeClass("active"),$("ul.nav \x3e li:first",b.node).addClass("active")))});0===$("li.active",b.node).length&&$("li",b.node).each(function(c,a){a=$(a);if("none"!==a.css("display"))return a.addClass("active"),!1});a=$("li.active",b.node).data("info-plugin");b.plugins[a].create();$("#infoPanel"+a,b.node).show()};d.prototype.rowChangedFn=
function(b,a){var c=this.currentRow,e=this;setTimeout(function(){var a=e.grid.getSelectedRows(),b=null;Insight.util.isNotNullOrUndefined(c)&&1===a.length?c!==a[0]?(e.hide(),Insight.util.isNotNullOrUndefined(this.currentItemId)&&e.show({row:a[0],cell:1},e.grid.getCanvasNode())):(e.position(c),b=e.getItem(),$.each(e.plugins,function(c,a){a.setItem(b)}),e.updatePanel()):e.hide()},10)};d.prototype.toggle=function(b,a){this.grid.removeCellCssStyles("popout");$(this.node).is(":hidden")||this.currentRow!==
a.row?this.show(this.grid.getCellFromEvent(b),$(b.currentTarget)):this.hide()};d.prototype.show=function(b,a){var c={},e=this.grid.getCellNode(b.row,b.cell),k=$(this.grid.getCanvasNode()).parent();k.offset();k.height();var g=this;Insight.util.isNullOrUndefined(e)&&(this.grid.scrollRowIntoView(b.row),e=this.grid.getCellNode(b.row,b.cell));this.node.css("top",e.offsetParent.offsetTop+e.offsetParent.clientHeight);this.node.addClass("shadowBottom");this.node.removeClass("shadowTop");g.node.appendTo(a);
this.updatePanel();g.position(b.row);g.node.show();this.currentRow=b.row;c[this.currentRow]={};$.each(g.grid.getColumns(),function(a,b){c[g.currentRow][b.id]="popout"});g.grid.setCellCssStyles("popout",c)};d.prototype.position=function(b){var a=this.node.offset().top,c=a+this.node.height(),e=$(this.grid.getCanvasNode()).parent(),k=e.offset().top,g=k+e.height(),l=this.grid.getCellNode(b,1);Insight.util.isNullOrUndefined(l)&&(this.grid.scrollRowIntoView(b),l=this.grid.getCellNode(b,1));(c>g||a<k)&&
e.scrollTop(e.scrollTop()+(this.node.offset().top-l.offsetParent.clientHeight)-e.offset().top)};h.prototype.getErrorFn=function(b,a,c){return function(){var e=$(b);e.html(Insight.templates.error.render());$(".btn",e).click(function(){a.apply(c,[])})}};h.prototype.isVisible=function(){return!0};h.prototype.getTitle=function(){return""};h.prototype.setItem=function(b){Insight.util.isNullOrUndefined(b.componentIdentifier)&&Insight.util.isNotNullOrUndefined(b.groupId)&&Insight.util.isNotNullOrUndefined(b.artifactId)&&
Insight.util.isNotNullOrUndefined(b.version)&&(b.componentIdentifier={format:"maven",coordinates:{groupId:b.groupId,artifactId:b.artifactId,version:b.version}});this.gav=this.component=b};h.prototype.message=function(b){$(".alert",this.node).remove();b=$('\x3cdiv class\x3d"alert" style\x3d"width:92.5%"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3e\x3c/div\x3e');$("div:first",this.node).prepend(b);return b};h.prototype.addErrorMessage=function(b){this.message(b).addClass("alert-error").append("\x3cstrong\x3eError: \x3c/strong\x3e",
$("\x3cspan\x3e\x3c/span\x3e").text(b))};h.prototype.addSuccessMessage=function(b){var a=this.message(b).addClass("alert-success").append($("\x3cspan\x3e\x3c/span\x3e").text(b));setTimeout(function(){a.fadeOut("fast",function(){a.remove()})},8E3);return a};h.prototype.setGrid=function(b){this.grid=b};h.prototype.create=$.noop;h.prototype.destroy=$.noop;$.extend(!0,window,{Insight:{InformationPanel:d,InformationPanelPlugin:h,InformationPanelPlugins:[]}})})();
(function(){function d(f){var b,a;if(0===f.indexOf("dependency:/"))return f=f.substring(12),b=f.lastIndexOf("/"),0>b?["Dependency "+f,""]:["Dependency "+f.substring(b+1),"Module "+f.substring(0,b)];b=f.lastIndexOf("/");if(-1===b)return[f,""];a=f.substring(b+1);f=f.substring(0,b);return[a,f]}function h(f,b){this.node=f;this.options=b}h.prototype=new Insight.InformationPanelPlugin({priority:64});h.prototype.buildView=function(f){if(0<f.length){f.sort();var b="\x3cdiv class\x3d'infoPanelText fileDetail'\x3e",
a=!1;$.each(f,function(c,e){$.each(e.pathnames,function(c,a){var e=d(a);b+="\x3cb\x3e"+Insight.util.encodeHtml(e[0])+"\x3c/b\x3e";0<e[1].length&&(b+=" \x3ci\x3elocated at\x3c/i\x3e "+Insight.util.encodeHtml(e[1]));b+="\x3cbr\x3e\x3cbr\x3e"});0>=e.pathnames.length&&(a=!0)});a&&(b+="Occurrences of this component cannot be listed because pathnames have been anonymized. To see all occurrences, please disable anonymization in the options of your CLM enforcement points and perform a new scan.");b+="\x3c/div\x3e";
$(this.node).html(b)}else $(this.node).html("\x3cdiv class\x3d'infoPanelText'\x3eInvalid data encountered, no files are associated with this component.\x3c/div\x3e")};h.prototype.create=function(){var f=this;f.options.byHash?this.buildView([f.component]):$.getJSON("bom.json",function(b){var a=[];$.each(b.aaData,function(c,b){Insight.util.componentsEqual(b,f.component)&&a.push(b)});f.buildView(a)},this.getErrorFn(f.node,f.create,f))};h.prototype.destroy=function(){};h.prototype.getTitle=function(){return"Occurrences"};
Insight.InformationPanelPlugins.push(h)})();
(function(){function d(a){return null===a||"undefined"===typeof a}function h(a){var c={s:"top",n:"bottom",w:"right",e:"left"};return(a?c[a.charAt(0)]:void 0)||"left"}function f(a,c,e,k){var g=$("#sv-info-modal .modal-body");a&&c?(g.empty(),g.append("\x3cp\x3eLoading vulnerability detail content\x3c/p\x3e"),b&&"pending"===b.state()&&b.reject("reject"),b=$.getJSON(Insight.toBrain(Brain.getVulnerabilityDetailUrl(a,c,e,k))).done(function(c){g.empty();g.append(c.htmlDetails)}).fail(function(b){"reject"!==b&&
(g.empty(),g.append(Insight.templates.error.render()),$(".btn",g).click(function(){f(a,c,e,k)}))})):(g.empty(),g.append("Unable to construct url for vulnerability detail content."));$("#sv-info-modal").modal("show")}var b;$.extend(!0,window,{Insight:{toBrain:function(a){return"/"===a.charAt(0)?"../brain"+a:"../brain/"+a},util:{enableTooltip:function(a){$(a).each(function(){var c=$(this);c.tooltip({placement:h(c.attr("data-gravity")),html:!0,trigger:"hover",container:c.attr("data-tooltip-container")})})},
getErrorMessage:function(a){var c="";return c=0===a.status||1E3<=a.status?"Network error while contacting server":a.responseText&&0<=(a.getResponseHeader("Content-Type")||"").indexOf("text/plain")?a.responseText:a.statusText?a.statusText:"Error "+a.status},getQueryParameter:function(a){var c=0<window.location.search.length?window.location.search.substring(1).split("\x26"):[],b=null,k=null;a=a.toLowerCase();for(k=0;k<c.length;k++)if(b=c[k].split("\x3d"),b[0].toLowerCase()===a)return b[1]},isNullOrUndefined:d,
isNotNullOrUndefined:function(a){return!d(a)},componentsEqual:function(a,c){if(Insight.util.isNullOrUndefined(a.componentIdentifier)&&Insight.util.isNullOrUndefined(c.componentIdentifier))return a.groupId===c.groupId&&a.artifactId===c.artifactId&&a.version===c.version;if(Insight.util.isNullOrUndefined(a.componentIdentifier)||Insight.util.isNullOrUndefined(c.componentIdentifier)||a.componentIdentifier.format!==c.componentIdentifier.format||a.componentIdentifier.coordinates.length!==c.componentIdentifier.coordinates.length)return!1;
for(var b in a.componentIdentifier.coordinates)if(a.componentIdentifier.coordinates.hasOwnProperty(b)&&a.componentIdentifier.coordinates[b]!==c.componentIdentifier.coordinates[b])return!1;return!0},toSvReference:function(b,c){var e=Insight.util.isNullOrUndefined(b)?"":b.toUpperCase(),k=Insight.util.isNullOrUndefined(c)?"":c.toUpperCase();return 0>k.indexOf(e)?e+"-"+k:k},showSvModal:f,showVulnerabilityDetail:function(){return Brain.getVulnerabilityDetailUrl},encodeHtml:function(){var b=$("\x3cdiv/\x3e");
return function(c){return b.text(c).html()}}()}}})})();
(function(){var d;$.extend(!0,window,{Insight:{templates:{error:d},selectTab:function(d){InsightDatatable.destroyActiveTable();switch(d){case "securitycontainer":table=InsightDatatable.createSecurityTable({headerRowHeight:30});table.addLoadListener(function(){InsightDatatable.addSecurityTableEditor(table)});break;case "componentcontainer":table=InsightDatatable.createComponentTable({headerRowHeight:30})}}}});$(document).ready(function(){d=Hogan.compile($("#errorTemplate").html());$("button[data-containerid]").click(function(d){$(this).hasClass("active")||
(d=$(this).data("containerid"),$("[data-container]").css("display","none"),$("#"+d).css("display",""),Insight.selectTab(d))});Insight.util.enableTooltip($("[data-gravity]"));$.browser.msie&&9>$.browser.version&&$(".btn-group:eq(1)").after('\x3cdiv class\x3d"alert alert-error" style\x3d"margin:5px 0"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3eYou are using older version of Internet Explorer (IE). You may notice degraded performance and/or functionality. To address this, download and install the latest version of IE, or other modern browser (e.g. Chrome, Firefox)\x3c/div\x3e');
Insight.selectTab("componentcontainer")})})();
(function(){function d(c){var b=$(window).innerHeight(),k=$(c).offset().top;c=$("#"+c.attr("id")+"Pager").height();return Math.max(150,b-k-a-c)}function h(c){$("#"+c+"container .message").remove()}function f(c,b){var a=$("#"+c+"container"),g=$("#"+c+"Table").position(),l;null!==g&&(h(c),a.append('\x3cdiv class\x3d"message" style\x3d"top:'+(g.top+70)+'px"\x3e'+b+"\x3c/div\x3e"),l=$(".message",a),l.css("left",g.left+a.outerWidth()/2-l.outerWidth()/2+"px"))}function b(c,b,a){function g(b){if(!m.destroyed){m.table=
new Slick.Grid("#"+c+"Table",m.dataView,a.columns,p);if(a.handlers)for(var g=0;g<a.handlers.length;g++)m.table[a.handlers[g].event].subscribe(a.handlers[g].handler);a.selectable&&(m.table.setSelectionModel(new Slick.RowSelectionModel),m.dataView.syncGridSelection(m.table,!0));h.init(m.table);q.css("height",a.height||d($("#"+c+"Table"))+"px");m.processData(b);m.initialize()}}function l(b){return function(a,c,g){a=q.empty().append(Insight.templates.error.render({message:g}));$("button",a).click(b)}}
function f(b){q.empty().append('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e');b.get().done(function(a){null!=a?g(a):l(function(){f(b)})()}).fail(l(function(){f(b)}))}var h=new Slick.Data.GroupItemMetadataProvider,p=$.extend({editable:!1,enableAddRow:!1,enableCellNavigation:a.enableCellNavigation,enableColumnReorder:!1,enableTextSelectionOnCells:!0,fullWidthRows:!0,forceFitColumns:!0,rowHeight:31,
explicitInitialization:!0,showHeaderRow:!a.disableFilter,multiSelect:!1,autoHeight:a.autoHeight,multiColumnSort:a.multiColumnSort},a.config||{}),m=this,q=$("#"+c+"Table");this.options=a;this.id=c;this.dataView=new Slick.Data.DataView({groupItemMetadataProvider:h});this.filter=new Slick.Filter;$.isArray(b)?g({aaData:b}):"string"===typeof b?f({get:function(){return $.getJSON(b)}}):"object"===typeof b?f(b):console.log("Unable to load: "+b)}var a=null;$.browser&&($.browser.mozilla&&4>parseFloat($.browser.version)?
a=9:$.browser.msie&&9>parseFloat($.browser.version)&&(a=15));null===a&&(a=14);b.prototype.updateHeight=function(){var b=$("#"+this.id+"Table"),a=this;b.css("height",d(b)+"px");window.clearTimeout(this.resizeTimeout);this.resizeTimeout=window.setTimeout(function(){a.table.resizeCanvas()},50)};b.prototype.destroy=function(){this.destroyed=!0;h(this.id);$(window).unbind("resize");this.table&&(this.table.pager&&(this.table.pager.destroy(),this.table.pager=null),this.table.columnsResizedFn&&(this.table.onColumnsResized.unsubscribe(this.table.columnsResizedFn),
this.table.columnsResizedFn=null),this.table.destroy())};b.prototype.initialize=function(){var b=this;this.initialized||(this.initialized=!0,this.options.defaultSort&&($.isArray(this.options.defaultSort)?this.table.setSortColumns(this.options.defaultSort):this.table.setSortColumns([this.options.defaultSort])),$.isArray(this.options.plugins)&&$.each(this.options.plugins,function(a,k){b.table.registerPlugin(k)}),this.table.registerPlugin(new Slick.Sort),this.table.init(),this.options.disableFilter||
this.table.registerPlugin(this.filter),this.table.registerPlugin(new Slick.BootstrapTooltip),$(window).resize(this.options.resizeFn||function(){Insight.util.isNullOrUndefined(b.options.height)&&b.updateHeight()}),this.listeners&&($.each(this.listeners,function(b,a){setTimeout(a,0)}),this.listeners=null))};b.prototype.processData=function(b){var a=this;this.initialize();Insight.util.isNotNullOrUndefined(b)&&(this.options.dataProcessor&&(b.aaData=this.options.dataProcessor.call(null,b.aaData)),this.dataView.beginUpdate(),
this.dataView.setItems(b.aaData),this.options.disableFilter||(this.options.externalFilters?this.dataView.setFilter(function(b,c){var l=!0;$.each(a.options.externalFilters,function(a,e){e(b,c)||(l=!1);return l});return l&&a.filter.getFilter()(b,c)}):this.dataView.setFilter(this.filter.getFilter())),this.options.groupInfo&&this.dataView.groupBy(this.options.groupInfo.field,this.options.groupInfo.groupHeaderFn,this.options.groupInfo.groupingComparer),this.dataView.endUpdate(),this.options.groupInfo&&
"collapsed"===this.options.groupInfo.initialState&&(this.dataView.beginUpdate(),$.each(this.dataView.getGroups(),function(b,c){a.dataView.collapseGroup(c.value)}),this.dataView.endUpdate()));h(this.id);(Insight.util.isNullOrUndefined(b)||0===b.aaData.length)&&f(this.id,this.options.emptyText||"None");this.options.disablePager||(this.table.pager=new Slick.Controls.Pager(this.dataView,this.table,$("#"+this.id+"TablePager")))};b.prototype.addMessage=function(b,a,k){var g=this,l=$('\x3cdiv class\x3d"alert"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3e\x3c/div\x3e');
l.addClass(a);l.append("\x3cspan\x3e\x3c/span\x3e").text(b);l.bind("closed",function(){g.updateHeight()});$("#"+g.id+"container").prepend(l);g.updateHeight();k&&setTimeout(function(){l.fadeOut("fast",function(){l.remove();g.updateHeight()})},1E3*k);return l};b.prototype.addLoadListener=function(b){this.table?setTimeout(b,0):(this.listeners=this.listeners||[],this.listeners.push(b))};b.prototype.addSuccess=function(b,a){this.addMessage(b,"alert-success",a)};b.prototype.addError=function(b,a){this.addMessage(b,
"alert-error",a)};$.extend(!0,window,{Insight:{Table:b}})})();
(function(){function d(){return a||c}function h(b,a){$("#"+b+"container .message").remove();$(window).unbind("resize");a.pager&&(a.pager.destroy(),a.pager=null);a.columnsResizedFn&&(a.onColumnsResized.unsubscribe(a.columnsResizedFn),a.columnsResizedFn=null);a.destroy()}var f={id:"coordinates",name:"Component",field:"coordinates",sortable:!0,width:295,toolTipGravity:"se",formatter:function(b,a,c,l,d){return(d.componentIdentifier?'\x3cimg src\x3d"public/coord-component.png" title\x3d"'+d.componentIdentifier.format+
'"/\x3e ':'\x3cimg src\x3d"public/coord-unknown.png" alt\x3d"Unknown"/\x3e ')+Insight.util.encodeHtml($.map(d.displayName.parts,function(b){return b.value}).join(""))}},b=function(b){b=b||[];$.each(b,function(b,a){Insight.util.isNullOrUndefined(a.componentIdentifier)&&Insight.util.isNotNullOrUndefined(a.groupId)&&(a.componentIdentifier={format:"maven",coordinates:{groupId:a.groupId,artifactId:a.artifactId,version:a.version}});if(Insight.util.isNullOrUndefined(a.displayName))if(a.displayName={},Insight.util.isNotNullOrUndefined(a.componentIdentifier)){var c=
a.componentIdentifier.coordinates;switch(a.componentIdentifier.format){case "maven":a.displayName.parts=[{field:"Group",value:c.groupId},{value:" : "},{field:"Artifact",value:c.artifactId},{value:" : "},{field:"Version",value:c.version}];break;case "nuget":a.displayName.parts=[{field:"ID",value:c.packageId},{value:" "},{field:"Version",value:c.version}];break;default:a.displayName.parts=[];for(var e in c)c.hasOwnProperty(e)&&(a.displayName.parts.push({field:e,value:c[e]}),a.displayName.parts.push({value:" : "}));
a.displayName.parts.pop()}}else if(a.filenames&&0<a.filenames.length)for(a.displayName.parts=[],c=0;c<a.filenames.length;c++)a.displayName.parts.push({field:"Filename",value:a.filenames[c]}),c<a.filenames.length-1&&a.displayName.parts.push({value:", "});else a.displayName.parts=[{value:"(Anonymized Path) SHA1: "},{field:"Hash",value:a.hash}];a.coordinates=$.map(a.displayName.parts,function(a){return a.value}).join("")})},a=null,c=null;$.extend(!0,window,{InsightDatatable:{createComponentTable:function(a){var d=
[$.extend({},f,{formatter:function(a,b,c,e,d){return'\x3cspan style\x3d"padding-right:20px"\x3e\x3c/span\x3e'+f.formatter(a,b,c,e,d)}}),{id:"filename",name:"Filename",field:"filename",width:110,sortable:!0,filterable:!0}];c=new Insight.Table("component",{get:function(){var a=$.Deferred(),b=[$.getJSON("bom.json")];$.when.apply($,b).done(function(b){if(null===b)a.reject([]);else{var c=[];$.each(b.aaData,function(a,b){c.push(b)});a.resolve({aaData:c})}}).fail(function(b){a.reject(b)});return a}},{columns:d,
config:a,multiColumnSort:!0,selectable:!0,plugins:[new Insight.InformationPanel({byHash:!0})],defaultSort:[{columnId:"coordinates",sortAsc:!0}],dataProcessor:function(a){a=a||[];$.each(a,function(a,b){b.id=a;b.filename=(b.filenames||[]).slice().sort().pop()||""});b(a);return a}})},createSecurityTable:function(c){var d=new Slick.ColumnGrouping({columnId:"_score",style:"scoreCol"}),g=d.getCellStyler(),l=d.getCellRenderer(),h=[{id:"_score",name:"Threat Level",shortName:"Level",field:"_score",sortable:!0,
width:120,toolTip:"'Threat Level' highlights the CVSS (Common Vulnerability Scoring System, version 2) base score for each listed vulnerability.",toolTipGravity:"w",styleFn:function(a,b,c,d,e){return"nopad "+g(a,b,c,d,e)},sortFn:function(a,b){var c=a._score,d=b._score;return isNaN(c)||isNaN(d)?d<c?-1:d>c?1:0:parseInt(c,10)-parseInt(d,10)},formatter:function(a,b,c,d,e){return'\x3cdiv class\x3d"'+(7<=c?" criticalScore":4<=c?" severeScore":" moderateScore")+'"\x3e'+(l(a,b,c,d,e)||"\x26nbsp;")+"\x3c/div\x3e"}},
{id:"problemCode",name:"Problem Code",shortName:"Code",field:"_reference",sortable:!0,width:105,formatter:function(a,b,c,d,e){a=e._reference;return Insight.util.isNullOrUndefined(a)?"":'\x3ca href\x3d"'+e.url+'" target\x3d"_blank"\x3e'+a+"\x3c/a\x3e"}},f,{id:"filename",name:"Filename",field:"filename",width:150,sortable:!0,filterable:!0}],d=[d,new Insight.InformationPanel],n=[];Insight.util.showVulnerabilityDetail()&&n.push({event:"onClick",handler:function(a,b){if($(a.target).hasClass("vulnerability-info-link")){a.stopPropagation();
var c=b.grid.getDataItem(b.row);Insight.util.showSvModal(c.source,c.reference,c.componentIdentifier,c.hash);return!1}return!0}});a=new Insight.Table("security",{get:function(){return $.when($.get("security.json"),$.get("bom.json")).pipe(function(a,b){var c={};b[0].aaData.forEach(function(a){c[a.hash]=a.filenames});a[0].aaData.forEach(function(a){a.filename=(c[a.hash]||[]).slice().sort().pop()||""});return a[0]})}},{columns:h,config:c,defaultSort:{columnId:"_score",sortAsc:!1},dataProcessor:function(a){for(var c=
0;c<a.length;c++)a[c].id=c,a[c]._score=Insight.util.isNullOrUndefined(a[c].score)?"Unscored":String(Math.floor(a[c].score)),a[c]._reference=Insight.util.toSvReference(a[c].source,a[c].reference),a[c].status=Insight.util.isNullOrUndefined(a[c].status)?"Open":a[c].status;b(a);return a},plugins:d,handlers:n});a.addLoadListener(function(){a.table.setSelectionModel(new Slick.RowSelectionModel)});return a},destroyActiveTable:function(){var b=d();b&&b.destroy();c=a=null},getActiveTable:d,removeComponentTable:function(){Insight.util.isNotNullOrUndefined(c)&&
(h("component",c),$("#componentcontainer ul.nav a").unbind("click"),c=null)},removeSecurityTable:function(){Insight.util.isNotNullOrUndefined(a)&&(h("security",a),a=null)}}})})();
(function(d){function h(b,e,k,g,l,h){var n=[],p=[],m=Brain.getCsrfHeaders?Brain.getCsrfHeaders():{};d.each(e,function(a,b){var c=d.extend({},b);d.each(k,function(a,b){c[a]=b});c.modified=!0;n.push(c)});d.merge(p,g);d.each(k,function(a,b){p.push(a)});d.ajax({type:"POST",url:"../augmentData/bom.json",data:f(n,d.merge(["modified"],a)),headers:m});d.ajax({type:"POST",url:"../augmentData/"+l,data:f(n,p),headers:m}).done(function(){b.beginUpdate();d.each(n,function(a,d){b.updateItem(d.id,d)});b.endUpdate();
Insight.updateSummary();h()}).fail(function(a,b,c){c=Insight.util.getErrorMessage(a);h(c)})}function f(a,b){for(var d=[],g=0;g<a.length;g++){var f=a[g],h={componentIdentifier:f.componentIdentifier};Insight.util.isNotNullOrUndefined(f.componentIdentifier)&&"maven"===f.componentIdentifier.format&&(h.groupId=f.componentIdentifier.coordinates.groupId,h.artifactId=f.componentIdentifier.coordinates.artifactId,h.version=f.componentIdentifier.coordinates.version);for(var n=0;n<b.length;n++)h[b[n]]=f[b[n]];
d.push(h)}return JSON.stringify(d)}var b=["source","reference"],a=["hash"];d.extend(!0,window,{InsightDatatable:{addSecurityTableEditor:function(a){a=a.table;var b=a.getColumns();a.setSelectionModel(new Slick.RowSelectionModel);a.getData().syncGridSelection(a,!0);a.setColumns(b)},updateSecurity:function(a){a=d.extend({dataView:null,items:[],mask:{},callback:d.noop},a);d.isArray(a.items)||(a.items=[a.items]);h(a.dataView,a.items,a.mask,b,"security.json",a.callback)}}})})(jQuery);