/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
package com.sonatype.insight.brain.api.v2.dto.githubapp;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;
import java.util.Map;

/**
 * DTO for GitHub App manifest.
 *
 * This manifest is used to register a new GitHub App via the GitHub App Manifest flow.
 * Field names use snake_case to match GitHub's API expectations.
 *
 * <p>
 * {@code hook_attributes} is optional; when present it directs GitHub to configure the App's
 * webhook URL at creation time so the customer never has to paste it in. When the relay
 * integration is enabled, the URL points at the relay's App-level webhook endpoint and the
 * webhook secret is generated by GitHub and returned alongside the App credentials in the
 * manifest-conversion response.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public record Manifest(
    String name,
    String url,
    String redirect_url,
    String setup_url,
    List<String> callback_urls,
    Boolean request_oauth_on_install,
    String description,
    @JsonProperty("public") Boolean isPublic,
    Map<String, String> default_permissions,
    Boolean setup_on_update,
    HookAttributes hook_attributes,
    List<String> default_events)
{
  /**
   * Webhook configuration the App will be created with. {@code url} is the endpoint GitHub
   * delivers webhooks to; {@code active} controls whether deliveries fire.
   */
  public record HookAttributes(String url, Boolean active)
  {
  }
}
