<!--

    Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
    Includes the third-party code listed at http://links.sonatype.com/products/insight/attributions.
    "Sonatype" is a trademark of Sonatype, Inc.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sonatype.insight.brain</groupId>
    <artifactId>insight-brain</artifactId>
    <version>0.1-SNAPSHOT</version>
  </parent>

  <artifactId>insight-brain-client</artifactId>
  <name>Insight Brain Client</name>

  <dependencies>
    <dependency>
      <groupId>org.codehaus.jackson</groupId>
      <artifactId>jackson-mapper-asl</artifactId>
      <version>${jackson.version}</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-model</artifactId>
      <version>0.1-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-client-utils</artifactId>
      <version>${insight-scanner.version}</version>
    </dependency>
    
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-service</artifactId>
      <version>0.1-SNAPSHOT</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-service</artifactId>
      <version>0.1-SNAPSHOT</version>
      <classifier>tests</classifier>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-mock-server</artifactId>
      <version>${insight-scanner.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
