/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */

export const AUTOMATED_REMEDIATION_STATUS = {
  MANUAL_PULL_REQUEST_POSSIBLE: 'MANUAL_PULL_REQUEST_POSSIBLE',
  MANUAL_PULL_REQUEST_NOT_POSSIBLE: 'MANUAL_PULL_REQUEST_NOT_POSSIBLE',
  PULL_REQUEST_CREATION_PENDING: 'PULL_REQUEST_CREATION_PENDING',
  PULL_REQUEST_CREATION_FAILED: 'PULL_REQUEST_CREATION_FAILED',
  PULL_REQUEST: 'PULL_REQUEST',
};

export const MANUAL_PULL_REQUEST_NOT_POSSIBLE_REASONS = {
  UNSUPPORTED_STAGE: 'UNSUPPORTED_STAGE',
  UNSUPPORTED_DEPENDENCY_TYPE: 'UNSUPPORTED_DEPENDENCY_TYPE',
  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',
  REMEDIATION_EVENT_EXISTS: 'REMEDIATION_EVENT_EXISTS',
  NO_REMEDIATION_VERSION_AVAILABLE: 'NO_REMEDIATION_VERSION_AVAILABLE',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  CONFIGURATION_DISABLED: 'CONFIGURATION_DISABLED',
  SCM_NOT_CONFIGURED: 'SCM_NOT_CONFIGURED',
  NOT_SUPPORTED_FOR_LICENSE: 'NOT_SUPPORTED_FOR_LICENSE',
  NOT_SUPPORTED_FOR_PROVIDER: 'NOT_SUPPORTED_FOR_PROVIDER',
  NOT_SUPPORTED_FOR_REPOSITORY: 'NOT_SUPPORTED_FOR_REPOSITORY',
  UNSUPPORTED_OWNER_TYPE: 'UNSUPPORTED_OWNER_TYPE',
  NOT_SUPPORTED_FOR_MTIQ: 'NOT_SUPPORTED_FOR_MTIQ',
  NON_DEFAULT_BRANCH: 'NON_DEFAULT_BRANCH',
};
