/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
export const mockResponse_Application_All_Local = [
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'LocalWaiver1',
    autoPolicyWaiverOwnerId: 'Application1',
    autoPolicyWaiverOwnerName: 'Application1',
    autoPolicyWaiverOwnerType: 'application',
    createTime: 1743599003798,
    threatLevel: 5,
    hasNotReachable: false,
    hasNoPathForward: true,
    scopesOperatorAny: true,
  },
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'LocalWaiver2',
    autoPolicyWaiverOwnerId: 'Application1',
    autoPolicyWaiverOwnerName: 'Application1',
    autoPolicyWaiverOwnerType: 'application',
    createTime: 1743599003800,
    threatLevel: 6,
    hasNotReachable: true,
    hasNoPathForward: false,
    scopesOperatorAny: false,
  },
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'LocalWaiver3',
    autoPolicyWaiverOwnerId: 'Application1',
    autoPolicyWaiverOwnerName: 'Application1',
    autoPolicyWaiverOwnerType: 'application',
    createTime: 1743599003802,
    threatLevel: 7,
    hasNotReachable: false,
    hasNoPathForward: true,
    scopesOperatorAny: true,
  },
];

export const mockResponse_Application_Local_RootOrg = [
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'LocalWaiver1',
    autoPolicyWaiverOwnerId: 'Application1',
    autoPolicyWaiverOwnerName: 'Application1',
    autoPolicyWaiverOwnerType: 'application',
    createTime: 1743599003798,
    threatLevel: 5,
    hasNotReachable: false,
    hasNoPathForward: true,
    scopesOperatorAny: true,
  },
  {
    isAutoWaiverEnabled: true,
    isInherited: true,
    autoPolicyWaiverId: 'InheritedWaiver1',
    autoPolicyWaiverOwnerId: 'ROOT_ORGANIZATION',
    autoPolicyWaiverOwnerName: 'Root Organization',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003800,
    threatLevel: 6,
    hasNotReachable: true,
    hasNoPathForward: false,
    scopesOperatorAny: false,
  },
  {
    isAutoWaiverEnabled: true,
    isInherited: true,
    autoPolicyWaiverId: 'InheritedWaiver2',
    autoPolicyWaiverOwnerId: 'ROOT_ORGANIZATION',
    autoPolicyWaiverOwnerName: 'Root Organization',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003802,
    threatLevel: 7,
    hasNotReachable: false,
    hasNoPathForward: true,
    scopesOperatorAny: true,
  },
];

export const mockResponse_Application_Local_Org_RootOrg = [
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'LocalWaiver1',
    autoPolicyWaiverOwnerId: 'Application1',
    autoPolicyWaiverOwnerName: 'Application1',
    autoPolicyWaiverOwnerType: 'application',
    createTime: 1743599003798,
    threatLevel: 5,
    hasNotReachable: false,
    hasNoPathForward: true,
    scopesOperatorAny: true,
  },
  {
    isAutoWaiverEnabled: true,
    isInherited: true,
    autoPolicyWaiverId: 'InheritedWaiver1',
    autoPolicyWaiverOwnerId: 'Test_Org',
    autoPolicyWaiverOwnerName: 'Test Organization',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003800,
    threatLevel: 6,
    hasNotReachable: true,
    hasNoPathForward: false,
    scopesOperatorAny: false,
  },
  {
    isAutoWaiverEnabled: true,
    isInherited: true,
    autoPolicyWaiverId: 'InheritedWaiver2',
    autoPolicyWaiverOwnerId: 'ROOT_ORGANIZATION',
    autoPolicyWaiverOwnerName: 'Root Organization',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003802,
    threatLevel: 7,
    hasNotReachable: false,
    hasNoPathForward: true,
    scopesOperatorAny: true,
  },
];

export const mockResponse_Organization_Local = [
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'OrgLocalWaiver1',
    autoPolicyWaiverOwnerId: 'Organization1',
    autoPolicyWaiverOwnerName: 'Organization1',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003798,
    threatLevel: 5,
    hasNotReachable: false,
    hasNoPathForward: true,
    scopesOperatorAny: true,
  },
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'OrgLocalWaiver2',
    autoPolicyWaiverOwnerId: 'Organization1',
    autoPolicyWaiverOwnerName: 'Organization1',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003800,
    threatLevel: 6,
    hasNotReachable: true,
    hasNoPathForward: false,
    scopesOperatorAny: false,
  },
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'OrgLocalWaiver3',
    autoPolicyWaiverOwnerId: 'Organization1',
    autoPolicyWaiverOwnerName: 'Organization1',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003802,
    threatLevel: 7,
    hasNotReachable: false,
    hasNoPathForward: true,
    scopesOperatorAny: true,
  },
];

export const mockResponse_Organization_Local_RootOrg = [
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'OrgLocalWaiver1',
    autoPolicyWaiverOwnerId: 'Organization1',
    autoPolicyWaiverOwnerName: 'Organization1',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003798,
    threatLevel: 5,
    hasNotReachable: false,
    hasNoPathForward: true,
    scopesOperatorAny: true,
  },
  {
    isAutoWaiverEnabled: true,
    isInherited: true,
    autoPolicyWaiverId: 'InheritedWaiver1',
    autoPolicyWaiverOwnerId: 'ROOT_ORGANIZATION',
    autoPolicyWaiverOwnerName: 'Root Organization',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003800,
    threatLevel: 6,
    hasNotReachable: true,
    hasNoPathForward: false,
    scopesOperatorAny: false,
  },
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'OrgLocalWaiver2',
    autoPolicyWaiverOwnerId: 'Organization1',
    autoPolicyWaiverOwnerName: 'Organization1',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003802,
    threatLevel: 7,
    hasNotReachable: false,
    hasNoPathForward: true,
    scopesOperatorAny: true,
  },
];

export const mockResponse_RootOrg_Local = [
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'RootLocalWaiver1',
    autoPolicyWaiverOwnerId: 'ROOT_ORGANIZATION',
    autoPolicyWaiverOwnerName: 'Root Organization',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003798,
    threatLevel: 5,
    hasNotReachable: false,
    hasNoPathForward: true,
    scopesOperatorAny: true,
  },
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'RootLocalWaiver2',
    autoPolicyWaiverOwnerId: 'ROOT_ORGANIZATION',
    autoPolicyWaiverOwnerName: 'Root Organization',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003800,
    threatLevel: 6,
    hasNotReachable: true,
    hasNoPathForward: false,
    scopesOperatorAny: false,
  },
  {
    isAutoWaiverEnabled: true,
    isInherited: false,
    autoPolicyWaiverId: 'RootLocalWaiver3',
    autoPolicyWaiverOwnerId: 'ROOT_ORGANIZATION',
    autoPolicyWaiverOwnerName: 'Root Organization',
    autoPolicyWaiverOwnerType: 'organization',
    createTime: 1743599003802,
    threatLevel: 7,
    hasNotReachable: false,
    hasNoPathForward: true,
    scopesOperatorAny: true,
  },
];
