/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */

export const hostedRepoItems = [
  {
    id: 'id1',
    repositoryManagerId: 'repoManagerId1',
    publicId: 'publicId1',
    repositoryType: 'hosted',
    auditEnabled: false,
    quarantineEnabled: false,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: true,
    format: 'maven',
  },
  {
    id: 'id2',
    repositoryManagerId: 'repoManagerId2',
    publicId: 'publicId2',
    repositoryType: 'hosted',
    auditEnabled: false,
    quarantineEnabled: false,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: true,
    format: 'maven',
  },
  {
    id: 'id3',
    repositoryManagerId: 'repoManagerId3',
    publicId: 'publicId3',
    repositoryType: 'hosted',
    auditEnabled: false,
    quarantineEnabled: false,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: false,
    format: 'maven',
  },
  {
    id: 'id4',
    repositoryManagerId: 'repoManagerId4',
    publicId: 'publicId4',
    repositoryType: 'hosted',
    auditEnabled: false,
    quarantineEnabled: false,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: false,
    format: 'npm',
  },
  {
    id: 'id5',
    repositoryManagerId: 'repoManagerId5',
    publicId: 'publicId5',
    repositoryType: 'hosted',
    auditEnabled: false,
    quarantineEnabled: false,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: false,
    format: 'npm',
  },
  {
    id: 'id6',
    repositoryManagerId: 'repoManagerId6',
    publicId: 'publicId6',
    repositoryType: 'hosted',
    auditEnabled: false,
    quarantineEnabled: false,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: false,
    format: 'go',
  },
  {
    id: 'id7',
    repositoryManagerId: 'repoManagerId7',
    publicId: 'publicId7',
    repositoryType: 'hosted',
    auditEnabled: false,
    quarantineEnabled: false,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: false,
    format: 'pypi',
  },
];

export const proxyRepoItems = [
  {
    id: 'id1',
    repositoryManagerId: 'repoManagerId1',
    publicId: 'publicId1',
    repositoryType: 'proxy',
    auditEnabled: true,
    quarantineEnabled: true,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: false,
    format: 'maven',
  },
  {
    id: 'id2',
    repositoryManagerId: 'repoManagerId2',
    publicId: 'publicId2',
    repositoryType: 'proxy',
    auditEnabled: true,
    quarantineEnabled: false,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: false,
    format: 'maven',
  },
  {
    id: 'id3',
    repositoryManagerId: 'repoManagerId3',
    publicId: 'publicId3',
    repositoryType: 'proxy',
    auditEnabled: true,
    quarantineEnabled: true,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: false,
    format: 'maven',
  },
  {
    id: 'id4',
    repositoryManagerId: 'repoManagerId4',
    publicId: 'publicId4',
    repositoryType: 'proxy',
    auditEnabled: true,
    quarantineEnabled: false,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: false,
    format: 'npm',
  },
  {
    id: 'id5',
    repositoryManagerId: 'repoManagerId5',
    publicId: 'publicId5',
    repositoryType: 'proxy',
    auditEnabled: true,
    quarantineEnabled: false,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: false,
    format: 'npm',
  },
  {
    id: 'id6',
    repositoryManagerId: 'repoManagerId6',
    publicId: 'publicId6',
    repositoryType: 'proxy',
    auditEnabled: true,
    quarantineEnabled: false,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: false,
    format: 'go',
  },
  {
    id: 'id7',
    repositoryManagerId: 'repoManagerId7',
    publicId: 'publicId7',
    repositoryType: 'proxy',
    auditEnabled: true,
    quarantineEnabled: false,
    policyCompliantComponentSelectionEnabled: false,
    namespaceConfusionProtectionEnabled: false,
    format: 'pypi',
  },
];
