<!--

    Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
    Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
    "Sonatype" is a trademark of Sonatype, Inc.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sonatype.insight.brain</groupId>
    <artifactId>insight-brain</artifactId>
    <version>1.121.0-SNAPSHOT</version>
  </parent>
  <artifactId>insight-brain-functional-test</artifactId>

  <properties>
    <clm.skip>true</clm.skip>
    <it.includes>**/*Spec.*</it.includes>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-compiler</artifactId>
            <version>3.3.0-01</version>
          </dependency>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-batch</artifactId>
            <version>2.4.16-03</version>
          </dependency>
        </dependencies>
        <configuration>
          <!-- Enable Groovy compilation. -->
          <compilerId>groovy-eclipse-compiler</compilerId>
        </configuration>
      </plugin>
      <!-- Make surefire aware of Spec tests -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <!--
            Don't halt on failures, so that the damage control report can pick up the test results.
            CI builds set this to true so that it can analyze the test results.
            If you want to use it locally then pass the property maven.test.failure.ignore to the build.
            
            <testFailureIgnore>true</testFailureIgnore>
          -->
          <excludes>
            <!-- Examples to be run as individual tests from Maven CLI or IDE. -->
            <exclude>**/example/**</exclude>
          </excludes>
          <includes>
            <include>${it.includes}</include>
          </includes>
          <systemPropertyVariables>
            <slowmo.enable>true</slowmo.enable>
            <phantomjs.binary.path>${phantomjs.binary}</phantomjs.binary.path>
            <!--
              Defined in GebConfig.groovy so that tests can be executed in Eclipse or from Maven CLI.
            -->
            <!-- <geb.build.reportsDir>${project.build.directory}/test-reports/geb</geb.build.reportsDir> -->
            <!-- <geb.build.baseUrl>http://localhost:8070/</geb.build.baseUrl> -->
          </systemPropertyVariables>
          <trimStackTrace>false</trimStackTrace>
        </configuration>
      </plugin>
      <!--
        A nice report using the Spock blocks
        https://github.com/damage-control/
      -->
      <plugin>
        <groupId>com.github.damage-control.report</groupId>
        <artifactId>damage-control-maven-plugin</artifactId>
        <version>1.1.0</version>
        <configuration>
          <skip>${skipTests}</skip>
          <specDefinitionsFolder>${project.build.testSourceDirectory}</specDefinitionsFolder>
        </configuration>
        <executions>
          <execution>
            <phase>test</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.github.klieber</groupId>
        <artifactId>phantomjs-maven-plugin</artifactId>
      </plugin>
    </plugins>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.eclipse.m2e</groupId>
          <artifactId>lifecycle-mapping</artifactId>
          <version>1.0.0</version>
          <configuration>
            <lifecycleMappingMetadata>
              <pluginExecutions>
                <pluginExecution>
                  <pluginExecutionFilter>
                    <groupId>com.github.klieber</groupId>
                    <artifactId>phantomjs-maven-plugin</artifactId>
                    <versionRange>[0.1,)</versionRange>
                    <goals>
                      <goal>install</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <ignore />
                  </action>
                </pluginExecution>
              </pluginExecutions>
            </lifecycleMappingMetadata>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <dependencies>
    <!-- Creation of page objects in main code. -->
    <dependency>
      <groupId>org.gebish</groupId>
      <artifactId>geb-core</artifactId>
      <version>${geb.version}</version>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-support</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-json-store</artifactId>
    </dependency>
    <!-- Mandatory dependencies for using Spock -->
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-all</artifactId>
    </dependency>
    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- Geb browser automation -->
    <dependency>
      <groupId>org.gebish</groupId>
      <artifactId>geb-spock</artifactId>
      <version>${geb.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-firefox-driver</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-chrome-driver</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-safari-driver</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-ie-driver</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.codeborne</groupId>
      <artifactId>phantomjsdriver</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- DW testing to start services -->
    <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-testing</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- The app to test against -->
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-service</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-data</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-data</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-service</artifactId>
      <classifier>tests</classifier>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>hds-mock-server</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.clm</groupId>
      <artifactId>com.sonatype.clm.dto.model</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.portal</groupId>
      <artifactId>insight-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <profiles>
    <!--
      Allows build of 'functional-test' to be disabled; required for build-automation optimizations.
    -->
    <profile>
      <id>exclude-functional-test</id>
      <activation>
        <property>
          <name>skip-functional-test</name>
          <value>true</value>
        </property>
      </activation>
      <properties>
        <skipTests>true</skipTests>
      </properties>
    </profile>
  </profiles>
</project>
