#!/bin/sh
#
# Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
# Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
# "Sonatype" is a trademark of Sonatype, Inc.
#
echo
exec powershell.exe -ExecutionPolicy RemoteSigned -File '.\githooks\windows\pre-push.ps1'
exit
