#!/bin/bash

# Define colors for output
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

# Get all staged files
staged_files=$(git diff --cached --name-only --diff-filter=d insight-brain-frontend/)

# Filter JavaScript, JSX, CSS, SCSS, and Markdown files
js_files=$(echo "$staged_files" | grep -E '\.(js|jsx)$')
css_scss_files=$(echo "$staged_files" | grep -E '\.(css|scss)$')
md_files=$(echo "$staged_files" | grep -E '\.md$')

# Run Prettier on the filtered files
if [ -n "$js_files" ] || [ -n "$css_scss_files" ] || [ -n "$md_files" ]; then
  found_files=true
  echo -e "${GREEN}Running Prettier...${NC}"
  echo "$js_files"$'\n'"$css_scss_files"$'\n'"$md_files" | \
    grep -v '^$' | \
    tr '\n' '\0' | \
    xargs -0 ./insight-brain-frontend/node_modules/.bin/prettier --write
  prettier_exit_code=$?
else
  prettier_exit_code=0
fi

# Check if Prettier succeeded
if [ $prettier_exit_code -ne 0 ]; then
  echo -e "${RED}Prettier failed.${NC}"
  exit 1
else
  if [ "$found_files" = true ]; then
    echo -e "${GREEN}Prettier succeeded.${NC}"
  fi
fi

# Add the formatted files back to the staging area
echo "$js_files"$'\n'"$css_scss_files"$'\n'"$md_files" | \
  grep -v '^$' | \
  tr '\n' '\0' | \
  xargs -0 git add

exit 0
