<!--

    Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
    Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
    "Sonatype" is a trademark of Sonatype, Inc.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sonatype.insight.brain</groupId>
    <artifactId>insight-brain</artifactId>
    <version>1.133.0-SNAPSHOT</version>
  </parent>
  <artifactId>insight-brain-java-functional-test</artifactId>

  <properties>
    <skip.functional.tests>false</skip.functional.tests>
    <clm.skip>true</clm.skip>
    <it.includes>**/*Test.*</it.includes>
    <selenide.driverManagerEnabled>false</selenide.driverManagerEnabled>
    <selenide.timeout>4000</selenide.timeout>
  </properties>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <configuration>
          <includes>
            <include>${it.includes}</include>
          </includes>
          <trimStackTrace>false</trimStackTrace>
          <skipITs>${skip.functional.tests}</skipITs>

          <!--
               Starting a separate JVM for each test class is both slow and problematic when it comes to generating
               run timestamps for use as applitools batch ids, so reuse the same JVM.
          -->
          <reuseForks>true</reuseForks>
          <forkedProcessTimeoutInSeconds>0</forkedProcessTimeoutInSeconds>
          <systemPropertyVariables>
            <slowmo.enable>true</slowmo.enable>
            <selenide.browserSize>1400x1050</selenide.browserSize>
            <selenide.driverManagerEnabled>${selenide.driverManagerEnabled}</selenide.driverManagerEnabled>
            <selenide.timeout>${selenide.timeout}</selenide.timeout>
            <browser>chrome</browser>
          </systemPropertyVariables>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>com.codeborne</groupId>
      <artifactId>selenide</artifactId>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-support</artifactId>
      <exclusions>
        <exclusion>
          <!-- help conflict resolution pick newer version referenced by mockito -->
          <groupId>net.bytebuddy</groupId>
          <artifactId>byte-buddy</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-json-store</artifactId>
    </dependency>
    <dependency>
      <groupId>javax.ws.rs</groupId>
      <artifactId>javax.ws.rs-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- DW testing to start services -->
    <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-testing</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- The app to test against -->
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-service</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-data</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-data</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-service</artifactId>
      <classifier>tests</classifier>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.directory.server</groupId>
      <artifactId>apacheds-core-integ</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>hds-mock-server</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.portal</groupId>
      <artifactId>insight-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-test-reverse-proxy</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.clm</groupId>
      <artifactId>com.sonatype.clm.dto.model</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.applitools</groupId>
      <artifactId>eyes-selenium-java3</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>keycloak-server</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jvnet.mock-javamail</groupId>
      <artifactId>mock-javamail</artifactId>
      <version>1.9</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>javax.mail</groupId>
          <artifactId>mail</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.github.tomakehurst</groupId>
      <artifactId>wiremock-jre8</artifactId>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>firefox</id>
      <activation>
        <property>
          <name>browser</name>
          <value>firefox</value>
        </property>
      </activation>
      <properties>
        <docker.image>standalone-firefox:${docker.image.version}</docker.image>
        <selenide.browser>firefox</selenide.browser>
      </properties>
    </profile>
    <profile>
      <id>docker-registry</id>
      <activation>
        <property>
          <name>docker.registry</name>
        </property>
      </activation>
      <properties>
        <docker.image.registry>${docker.registry}/</docker.image.registry>
      </properties>
    </profile>
    <profile>
      <id>docker-functional-tests</id>
      <activation>
        <property>
          <name>run-functional-tests</name>
          <value>docker</value>
        </property>
      </activation>
      <properties>
        <skip.functional.tests>false</skip.functional.tests>
        <selenide.timeout>8000</selenide.timeout>
      </properties>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <configuration>
              <argLine>@{argLine} -Duser.timezone=UTC</argLine>
              <systemPropertyVariables>
                <remote>http://${host}:${port}/wd/hub</remote>
                <applitoolsLogFileName>
                  ${project.parent.basedir}/test-group-${test.group}-docker.log
                </applitoolsLogFileName>
              </systemPropertyVariables>
            </configuration>
          </plugin>
          <plugin>
            <groupId>io.fabric8</groupId>
            <artifactId>docker-maven-plugin</artifactId>
            <version>0.31.0</version>
            <configuration>
              <skip>${skip.functional.tests}</skip>
              <images>
                <image>
                  <name>${docker.image.registry}selenium/${docker.image}</name>
                  <run>
                    <ports>
                      <port>+host:port:4444</port>
                    </ports>
                    <volumes>
                      <bind>
                        <volume>/dev/shm:/dev/shm</volume>
                      </bind>
                    </volumes>
                    <log>
                      <file>test-group-${test.group}-docker.log</file>
                    </log>
                  </run>
                </image>
              </images>
              <removeMode>all</removeMode>
            </configuration>
            <executions>
              <execution>
                <id>start-integration-test</id>
                <phase>pre-integration-test</phase>
                <goals>
                  <goal>start</goal>
                </goals>
              </execution>
              <execution>
                <id>stop-integration-test</id>
                <phase>post-integration-test</phase>
                <goals>
                  <goal>stop</goal>
                  <goal>remove</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>download-webdriver</id>
      <activation>
        <property>
          <name>!webdriver.chrome.driver</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-dependency-plugin</artifactId>
            <executions>
              <execution>
                <id>unpack-chromedriver</id>
                <phase>pre-integration-test</phase>
                <goals>
                  <goal>unpack</goal>
                </goals>
                <configuration>
                  <skip>${skip.functional.tests}</skip>
                  <artifactItems>
                    <artifactItem>
                      <groupId>org.chromium</groupId>
                      <artifactId>chromedriver</artifactId>
                      <version>91.0.4472.19</version>
                      <classifier>${chromedriver.classifier}</classifier>
                      <type>zip</type>
                    </artifactItem>
                  </artifactItems>
                  <outputDirectory>${project.build.directory}</outputDirectory>
                  <overWriteIfNewer>true</overWriteIfNewer>
                  <overWriteReleases>true</overWriteReleases>
                  <overWriteSnapshots>true</overWriteSnapshots>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <configuration>
              <systemPropertyVariables>
                <webdriver.chrome.driver>${webdriver.chrome.driver}</webdriver.chrome.driver>
              </systemPropertyVariables>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>windows</id>
      <activation>
        <os>
          <family>windows</family>
        </os>
      </activation>
      <properties>
        <chromedriver.classifier>windows</chromedriver.classifier>
        <webdriver.chrome.driver>${project.build.directory}/chromedriver.exe</webdriver.chrome.driver>
      </properties>
    </profile>
    <profile>
      <id>linux-x86</id>
      <activation>
        <os>
          <family>unix</family>
          <arch>x86</arch>
        </os>
      </activation>
      <properties>
        <chromedriver.classifier>linux32</chromedriver.classifier>
      </properties>
    </profile>
    <profile>
      <id>linux-i386</id>
      <activation>
        <os>
          <family>unix</family>
          <arch>i386</arch>
        </os>
      </activation>
      <properties>
        <chromedriver.classifier>linux32</chromedriver.classifier>
      </properties>
    </profile>
    <profile>
      <id>linux-64</id>
      <activation>
        <os>
          <family>unix</family>
          <arch>x64</arch>
        </os>
      </activation>
      <properties>
        <chromedriver.classifier>linux64</chromedriver.classifier>
      </properties>
    </profile>
    <profile>
      <id>linux-i686</id>
      <activation>
        <os>
          <family>unix</family>
          <arch>i686</arch>
        </os>
      </activation>
      <properties>
        <chromedriver.classifier>linux64</chromedriver.classifier>
      </properties>
    </profile>
    <profile>
      <id>linux-amd64</id>
      <activation>
        <os>
          <family>unix</family>
          <arch>amd64</arch>
        </os>
      </activation>
      <properties>
        <chromedriver.classifier>linux64</chromedriver.classifier>
      </properties>
    </profile>
    <profile>
      <id>osx</id>
      <activation>
        <os>
          <family>mac</family>
        </os>
      </activation>
      <properties>
        <chromedriver.classifier>mac64</chromedriver.classifier>
      </properties>
    </profile>
    <!--
      Allows build of 'functional-test' to be disabled; required for build-automation optimizations.
    -->
    <profile>
      <id>exclude-functional-test</id>
      <activation>
        <property>
          <name>skip-functional-test</name>
          <value>true</value>
        </property>
      </activation>
      <properties>
        <skipTests>true</skipTests>
      </properties>
    </profile>
  </profiles>
</project>
