<!--

    Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
    Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
    "Sonatype" is a trademark of Sonatype, Inc.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sonatype.insight.brain</groupId>
    <artifactId>insight-brain</artifactId>
    <version>1.104.0-SNAPSHOT</version>
  </parent>

  <artifactId>insight-brain-scanner</artifactId>
  <name>Insight Brain Scanner</name>

  <dependencies>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

    <dependency>
      <groupId>javax.inject</groupId>
      <artifactId>javax.inject</artifactId>
    </dependency>

    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-archive</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-model</artifactId>
    </dependency>
    
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-common</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.clm</groupId>
      <artifactId>com.sonatype.clm.dto.model</artifactId>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.sisu</groupId>
      <artifactId>org.eclipse.sisu.inject</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <id>uber-jar</id>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <createDependencyReducedPom>true</createDependencyReducedPom>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/sisu/javax.inject.Named</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/insight/configuration.properties</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/NOTICE</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/NOTICE.txt</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/LICENSE</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/LICENSE.txt</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
              </transformers>
              <artifactSet>
                <excludes>
                  <!-- for proper integration, allow host environment to override these -->
                  <exclude>*:slf4j-api</exclude>
                </excludes>
              </artifactSet>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                    <exclude>META-INF/maven/*/*/**</exclude>
                    <exclude>META-INF/maven/remote-resources.xml</exclude>
                    <exclude>META-INF/sisu/**</exclude>
                    <exclude>module-info.class</exclude>
                  </excludes>
                </filter>
              </filters>
              <relocations>
                <relocation>
                  <pattern>com.sonatype.insight.scan.</pattern>
                  <shadedPattern>zy.com.sonatype.insight.scan.</shadedPattern>
                  <excludes>
                    <exclude>com.sonatype.insight.scan.model.*</exclude>
                  </excludes>
                </relocation>
                <relocation>
                  <pattern>org.objectweb.</pattern>
                  <shadedPattern>zy.org.objectweb.</shadedPattern>
                </relocation>
              </relocations>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- We run the tests using maven-failsafe-plugin because we want to run them
           after the obfuscation was done and to use the artifact jar, not the classes. 
           (The obfuscation may break things in unexpected ways.)  -->
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <configuration>
          <includes>
            <include>**/*Test.*</include>
          </includes>
          <trimStackTrace>false</trimStackTrace>
          <reuseForks>true</reuseForks>
          <forkedProcessTimeoutInSeconds>0</forkedProcessTimeoutInSeconds>
          <!-- Exclude the dependencies we obfuscate in order to ensure the un-obfuscated code is not available. -->
          <classpathDependencyExcludes>
            <classpathDependencyExcludes>com.sonatype.insight.scan:insight-scanner-hashing*</classpathDependencyExcludes>
            <classpathDependencyExcludes>org.ow2.asm:asm*</classpathDependencyExcludes>
          </classpathDependencyExcludes>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>obfuscate</id>
      <activation>
        <property>
          <name>!skip-obfuscate</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.wvengen</groupId>
            <artifactId>proguard-maven-plugin</artifactId>
            <configuration>
              <exclusions>
                <exclusion>
                  <!-- already embedded/inlined into the program jar -->
                  <groupId>org.ow2.asm</groupId>
                  <artifactId>*</artifactId>
                </exclusion>
              </exclusions>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>seed-map</id>
                <phase>package</phase>
                <goals>
                  <goal>attach-artifact</goal>
                </goals>
                <configuration>
                  <artifacts>
                    <artifact>
                      <file>${project.build.directory}/proguard_seed.txt</file>
                      <classifier>seeds</classifier>
                      <type>txt</type>
                    </artifact>
                    <artifact>
                      <file>${project.build.directory}/proguard_map.txt</file>
                      <classifier>map</classifier>
                      <type>txt</type>
                    </artifact>
                  </artifacts>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
