# NOTE: Package name should not clash with similar proguard configuration in other modules
-repackageclasses zy

-dontusemixedcaseclassnames

-dontoptimize
-dontshrink
-dontnote

-dontwarn com.fasterxml.jackson.**
-dontwarn com.thoughtworks.xstream.**
-dontwarn de.schlichtherle.**
-dontwarn org.apache.**
-dontwarn org.bouncycastle.**
-dontwarn org.xml.**
-dontwarn javax.xml.**
-dontwarn org.w3c.**
-dontwarn org.cyclonedx.**
-dontwarn org.codehaus.groovy.**
-dontwarn groovy.servlet.**
-dontwarn groovy.util.**
-dontwarn groovy.test.**
-dontwarn groovy.mock.**
-dontwarn groovyjarjarasm.**

# 3rd party stuff excluded from obfuscation
-keep class !zy.com.sonatype.insight.**,!zy.org.objectweb.** { *; }

# API of this module and DTOs used by XStream to build the scan report XML
-keep class com.sonatype.insight.scan.model.* { *; }

# classes with prominent logging to retain their logger name
-keep public class zy.com.sonatype.insight.scan.**Scanner { *; }

-renamesourcefileattribute SourceFile
-keepattributes *Annotation*,Exceptions,InnerClasses,EnclosingMethod,Signature,SourceFile,LineNumberTable

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
