-repackageclasses zz

-dontusemixedcaseclassnames

-dontoptimize
-dontshrink
-dontnote

-dontwarn com.fasterxml.jackson.**
-dontwarn com.thoughtworks.xstream.**
-dontwarn de.schlichtherle.**
-dontwarn org.apache.**
-dontwarn org.bouncycastle.**

# 3rd party stuff excluded from obfuscation
-keep class !zz.com.sonatype.insight.**,!zz.org.objectweb.** { *; }

# DTOs used by XStream to build the scan report XML
-keepclassmembers public class zz.com.sonatype.insight.scan.model.* { *; }

# classes with prominent logging to retain their logger name
-keep public class zz.com.sonatype.insight.scan.**Scanner { *; }

# class used for API Third Party Scan
-keep public class com.sonatype.insight.scan.model.ItemContentType { *; }

# Custom JSON serializers and deserializers
-dontwarn com.sonatype.insight.scan.file.BowerProcessor*

-renamesourcefileattribute SourceFile
-keepattributes *Annotation*,Exceptions,InnerClasses,EnclosingMethod,Signature,SourceFile,LineNumberTable

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
