<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
    Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
    "Sonatype" is a trademark of Sonatype, Inc.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sonatype.insight.brain</groupId>
    <artifactId>insight-brain</artifactId>
    <version>1.152.0-SNAPSHOT</version>
  </parent>

  <artifactId>insight-brain-cli-common</artifactId>
  <name>Insight Brain CLI Common</name>

  <dependencies>
    <dependency>
      <groupId>javax.inject</groupId>
      <artifactId>javax.inject</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-model</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-model-io</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-archive</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-module-model</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-call-flow-analyzer</artifactId>
    </dependency>

    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-client</artifactId>
    </dependency>

    <dependency>
      <groupId>com.sonatype.nexus</groupId>
      <artifactId>nexus-git-utils</artifactId>
    </dependency>

    <dependency>
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-utils</artifactId>
    </dependency>

    <dependency>
      <groupId>com.beust</groupId>
      <artifactId>jcommander</artifactId>
    </dependency>

    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jcl-over-slf4j</artifactId>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>xmlpull</groupId>
      <artifactId>xmlpull</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.portal</groupId>
      <artifactId>insight-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
