<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
    Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
    "Sonatype" is a trademark of Sonatype, Inc.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.sonatype.insight.brain</groupId>
    <artifactId>nexus-iq-cli-native-image</artifactId>
    <version>1.100.0-SNAPSHOT</version>
  </parent>

  <artifactId>nexus-iq-cli-native-image-config</artifactId>
  <packaging>jar</packaging>

  <dependencies>
      <dependency>
        <groupId>com.sonatype.insight.brain</groupId>
        <artifactId>nexus-iq-cli</artifactId>
        <version>${project.version}</version>
        <scope>test</scope>
        <type>test-jar</type>
      </dependency>
      <dependency>
        <groupId>com.sonatype.insight.scan</groupId>
        <artifactId>insight-test-reverse-proxy</artifactId>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>com.sonatype.insight.brain</groupId>
        <artifactId>insight-brain-service</artifactId>
        <classifier>tests</classifier>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>com.sonatype.insight.brain</groupId>
        <artifactId>insight-brain-data</artifactId>
        <type>test-jar</type>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>com.sonatype.insight.brain</groupId>
        <artifactId>insight-brain-service</artifactId>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>com.sonatype.insight.brain</groupId>
        <artifactId>hds-mock-server</artifactId>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>com.sonatype.insight.portal</groupId>
        <artifactId>insight-test</artifactId>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>com.sonatype.insight.portal</groupId>
        <artifactId>insight-jaxrs-testing</artifactId>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.assertj</groupId>
        <artifactId>assertj-core</artifactId>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-core</artifactId>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-server</artifactId>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.eclipse.jetty</groupId>
        <artifactId>jetty-security</artifactId>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>com.github.stefanbirkner</groupId>
        <artifactId>system-rules</artifactId>
        <scope>test</scope>
      </dependency>
  </dependencies>

  <build>
    <plugins>
      <!-- Copy the nexus-iq-cli JAR to a known location so we can invoke it -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-nexus-iq-jar</id>
            <phase>process-resources</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>${project.groupId}</groupId>
                  <artifactId>nexus-iq-cli</artifactId>
                  <version>${project.version}</version>
                  <type>jar</type>
                  <destFileName>nexus-iq-cli.jar</destFileName>
                </artifactItem>
              </artifactItems>
              <outputDirectory>target/native-image-jar/</outputDirectory>
            </configuration>
          </execution>
          <!-- Extra required test resource files from nexus-iq-cli test jar -->
          <execution>
            <id>resource-dependencies</id>
            <phase>process-resources</phase>
            <goals>
              <goal>unpack-dependencies</goal>
            </goals>
            <configuration>
              <includeArtifactIds>nexus-iq-cli</includeArtifactIds>
              <includeScope>test</includeScope>
              <includes>**/ExpandedCoveragePolicyEvaluatorTest/**,small-report.zip,logback-test.xml</includes>
              <outputDirectory>${project.build.directory}/test-classes</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
