/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
export const ROOT_ORGANIZATION_ID = 'ROOT_ORGANIZATION_ID';
export const ROOT_ORGANIZATION_NAME = 'Root Organization';
export const ORGANIZATION_ID = 'someOrganizationId';
export const ORGANIZATION_NAME = 'Some non root organization';
export const APPLICATION_ID = 'someApplicationId';
export const APPLICATION_NAME = 'Some application';

export const applicationsResponse = {
  id: APPLICATION_ID,
  publicId: APPLICATION_ID,
  name: APPLICATION_NAME,
};

export const rootOrganizationResponse = {
  id: ROOT_ORGANIZATION_ID,
  name: ROOT_ORGANIZATION_NAME,
};

export const organizationResponse = {
  id: ORGANIZATION_ID,
  name: ORGANIZATION_NAME,
};

export const defaultRootOrgConfigResponse = {
  id: null,
  ownerId: ROOT_ORGANIZATION_ID,
  repositoryUrl: null,
  provider: { value: null, parentValue: null, parentName: null },
  username: { value: null, parentValue: null, parentName: null },
  token: { value: null, parentValue: null, parentName: null },
  baseBranch: { value: null, parentValue: null, parentName: null },
  authenticationType: { value: null, parentValue: null, parentName: null },
  remediationPullRequestsEnabled: { value: null, parentValue: null, parentName: null },
  statusChecksEnabled: { value: null, parentValue: null, parentName: null },
  pullRequestCommentingEnabled: { value: null, parentValue: null, parentName: null },
  commitStatusEnabled: { value: null, parentValue: null, parentName: null },
  sourceControlEvaluationsEnabled: { value: null, parentValue: null, parentName: null },
  sourceControlScanTarget: { value: null, parentValue: null, parentName: null },
  sshEnabled: { value: null, parentValue: null, parentName: null },
  manualPullRequestsEnabled: { value: null, parentValue: null, parentName: null },
  innerSourceAutomatedUpdatesEnabled: { value: null, parentValue: null, parentName: null },
  closePrOnFailedChecksEnabled: { value: null, parentValue: null, parentName: null },
  closePrAfterDaysOpenEnabled: { value: null, parentValue: null, parentName: null },
  closePrAfterDays: { value: null, parentValue: null, parentName: null },
};

export const existingRootOrgConfigResponse = {
  id: 'f3d15f6dbdda475380f8f41e8546939e',
  ownerId: ROOT_ORGANIZATION_ID,
  repositoryUrl: null,
  provider: { value: 'azure', parentValue: null, parentName: null },
  username: { value: 'admin', parentValue: null, parentName: null },
  token: { value: '#~FAKE~SECRET~KEY~#', parentValue: null, parentName: null },
  baseBranch: { value: 'main', parentValue: null, parentName: null },
  authenticationType: { value: null, parentValue: null, parentName: null },
  remediationPullRequestsEnabled: { value: false, parentValue: null, parentName: null },
  statusChecksEnabled: { value: true, parentValue: null, parentName: null },
  pullRequestCommentingEnabled: { value: true, parentValue: null, parentName: null },
  commitStatusEnabled: { value: true, parentValue: null, parentName: null },
  sourceControlEvaluationsEnabled: { value: true, parentValue: null, parentName: null },
  sourceControlScanTarget: { value: null, parentValue: null, parentName: null },
  sshEnabled: { value: null, parentValue: null, parentName: null },
  manualPullRequestsEnabled: { value: false, parentValue: null, parentName: null },
  innerSourceAutomatedUpdatesEnabled: { value: false, parentValue: null, parentName: null },
};

export const defaultOrgConfigResponse = {
  id: null,
  ownerId: ORGANIZATION_ID,
  repositoryUrl: null,
  provider: { value: null, parentValue: null, parentName: null },
  username: { value: null, parentValue: null, parentName: null },
  token: { value: null, parentValue: null, parentName: null },
  baseBranch: { value: null, parentValue: null, parentName: null },
  authenticationType: { value: null, parentValue: null, parentName: null },
  remediationPullRequestsEnabled: { value: null, parentValue: null, parentName: null },
  statusChecksEnabled: { value: null, parentValue: null, parentName: null },
  pullRequestCommentingEnabled: { value: null, parentValue: null, parentName: null },
  commitStatusEnabled: { value: null, parentValue: null, parentName: null },
  sourceControlEvaluationsEnabled: { value: null, parentValue: null, parentName: null },
  sourceControlScanTarget: { value: null, parentValue: null, parentName: null },
  sshEnabled: { value: null, parentValue: null, parentName: null },
  manualPullRequestsEnabled: { value: null, parentValue: null, parentName: null },
  innerSourceAutomatedUpdatesEnabled: { value: null, parentValue: null, parentName: null },
};

export const inheritedOrgConfigResponse = {
  id: null,
  ownerId: ORGANIZATION_ID,
  repositoryUrl: null,
  provider: { value: null, parentValue: 'azure', parentName: ROOT_ORGANIZATION_NAME },
  username: { value: null, parentValue: 'admin', parentName: ROOT_ORGANIZATION_NAME },
  token: { value: null, parentValue: '#~FAKE~SECRET~KEY~#', parentName: ROOT_ORGANIZATION_NAME },
  baseBranch: { value: null, parentValue: 'main', parentName: ROOT_ORGANIZATION_NAME },
  authenticationType: { value: null, parentValue: null, parentName: ROOT_ORGANIZATION_NAME },
  remediationPullRequestsEnabled: { value: null, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
  statusChecksEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  pullRequestCommentingEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  commitStatusEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  sourceControlEvaluationsEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  sourceControlScanTarget: { value: null, parentValue: null, parentName: ROOT_ORGANIZATION_NAME },
  sshEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  manualPullRequestsEnabled: { value: null, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
  innerSourceAutomatedUpdatesEnabled: { value: null, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
};

export const existingOrgConfigResponse = {
  id: 'f3d15f6dbdda475380f8f41e8546939e',
  ownerId: ORGANIZATION_ID,
  repositoryUrl: null,
  provider: { value: 'github', parentValue: 'azure', parentName: ROOT_ORGANIZATION_NAME },
  username: { value: 'admin2', parentValue: 'admin', parentName: ROOT_ORGANIZATION_NAME },
  token: { value: '#~FAKE~SECRET~KEY~#', parentValue: '#~FAKE~SECRET~KEY~#', parentName: ROOT_ORGANIZATION_NAME },
  baseBranch: { value: 'master', parentValue: 'main', parentName: ROOT_ORGANIZATION_NAME },
  authenticationType: { value: 'PAT', parentValue: null, parentName: ROOT_ORGANIZATION_NAME },
  remediationPullRequestsEnabled: { value: true, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
  statusChecksEnabled: { value: false, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  pullRequestCommentingEnabled: { value: false, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  commitStatusEnabled: { value: false, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  sourceControlEvaluationsEnabled: { value: false, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  sourceControlScanTarget: { value: null, parentValue: null, parentName: ROOT_ORGANIZATION_NAME },
  sshEnabled: { value: false, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  manualPullRequestsEnabled: { value: false, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
  innerSourceAutomatedUpdatesEnabled: { value: false, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
};

export const assertionsForOrgDefaultState = [
  {
    name: 'Provider',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'combobox',
    assertions: [{ assertion: 'toBeDisabled' }],
    value: '',
    inherit: true,
    override: false,
  },
  // Credentials / Authentication Method section is hidden when no provider is selected (inherited or overridden).
  {
    name: 'Branch',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'textbox',
    assertions: [{ assertion: 'toBeDisabled' }],
    value: '',
    inherit: true,
    override: false,
  },
  {
    name: 'SSH',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Automated Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
  {
    name: 'Pull Request Commenting',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: false,
    enabled: true,
    disabled: false,
  },
  {
    name: 'Automated InnerSource Updates',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: false,
    enabled: true,
    disabled: false,
  },
  {
    name: 'Source Control',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: false,
    enabled: true,
    disabled: false,
  },
  {
    name: 'Automated Commit',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: false,
    enabled: true,
    disabled: false,
  },
  {
    name: 'Manual Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: false,
    enabled: true,
    disabled: false,
  },
];

export const assertionsForOrgInheritedState = [
  {
    name: 'Provider',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'combobox',
    assertions: [{ assertion: 'toBeDisabled' }],
    value: 'azure',
    inherit: true,
    override: false,
  },
  {
    name: 'Credentials',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    isRadioVisible: true,
    type: 'credentials',
    tokenQuery: 'getByTestId',
    usernameQuery: 'getByTestId',
    tokenAssertions: [{ assertion: 'toBeDisabled' }],
    usernameAssertions: [{ assertion: 'toBeDisabled' }],
    tokenValue: '#~FAKE~SECRET~KEY~#',
    usernameValue: 'admin',
    inherit: true,
    override: false,
  },
  {
    name: 'Branch',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'textbox',
    assertions: [{ assertion: 'toBeDisabled' }],
    value: 'main',
    inherit: true,
    override: false,
  },
  {
    name: 'SSH',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Automated Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Pull Request Commenting',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Source Control',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Automated Commit',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Manual Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Automated InnerSource Updates',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
];

export const assertionsForOrgExistingState = [
  {
    name: 'Provider',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'combobox',
    assertions: [{ assertion: 'toBeDisabled', isNegative: true }],
    value: 'github',
    inherit: false,
    override: true,
  },
  {
    // GitHub provider + feature-on renders the Authentication Method fieldset (inherit/override + GitHub App/PAT radios)
    // instead of the legacy Credentials fieldset. We only verify visibility here; detailed auth-method behavior is
    // covered by GitHubAppAuthenticationMethod.jestspec.jsx.
    name: 'Authentication Method',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'visibility-only',
  },
  {
    name: 'Branch',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'textbox',
    assertions: [{ assertion: 'toBeDisabled', isNegative: true }],
    value: 'master',
    inherit: false,
    override: true,
  },
  {
    name: 'SSH',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
  {
    name: 'Automated Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: true,
    disabled: false,
  },
  {
    name: 'Pull Request Commenting',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
  {
    name: 'Source Control',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
  {
    name: 'Automated Commit',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
  {
    name: 'Manual Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
  {
    name: 'Automated InnerSource Updates',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
];

export const defaultAppConfigResponse = {
  id: null,
  ownerId: ORGANIZATION_ID,
  repositoryUrl: null,
  provider: { value: null, parentValue: null, parentName: null },
  username: { value: null, parentValue: null, parentName: null },
  token: { value: null, parentValue: null, parentName: null },
  baseBranch: { value: null, parentValue: null, parentName: null },
  authenticationType: { value: null, parentValue: null, parentName: null },
  remediationPullRequestsEnabled: { value: null, parentValue: null, parentName: null },
  statusChecksEnabled: { value: null, parentValue: null, parentName: null },
  pullRequestCommentingEnabled: { value: null, parentValue: null, parentName: null },
  commitStatusEnabled: { value: null, parentValue: null, parentName: null },
  sourceControlEvaluationsEnabled: { value: null, parentValue: null, parentName: null },
  sourceControlScanTarget: { value: null, parentValue: null, parentName: null },
  sshEnabled: { value: null, parentValue: null, parentName: null },
  manualPullRequestsEnabled: { value: null, parentValue: null, parentName: null },
  innerSourceAutomatedUpdatesEnabled: { value: null, parentValue: null, parentName: null },
};

export const inheritedAppConfigResponse = {
  id: null,
  ownerId: ORGANIZATION_ID,
  repositoryUrl: null,
  provider: { value: null, parentValue: 'azure', parentName: ROOT_ORGANIZATION_NAME },
  username: { value: null, parentValue: 'admin', parentName: ROOT_ORGANIZATION_NAME },
  token: { value: null, parentValue: '#~FAKE~SECRET~KEY~#', parentName: ROOT_ORGANIZATION_NAME },
  baseBranch: { value: null, parentValue: 'main', parentName: ROOT_ORGANIZATION_NAME },
  authenticationType: { value: null, parentValue: null, parentName: ROOT_ORGANIZATION_NAME },
  remediationPullRequestsEnabled: { value: null, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
  statusChecksEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  pullRequestCommentingEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  commitStatusEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  sourceControlEvaluationsEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  sourceControlScanTarget: { value: null, parentValue: null, parentName: ROOT_ORGANIZATION_NAME },
  sshEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  manualPullRequestsEnabled: { value: null, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
  innerSourceAutomatedUpdatesEnabled: { value: null, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
};

export const inheritedAppNoTokenConfigResponse = {
  id: null,
  ownerId: ORGANIZATION_ID,
  repositoryUrl: null,
  provider: { value: null, parentValue: 'azure', parentName: ROOT_ORGANIZATION_NAME },
  username: { value: null, parentValue: null, parentName: null },
  token: { value: null, parentValue: null, parentName: null },
  baseBranch: { value: null, parentValue: 'main', parentName: ROOT_ORGANIZATION_NAME },
  authenticationType: { value: null, parentValue: null, parentName: ROOT_ORGANIZATION_NAME },
  remediationPullRequestsEnabled: { value: null, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
  statusChecksEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  pullRequestCommentingEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  commitStatusEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  sourceControlEvaluationsEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  sourceControlScanTarget: { value: null, parentValue: null, parentName: ROOT_ORGANIZATION_NAME },
  sshEnabled: { value: null, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  manualPullRequestsEnabled: { value: null, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
  innerSourceAutomatedUpdatesEnabled: { value: null, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
};

export const existingAppConfigResponse = {
  id: 'f3d15f6dbdda475380f8f41e8546939e',
  ownerId: ORGANIZATION_ID,
  repositoryUrl: 'https://github.com',
  provider: { value: 'github', parentValue: 'azure', parentName: ROOT_ORGANIZATION_NAME },
  username: { value: 'admin2', parentValue: 'admin', parentName: ROOT_ORGANIZATION_NAME },
  token: { value: '#~FAKE~SECRET~KEY~#', parentValue: '#~FAKE~SECRET~KEY~#', parentName: ROOT_ORGANIZATION_NAME },
  baseBranch: { value: 'master', parentValue: 'main', parentName: ROOT_ORGANIZATION_NAME },
  authenticationType: { value: 'PAT', parentValue: null, parentName: ROOT_ORGANIZATION_NAME },
  remediationPullRequestsEnabled: { value: true, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
  statusChecksEnabled: { value: false, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  pullRequestCommentingEnabled: { value: false, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  commitStatusEnabled: { value: false, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  sourceControlEvaluationsEnabled: { value: false, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  sourceControlScanTarget: { value: null, parentValue: null, parentName: ROOT_ORGANIZATION_NAME },
  sshEnabled: { value: false, parentValue: true, parentName: ROOT_ORGANIZATION_NAME },
  manualPullRequestsEnabled: { value: false, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
  innerSourceAutomatedUpdatesEnabled: { value: false, parentValue: false, parentName: ROOT_ORGANIZATION_NAME },
};

export const assertionsForAppDefaultState = [
  {
    name: 'Provider',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'combobox',
    assertions: [{ assertion: 'toBeDisabled' }],
    value: '',
    inherit: true,
    override: false,
  },
  // Credentials / Authentication Method section is hidden when no provider is selected (inherited or overridden).
  {
    name: 'Branch',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'textbox',
    assertions: [{ assertion: 'toBeDisabled' }],
    value: '',
    inherit: true,
    override: false,
  },
  {
    name: 'SSH',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Automated Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
  {
    name: 'Pull Request Commenting',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: false,
    enabled: true,
    disabled: false,
  },
  {
    name: 'Automated InnerSource Updates',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: false,
    enabled: true,
    disabled: false,
  },
  {
    name: 'Source Control',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: false,
    enabled: true,
    disabled: false,
  },
  {
    name: 'Automated Commit',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: false,
    enabled: true,
    disabled: false,
  },
  {
    name: 'Manual Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled' },
    type: 'radio',
    inherit: false,
    enabled: true,
    disabled: false,
  },
];

export const assertionsForAppInheritedState = [
  {
    name: 'Provider',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'combobox',
    assertions: [{ assertion: 'toBeDisabled' }],
    value: 'azure',
    inherit: true,
    override: false,
  },
  {
    name: 'Credentials',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    isRadioVisible: true,
    type: 'credentials',
    tokenQuery: 'getByTestId',
    usernameQuery: 'getByTestId',
    tokenAssertions: [{ assertion: 'toBeDisabled' }],
    usernameAssertions: [{ assertion: 'toBeDisabled' }],
    tokenValue: '#~FAKE~SECRET~KEY~#',
    usernameValue: 'admin',
    inherit: true,
    override: false,
  },
  {
    name: 'Branch',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'textbox',
    assertions: [{ assertion: 'toBeDisabled' }],
    value: 'main',
    inherit: true,
    override: false,
  },
  {
    name: 'SSH',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Automated Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Pull Request Commenting',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Source Control',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Automated Commit',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Manual Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Automated InnerSource Updates',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
];

export const assertionsForAppNoTokenInheritedState = [
  {
    name: 'Provider',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'combobox',
    assertions: [{ assertion: 'toBeDisabled' }],
    value: 'azure',
    inherit: true,
    override: false,
  },
  {
    name: 'Credentials',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    isRadioVisible: true,
    type: 'credentials',
    tokenQuery: 'getByTestId',
    usernameQuery: 'getByTestId',
    tokenAssertions: [{ assertion: 'toBeDisabled', isNegative: true }],
    usernameAssertions: [{ assertion: 'toBeDisabled', isNegative: true }],
    tokenValue: '',
    usernameValue: '',
    inherit: false,
    override: true,
  },
  {
    name: 'Branch',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'textbox',
    assertions: [{ assertion: 'toBeDisabled' }],
    value: 'main',
    inherit: true,
    override: false,
  },
  {
    name: 'SSH',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Automated Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Pull Request Commenting',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Source Control',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Automated Commit',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Manual Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
  {
    name: 'Automated InnerSource Updates',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: true,
    enabled: false,
    disabled: false,
  },
];

export const assertionsForAppExistingState = [
  {
    name: 'Provider',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'combobox',
    assertions: [{ assertion: 'toBeDisabled', isNegative: true }],
    value: 'github',
    inherit: false,
    override: true,
  },
  {
    // GitHub provider + feature-on renders the Authentication Method fieldset instead of the legacy Credentials
    // fieldset. Detailed auth-method behavior is covered by GitHubAppAuthenticationMethod.jestspec.jsx.
    name: 'Authentication Method',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'visibility-only',
  },
  {
    name: 'Branch',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'textbox',
    assertions: [{ assertion: 'toBeDisabled', isNegative: true }],
    value: 'master',
    inherit: false,
    override: true,
  },
  {
    name: 'SSH',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
  {
    name: 'Automated Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: true,
    disabled: false,
  },
  {
    name: 'Pull Request Commenting',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
  {
    name: 'Source Control',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
  {
    name: 'Automated Commit',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
  {
    name: 'Manual Pull Requests',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
  {
    name: 'Automated InnerSource Updates',
    visibility: { assertion: 'toBeVisible' },
    isDisabled: { assertion: 'toBeDisabled', isNegative: true },
    type: 'radio',
    inherit: false,
    enabled: false,
    disabled: true,
  },
];
