<!--

    Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
    Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
    "Sonatype" is a trademark of Sonatype, Inc.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sonatype.insight.brain</groupId>
    <artifactId>insight-brain</artifactId>
    <version>1.198.0-01</version>
  </parent>

  <artifactId>insight-brain-frontend</artifactId>
  <name>Insight Brain Frontend</name>

  <properties>
    <node.version>v18.20.4</node.version>
    <yarn.version>v1.22.22</yarn.version>
    <sonar.sources>src/main/frontend</sonar.sources>
    <sonar.exclusions>src/main/frontend/lib/**/*,src/main/frontend/audit-report/lib/**/*</sonar.exclusions>
    <sonar.coverage.exclusions>
      src/main/frontend/lib/**/*,src/main/frontend/audit-report/lib/**/*
    </sonar.coverage.exclusions>
    <sonar.tests>src/test/frontend</sonar.tests>
    <sonar.javascript.lcov.reportPaths>${project.build.directory}/coverage/lcov.info</sonar.javascript.lcov.reportPaths>
    <!--- disable frontend build cache until the cache extension can handle symlinks in node_modules as a cache output -->
    <maven.build.cache.skipCache>true</maven.build.cache.skipCache>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>install-node-and-yarn</id>
            <goals>
              <goal>install-node-and-yarn</goal>
            </goals>
            <configuration>
              <nodeVersion>${node.version}</nodeVersion>
              <yarnVersion>${yarn.version}</yarnVersion>
            </configuration>
          </execution>
          <execution>
            <id>yarn-install</id>
            <goals>
              <goal>yarn</goal>
            </goals>
            <configuration>
              <arguments>install --check-files --frozen-lockfile</arguments>
            </configuration>
          </execution>
          <execution>
            <id>build</id>
            <goals>
              <goal>yarn</goal>
            </goals>
            <configuration>
              <arguments>run build</arguments>
            </configuration>
          </execution>
          <execution>
            <id>test-compile</id>
            <phase>test-compile</phase>
            <goals>
              <goal>yarn</goal>
            </goals>
            <configuration>
              <skip>${jasmine.tests.skip}</skip>
              <arguments>run test-compile</arguments>
            </configuration>
          </execution>
          <!--
            There are currently two suites of frontend unit tests: newer tests in jest and
            older tests in jasmine (the latter are run by karma). The two executions below run these
            two suites respentively
          -->
          <execution>
            <id>jest</id>
            <phase>test</phase>
            <goals>
              <goal>yarn</goal>
            </goals>
            <configuration>
              <skip>${jasmine.tests.skip}</skip>
              <arguments>run jest</arguments>
            </configuration>
          </execution>
          <execution>
            <id>jasmine</id>
            <phase>test</phase>
            <goals>
              <goal>yarn</goal>
            </goals>
            <configuration>
              <skip>${jasmine.tests.skip}</skip>
              <arguments>run karma</arguments>

               <!--
                   CI is set up to ignore test failures within the actual testing phase and then to inspect
                   the junit.xml file for failures later. The jasmine test suite unfortunately is prone to
                   failing due to uncaught promise rejections - which aren't recorded as part of any one test
                   and thus don't show up in junit.xml. Those uncaught promises _do_ cause the test process
                   to return an error code, but testFailureIgnore=true ignores that. So we need to override
                   it to false here
               -->
              <testFailureIgnore>false</testFailureIgnore>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
    <resources>
      <resource>
        <directory>${project.build.directory}/generated-resources/webpack/</directory>
      </resource>
    </resources>
  </build>

  <profiles>
    <profile>
      <id>m2e</id>
      <activation>
        <property>
          <name>m2e.version</name>
        </property>
      </activation>
      <properties>
        <jasmine.tests.skip>true</jasmine.tests.skip>
      </properties>
    </profile>
    <profile>
      <id>idea</id>
      <properties>
      </properties>
    </profile>
    <profile>
      <id>clean-node</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-clean-plugin</artifactId>
            <configuration>
              <filesets>
                <fileset>
                  <directory>node</directory>
                </fileset>
                <fileset>
                  <directory>node_modules</directory>
                </fileset>
              </filesets>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <!--
    Profile to be used during CI builds. The install command will specify the yarn cache folder, which
    the jenkins job cacher plugin will cache to speed up builds.
    -->
    <profile>
      <id>ci-cache-yarn</id>
      <activation>
        <property>
          <name>env.CI</name>
          <value>true</value>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.eirslett</groupId>
            <artifactId>frontend-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>yarn-install</id>
                <goals>
                  <goal>yarn</goal>
                </goals>
                <configuration>
                  <arguments>install --cache-folder yarn-cache --check-files --frozen-lockfile</arguments>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
