/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
export const actionStagesPayload = [
  { stageTypeId: 'proxy', stageName: 'Proxy' },
  { stageTypeId: 'develop', stageName: 'Develop' },
  { stageTypeId: 'source', stageName: 'Source' },
  { stageTypeId: 'build', stageName: 'Build' },
  { stageTypeId: 'stage-release', stageName: 'Stage Release' },
  { stageTypeId: 'release', stageName: 'Release' },
  { stageTypeId: 'operate', stageName: 'Operate' },
];

const organizationWithPoliciesPayload = {
  ownerId: 'adbf8ae5db8a421881f0c2faf20df9ba',
  ownerName: 'API Organization Test',
  ownerType: 'organization',
  policies: [
    {
      id: 'aaa06575b01d43f18315c1ed6843c00d',
      name: 'Testing Policy 1',
      ownerId: 'adbf8ae5db8a421881f0c2faf20df9ba',
      threatLevel: 1,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        source: 'warn',
        build: 'warn',
        'stage-release': 'fail',
        release: 'fail',
        operate: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
  ],
  policyTags: [],
};

export const organizationWithoutPolicies = {
  ownerId: 'b2bfb6ac354944ba843610cc67596a62',
  ownerName: 'New Organization',
  ownerType: 'organization',
  policies: [],
  policyTags: [],
};

export const repositoryContainerWithoutPolicies = {
  ownerId: 'REPOSITORY_CONTAINER_ID',
  ownerName: 'Repository Managers',
  ownerType: 'repository_container',
  policies: [],
  policyTags: [],
};

export const rootOrganizationPolicies = {
  ownerId: 'ROOT_ORGANIZATION_ID',
  ownerName: 'Root Organization',
  ownerType: 'organization',
  policies: [
    {
      id: '7d68e2609df546e5aef27d48d64c600d',
      name: 'Architecture-Cleanup',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 1,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '399b6b110d2a4f09bfb7b45180ab8f70',
      name: 'Architecture-Quality',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 1,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '2c5c26ec26834559957e77a039927ca0',
      name: 'Component-Similar',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 7,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '5397946041d54e608ffd307b7351afbd',
      name: 'Component-Unknown',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 2,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: 'd88f917a2a634c71aa152fb0d2f33c38',
      name: 'New ROOT ORG policy',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: {
        '502a0248b17c4bc7914de4ee7bf92637': {
          proxy: 'warn',
          develop: 'warn',
          source: 'fail',
        },
      },
    },
    {
      id: '28cd3b9301a4496cb65a51a5cd9873d8',
      name: 'Security-Critical',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '8c9d52081f2346f7a10d6c19ad40d6a2',
      name: 'Security-High',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 9,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '8554a1cb446e4ccf8cce47665134aba1',
      name: 'Security-Low',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 3,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '96316caccf3a4b36a0823b721a51c568',
      name: 'Security-Malicious',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '5e5bcdd1f85a4a769502394d428db049',
      name: 'Security-Medium',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 7,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: 'ab1ad13928954fbd87d1fe70d0ff5e8a',
      name: 'Security-Namespace Conflict',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {
        proxy: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '2ebdd1bfcce34f449ba837931b1f4d7e',
      name: 'Testing simple constraint',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 5,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        source: 'warn',
        build: 'warn',
        'stage-release': 'warn',
        release: 'fail',
        operate: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: null,
    },
  ],
  policyTags: [],
  inherited: false,
};

export const repositoryContainerPolicies = {
  ownerId: 'REPOSITORY_CONTAINER_ID',
  ownerName: 'Repository Managers',
  ownerType: 'repository_container',
  policies: [
    {
      id: '7d68e2609df546e5aef27d48d64c600d',
      name: 'Architecture-Cleanup',
      ownerId: 'REPOSITORY_CONTAINER_ID',
      threatLevel: 1,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '399b6b110d2a4f09bfb7b45180ab8f70',
      name: 'Architecture-Quality',
      ownerId: 'REPOSITORY_CONTAINER_ID',
      threatLevel: 1,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '2c5c26ec26834559957e77a039927ca0',
      name: 'Component-Similar',
      ownerId: 'REPOSITORY_CONTAINER_ID',
      threatLevel: 7,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '5397946041d54e608ffd307b7351afbd',
      name: 'Component-Unknown',
      ownerId: 'REPOSITORY_CONTAINER_ID',
      threatLevel: 2,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: 'd88f917a2a634c71aa152fb0d2f33c38',
      name: 'New ROOT ORG policy',
      ownerId: 'REPOSITORY_CONTAINER_ID',
      threatLevel: 10,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: {
        '502a0248b17c4bc7914de4ee7bf92637': {
          proxy: 'warn',
          develop: 'warn',
          source: 'fail',
        },
      },
    },
    {
      id: '28cd3b9301a4496cb65a51a5cd9873d8',
      name: 'Security-Critical',
      ownerId: 'REPOSITORY_CONTAINER_ID',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '8c9d52081f2346f7a10d6c19ad40d6a2',
      name: 'Security-High',
      ownerId: 'REPOSITORY_CONTAINER_ID',
      threatLevel: 9,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '8554a1cb446e4ccf8cce47665134aba1',
      name: 'Security-Low',
      ownerId: 'REPOSITORY_CONTAINER_ID',
      threatLevel: 3,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '96316caccf3a4b36a0823b721a51c568',
      name: 'Security-Malicious',
      ownerId: 'REPOSITORY_CONTAINER_ID',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '5e5bcdd1f85a4a769502394d428db049',
      name: 'Security-Medium',
      ownerId: 'REPOSITORY_CONTAINER_ID',
      threatLevel: 7,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: 'ab1ad13928954fbd87d1fe70d0ff5e8a',
      name: 'Security-Namespace Conflict',
      ownerId: 'REPOSITORY_CONTAINER_ID',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {
        proxy: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '2ebdd1bfcce34f449ba837931b1f4d7e',
      name: 'Testing simple constraint',
      ownerId: 'REPOSITORY_CONTAINER_ID',
      threatLevel: 5,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        source: 'warn',
        build: 'warn',
        'stage-release': 'warn',
        release: 'fail',
        operate: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: null,
    },
  ],
  policyTags: [],
  inherited: false,
};

export const repositoryContainerInheretencePolicies = { ...repositoryContainerPolicies, inherited: true };

export const repositoryManagerPolicies = {
  ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
  ownerName: 'Repository Manager',
  ownerType: 'repository_manager',
  policies: [
    {
      id: '7d68e2609df546e5aef27d48d64c6055',
      name: 'Architecture-Cleanup',
      ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
      threatLevel: 1,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '399b6b110d2a4f09bfb7b45180ab8f55',
      name: 'Architecture-Quality',
      ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
      threatLevel: 1,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '2c5c26ec26834559957e77a039927c55',
      name: 'Component-Similar',
      ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
      threatLevel: 7,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '5397946041d54e608ffd307b7351af55',
      name: 'Component-Unknown',
      ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
      threatLevel: 2,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: 'd88f917a2a634c71aa152fb0d2f33c55',
      name: 'New ROOT ORG policy',
      ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
      threatLevel: 10,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: {
        '502a0248b17c4bc7914de4ee7bf92637': {
          proxy: 'fail',
        },
      },
    },
    {
      id: '28cd3b9301a4496cb65a51a5cd987355',
      name: 'Security-Critical',
      ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '8c9d52081f2346f7a10d6c19ad40d655',
      name: 'Security-High',
      ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
      threatLevel: 9,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '8554a1cb446e4ccf8cce47665134ab55',
      name: 'Security-Low',
      ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
      threatLevel: 3,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '96316caccf3a4b36a0823b721a51c555',
      name: 'Security-Malicious',
      ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '5e5bcdd1f85a4a769502394d428db055',
      name: 'Security-Medium',
      ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
      threatLevel: 7,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: 'ab1ad13928954fbd87d1fe70d0ff5e55',
      name: 'Security-Namespace Conflict',
      ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {
        proxy: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '2ebdd1bfcce34f449ba837931b1f4d55',
      name: 'Testing simple constraint',
      ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
      threatLevel: 5,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: null,
    },
  ],
  policyTags: [],
  inherited: false,
};

export const repositoryManagerInheretencePolicies = { ...repositoryManagerPolicies, inherited: true };

export const repositoryPolicies = {
  ownerId: '773e6dee1f0a45ada355ffe534a70533',
  ownerName: 'Repository',
  ownerType: 'repository',
  policies: [
    {
      id: '7d68e2609df546e5aef27d48d64c6055',
      name: 'Architecture-Cleanup',
      ownerId: '773e6dee1f0a45ada355ffe534a70533',
      threatLevel: 1,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '399b6b110d2a4f09bfb7b45180ab8f55',
      name: 'Architecture-Quality',
      ownerId: '773e6dee1f0a45ada355ffe534a70533',
      threatLevel: 1,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '2c5c26ec26834559957e77a039927c55',
      name: 'Component-Similar',
      ownerId: '773e6dee1f0a45ada355ffe534a70533',
      threatLevel: 7,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '5397946041d54e608ffd307b7351af55',
      name: 'Component-Unknown',
      ownerId: '773e6dee1f0a45ada355ffe534a70533',
      threatLevel: 2,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: 'd88f917a2a634c71aa152fb0d2f33c55',
      name: 'New ROOT ORG policy',
      ownerId: '773e6dee1f0a45ada355ffe534a70533',
      threatLevel: 10,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: {
        '502a0248b17c4bc7914de4ee7bf92637': {
          proxy: 'fail',
        },
      },
    },
    {
      id: '28cd3b9301a4496cb65a51a5cd987355',
      name: 'Security-Critical',
      ownerId: '773e6dee1f0a45ada355ffe534a70533',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '8c9d52081f2346f7a10d6c19ad40d655',
      name: 'Security-High',
      ownerId: '773e6dee1f0a45ada355ffe534a70533',
      threatLevel: 9,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '8554a1cb446e4ccf8cce47665134ab55',
      name: 'Security-Low',
      ownerId: '773e6dee1f0a45ada355ffe534a70533',
      threatLevel: 3,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '96316caccf3a4b36a0823b721a51c555',
      name: 'Security-Malicious',
      ownerId: '773e6dee1f0a45ada355ffe534a70533',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '5e5bcdd1f85a4a769502394d428db055',
      name: 'Security-Medium',
      ownerId: '773e6dee1f0a45ada355ffe534a70533',
      threatLevel: 7,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: 'ab1ad13928954fbd87d1fe70d0ff5e55',
      name: 'Security-Namespace Conflict',
      ownerId: '773e6dee1f0a45ada355ffe534a70533',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {
        proxy: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '2ebdd1bfcce34f449ba837931b1f4d55',
      name: 'Testing simple constraint',
      ownerId: '773e6dee1f0a45ada355ffe534a70533',
      threatLevel: 5,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: null,
    },
  ],
  policyTags: [],
  inherited: false,
};

const rootOrganizationWithoutPolicies = {
  ownerId: 'ROOT_ORGANIZATION_ID',
  ownerName: 'Root Organization',
  ownerType: 'organization',
  policies: [],
  policyTags: [],
};

export const organizationPoliciesByOwnerPayload = {
  ownerName: 'API Organization Test',
  ownerId: 'adbf8ae5db8a421881f0c2faf20df9ba',
  ownerType: 'organization',
  policiesByOwner: [organizationWithPoliciesPayload, organizationWithoutPolicies, rootOrganizationPolicies],
};

export const rootOrganizationPoliciesByOwnerPayload = {
  ownerName: 'Root Organization',
  ownerId: 'ROOT_ORGANIZATION_ID',
  ownerType: 'organization',
  policiesByOwner: [rootOrganizationPolicies],
};

export const rootOrganizationNoPoliciesByOwnerPayload = {
  ownerName: 'Root Organization',
  ownerId: 'ROOT_ORGANIZATION_ID',
  ownerType: 'organization',
  policiesByOwner: [rootOrganizationWithoutPolicies],
};

export const applicationWithNoPolicies = {
  ownerId: '6b4684c392e2453aa9a3d2483c9611c4',
  ownerName: 'Artifactory Test',
  ownerType: 'application',
  policies: [],
  policyTags: [],
  inherited: false,
};

export const rootOrganizationInheretencePolicies = { ...rootOrganizationPolicies, inherited: true };

export const applicationWithPolicies = {
  ownerName: 'Artifactory Test 2',
  ownerId: '6b4684c392e2453aa9a3d2483c9611c4',
  ownerType: 'application',
  policies: [
    {
      id: 'd88f917a2a634c71aa152fb0d2f33c38',
      name: 'New ROOT ORG policy',
      ownerId: '6b4684c392e2453aa9a3d2483c9611c4',
      threatLevel: 10,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: {
        '502a0248b17c4bc7914de4ee7bf92637': {
          proxy: 'warn',
          develop: 'warn',
          source: 'fail',
        },
      },
      enforcementAction: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
    },
    {
      id: '28cd3b9301a4496cb65a51a5cd9873d8',
      name: 'Security-Critical',
      ownerId: '6b4684c392e2453aa9a3d2483c9611c4',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
  ],
  policyTags: [],
  inherited: false,
};

export const applicationPoliciesByOwnerPayload = {
  ownerName: 'Artifactory Test 2',
  ownerId: '4dce3fdb25d342b6a5e1177bb229b7ee',
  ownerType: 'application',
  policiesByOwner: [
    {
      ownerId: '4dce3fdb25d342b6a5e1177bb229b7ee',
      ownerName: 'Artifactory Test 2',
      ownerType: 'application',
      policies: [],
      policyTags: [],
      inherited: false,
    },
    {
      ownerId: 'f857a3ea49af492481112d6c6ab24054',
      ownerName: 'org-1-1',
      ownerType: 'organization',
      policies: [
        {
          id: '7cc2e8da3853434897e4ab8d5bc9d6ab',
          name: 'test-pol',
          ownerId: 'f857a3ea49af492481112d6c6ab24054',
          threatLevel: 5,
          legacyViolationAllowed: true,
          constraints: [],
          actions: {
            develop: 'fail',
            source: 'fail',
            build: 'fail',
          },
          notifications: {
            userNotifications: [
              {
                stageIds: ['build', 'develop', 'source'],
                emailAddress: 'cfigueroa@sonatype.com',
              },
            ],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {
            develop: 'fail',
            source: 'fail',
            build: 'fail',
          },
        },
      ],
      policyTags: [],
      inherited: true,
    },
    {
      ownerId: '96ab3967eb574f6ca0f62a6ee0ed8488',
      ownerName: 'org-1',
      ownerType: 'organization',
      policies: [],
      policyTags: [],
      inherited: true,
    },
    {
      ownerId: 'ROOT_ORGANIZATION_ID',
      ownerName: 'Root Organization',
      ownerType: 'organization',
      policies: [
        {
          id: '9f5d13e238d14889a1406fd52fefc3d0',
          name: 'Security-Namespace Conflict',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 10,
          legacyViolationAllowed: false,
          constraints: [],
          actions: {
            proxy: 'fail',
          },
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {
            proxy: 'fail',
          },
        },
        {
          id: 'b87d0c78beb44d1da85ec8b49422c47f',
          name: 'Security-Malicious',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 10,
          legacyViolationAllowed: false,
          constraints: [],
          actions: {},
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {},
        },
        {
          id: 'eb1d73222e184178b728c884eaa2f770',
          name: 'Security-Critical',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 10,
          legacyViolationAllowed: false,
          constraints: [],
          actions: {},
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {},
        },
        {
          id: 'c1656941060f4f6195b128fb19413136',
          name: 'License-Banned',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 10,
          legacyViolationAllowed: false,
          constraints: [],
          actions: {},
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {},
        },
        {
          id: '911b6c41ca4e491fb6ffef9a284bf35c',
          name: 'Security-High',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 9,
          legacyViolationAllowed: false,
          constraints: [],
          actions: {},
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {},
        },
        {
          id: 'c88fb1c0b0d6481c9cbbcf2fb423ab12',
          name: 'Integrity-Rating',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 9,
          legacyViolationAllowed: false,
          constraints: [],
          actions: {
            proxy: 'fail',
          },
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {
            proxy: 'fail',
          },
        },
        {
          id: '18782ea5185d4d619567613597d4ff7c',
          name: 'Security-Medium',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 7,
          legacyViolationAllowed: true,
          constraints: [],
          actions: {},
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {},
        },
        {
          id: 'b7f54fc3136a446792d475238d7f690d',
          name: 'License-Threat Not Assigned',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 7,
          legacyViolationAllowed: true,
          constraints: [],
          actions: {},
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {},
        },
        {
          id: 'b7282516113a495fab407b833b145d2e',
          name: 'Component-Similar',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 7,
          legacyViolationAllowed: true,
          constraints: [],
          actions: {},
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {},
        },
        {
          id: 'cf9bf57af8f0451dba0f76fde4a2b653',
          name: 'Security-Low',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 3,
          legacyViolationAllowed: true,
          constraints: [],
          actions: {},
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {},
        },
        {
          id: 'fa6fb554e83e48049cff5b305adc1596',
          name: 'Component-Unknown',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 2,
          legacyViolationAllowed: true,
          constraints: [],
          actions: {},
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {},
        },
        {
          id: '94280a1a0628461fa15763dcafeb6e37',
          name: 'Architecture-Quality',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 1,
          legacyViolationAllowed: true,
          constraints: [],
          actions: {},
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {},
        },
        {
          id: '6f1cff4e6379428f9917673814fc8e3e',
          name: 'Architecture-Cleanup',
          ownerId: 'ROOT_ORGANIZATION_ID',
          threatLevel: 1,
          legacyViolationAllowed: true,
          constraints: [],
          actions: {},
          notifications: {
            userNotifications: [],
            roleNotifications: [],
            jiraNotifications: [],
            webhookNotifications: [],
          },
          policyActionsOverrideAllowed: false,
          policyActionsOverrides: null,
          policyNotificationsOverrideAllowed: false,
          policyNotificationsOverrides: null,
          enforcementAction: {},
        },
      ],
      policyTags: [],
      inherited: true,
    },
  ],
};

export const rootOrganizationWithPolicies = {
  ownerId: 'ROOT_ORGANIZATION_ID',
  ownerName: 'Root Organization',
  ownerType: 'organization',
  policies: [
    {
      id: 'd88f917a2a634c71aa152fb0d2f33c38',
      name: 'New ROOT ORG policy',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: {
        '502a0248b17c4bc7914de4ee7bf92637': {
          proxy: 'warn',
          develop: 'warn',
          source: 'fail',
        },
      },
      enforcementAction: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
    },
    {
      id: '28cd3b9301a4496cb65a51a5cd9873d8',
      name: 'Security-Critical',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '96316caccf3a4b36a0823b721a51c568',
      name: 'Security-Malicious',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: 'ab1ad13928954fbd87d1fe70d0ff5e8a',
      name: 'Security-Namespace Conflict',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {
        proxy: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {
        proxy: 'fail',
      },
    },
    {
      id: '8c9d52081f2346f7a10d6c19ad40d6a2',
      name: 'Security-High',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 9,
      legacyViolationAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '2c5c26ec26834559957e77a039927ca0',
      name: 'Component-Similar',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 7,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '5e5bcdd1f85a4a769502394d428db049',
      name: 'Security-Medium',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 7,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '2ebdd1bfcce34f449ba837931b1f4d7e',
      name: 'Testing simple constraint',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 5,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        source: 'warn',
        build: 'warn',
        'stage-release': 'warn',
        release: 'fail',
        operate: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: null,
      enforcementAction: {
        source: 'warn',
        build: 'warn',
        'stage-release': 'warn',
        release: 'fail',
        operate: 'fail',
      },
    },
    {
      id: '8554a1cb446e4ccf8cce47665134aba1',
      name: 'Security-Low',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 3,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '5397946041d54e608ffd307b7351afbd',
      name: 'Component-Unknown',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 2,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '7d68e2609df546e5aef27d48d64c600d',
      name: 'Architecture-Cleanup',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 1,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '399b6b110d2a4f09bfb7b45180ab8f70',
      name: 'Architecture-Quality',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 1,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
  ],
  policyTags: [],
  inherited: false,
};

export const rootOrganizationWithOnePolicy = {
  ownerId: 'ROOT_ORGANIZATION_ID',
  ownerName: 'Root Organization',
  ownerType: 'organization',
  policies: [
    {
      id: 'd88f917a2a634c71aa152fb0d2f33c38',
      name: 'New ROOT ORG policy',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: {
        '502a0248b17c4bc7914de4ee7bf92637': {
          proxy: 'warn',
          develop: 'warn',
          source: 'fail',
        },
      },
      enforcementAction: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
    },
  ],
  policyTags: [],
  inherited: false,
};

export const inheritanceOrgWithOnePolicy = {
  ownerId: 'inheritance_policy',
  ownerName: 'Top Organization',
  ownerType: 'organization',
  policies: [
    {
      id: 'd88f917a2a634c71aa152fb0d2f33c44',
      name: 'New Top ORG policy',
      ownerId: 'inheritance_policy',
      threatLevel: 10,
      legacyViolationAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: {
        '502a0248b17c4bc7914de4ee7bf92637': {
          proxy: 'warn',
          develop: 'warn',
          source: 'fail',
        },
      },
      enforcementAction: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
    },
  ],
  policyTags: [],
  inherited: true,
};

export const inheritanceOrgWithNoPolicy = {
  ownerId: 'inheritance_no_policies',
  ownerName: 'No Policies Organization',
  ownerType: 'organization',
  policies: [],
  policyTags: [],
  inherited: true,
};

export const repositoryContainerByOwnerPayload = {
  ownerName: 'Repository Managers',
  ownerId: 'REPOSITORY_CONTAINER_ID',
  ownerType: 'repository_container',
  policiesByOwner: [repositoryContainerPolicies, rootOrganizationInheretencePolicies],
};

export const repositoryManagerByOwnerPayload = {
  ownerName: 'Repository Manager',
  ownerId: 'F2BC2A0B-E7D0DDA9-425601AB-F0AAD535-FDF19232',
  ownerType: 'repository_manager',
  policiesByOwner: [repositoryManagerPolicies, repositoryContainerInheretencePolicies],
};

export const repositoryByOwnerPayload = {
  ownerName: 'Repository',
  ownerId: '773e6dee1f0a45ada355ffe534a70533',
  ownerType: 'repository',
  policiesByOwner: [repositoryPolicies, repositoryManagerInheretencePolicies, repositoryContainerInheretencePolicies],
};
