/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
export const actionStagesPayload = [
  { stageTypeId: 'proxy', stageName: 'Proxy' },
  { stageTypeId: 'develop', stageName: 'Develop' },
  { stageTypeId: 'source', stageName: 'Source' },
  { stageTypeId: 'build', stageName: 'Build' },
  { stageTypeId: 'stage-release', stageName: 'Stage Release' },
  { stageTypeId: 'release', stageName: 'Release' },
  { stageTypeId: 'operate', stageName: 'Operate' },
];

const organizationWithPoliciesPayload = {
  ownerId: 'adbf8ae5db8a421881f0c2faf20df9ba',
  ownerName: 'API Organization Test',
  ownerType: 'organization',
  policies: [
    {
      id: 'aaa06575b01d43f18315c1ed6843c00d',
      name: 'Testing Policy 1',
      ownerId: 'adbf8ae5db8a421881f0c2faf20df9ba',
      threatLevel: 1,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {
        source: 'warn',
        build: 'warn',
        'stage-release': 'fail',
        release: 'fail',
        operate: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
  ],
  policyTags: [],
};

export const organizationWithoutPolicies = {
  ownerId: 'b2bfb6ac354944ba843610cc67596a62',
  ownerName: 'New Organization',
  ownerType: 'organization',
  policies: [],
  policyTags: [],
};

export const rootOrganizationPolicies = {
  ownerId: 'ROOT_ORGANIZATION_ID',
  ownerName: 'Root Organization',
  ownerType: 'organization',
  policies: [
    {
      id: '7d68e2609df546e5aef27d48d64c600d',
      name: 'Architecture-Cleanup',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 1,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '399b6b110d2a4f09bfb7b45180ab8f70',
      name: 'Architecture-Quality',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 1,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '2c5c26ec26834559957e77a039927ca0',
      name: 'Component-Similar',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 7,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '5397946041d54e608ffd307b7351afbd',
      name: 'Component-Unknown',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 2,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: 'd88f917a2a634c71aa152fb0d2f33c38',
      name: 'New ROOT ORG policy',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: {
        '502a0248b17c4bc7914de4ee7bf92637': {
          proxy: 'warn',
          develop: 'warn',
          source: 'fail',
        },
      },
    },
    {
      id: '28cd3b9301a4496cb65a51a5cd9873d8',
      name: 'Security-Critical',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      policyViolationGrandfatheringAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '8c9d52081f2346f7a10d6c19ad40d6a2',
      name: 'Security-High',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 9,
      policyViolationGrandfatheringAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '8554a1cb446e4ccf8cce47665134aba1',
      name: 'Security-Low',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 3,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '96316caccf3a4b36a0823b721a51c568',
      name: 'Security-Malicious',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      policyViolationGrandfatheringAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '5e5bcdd1f85a4a769502394d428db049',
      name: 'Security-Medium',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 7,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: 'ab1ad13928954fbd87d1fe70d0ff5e8a',
      name: 'Security-Namespace Conflict',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      policyViolationGrandfatheringAllowed: false,
      constraints: [],
      actions: {
        proxy: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
    },
    {
      id: '2ebdd1bfcce34f449ba837931b1f4d7e',
      name: 'Testing simple constraint',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 5,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {
        source: 'warn',
        build: 'warn',
        'stage-release': 'warn',
        release: 'fail',
        operate: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: null,
    },
  ],
  policyTags: [],
  inherited: false,
};

const rootOrganizationWithoutPolicies = {
  ownerId: 'ROOT_ORGANIZATION_ID',
  ownerName: 'Root Organization',
  ownerType: 'organization',
  policies: [],
  policyTags: [],
};

export const organizationPoliciesByOwnerPayload = {
  ownerName: 'API Organization Test',
  ownerId: 'adbf8ae5db8a421881f0c2faf20df9ba',
  ownerType: 'organization',
  policiesByOwner: [organizationWithPoliciesPayload, organizationWithoutPolicies, rootOrganizationPolicies],
};

export const rootOrganizationPoliciesByOwnerPayload = {
  ownerName: 'Root Organization',
  ownerId: 'ROOT_ORGANIZATION_ID',
  ownerType: 'organization',
  policiesByOwner: [rootOrganizationPolicies],
};

export const rootOrganizationNoPoliciesByOwnerPayload = {
  ownerName: 'Root Organization',
  ownerId: 'ROOT_ORGANIZATION_ID',
  ownerType: 'organization',
  policiesByOwner: [rootOrganizationWithoutPolicies],
};

export const applicationWithNoPolicies = {
  ownerId: '6b4684c392e2453aa9a3d2483c9611c4',
  ownerName: 'Artifactory Test',
  ownerType: 'application',
  policies: [],
  policyTags: [],
  inherited: false,
};

export const rootOrganizationWithPolicies = {
  ownerId: 'ROOT_ORGANIZATION_ID',
  ownerName: 'Root Organization',
  ownerType: 'organization',
  policies: [
    {
      id: 'd88f917a2a634c71aa152fb0d2f33c38',
      name: 'New ROOT ORG policy',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: {
        '502a0248b17c4bc7914de4ee7bf92637': {
          proxy: 'warn',
          develop: 'warn',
          source: 'fail',
        },
      },
      enforcementAction: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
    },
    {
      id: '28cd3b9301a4496cb65a51a5cd9873d8',
      name: 'Security-Critical',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      policyViolationGrandfatheringAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '96316caccf3a4b36a0823b721a51c568',
      name: 'Security-Malicious',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      policyViolationGrandfatheringAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: 'ab1ad13928954fbd87d1fe70d0ff5e8a',
      name: 'Security-Namespace Conflict',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      policyViolationGrandfatheringAllowed: false,
      constraints: [],
      actions: {
        proxy: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {
        proxy: 'fail',
      },
    },
    {
      id: '8c9d52081f2346f7a10d6c19ad40d6a2',
      name: 'Security-High',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 9,
      policyViolationGrandfatheringAllowed: false,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '2c5c26ec26834559957e77a039927ca0',
      name: 'Component-Similar',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 7,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '5e5bcdd1f85a4a769502394d428db049',
      name: 'Security-Medium',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 7,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '2ebdd1bfcce34f449ba837931b1f4d7e',
      name: 'Testing simple constraint',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 5,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {
        source: 'warn',
        build: 'warn',
        'stage-release': 'warn',
        release: 'fail',
        operate: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: null,
      enforcementAction: {
        source: 'warn',
        build: 'warn',
        'stage-release': 'warn',
        release: 'fail',
        operate: 'fail',
      },
    },
    {
      id: '8554a1cb446e4ccf8cce47665134aba1',
      name: 'Security-Low',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 3,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '5397946041d54e608ffd307b7351afbd',
      name: 'Component-Unknown',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 2,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '7d68e2609df546e5aef27d48d64c600d',
      name: 'Architecture-Cleanup',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 1,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
    {
      id: '399b6b110d2a4f09bfb7b45180ab8f70',
      name: 'Architecture-Quality',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 1,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {},
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: false,
      policyActionsOverrides: null,
      enforcementAction: {},
    },
  ],
  policyTags: [],
  inherited: false,
};

export const rootOrganizationWithOnePolicy = {
  ownerId: 'ROOT_ORGANIZATION_ID',
  ownerName: 'Root Organization',
  ownerType: 'organization',
  policies: [
    {
      id: 'd88f917a2a634c71aa152fb0d2f33c38',
      name: 'New ROOT ORG policy',
      ownerId: 'ROOT_ORGANIZATION_ID',
      threatLevel: 10,
      policyViolationGrandfatheringAllowed: true,
      constraints: [],
      actions: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
      notifications: {
        userNotifications: [],
        roleNotifications: [],
        jiraNotifications: [],
        webhookNotifications: [],
      },
      policyActionsOverrideAllowed: true,
      policyActionsOverrides: {
        '502a0248b17c4bc7914de4ee7bf92637': {
          proxy: 'warn',
          develop: 'warn',
          source: 'fail',
        },
      },
      enforcementAction: {
        proxy: 'warn',
        develop: 'warn',
        source: 'fail',
        build: 'fail',
      },
    },
  ],
  policyTags: [],
  inherited: false,
};
