#!/bin/sh

# The following comment lines are used by the init setup script like the
# chkconfig command for RedHat-based distributions. Change as
# appropriate for your installation.

### BEGIN INIT INFO
# Provides:          sonatype-iq-server
# Required-Start:    $local_fs $remote_fs $network $time $named
# Required-Stop:     $local_fs $remote_fs $network $time $named
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: sonatype-iq-server service
# Description:       Start the sonatype-iq-server service
### END INIT INFO

IQ_SERVER_HOME="/opt/sonatype-iq-server"
VERSION="[0-9.]*-??"
JAVA_OPTS="-Xmx16g -XX:+UseG1GC"

# The user requires privileges to write into the sonatype-work directory.
RUN_AS_USER="iqserver"

do_start()
{
    _cmd &
    echo "Started sonatype-iq-server"
}

do_console()
{
    _cmd
}

do_stop()
{
    pid=`ps aux | grep nexus-iq-server | grep '.jar server' | grep -vE '(stop|grep)' | awk '{print $2}'`
    kill $pid
    echo "Stopping sonatype-iq-server - PID $pid ($?)"
}

do_usage()
{
    echo "Usage: sonatype-iq-server [console|start|stop]"
}

_cmd()
{
    cd $IQ_SERVER_HOME || return $?
    chown $RUN_AS_USER ./stderr.log
    if [ "$RUN_AS_USER" == "$USER" ]; then
        JAVA_OPTS="${JAVA_OPTS}" ./bin/nexus-iq-server $JAVA_OPTIONS server config.yml 2> stderr.log
    else

        sudo -u $RUN_AS_USER JAVA_OPTS="${JAVA_OPTS}" ./bin/nexus-iq-server server config.yml 2> stderr.log
    fi
}

case $1 in
    console)
        do_console
        ;;
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    *)
        do_usage
        ;;
esac
