<!--

    Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
    Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
    "Sonatype" is a trademark of Sonatype, Inc.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.sonatype.insight.brain</groupId>
    <artifactId>insight-brain</artifactId>
    <version>1.160.0-01</version>
  </parent>

  <artifactId>insight-rm-common</artifactId>
  <name>Sonatype CLM Repository Manager Common Integration</name>

  <dependencies>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-client</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.sonatype.insight.brain</groupId>
          <artifactId>insight-brain-data</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.sonatype.insight.portal</groupId>
          <artifactId>insight-db-common</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.brain</groupId>
      <artifactId>insight-brain-common</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-client-utils</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-archive</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-model</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.insight.scan</groupId>
      <artifactId>insight-scanner-model-io</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sonatype.clm</groupId>
      <artifactId>com.sonatype.clm.dto.model</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>xmlpull</groupId>
      <artifactId>xmlpull</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>xpp3</groupId>
      <artifactId>xpp3_min</artifactId>
      <version>1.1.4c</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <executions>
          <execution>
            <id>verify-bytecode-version</id>
            <phase>test</phase>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <enforceBytecodeVersion>
                  <maxJdkVersion>${maven.compiler.target}</maxJdkVersion>
                  <ignoredScopes>
                    <ignoredScope>system</ignoredScope>
                    <ignoredScope>provided</ignoredScope>
                    <ignoredScope>test</ignoredScope>
                  </ignoredScopes>
                </enforceBytecodeVersion>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <id>uber-jar</id>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <createDependencyReducedPom>true</createDependencyReducedPom>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/sisu/javax.inject.Named</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/insight/configuration.properties</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/NOTICE</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/NOTICE.txt</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/LICENSE</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/LICENSE.txt</resource>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
              </transformers>
              <artifactSet>
                <excludes>
                  <!-- for proper integration, allow host environment to override these -->
                  <exclude>*:slf4j-api</exclude>
                  <exclude>*:httpcore</exclude>
                  <exclude>*:httpclient</exclude>
                  <!-- for smooth interop with RHC, let these through as is -->
                  <exclude>*:insight-scanner-core</exclude>
                  <exclude>*:insight-scanner-model</exclude>
                  <exclude>*:insight-scanner-model-io</exclude>
                </excludes>
              </artifactSet>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                    <exclude>META-INF/maven/*/*/**</exclude>
                    <exclude>META-INF/maven/remote-resources.xml</exclude>
                    <exclude>META-INF/sisu/**</exclude>
                    <exclude>module-info.class</exclude>
                  </excludes>
                </filter>
              </filters>
              <relocations>
                <relocation>
                  <pattern>de.</pattern>
                  <shadedPattern>zz.de.</shadedPattern>
                </relocation>
                <relocation>
                  <pattern>com.</pattern>
                  <shadedPattern>zz.com.</shadedPattern>
                  <excludes>
                    <exclude>com.sonatype.**</exclude>
                    <!-- NOTE: The leading slash on the below pattern is needed to exclude absolute resource strings, too -->
                    <exclude>/com/sonatype/**</exclude>
                  </excludes>
                </relocation>
                <relocation>
                  <pattern>org.</pattern>
                  <shadedPattern>zz.org.</shadedPattern>
                  <excludes>
                    <exclude>org.apache.http.**</exclude>
                    <exclude>org.ietf.**</exclude>
                    <exclude>org.slf4j.**</exclude>
                    <exclude>org.w3c.**</exclude>
                    <exclude>org.xml.**</exclude>
                    <exclude>org.codehaus.groovy.**</exclude>
                  </excludes>
                </relocation>
              </relocations>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <id>uber-jar-fixes</id>
            <phase>package</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <copy todir="${project.build.directory}/uberjar">
                  <zipfileset src="${project.build.directory}/${project.build.finalName}.jar" includes="META-INF/services/**" />
                  <firstmatchmapper>
                    <regexpmapper from="META-INF/services/((?:java)\..+)" to="META-INF/services/\1" handledirsep="true" />
                    <regexpmapper from="META-INF/services/(.+)" to="META-INF/services/zz.\1" handledirsep="true" />
                  </firstmatchmapper>
                  <filterchain>
                    <tokenfilter>
                      <replaceregex pattern="(?:com|de|org)\.[^,]+" replace="zz.\0" flags="gim" />
                    </tokenfilter>
                  </filterchain>
                </copy>
                <move file="${project.build.directory}/${project.build.finalName}.jar" tofile="${project.build.directory}/${project.build.finalName}-shade.jar" />
                <jar destfile="${project.build.directory}/${project.build.finalName}.jar" filesetmanifest="merge">
                  <zipfileset src="${project.build.directory}/${project.build.finalName}-shade.jar" excludes="META-INF/services/**" />
                  <fileset dir="${project.build.directory}/uberjar" />
                </jar>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
