# NOTE: Package name should not clash with similar proguard configuration in other modules
-repackageclasses zz

-dontusemixedcaseclassnames

-dontoptimize
-dontshrink
-dontnote

-dontwarn com.sonatype.insight.brain.dataaccess.**
-dontwarn com.sonatype.insight.model.**
-dontwarn zz.com.thoughtworks.xstream.**
-dontwarn zz.de.schlichtherle.**
-dontwarn javax.inject.**
-dontwarn javax.persistence.**
-dontwarn javax.servlet.http.**
-dontwarn javax.ws.rs.**
-dontwarn zz.org.apache.**
-dontwarn zz.org.bouncycastle.**
-dontwarn zz.org.joda.**
-dontwarn zz.com.jcraft.jsch.jce.**
-dontwarn zz.com.jcraft.jsch.jgss.**
-dontwarn zz.org.eclipse.jgit.**
-dontwarn zz.com.googlecode.javaewah**
-dontwarn zz.org.cyclonedx.**
-dontwarn javax.xml.**
-dontwarn org.w3c.**
-dontwarn org.xml.**
-dontwarn org.codehaus.groovy.**
-dontwarn groovy.servlet.**
-dontwarn groovy.util.**
-dontwarn groovy.test.**
-dontwarn groovy.mock.**
-dontwarn groovyjarjarasm.**
-dontwarn zz.org.codehaus.groovy.**

# 3rd party stuff excluded from obfuscation
-keep class !com.sonatype.insight.**,!zz.org.objectweb.** { *; }

# API of this module
-keep class com.sonatype.insight.rm.** { *; }

# DTOs exposed via API
-keep public class com.sonatype.clm.dto.model.** { *; }

# classes with prominent logging to retain their logger name
-keep public class com.sonatype.insight.scan.**Scanner { *; }

-renamesourcefileattribute SourceFile
-keepattributes *Annotation*,Exceptions,InnerClasses,EnclosingMethod,Signature,SourceFile,LineNumberTable

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

