
-repackageclasses zz

-dontusemixedcaseclassnames

-dontoptimize
-dontshrink
-dontnote

-dontwarn com.sonatype.insight.brain.dataaccess.**
-dontwarn com.sonatype.insight.model.**
-dontwarn com.thoughtworks.xstream.**
-dontwarn de.schlichtherle.**
-dontwarn javax.inject.**
-dontwarn javax.persistence.**
-dontwarn javax.servlet.http.**
-dontwarn javax.ws.rs.**
-dontwarn org.apache.**
-dontwarn org.joda.**
-dontwarn org.slf4j.**

# 3rd party stuff excluded from obfuscation
-keep class !com.sonatype.insight.**,!org.objectweb.** { *; }

# API of this module
-keep public class com.sonatype.insight.rm.** { *; }

# DTOs exposed via API
-keep public class com.sonatype.insight.brain.model.** { *; }
-keep public class com.sonatype.insight.model.brain.** { *; }

# DTOs used by XStream to build the scan report XML
-keepclassmembers public class com.sonatype.insight.scan.model.* { *; }

-renamesourcefileattribute SourceFile
-keepattributes *Annotation*,Exceptions,InnerClasses,EnclosingMethod,Signature,SourceFile,LineNumberTable

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

