/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
package com.sonatype.insight.brain.audit;

/**
 * Enumeration of audited events, ensuring consistency when multiple code paths trigger the same event.
 */
public enum AuditEvent
{
  AUTHENTICATION_FAILURE(Domain.AUTHENTICATION, Type.FAILURE),
  LOGIN(Domain.AUTHENTICATION, Type.LOGIN),
  LOGOUT(Domain.AUTHENTICATION, Type.LOGOUT),

  CREATE_USER(Domain.SECURITY_USER, Type.CREATE),
  UPDATE_USER(Domain.SECURITY_USER, Type.UPDATE),
  DELETE_USER(Domain.SECURITY_USER, Type.DELETE),
  UPDATE_USER_PASSWORD(Domain.SECURITY_USER_PASSWORD, Type.UPDATE),
  RESET_USER_PASSWORD(Domain.SECURITY_USER_PASSWORD, Type.RESET),

  CREATE_ROLE(Domain.SECURITY_ROLE, Type.CREATE),
  UPDATE_ROLE(Domain.SECURITY_ROLE, Type.UPDATE),
  DELETE_ROLE(Domain.SECURITY_ROLE, Type.DELETE),

  CONFIGURE_ROLE_MEMBERSHIP(Domain.SECURITY_ROLE_MEMBERSHIP, Type.CONFIGURE),
  GRANT_ROLE_MEMBERSHIP(Domain.SECURITY_ROLE_MEMBERSHIP, Type.GRANT),
  REVOKE_ROLE_MEMBERSHIP(Domain.SECURITY_ROLE_MEMBERSHIP, Type.REVOKE),

  UPDATE_COMPONENT_VULNERABILITY(Domain.GOVERNANCE_COMPONENT_VULNERABILITY, Type.UPDATE),
  UPDATE_COMPONENT_LICENSE(Domain.GOVERNANCE_COMPONENT_LICENSE, Type.UPDATE),
  SET_COMPONENT_IDENTITY(Domain.GOVERNANCE_COMPONENT_IDENTITY, Type.SET),
  UNSET_COMPONENT_IDENTITY(Domain.GOVERNANCE_COMPONENT_IDENTITY, Type.UNSET),
  ASSIGN_COMPONENT_LABEL(Domain.GOVERNANCE_COMPONENT_LABEL, Type.ASSIGN),
  REMOVE_COMPONENT_LABEL(Domain.GOVERNANCE_COMPONENT_LABEL, Type.REMOVE),

  CREATE_APPLICATION_CATEGORY(Domain.GOVERNANCE_APPLICATION_CATEGORY, Type.CREATE),
  UPDATE_APPLICATION_CATEGORY(Domain.GOVERNANCE_APPLICATION_CATEGORY, Type.UPDATE),
  DELETE_APPLICATION_CATEGORY(Domain.GOVERNANCE_APPLICATION_CATEGORY, Type.DELETE),
  IMPORT_APPLICATION_CATEGORY(Domain.GOVERNANCE_APPLICATION_CATEGORY, Type.IMPORT),

  CREATE_WAIVER(Domain.GOVERNANCE_WAIVER, Type.CREATE),
  DELETE_WAIVER(Domain.GOVERNANCE_WAIVER, Type.DELETE),

  CREATE_LABEL(Domain.GOVERNANCE_LABEL, Type.CREATE),
  UPDATE_LABEL(Domain.GOVERNANCE_LABEL, Type.UPDATE),
  DELETE_LABEL(Domain.GOVERNANCE_LABEL, Type.DELETE),
  IMPORT_LABEL(Domain.GOVERNANCE_LABEL, Type.IMPORT),

  EVALUATE_APPLICATION(Domain.GOVERNANCE_EVALUATION_APPLICATION, Type.EVALUATE),
  EVALUATE_PROJECT(Domain.GOVERNANCE_EVALUATION_PROJECT, Type.EVALUATE),
  EVALUATE_REPOSITORY(Domain.GOVERNANCE_EVALUATION_REPOSITORY, Type.EVALUATE),
  INITIATE_EVALUATE_REPOSITORY(Domain.GOVERNANCE_EVALUATION_REPOSITORY, Type.INITIATE),

  EVALUATE_AD_HOC(Domain.GOVERNANCE_EVALUATION_AD_HOC, Type.EVALUATE),
  EXPORT_EVALUATION_AD_HOC(Domain.GOVERNANCE_EVALUATION_AD_HOC, Type.EXPORT),

  CONFIGURE_PROPRIETARY_COMPONENTS(Domain.GOVERNANCE_PROPRIETARY_COMPONENTS, Type.CONFIGURE),

  IMPORT(Domain.GOVERNANCE_IMPORT, Type.IMPORT),

  CREATE_LICENSE_THREAT_GROUP(Domain.GOVERNANCE_LICENSE_THREAT_GROUP, Type.CREATE),
  UPDATE_LICENSE_THREAT_GROUP(Domain.GOVERNANCE_LICENSE_THREAT_GROUP, Type.UPDATE),
  DELETE_LICENSE_THREAT_GROUP(Domain.GOVERNANCE_LICENSE_THREAT_GROUP, Type.DELETE),
  IMPORT_LICENSE_THREAT_GROUP(Domain.GOVERNANCE_LICENSE_THREAT_GROUP, Type.IMPORT),
  CONFIGURE_LICENSE_THREAT_GROUP_LICENSES(Domain.GOVERNANCE_LICENSE_THREAT_GROUP_LICENSES, Type.CONFIGURE),

  APPLY_GRANDFATHERING(Domain.GOVERNANCE_GRANDFATHERING, Type.APPLY),
  REVOKE_GRANDFATHERING(Domain.GOVERNANCE_GRANDFATHERING, Type.REVOKE),
  CONFIGURE_GRANDFATHERING(Domain.GOVERNANCE_GRANDFATHERING, Type.CONFIGURE),

  CONFIGURE_CONTINUOUS_MONITORING(Domain.GOVERNANCE_CONTINUOUS_MONITORING, Type.CONFIGURE),

  CREATE_ORGANIZATION(Domain.GOVERNANCE_ORGANIZATION, Type.CREATE),
  UPDATE_ORGANIZATION(Domain.GOVERNANCE_ORGANIZATION, Type.UPDATE),
  DELETE_ORGANIZATION(Domain.GOVERNANCE_ORGANIZATION, Type.DELETE),

  CONFIGURE_ORGANIZATION_ICON(Domain.GOVERNANCE_ORGANIZATION_ICON, Type.CONFIGURE),

  CREATE_POLICY(Domain.GOVERNANCE_POLICY, Type.CREATE),
  UPDATE_POLICY(Domain.GOVERNANCE_POLICY, Type.UPDATE),
  DELETE_POLICY(Domain.GOVERNANCE_POLICY, Type.DELETE),
  IMPORT_POLICY(Domain.GOVERNANCE_POLICY, Type.IMPORT),

  CONFIGURE_POLICY_INHERITANCE(Domain.GOVERNANCE_POLICY_INHERITANCE, Type.CONFIGURE),

  CONNECT_REPOSITORY(Domain.GOVERNANCE_REPOSITORY, Type.CONNECT),
  DISCONNECT_REPOSITORY(Domain.GOVERNANCE_REPOSITORY, Type.DISCONNECT),
  REMOVE_REPOSITORY(Domain.GOVERNANCE_REPOSITORY, Type.REMOVE),
  MIGRATE_REPOSITORY(Domain.GOVERNANCE_REPOSITORY, Type.MIGRATE),

  CONFIGURE_QUARANTINE(Domain.GOVERNANCE_REPOSITORY_QUARANTINE, Type.CONFIGURE),
  RELEASE_QUARANTINE(Domain.GOVERNANCE_REPOSITORY_QUARANTINE, Type.RELEASE),
  RETAIN_QUARANTINE(Domain.GOVERNANCE_REPOSITORY_QUARANTINE, Type.RETAIN),
  RESET_QUARANTINE(Domain.GOVERNANCE_REPOSITORY_QUARANTINE, Type.RESET),

  CREATE_LDAP_SERVER(Domain.SECURITY_LDAP_SERVER, Type.CREATE),
  UPDATE_LDAP_SERVER(Domain.SECURITY_LDAP_SERVER, Type.UPDATE),
  DELETE_LDAP_SERVER(Domain.SECURITY_LDAP_SERVER, Type.DELETE),
  CONFIGURE_LDAP_CONNECTION(Domain.SECURITY_LDAP_SERVER_CONNECTION, Type.CONFIGURE),
  CONFIGURE_LDAP_USER_MAPPING(Domain.SECURITY_LDAP_SERVER_USER_MAPPING, Type.CONFIGURE),
  PRIORITIZE_LDAP(Domain.SECURITY_LDAP, Type.PRIORITIZE),

  CREATE_APPLICATION(Domain.GOVERNANCE_APPLICATION, Type.CREATE),
  UPDATE_APPLICATION(Domain.GOVERNANCE_APPLICATION, Type.UPDATE),
  DELETE_APPLICATION(Domain.GOVERNANCE_APPLICATION, Type.DELETE),
  MOVE_APPLICATION(Domain.GOVERNANCE_APPLICATION, Type.MOVE),
  AUTO_CREATE_APPLICATION(Domain.GOVERNANCE_APPLICATION, Type.AUTO_CREATE),
  CONFIGURE_APPLICATION_CATEGORY(Domain.GOVERNANCE_APPLICATION_CATEGORIES, Type.CONFIGURE),
  CONFIGURE_APPLICATION_ICON(Domain.GOVERNANCE_APPLICATION_ICON, Type.CONFIGURE),
  CONFIGURE_AUTOMATIC_APPLICATIONS(Domain.GOVERNANCE_AUTOMATIC_APPLICATIONS, Type.CONFIGURE),

  CONFIGURE_DATA_RETENTION(Domain.SERVER_DATA_RETENTION, Type.CONFIGURE),

  CONFIGURE_SYSTEM_NOTICE(Domain.SERVER_SYSTEM_NOTICE, Type.CONFIGURE),

  INSTALL_LICENSE(Domain.SERVER_LICENSE, Type.INSTALL),
  UNINSTALL_LICENSE(Domain.SERVER_LICENSE, Type.UNINSTALL),
  START_SERVER(Domain.SERVER, Type.START),
  STOP_SERVER(Domain.SERVER, Type.STOP),

  CREATE_WEBHOOK(Domain.SERVER_WEBHOOK, Type.CREATE),
  UPDATE_WEBHOOK(Domain.SERVER_WEBHOOK, Type.UPDATE),
  DELETE_WEBHOOK(Domain.SERVER_WEBHOOK, Type.DELETE),

  VIEW_APPLICATION_COMPOSITION_REPORT(Domain.REPORTING_APPLICATION_COMPOSITION_REPORT, Type.VIEW),
  EXPORT_APPLICATION_COMPOSITION_REPORT(Domain.REPORTING_APPLICATION_COMPOSITION_REPORT, Type.EXPORT),
  PRINT_APPLICATION_COMPOSITION_REPORT(Domain.REPORTING_APPLICATION_COMPOSITION_REPORT, Type.PRINT),

  CONFIGURE_SUCCESS_METRICS(Domain.REPORTING_SUCCESS_METRICS, Type.CONFIGURE),

  SAVE_DASHBOARD_FILTER(Domain.REPORTING_DASHBOARD_FILTER, Type.SAVE),
  DELETE_DASHBOARD_FILTER(Domain.REPORTING_DASHBOARD_FILTER, Type.DELETE),

  VIEW_DASHBOARD_COMPONENT_DETAILS(Domain.REPORTING_DASHBOARD_COMPONENT_DETAILS, Type.VIEW),
  VIEW_REPOSITORY_RESULTS(Domain.REPORTING_REPOSITORY_RESULTS, Type.VIEW),
  VIEW_COMPONENT_INFORMATION(Domain.REPORTING_COMPONENT_INFORMATION, Type.VIEW),

  VIEW_SUCCESS_METRICS_REPORT(Domain.REPORTING_SUCCESS_METRICS_REPORT, Type.VIEW),
  EXPORT_SUCCESS_METRICS(Domain.REPORTING_SUCCESS_METRICS, Type.EXPORT),
  CREATE_SUCCESS_METRICS_REPORT(Domain.REPORTING_SUCCESS_METRICS_REPORT, Type.CREATE),
  DELETE_SUCCESS_METRICS_REPORT(Domain.REPORTING_SUCCESS_METRICS_REPORT, Type.DELETE),

  VIEW_DASHBOARD_VIOLATION_LIST(Domain.REPORTING_DASHBOARD_VIOLATION_LIST, Type.VIEW),
  VIEW_DASHBOARD_APPLICATION_LIST(Domain.REPORTING_DASHBOARD_APPLICATION_LIST, Type.VIEW),
  VIEW_DASHBOARD_COMPONENT_LIST(Domain.REPORTING_DASHBOARD_COMPONENT_LIST, Type.VIEW),
  
  EXPORT_DASHBOARD_APPLICATION_LIST(Domain.REPORTING_DASHBOARD_APPLICATION_LIST, Type.EXPORT), //
  EXPORT_DASHBOARD_COMPONENT_LIST(Domain.REPORTING_DASHBOARD_COMPONENT_LIST, Type.EXPORT), //
  EXPORT_DASHBOARD_VIOLATION_LIST(Domain.REPORTING_DASHBOARD_VIOLATION_LIST, Type.EXPORT), //

  EXPORT_POLICY_VIOLATIONS(Domain.REPORTING_POLICY_VIOLATIONS, Type.EXPORT), //

  SEARCH_COMPONENT_USES(Domain.REPORTING_COMPONENT_USES, Type.SEARCH), //

  INVOKE_WEBHOOK(Domain.NOTIFICATION_WEBHOOK, Type.INVOKE), //

  SEND_MAIL(Domain.NOTIFICATION_MAIL, Type.SEND),

  CREATE_JIRA_ISSUE(Domain.NOTIFICATION_ISSUE_JIRA, Type.CREATE),

  CONFIGURE_PROXY(Domain.SERVER_PROXY, Type.CONFIGURE),
  
  CREATE_SOURCE_CONTROL(Domain.GOVERNANCE_SOURCE_CONTROL, Type.CREATE),
  UPDATE_SOURCE_CONTROL(Domain.GOVERNANCE_SOURCE_CONTROL, Type.UPDATE),
  DELETE_SOURCE_CONTROL(Domain.GOVERNANCE_SOURCE_CONTROL, Type.DELETE);

  private final String domain;

  private final String type;

  AuditEvent(String domain, String event) {
    this.domain = domain;
    this.type = event;
  }

  public String getDomain() {
    return domain;
  }

  public String getType() {
    return type;
  }

  interface Domain
  {
    String AUTHENTICATION = "authentication";

    String GOVERNANCE = "governance";

    String SERVER = "server";

    String REPORTING = "reporting";

    String GOVERNANCE_COMPONENT = join(GOVERNANCE, "component");

    String GOVERNANCE_COMPONENT_VULNERABILITY = join(GOVERNANCE_COMPONENT, "vulnerability");

    String GOVERNANCE_COMPONENT_IDENTITY = join(GOVERNANCE_COMPONENT, "identity");

    String GOVERNANCE_COMPONENT_LABEL = join(GOVERNANCE_COMPONENT, "label");

    String GOVERNANCE_APPLICATION_CATEGORY = join(GOVERNANCE, "application-category");

    String GOVERNANCE_WAIVER = join(GOVERNANCE, "waiver");

    String GOVERNANCE_EVALUATION = join(GOVERNANCE, "evaluation");

    String GOVERNANCE_EVALUATION_APPLICATION = join(GOVERNANCE_EVALUATION, "application");

    String GOVERNANCE_EVALUATION_PROJECT = join(GOVERNANCE_EVALUATION, "project");

    String GOVERNANCE_EVALUATION_REPOSITORY = join(GOVERNANCE_EVALUATION, "repository");

    String GOVERNANCE_EVALUATION_AD_HOC = join(GOVERNANCE_EVALUATION, "ad-hoc");

    String GOVERNANCE_COMPONENT_LICENSE = join(GOVERNANCE_COMPONENT, "license");

    String GOVERNANCE_IMPORT = join(GOVERNANCE, "import");

    String GOVERNANCE_GRANDFATHERING = join(GOVERNANCE, "grandfathering");

    String GOVERNANCE_PROPRIETARY_COMPONENTS = join(GOVERNANCE, "proprietary-components");

    String GOVERNANCE_ORGANIZATION = join(GOVERNANCE, "organization");

    String GOVERNANCE_ORGANIZATION_ICON = join(GOVERNANCE_ORGANIZATION, "icon");

    String GOVERNANCE_CONTINUOUS_MONITORING = join(GOVERNANCE, "continuous-monitoring");

    String GOVERNANCE_LABEL = join(GOVERNANCE, "component-label");

    String GOVERNANCE_LICENSE_THREAT_GROUP = join(GOVERNANCE, "license-threat-group");

    String GOVERNANCE_LICENSE_THREAT_GROUP_LICENSES = join(GOVERNANCE_LICENSE_THREAT_GROUP, "licenses");

    String GOVERNANCE_POLICY = join(GOVERNANCE, "policy");

    String GOVERNANCE_POLICY_INHERITANCE = join(GOVERNANCE_POLICY, "inheritance");

    String GOVERNANCE_REPOSITORY = join(GOVERNANCE, "repository");

    String GOVERNANCE_REPOSITORY_QUARANTINE = join(GOVERNANCE_REPOSITORY, "quarantine");

    String GOVERNANCE_APPLICATION = join(GOVERNANCE, "application");

    String GOVERNANCE_APPLICATION_CATEGORIES = join(GOVERNANCE_APPLICATION, "categories");

    String GOVERNANCE_APPLICATION_ICON = join(GOVERNANCE_APPLICATION, "icon");

    String GOVERNANCE_AUTOMATIC_APPLICATIONS = join(GOVERNANCE, "automatic-applications");

    String GOVERNANCE_SOURCE_CONTROL = join(GOVERNANCE, "source-control");

    String SECURITY = "security";

    String SECURITY_USER = join(SECURITY, "user");

    String SECURITY_USER_PASSWORD = join(SECURITY_USER, "password");

    String SECURITY_ROLE = join(SECURITY, "role");

    String SECURITY_ROLE_MEMBERSHIP = join(SECURITY_ROLE, "membership");

    String SECURITY_LDAP = join(SECURITY, "ldap");

    String SECURITY_LDAP_SERVER = join(SECURITY_LDAP, "server");

    String SECURITY_LDAP_SERVER_CONNECTION = join(SECURITY_LDAP_SERVER, "connection");

    String SECURITY_LDAP_SERVER_USER_MAPPING = join(SECURITY_LDAP_SERVER, "user-mapping");

    String SERVER_DATA_RETENTION = join(SERVER, "data-retention");

    String SERVER_LICENSE = join(SERVER, "license");

    String SERVER_SYSTEM_NOTICE = join(SERVER, "system-notice");

    String SERVER_WEBHOOK = join(SERVER, "webhook");

    String SERVER_PROXY = join(SERVER, "proxy");
    
    String REPORTING_APPLICATION_COMPOSITION = join(REPORTING, "application-composition");

    String REPORTING_APPLICATION_COMPOSITION_REPORT = join(REPORTING_APPLICATION_COMPOSITION, "report");

    String REPORTING_SUCCESS_METRICS = join(REPORTING, "success-metrics");

    String REPORTING_DASHBOARD = join(REPORTING, "dashboard");

    String REPORTING_DASHBOARD_FILTER = join(REPORTING_DASHBOARD, "filter");

    String REPORTING_DASHBOARD_COMPONENT_DETAILS = join(REPORTING_DASHBOARD, "component-details");

    String REPORTING_REPOSITORY_RESULTS = join(REPORTING, "repository-results");

    String REPORTING_COMPONENT_INFORMATION = join(REPORTING, "component-information");
    
    String REPORTING_SUCCESS_METRICS_REPORT = join(REPORTING_SUCCESS_METRICS, "report");

    String REPORTING_DASHBOARD_VIOLATION_LIST = join(REPORTING_DASHBOARD, "violation-list");

    String REPORTING_DASHBOARD_APPLICATION_LIST = join(REPORTING_DASHBOARD, "application-list");

    String REPORTING_DASHBOARD_COMPONENT_LIST = join(REPORTING_DASHBOARD, "component-list");

    String REPORTING_POLICY_VIOLATIONS = join(REPORTING, "policy-violations");

    String REPORTING_COMPONENT_USES = join(REPORTING, "component-uses");

    String NOTIFICATION = "notification";

    String NOTIFICATION_WEBHOOK = join(NOTIFICATION, "webhook");

    String NOTIFICATION_MAIL = join(NOTIFICATION, "mail");

    String NOTIFICATION_ISSUE_JIRA = join(NOTIFICATION, join("issue", "jira"));
    
    static String join(String parent, String child) {
      return parent + "." + child;
    }
  }

  private interface Type
  {
    String FAILURE = "failure";

    String LOGIN = "login";

    String LOGOUT = "logout";

    String EVALUATE = "evaluate";

    String SET = "set";

    String RESET = "reset";

    String UNSET = "unset";

    String ASSIGN = "assign";

    String REMOVE = "remove";

    String APPLY = "apply";

    String REVOKE = "revoke";

    String CONFIGURE = "configure";

    String CREATE = "create";

    String UPDATE = "update";

    String DELETE = "delete";

    String IMPORT = "import";

    String CONNECT = "connect";

    String DISCONNECT = "disconnect";

    String MIGRATE = "migrate";

    String INITIATE = "initiate";

    String RELEASE = "release";

    String RETAIN = "retain";

    String PRIORITIZE = "prioritize";

    String MOVE = "move";

    String AUTO_CREATE = "auto-create";

    String INSTALL = "install";

    String UNINSTALL = "uninstall";

    String START = "start";

    String STOP = "stop";

    String VIEW = "view";

    String EXPORT = "export";

    String PRINT = "print";

    String SAVE = "save";

    String SEARCH = "search";

    String INVOKE = "invoke";

    String SEND = "send";

    String GRANT = "grant";
  }
}
