/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
package com.sonatype.insight.brain.audit;

/**
 * Enumeration of audited events, ensuring consistency when multiple code paths trigger the same event.
 */
public enum AuditEvent
{
  AUTHENTICATION_FAILURE(Domain.AUTHENTICATION, Type.FAILURE),
  LOGIN(Domain.AUTHENTICATION, Type.LOGIN),
  LOGOUT(Domain.AUTHENTICATION, Type.LOGOUT),

  CREATE_USER(Domain.SECURITY_USER, Type.CREATE),
  UPDATE_USER(Domain.SECURITY_USER, Type.UPDATE),
  DELETE_USER(Domain.SECURITY_USER, Type.DELETE),
  UPDATE_USER_PASSWORD(Domain.SECURITY_USER_PASSWORD, Type.UPDATE),
  RESET_USER_PASSWORD(Domain.SECURITY_USER_PASSWORD, Type.RESET),

  CREATE_ROLE(Domain.SECURITY_ROLE, Type.CREATE),
  UPDATE_ROLE(Domain.SECURITY_ROLE, Type.UPDATE),
  DELETE_ROLE(Domain.SECURITY_ROLE, Type.DELETE),

  CONFIGURE_ROLE_MEMBERSHIP(Domain.SECURITY_ROLE_MEMBERSHIP, Type.CONFIGURE),
  GRANT_ROLE_MEMBERSHIP(Domain.SECURITY_ROLE_MEMBERSHIP, Type.GRANT),
  REVOKE_ROLE_MEMBERSHIP(Domain.SECURITY_ROLE_MEMBERSHIP, Type.REVOKE),

  CREATE_USER_MAPPINGS(Domain.SECURITY_ROLE, Type.CREATE),
  DELETE_USER_MAPPINGS(Domain.SECURITY_ROLE, Type.DELETE),

  UPDATE_COMPONENT_VULNERABILITY(Domain.GOVERNANCE_COMPONENT_VULNERABILITY, Type.UPDATE),
  UPDATE_COMPONENT_LICENSE(Domain.GOVERNANCE_COMPONENT_LICENSE, Type.UPDATE),
  SET_COMPONENT_IDENTITY(Domain.GOVERNANCE_COMPONENT_IDENTITY, Type.SET),
  UNSET_COMPONENT_IDENTITY(Domain.GOVERNANCE_COMPONENT_IDENTITY, Type.UNSET),
  ASSIGN_COMPONENT_LABEL(Domain.GOVERNANCE_COMPONENT_LABEL, Type.ASSIGN),
  REMOVE_COMPONENT_LABEL(Domain.GOVERNANCE_COMPONENT_LABEL, Type.REMOVE),
  UPDATE_COMPONENT_COPYRIGHT(Domain.GOVERNANCE_COMPONENT_COPYRIGHT, Type.UPDATE),
  UPDATE_COMPONENT_SOURCE_LINK(Domain.GOVERNANCE_COMPONENT_SOURCE_LINK, Type.UPDATE),
  UPDATE_COMPONENT_LEGAL_FILE(Domain.GOVERNANCE_COMPONENT_LEGAL_FILE, Type.UPDATE),
  CREATE_COMPONENT_OBLIGATION(Domain.GOVERNANCE_COMPONENT_OBLIGATION, Type.CREATE),
  UPDATE_COMPONENT_OBLIGATION(Domain.GOVERNANCE_COMPONENT_OBLIGATION, Type.UPDATE),
  DELETE_COMPONENT_OBLIGATION(Domain.GOVERNANCE_COMPONENT_OBLIGATION, Type.DELETE),
  SAVE_COMPONENT_OBLIGATIONS(Domain.GOVERNANCE_COMPONENT_OBLIGATIONS, Type.SAVE),
  CREATE_COMPONENT_OBLIGATION_ATTRIBUTION(Domain.GOVERNANCE_COMPONENT_OBLIGATION_ATTRIBUTION, Type.CREATE),
  UPDATE_COMPONENT_OBLIGATION_ATTRIBUTION(Domain.GOVERNANCE_COMPONENT_OBLIGATION_ATTRIBUTION, Type.UPDATE),
  DELETE_COMPONENT_OBLIGATION_ATTRIBUTION(Domain.GOVERNANCE_COMPONENT_OBLIGATION_ATTRIBUTION, Type.DELETE),

  CREATE_APPLICATION_CATEGORY(Domain.GOVERNANCE_APPLICATION_CATEGORY, Type.CREATE),
  UPDATE_APPLICATION_CATEGORY(Domain.GOVERNANCE_APPLICATION_CATEGORY, Type.UPDATE),
  DELETE_APPLICATION_CATEGORY(Domain.GOVERNANCE_APPLICATION_CATEGORY, Type.DELETE),
  IMPORT_APPLICATION_CATEGORY(Domain.GOVERNANCE_APPLICATION_CATEGORY, Type.IMPORT),

  CREATE_AUTO_WAIVER(Domain.GOVERNANCE_WAIVER, Type.CREATE),
  DELETE_AUTO_WAIVER(Domain.GOVERNANCE_WAIVER, Type.DELETE),
  UPDATE_AUTO_WAIVER(Domain.GOVERNANCE_WAIVER, Type.UPDATE),
  
  CREATE_AUTO_WAIVER_REVOCATION(Domain.GOVERNANCE_WAIVER, Type.CREATE),
  DELETE_AUTO_WAIVER_REVOCATION(Domain.GOVERNANCE_WAIVER, Type.DELETE),

  CREATE_WAIVER(Domain.GOVERNANCE_WAIVER, Type.CREATE),
  UPDATE_WAIVER(Domain.GOVERNANCE_WAIVER, Type.UPDATE),
  DELETE_WAIVER(Domain.GOVERNANCE_WAIVER, Type.DELETE),
  VIEW_WAIVER(Domain.GOVERNANCE_WAIVER, Type.VIEW),

  CREATE_WAIVER_REQUEST(Domain.GOVERNANCE_WAIVER_REQUEST, Type.CREATE),
  UPDATE_WAIVER_REQUEST(Domain.GOVERNANCE_WAIVER_REQUEST, Type.UPDATE),
  REVIEW_WAIVER_REQUEST(Domain.GOVERNANCE_WAIVER_REQUEST, Type.REVIEW),

  CREATE_LABEL(Domain.GOVERNANCE_LABEL, Type.CREATE),
  UPDATE_LABEL(Domain.GOVERNANCE_LABEL, Type.UPDATE),
  DELETE_LABEL(Domain.GOVERNANCE_LABEL, Type.DELETE),
  IMPORT_LABEL(Domain.GOVERNANCE_LABEL, Type.IMPORT),

  EVALUATE_APPLICATION(Domain.GOVERNANCE_EVALUATION_APPLICATION, Type.EVALUATE),
  EVALUATE_PROJECT(Domain.GOVERNANCE_EVALUATION_PROJECT, Type.EVALUATE),
  EVALUATE_REPOSITORY(Domain.GOVERNANCE_EVALUATION_REPOSITORY, Type.EVALUATE),
  INITIATE_EVALUATE_REPOSITORY(Domain.GOVERNANCE_EVALUATION_REPOSITORY, Type.INITIATE),
  INITIATE_CASCADE_REEVALUATION(Domain.GOVERNANCE_EVALUATION_CASCADE, Type.INITIATE),

  EVALUATE_AD_HOC(Domain.GOVERNANCE_EVALUATION_AD_HOC, Type.EVALUATE),
  EVALUATE_THIRD_PARTY(Domain.GOVERNANCE_EVALUATION_THIRD_PARTY, Type.EVALUATE),
  EXPORT_EVALUATION_AD_HOC(Domain.GOVERNANCE_EVALUATION_AD_HOC, Type.EXPORT),

  CONFIGURE_PROPRIETARY_COMPONENTS(Domain.GOVERNANCE_PROPRIETARY_COMPONENTS, Type.CONFIGURE),

  CONFIGURE_CALL_FLOW_ANALYSIS(Domain.GOVERNANCE_CALL_FLOW_ANALYSIS_CONFIG, Type.CONFIGURE),

  DELETE_CONFIGURE_CALL_FLOW_ANALYSIS(Domain.GOVERNANCE_CALL_FLOW_ANALYSIS_DELETE, Type.DELETE),

  ADD_PROPRIETARY_COMPONENT_NAMES(Domain.GOVERNANCE_PROPRIETARY_COMPONENTS, Type.ADD),
  REMOVE_PROPRIETARY_COMPONENT_NAMES(Domain.GOVERNANCE_PROPRIETARY_COMPONENTS, Type.REMOVE),

  IMPORT(Domain.GOVERNANCE_IMPORT, Type.IMPORT),

  CREATE_LICENSE_THREAT_GROUP(Domain.GOVERNANCE_LICENSE_THREAT_GROUP, Type.CREATE),
  UPDATE_LICENSE_THREAT_GROUP(Domain.GOVERNANCE_LICENSE_THREAT_GROUP, Type.UPDATE),
  DELETE_LICENSE_THREAT_GROUP(Domain.GOVERNANCE_LICENSE_THREAT_GROUP, Type.DELETE),
  IMPORT_LICENSE_THREAT_GROUP(Domain.GOVERNANCE_LICENSE_THREAT_GROUP, Type.IMPORT),
  CONFIGURE_LICENSE_THREAT_GROUP_LICENSES(Domain.GOVERNANCE_LICENSE_THREAT_GROUP_LICENSES, Type.CONFIGURE),

  APPLY_LEGACY_VIOLATION_STATUS(Domain.GOVERNANCE_LEGACY_VIOLATION_STATUS, Type.APPLY),
  REVOKE_LEGACY_VIOLATION_STATUS(Domain.GOVERNANCE_LEGACY_VIOLATION_STATUS, Type.REVOKE),
  CONFIGURE_LEGACY_VIOLATION_STATUS(Domain.GOVERNANCE_LEGACY_VIOLATION_STATUS, Type.CONFIGURE),

  UPDATE_CPE_MATCHING_CONFIGURATION(Domain.GOVERNANCE_CPE_MATCHING_CONFIGURATION, Type.UPDATE),

  UPDATE_CI_CONFIGURATION(Domain.GOVERNANCE_CI_CONFIGURATION, Type.UPDATE),
  DELETE_CI_CONFIGURATION(Domain.GOVERNANCE_CI_CONFIGURATION, Type.DELETE),

  CONFIGURE_CONTINUOUS_MONITORING(Domain.GOVERNANCE_CONTINUOUS_MONITORING, Type.CONFIGURE),

  CREATE_ORGANIZATION(Domain.GOVERNANCE_ORGANIZATION, Type.CREATE),
  UPDATE_ORGANIZATION(Domain.GOVERNANCE_ORGANIZATION, Type.UPDATE),
  DELETE_ORGANIZATION(Domain.GOVERNANCE_ORGANIZATION, Type.DELETE),

  CONFIGURE_ORGANIZATION_ICON(Domain.GOVERNANCE_ORGANIZATION_ICON, Type.CONFIGURE),

  CREATE_POLICY(Domain.GOVERNANCE_POLICY, Type.CREATE),
  UPDATE_POLICY(Domain.GOVERNANCE_POLICY, Type.UPDATE),
  DELETE_POLICY(Domain.GOVERNANCE_POLICY, Type.DELETE),
  IMPORT_POLICY(Domain.GOVERNANCE_POLICY, Type.IMPORT),

  CONFIGURE_POLICY_INHERITANCE(Domain.GOVERNANCE_POLICY_INHERITANCE, Type.CONFIGURE),
  UPDATE_OVERRIDES(Domain.GOVERNANCE_POLICY_OVERRIDES, Type.UPDATE),
  CONNECT_REPOSITORY(Domain.GOVERNANCE_REPOSITORY, Type.CONNECT),
  CONFIGURE_REPOSITORY(Domain.GOVERNANCE_REPOSITORY, Type.CONFIGURE),
  DISCONNECT_REPOSITORY(Domain.GOVERNANCE_REPOSITORY, Type.DISCONNECT),
  REMOVE_REPOSITORY(Domain.GOVERNANCE_REPOSITORY, Type.REMOVE),
  MIGRATE_REPOSITORY(Domain.GOVERNANCE_REPOSITORY, Type.MIGRATE),

  CONFIGURE_QUARANTINE(Domain.GOVERNANCE_REPOSITORY_QUARANTINE, Type.CONFIGURE),
  RELEASE_QUARANTINE(Domain.GOVERNANCE_REPOSITORY_QUARANTINE, Type.RELEASE),
  RETAIN_QUARANTINE(Domain.GOVERNANCE_REPOSITORY_QUARANTINE, Type.RETAIN),
  RESET_QUARANTINE(Domain.GOVERNANCE_REPOSITORY_QUARANTINE, Type.RESET),

  CREATE_LDAP_SERVER(Domain.SECURITY_LDAP_SERVER, Type.CREATE),
  UPDATE_LDAP_SERVER(Domain.SECURITY_LDAP_SERVER, Type.UPDATE),
  DELETE_LDAP_SERVER(Domain.SECURITY_LDAP_SERVER, Type.DELETE),
  CONFIGURE_LDAP_CONNECTION(Domain.SECURITY_LDAP_SERVER_CONNECTION, Type.CONFIGURE),
  CONFIGURE_LDAP_USER_MAPPING(Domain.SECURITY_LDAP_SERVER_USER_MAPPING, Type.CONFIGURE),
  PRIORITIZE_LDAP(Domain.SECURITY_LDAP, Type.PRIORITIZE),

  CREATE_APPLICATION(Domain.GOVERNANCE_APPLICATION, Type.CREATE),
  UPDATE_APPLICATION(Domain.GOVERNANCE_APPLICATION, Type.UPDATE),
  DELETE_APPLICATION(Domain.GOVERNANCE_APPLICATION, Type.DELETE),
  MOVE_APPLICATION(Domain.GOVERNANCE_APPLICATION, Type.MOVE),
  AUTO_CREATE_APPLICATION(Domain.GOVERNANCE_APPLICATION, Type.AUTO_CREATE),
  CONFIGURE_APPLICATION_CATEGORY(Domain.GOVERNANCE_APPLICATION_CATEGORIES, Type.CONFIGURE),
  CONFIGURE_APPLICATION_ICON(Domain.GOVERNANCE_APPLICATION_ICON, Type.CONFIGURE),
  CONFIGURE_AUTOMATIC_APPLICATIONS(Domain.GOVERNANCE_AUTOMATIC_APPLICATIONS, Type.CONFIGURE),
  CONFIGURE_AUTOMATIC_SOURCE_CONTROL(Domain.GOVERNANCE_AUTOMATIC_SOURCE_CONTROL, Type.CONFIGURE),

  CONFIGURE_DATA_RETENTION(Domain.SERVER_DATA_RETENTION, Type.CONFIGURE),

  CONFIGURE_SYSTEM_NOTICE(Domain.SERVER_SYSTEM_NOTICE, Type.CONFIGURE),

  INSTALL_LICENSE(Domain.SERVER_LICENSE, Type.INSTALL),
  UNINSTALL_LICENSE(Domain.SERVER_LICENSE, Type.UNINSTALL),
  START_SERVER(Domain.SERVER, Type.START),
  STOP_SERVER(Domain.SERVER, Type.STOP),

  CREATE_WEBHOOK(Domain.SERVER_WEBHOOK, Type.CREATE),
  UPDATE_WEBHOOK(Domain.SERVER_WEBHOOK, Type.UPDATE),
  DELETE_WEBHOOK(Domain.SERVER_WEBHOOK, Type.DELETE),

  VIEW_APPLICATION_COMPOSITION_REPORT(Domain.REPORTING_APPLICATION_COMPOSITION_REPORT, Type.VIEW),
  EXPORT_APPLICATION_COMPOSITION_REPORT(Domain.REPORTING_APPLICATION_COMPOSITION_REPORT, Type.EXPORT),
  PRINT_APPLICATION_COMPOSITION_REPORT(Domain.REPORTING_APPLICATION_COMPOSITION_REPORT, Type.PRINT),

  CONFIGURE_ADVANCED_SEARCH(Domain.REPORTING_ADVANCED_SEARCH, Type.CONFIGURE),
  PERFORM_ADVANCED_SEARCH(Domain.REPORTING_ADVANCED_SEARCH, Type.SEARCH),

  CONFIGURE_SUCCESS_METRICS(Domain.REPORTING_SUCCESS_METRICS, Type.CONFIGURE),

  SAVE_DASHBOARD_FILTER(Domain.REPORTING_DASHBOARD_FILTER, Type.SAVE),
  DELETE_DASHBOARD_FILTER(Domain.REPORTING_DASHBOARD_FILTER, Type.DELETE),

  VIEW_DASHBOARD_COMPONENT_DETAILS(Domain.REPORTING_DASHBOARD_COMPONENT_DETAILS, Type.VIEW),
  VIEW_REPOSITORY_RESULTS(Domain.REPORTING_REPOSITORY_RESULTS, Type.VIEW),
  VIEW_COMPONENT_INFORMATION(Domain.REPORTING_COMPONENT_INFORMATION, Type.VIEW),

  VIEW_SUCCESS_METRICS_REPORT(Domain.REPORTING_SUCCESS_METRICS_REPORT, Type.VIEW),
  EXPORT_SUCCESS_METRICS(Domain.REPORTING_SUCCESS_METRICS, Type.EXPORT),
  CREATE_SUCCESS_METRICS_REPORT(Domain.REPORTING_SUCCESS_METRICS_REPORT, Type.CREATE),
  DELETE_SUCCESS_METRICS_REPORT(Domain.REPORTING_SUCCESS_METRICS_REPORT, Type.DELETE),

  VIEW_DASHBOARD_VIOLATION_LIST(Domain.REPORTING_DASHBOARD_VIOLATION_LIST, Type.VIEW),
  VIEW_DASHBOARD_APPLICATION_LIST(Domain.REPORTING_DASHBOARD_APPLICATION_LIST, Type.VIEW),
  VIEW_DASHBOARD_COMPONENT_LIST(Domain.REPORTING_DASHBOARD_COMPONENT_LIST, Type.VIEW),
  VIEW_DASHBOARD_WAIVER_LIST(Domain.REPORTING_DASHBOARD_WAIVER_LIST, Type.VIEW),

  EXPORT_DASHBOARD_APPLICATION_LIST(Domain.REPORTING_DASHBOARD_APPLICATION_LIST, Type.EXPORT), //
  EXPORT_DASHBOARD_COMPONENT_LIST(Domain.REPORTING_DASHBOARD_COMPONENT_LIST, Type.EXPORT), //
  EXPORT_DASHBOARD_VIOLATION_LIST(Domain.REPORTING_DASHBOARD_VIOLATION_LIST, Type.EXPORT), //
  EXPORT_DASHBOARD_WAIVER_LIST(Domain.REPORTING_DASHBOARD_WAIVER_LIST, Type.EXPORT), //

  EXPORT_MOVE_ORGANIZATION_ERRORS_LIST(Domain.REPORTING_MOVE_ORGANIZATION_ERRORS, Type.EXPORT),

  EXPORT_VULNERABILITY_SIGNATURES(Domain.REPORTING_VULNERABILITY_SIGNATURES, Type.EXPORT),
  IMPORT_VULNERABILITY_SIGNATURES_REACHABILITY(Domain.GOVERNANCE_VULNERABILITY_SIGNATURES_REACHABILITY, Type.IMPORT),

  EXPORT_POLICY_VIOLATIONS(Domain.REPORTING_POLICY_VIOLATIONS, Type.EXPORT), //

  VIEW_COMPONENT_TRANSITIVE_POLICY_VIOLATIONS(Domain.REPORTING_COMPONENT_TRANSITIVE_POLICY_VIOLATIONS, Type.VIEW), //
  CREATE_TRANSITIVE_POLICY_VIOLATIONS_WAIVER(Domain.GOVERNANCE_WAIVER_TRANSITIVE, Type.CREATE), //

  CREATE_CONTAINER_IMAGE_POLICY_VIOLATIONS_WAIVER(Domain.GOVERNANCE_WAIVER_CONTAINER, Type.CREATE), //
  DELETE_CONTAINER_IMAGE_POLICY_VIOLATIONS_WAIVER(Domain.GOVERNANCE_WAIVER_CONTAINER, Type.DELETE), //

  SEARCH_COMPONENT_USES(Domain.REPORTING_COMPONENT_USES, Type.SEARCH), //

  INVOKE_WEBHOOK(Domain.NOTIFICATION_WEBHOOK, Type.INVOKE), //

  SEND_MAIL(Domain.NOTIFICATION_MAIL, Type.SEND),

  CREATE_JIRA_ISSUE(Domain.NOTIFICATION_ISSUE_JIRA, Type.CREATE),

  CREATE_PULL_REQUEST(Domain.NOTIFICATION_PULL_REQUEST, Type.CREATE),

  CREATE_PULL_REQUEST_COMMENT(Domain.NOTIFICATION_PULL_REQUEST_COMMENT, Type.CREATE),
  UPDATE_PULL_REQUEST_COMMENT(Domain.NOTIFICATION_PULL_REQUEST_COMMENT, Type.UPDATE),

  CONFIGURE_PROXY(Domain.SERVER_PROXY, Type.CONFIGURE),

  CONFIGURE_MAIL(Domain.SERVER_MAIL, Type.CONFIGURE),
  DELETE_MAIL(Domain.SERVER_MAIL, Type.DELETE),

  DELETE_PROXY(Domain.SERVER_PROXY, Type.DELETE),

  CREATE_SOURCE_CONTROL(Domain.GOVERNANCE_SOURCE_CONTROL, Type.CREATE),
  UPDATE_SOURCE_CONTROL(Domain.GOVERNANCE_SOURCE_CONTROL, Type.UPDATE),
  DELETE_SOURCE_CONTROL(Domain.GOVERNANCE_SOURCE_CONTROL, Type.DELETE),
  AUTO_CREATE_SOURCE_CONTROL(Domain.GOVERNANCE_SOURCE_CONTROL, Type.AUTO_CREATE),
  CONFIGURE_SAML(Domain.SECURITY_SAML, Type.CONFIGURE),
  DELETE_SAML(Domain.SECURITY_SAML, Type.DELETE),
  CONFIGURE_CROWD(Domain.SECURITY_CROWD, Type.CONFIGURE),
  DELETE_CROWD(Domain.SECURITY_CROWD, Type.DELETE),

  VIEW_COMPONENTS_WITH_WAIVERS(Domain.REPORTING_COMPONENTS_WITH_WAIVERS, Type.VIEW),
  VIEW_STALE_WAIVERS(Domain.REPORTING_STALE_WAIVERS, Type.VIEW),
  VIEW_QUARANTINED_COMPONENTS(Domain.REPORTING_QUARANTINED_COMPONENTS, Type.VIEW),

  CREATE_USER_TOKEN(Domain.SECURITY_USER_TOKEN, Type.CREATE),
  DELETE_USER_TOKEN(Domain.SECURITY_USER_TOKEN, Type.DELETE),
  PURGE_USER_TOKENS(Domain.SECURITY_USER_TOKEN, Type.PURGE),

  CONFIGURE_REPOSITORY_CONNECTION(Domain.SERVER_REPOSITORY, Type.CONFIGURE),
  DELETE_REPOSITORY_CONNECTION(Domain.SERVER_REPOSITORY, Type.DELETE),

  CONFIGURE_ARTIFACTORY_CONNECTION(Domain.SERVER_ARTIFACTORY, Type.CONFIGURE),
  DELETE_ARTIFACTORY_CONNECTION(Domain.SERVER_ARTIFACTORY, Type.DELETE),

  SAVE_USER_FILTER(Domain.REPORTING_USER_FILTER, Type.SAVE),
  DELETE_USER_FILTER(Domain.REPORTING_USER_FILTER, Type.DELETE),

  CONFIGURE_SECURITY_QUARANTINED_COMPONENT_VIEW_ANON_ACCESS(Domain.SECURITY_QUARANTINED_COMPONENT_VIEW_ANON_ACCESS,
      Type.CONFIGURE),

  DELETE_REPOSITORY_IDENTIFIED_COMPONENT(Domain.GOVERNANCE_REPOSITORY_IDENTIFIED_COMPONENT, Type.DELETE),

  PURGE_REPOSITORY_IDENTIFIED_COMPONENTS(Domain.GOVERNANCE_REPOSITORY_IDENTIFIED_COMPONENT, Type.PURGE),

  CONFIGURE_REVERSE_PROXY_AUTHENTICATION(Domain.SERVER_REVERSE_PROXY_AUTHENTICATION, Type.CONFIGURE),
  DELETE_REVERSE_PROXY_AUTHENTICATION(Domain.SERVER_REVERSE_PROXY_AUTHENTICATION, Type.DELETE),

  CONFIGURE_JIRA(Domain.SERVER_JIRA, Type.CONFIGURE),
  DELETE_JIRA(Domain.SERVER_JIRA, Type.DELETE),

  SAVE_VULNERABILITY_CUSTOM_REMEDIATION(Domain.GOVERNANCE_VULNERABILITY_CUSTOM_REMEDIATION, Type.SAVE),
  SAVE_VULNERABILITY_CUSTOM_CWE(Domain.GOVERNANCE_VULNERABILITY_CUSTOM_CWE, Type.SAVE),
  SAVE_VULNERABILITY_CUSTOM_CVSS_VECTOR(Domain.GOVERNANCE_VULNERABILITY_CUSTOM_CVSS_VECTOR,Type.SAVE),
  SAVE_VULNERABILITY_CUSTOM_CVSS_SEVERITY(Domain.GOVERNANCE_VULNERABILITY_CUSTOM_CVSS_SEVERITY,Type.SAVE),
  DELETE_VULNERABILITY_CUSTOM_REMEDIATION(Domain.GOVERNANCE_VULNERABILITY_CUSTOM_REMEDIATION, Type.DELETE),
  DELETE_VULNERABILITY_CUSTOM_CWE(Domain.GOVERNANCE_VULNERABILITY_CUSTOM_CWE, Type.DELETE),
  DELETE_VULNERABILITY_CUSTOM_CVSS_VECTOR(Domain.GOVERNANCE_VULNERABILITY_CUSTOM_CVSS_VECTOR, Type.DELETE),
  DELETE_VULNERABILITY_CUSTOM_CVSS_SEVERITY(Domain.GOVERNANCE_VULNERABILITY_CUSTOM_CVSS_SEVERITY, Type.DELETE),

  CONFIGURE_SOURCE_CONTROL_CONFIGURATION(Domain.SERVER_SOURCE_CONTROL, Type.CONFIGURE),
  DELETE_SOURCE_CONTROL_CONFIGURATION(Domain.SERVER_SOURCE_CONTROL, Type.DELETE),

  CONFIGURE_PROPERTIES(Domain.SERVER_PROPERTIES, Type.CONFIGURE),
  DELETE_PROPERTIES(Domain.SERVER_PROPERTIES, Type.DELETE),

  SET_FEATURES(Domain.SERVER_FEATURES, Type.SET),
  UNSET_FEATURES(Domain.SERVER_FEATURES, Type.UNSET),

  SAVE_VULNERABILITY_GROUP(Domain.GOVERNANCE_VULNERABILITY_GROUP, Type.SAVE),
  DELETE_VULNERABILITY_GROUP(Domain.GOVERNANCE_VULNERABILITY_GROUP, Type.DELETE),

  // Events for MTIQ Admin endpoints
  LIST_TENANTS(Domain.MTIQ_TENANT, Type.VIEW),
  PROVISION_TENANT(Domain.MTIQ_TENANT, Type.CREATE),
  DELETE_TENANT(Domain.MTIQ_TENANT, Type.DELETE),
  MIGRATE_TENANT(Domain.MTIQ_TENANT, Type.MIGRATE),
  INSTALL_TENANT_LICENSE(Domain.MTIQ_TENANT_LICENSE, Type.INSTALL),
  UPDATE_TENANT_SECURITY(Domain.MTIQ_TENANT_SECURITY, Type.UPDATE),
  UPDATE_TENANT_CONFIGURATION(Domain.MTIQ_TENANT_CONFIGURATION, Type.UPDATE),
  DELETE_TENANT_CONFIGURATION(Domain.MTIQ_TENANT_CONFIGURATION, Type.DELETE),
  GENERATE_TENANT_SUPPORT_INFO(Domain.MTIQ_TENANT_SUPPORT, Type.EXPORT),
  EXPORT_AUDIT_LOG(Domain.AUDIT_LOG, Type.EXPORT),
  SOURCE_CONTROL_IMPORT(Domain.GOVERNANCE_SOURCE_CONTROL, Type.IMPORT),
  UPDATE_TENANT_METADATA(Domain.MTIQ_TENANT_METADATA, Type.UPDATE),

  UPDATE_TENANT_SS0_CONFIGURATION(Domain.MTIQ_TENANT_SSO_CONFIGURATION, Type.UPDATE),

  CREATE_REPOSITORY_MANAGER(Domain.GOVERNANCE_REPOSITORY_MANAGER, Type.CREATE),
  UPDATE_REPOSITORY_MANAGER(Domain.GOVERNANCE_REPOSITORY_MANAGER, Type.UPDATE),
  DELETE_REPOSITORY_MANAGER(Domain.GOVERNANCE_REPOSITORY_MANAGER, Type.DELETE),
  CONFIGURE_REPOSITORY_MANAGER_ICON(Domain.GOVERNANCE_REPOSITORY_MANAGER_ICON, Type.CONFIGURE),

  VIEW_INTEGRATED_ENTERPRISE_REPORTING_DASHBOARD(Domain.REPORTING_DASHBOARD_INTEGRATED_ENTERPRISE_REPORTING, Type.VIEW),

  CREATE_SAST_SCAN(Domain.GOVERNANCE_SAST_SCAN, Type.CREATE),

  DELETE_SBOM_VERSION(Domain.GOVERNANCE_SBOM, Type.DELETE),
  CREATE_SBOM_VERSION(Domain.GOVERNANCE_SBOM, Type.CREATE),
  EXPORT_SBOM_VERSION(Domain.GOVERNANCE_SBOM, Type.EXPORT),
  IMPORT_SBOM_VERSION(Domain.GOVERNANCE_SBOM, Type.IMPORT),
  VIEW_SBOM_COMPONENT_DETAILS(Domain.GOVERNANCE_SBOM, Type.VIEW),
  UPDATE_SBOM_VULNERABILITY_ANALYSIS(Domain.GOVERNANCE_SBOM, Type.UPDATE),
  DELETE_SBOM_VULNERABILITY_ANALYSIS(Domain.GOVERNANCE_SBOM, Type.DELETE),
  EXPORT_DEVELOPER_PRIORITIES(Domain.REPORTING_DEVELOPER_PRIORITIES, Type.EXPORT),

  VIEW_AUDIT_LOG(Domain.AUDIT_LOG, Type.VIEW),

  ROI_CONFIG_UPDATE(Domain.ROI_CONFIGURATION, Type.CONFIGURE),
  ROI_CONFIG_CREATE(Domain.ROI_CONFIGURATION, Type.CONFIGURE),

  CONFIGURE_OIDC(Domain.SECURITY_OIDC, Type.CONFIGURE),
  DELETE_OIDC(Domain.SECURITY_OIDC, Type.DELETE),

  CONFIGURE_VERSION_EVALUATION_WINDOW(Domain.GOVERNANCE_VERSION_EVALUATION_WINDOW, Type.CONFIGURE),
  DELETE_VERSION_EVALUATION_WINDOW(Domain.GOVERNANCE_VERSION_EVALUATION_WINDOW, Type.DELETE);

  private final String domain;

  private final String type;

  AuditEvent(String domain, String event) {
    this.domain = domain;
    this.type = event;
  }

  public String getDomain() {
    return domain;
  }

  public String getType() {
    return type;
  }

  interface Domain
  {
    String AUTHENTICATION = "authentication";

    String GOVERNANCE = "governance";

    String SERVER = "server";

    String REPORTING = "reporting";

    String ROI = "roi";

    String GOVERNANCE_COMPONENT = join(GOVERNANCE, "component");

    String GOVERNANCE_COMPONENT_VULNERABILITY = join(GOVERNANCE_COMPONENT, "vulnerability");

    String GOVERNANCE_COMPONENT_IDENTITY = join(GOVERNANCE_COMPONENT, "identity");

    String GOVERNANCE_COMPONENT_LABEL = join(GOVERNANCE_COMPONENT, "label");

    String GOVERNANCE_APPLICATION_CATEGORY = join(GOVERNANCE, "application-category");

    String GOVERNANCE_WAIVER = join(GOVERNANCE, "waiver");

    String GOVERNANCE_WAIVER_REQUEST = join(GOVERNANCE, "waiver-request");

    String GOVERNANCE_WAIVER_TRANSITIVE = join(GOVERNANCE_WAIVER, "transitive");

    String GOVERNANCE_WAIVER_CONTAINER = join(GOVERNANCE_WAIVER, "container");

    String GOVERNANCE_EVALUATION = join(GOVERNANCE, "evaluation");

    String GOVERNANCE_EVALUATION_APPLICATION = join(GOVERNANCE_EVALUATION, "application");

    String GOVERNANCE_EVALUATION_PROJECT = join(GOVERNANCE_EVALUATION, "project");

    String GOVERNANCE_EVALUATION_REPOSITORY = join(GOVERNANCE_EVALUATION, "repository");

    String GOVERNANCE_EVALUATION_CASCADE = join(GOVERNANCE_EVALUATION, "cascade");

    String GOVERNANCE_EVALUATION_AD_HOC = join(GOVERNANCE_EVALUATION, "ad-hoc");

    String GOVERNANCE_EVALUATION_THIRD_PARTY = join(GOVERNANCE_EVALUATION, "third-party");

    String GOVERNANCE_COMPONENT_LICENSE = join(GOVERNANCE_COMPONENT, "license");

    String GOVERNANCE_COMPONENT_COPYRIGHT = join(GOVERNANCE_COMPONENT, "copyright");

    String GOVERNANCE_COMPONENT_SOURCE_LINK = join(GOVERNANCE_COMPONENT, "source-link");

    String GOVERNANCE_COMPONENT_LEGAL_FILE = join(GOVERNANCE_COMPONENT, "legal-file");

    String GOVERNANCE_COMPONENT_OBLIGATION = join(GOVERNANCE_COMPONENT, "obligation");

    String GOVERNANCE_COMPONENT_OBLIGATIONS = join(GOVERNANCE_COMPONENT, "obligations");

    String GOVERNANCE_COMPONENT_OBLIGATION_ATTRIBUTION = join(GOVERNANCE_COMPONENT_OBLIGATION, "attribution");

    String GOVERNANCE_IMPORT = join(GOVERNANCE, "import");

    String GOVERNANCE_LEGACY_VIOLATION_STATUS = join(GOVERNANCE, "legacy-violation-status");

    String GOVERNANCE_PROPRIETARY_COMPONENTS = join(GOVERNANCE, "proprietary-components");

    String GOVERNANCE_CALL_FLOW_ANALYSIS_CONFIG = join(GOVERNANCE, "call-flow-analysis-config-upsert");

    String GOVERNANCE_CALL_FLOW_ANALYSIS_DELETE = join(GOVERNANCE, "call-flow-analysis-delete");

    String GOVERNANCE_ORGANIZATION = join(GOVERNANCE, "organization");

    String GOVERNANCE_ORGANIZATION_ICON = join(GOVERNANCE_ORGANIZATION, "icon");

    String GOVERNANCE_CONTINUOUS_MONITORING = join(GOVERNANCE, "continuous-monitoring");

    String GOVERNANCE_CPE_MATCHING_CONFIGURATION = join(GOVERNANCE, "cpe-matching-configuration");

    String GOVERNANCE_CI_CONFIGURATION = join(GOVERNANCE, "ci-configuration");

    String GOVERNANCE_LABEL = join(GOVERNANCE, "component-label");

    String GOVERNANCE_LICENSE_THREAT_GROUP = join(GOVERNANCE, "license-threat-group");

    String GOVERNANCE_LICENSE_THREAT_GROUP_LICENSES = join(GOVERNANCE_LICENSE_THREAT_GROUP, "licenses");

    String GOVERNANCE_POLICY = join(GOVERNANCE, "policy");

    String GOVERNANCE_POLICY_INHERITANCE = join(GOVERNANCE_POLICY, "inheritance");

    String GOVERNANCE_POLICY_OVERRIDES = join(GOVERNANCE_POLICY, "overrides");

    String GOVERNANCE_REPOSITORY = join(GOVERNANCE, "repository");

    String GOVERNANCE_REPOSITORY_MANAGER = join(GOVERNANCE, "repository_manager");

    String GOVERNANCE_REPOSITORY_QUARANTINE = join(GOVERNANCE_REPOSITORY, "quarantine");

    String GOVERNANCE_REPOSITORY_MANAGER_ICON = join(GOVERNANCE_REPOSITORY_MANAGER, "icon");

    String GOVERNANCE_APPLICATION = join(GOVERNANCE, "application");

    String GOVERNANCE_APPLICATION_CATEGORIES = join(GOVERNANCE_APPLICATION, "categories");

    String GOVERNANCE_APPLICATION_ICON = join(GOVERNANCE_APPLICATION, "icon");

    String GOVERNANCE_AUTOMATIC_APPLICATIONS = join(GOVERNANCE, "automatic-applications");

    String GOVERNANCE_AUTOMATIC_SOURCE_CONTROL = join(GOVERNANCE, "automatic-source-control");

    String GOVERNANCE_SOURCE_CONTROL = join(GOVERNANCE, "source-control");

    String GOVERNANCE_VULNERABILITY_SIGNATURES_REACHABILITY =
        join(join(GOVERNANCE, "vulnerability-signatures"), "reachability");

    String GOVERNANCE_REPOSITORY_IDENTIFIED_COMPONENT = join(GOVERNANCE, "repository-identified-component");

    String GOVERNANCE_VULNERABILITY_GROUP = join(GOVERNANCE, "vulnerability-group");

    String GOVERNANCE_VULNERABILITY_CUSTOM_REMEDIATION = join(GOVERNANCE, "vulnerability-custom-remediation");

    String GOVERNANCE_VULNERABILITY_CUSTOM_CWE = join(GOVERNANCE, "vulnerability-custom-cwe");

    String GOVERNANCE_VULNERABILITY_CUSTOM_CVSS_VECTOR = join(GOVERNANCE, "vulnerability-custom-cvss-vector");

    String GOVERNANCE_VULNERABILITY_CUSTOM_CVSS_SEVERITY = join(GOVERNANCE, "vulnerability-custom-cvss-severity");

    String GOVERNANCE_SBOM = join(GOVERNANCE, "sbom");

    String GOVERNANCE_VERSION_EVALUATION_WINDOW = join(GOVERNANCE, "version-evaluation-window");

    String SECURITY = "security";

    String SECURITY_USER = join(SECURITY, "user");

    String SECURITY_USER_PASSWORD = join(SECURITY_USER, "password");

    String SECURITY_ROLE = join(SECURITY, "role");

    String SECURITY_ROLE_MEMBERSHIP = join(SECURITY_ROLE, "membership");

    String SECURITY_LDAP = join(SECURITY, "ldap");

    String SECURITY_SAML = join(SECURITY, "saml");

    String SECURITY_OIDC = join(SECURITY, "oidc");

    String SECURITY_CROWD = join(SECURITY, "crowd");

    String SECURITY_LDAP_SERVER = join(SECURITY_LDAP, "server");

    String SECURITY_LDAP_SERVER_CONNECTION = join(SECURITY_LDAP_SERVER, "connection");

    String SECURITY_LDAP_SERVER_USER_MAPPING = join(SECURITY_LDAP_SERVER, "user-mapping");

    String SECURITY_USER_TOKEN = join(SECURITY_USER, "token");

    String SECURITY_QUARANTINED_COMPONENT_VIEW_ANON_ACCESS =
        join(SECURITY, "quarantined-component-view-anonymous-access");

    String SERVER_DATA_RETENTION = join(SERVER, "data-retention");

    String SERVER_LICENSE = join(SERVER, "license");

    String SERVER_SYSTEM_NOTICE = join(SERVER, "system-notice");

    String SERVER_WEBHOOK = join(SERVER, "webhook");

    String SERVER_PROXY = join(SERVER, "proxy");

    String SERVER_MAIL = join(SERVER, "mail");

    String SERVER_REVERSE_PROXY_AUTHENTICATION = join(SERVER, "reverse-proxy-authentication");

    String SERVER_JIRA = join(SERVER, "jira");

    String SERVER_SOURCE_CONTROL = join(SERVER, "source-control");

    String SERVER_FEATURES = join(SERVER, "features");

    String SERVER_PROPERTIES = join(SERVER, "properties");

    String SERVER_REPOSITORY = join(SERVER, "repository");

    String SERVER_ARTIFACTORY = join(SERVER, "artifactory");

    String REPORTING_APPLICATION_COMPOSITION = join(REPORTING, "application-composition");

    String REPORTING_APPLICATION_COMPOSITION_REPORT = join(REPORTING_APPLICATION_COMPOSITION, "report");

    String REPORTING_SUCCESS_METRICS = join(REPORTING, "success-metrics");

    String ROI_CONFIGURATION = join(ROI, "configuration");

    String REPORTING_DASHBOARD = join(REPORTING, "dashboard");

    String REPORTING_DASHBOARD_FILTER = join(REPORTING_DASHBOARD, "filter");

    String REPORTING_DASHBOARD_COMPONENT_DETAILS = join(REPORTING_DASHBOARD, "component-details");

    String REPORTING_REPOSITORY_RESULTS = join(REPORTING, "repository-results");

    String REPORTING_COMPONENT_INFORMATION = join(REPORTING, "component-information");

    String REPORTING_SUCCESS_METRICS_REPORT = join(REPORTING_SUCCESS_METRICS, "report");

    String REPORTING_DASHBOARD_VIOLATION_LIST = join(REPORTING_DASHBOARD, "violation-list");

    String REPORTING_DASHBOARD_APPLICATION_LIST = join(REPORTING_DASHBOARD, "application-list");

    String REPORTING_DASHBOARD_COMPONENT_LIST = join(REPORTING_DASHBOARD, "component-list");

    String REPORTING_DASHBOARD_WAIVER_LIST = join(REPORTING_DASHBOARD, "waiver-list");

    String REPORTING_POLICY_VIOLATIONS = join(REPORTING, "policy-violations");

    String REPORTING_DEVELOPER_PRIORITIES = join(REPORTING, "developer-priorities");

    String REPORTING_COMPONENT_TRANSITIVE_POLICY_VIOLATIONS = join(REPORTING, "component-transitive-policy-violations");

    String REPORTING_COMPONENT_USES = join(REPORTING, "component-uses");

    String REPORTING_COMPONENTS_WITH_WAIVERS = join(REPORTING, "components-with-waivers");

    String REPORTING_ADVANCED_SEARCH = join(REPORTING, "advanced-search");

    String REPORTING_STALE_WAIVERS = join(REPORTING, "stale-waivers");

    String REPORTING_QUARANTINED_COMPONENTS = join(REPORTING, "quarantined-components");

    String REPORTING_VULNERABILITY_SIGNATURES = join(REPORTING, "vulnerability-signatures");

    String REPORTING_USER_FILTER = join(REPORTING, "user-filter");

    String REPORTING_MOVE_ORGANIZATION_ERRORS = join(REPORTING, "move-organization-errors");

    String REPORTING_DASHBOARD_INTEGRATED_ENTERPRISE_REPORTING = join(REPORTING, "integrated-enterprise-reporting");

    String NOTIFICATION = "notification";

    String NOTIFICATION_WEBHOOK = join(NOTIFICATION, "webhook");

    String NOTIFICATION_MAIL = join(NOTIFICATION, "mail");

    String NOTIFICATION_ISSUE_JIRA = join(NOTIFICATION, join("issue", "jira"));

    String NOTIFICATION_PULL_REQUEST = join(NOTIFICATION, "pull-request");

    String NOTIFICATION_PULL_REQUEST_COMMENT = join(NOTIFICATION_PULL_REQUEST, "comment");

    // Domains for MTIQ admin endpoints

    String MTIQ = "mtiq";

    String TENANT = "tenant";

    String MTIQ_TENANT = join(MTIQ, TENANT);

    String MTIQ_TENANT_LICENSE = join(MTIQ, join(TENANT, "license"));

    String MTIQ_TENANT_SECURITY = join(MTIQ, join(TENANT, "security"));

    String MTIQ_TENANT_CONFIGURATION = join(MTIQ, join(TENANT, "configuration"));

    String MTIQ_TENANT_SUPPORT = join(MTIQ, join(TENANT, "support"));

    String MTIQ_TENANT_METADATA = join(MTIQ, join(TENANT, "metadata"));

    String MTIQ_TENANT_SSO_CONFIGURATION = join(MTIQ, join(TENANT, "sso"));

    String GOVERNANCE_SAST_SCAN = join(GOVERNANCE, "sast-scan");

    String AUDIT_LOG = "audit-log";

    static String join(String parent, String child) {
      return parent + "." + child;
    }
  }

  private interface Type
  {
    String FAILURE = "failure";

    String LOGIN = "login";

    String LOGOUT = "logout";

    String EVALUATE = "evaluate";

    String SET = "set";

    String RESET = "reset";

    String UNSET = "unset";

    String ASSIGN = "assign";

    String ADD = "add";

    String REMOVE = "remove";

    String APPLY = "apply";

    String REVOKE = "revoke";

    String CONFIGURE = "configure";

    String CREATE = "create";

    String UPDATE = "update";

    String DELETE = "delete";

    String PURGE = "purge";

    String IMPORT = "import";

    String CONNECT = "connect";

    String DISCONNECT = "disconnect";

    String MIGRATE = "migrate";

    String INITIATE = "initiate";

    String RELEASE = "release";

    String RETAIN = "retain";

    String PRIORITIZE = "prioritize";

    String MOVE = "move";

    String AUTO_CREATE = "auto-create";

    String INSTALL = "install";

    String UNINSTALL = "uninstall";

    String START = "start";

    String STOP = "stop";

    String VIEW = "view";

    String EXPORT = "export";

    String PRINT = "print";

    String SAVE = "save";

    String SEARCH = "search";

    String INVOKE = "invoke";

    String SEND = "send";

    String GRANT = "grant";

    String REVIEW = "review";
  }
}
