/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
package com.sonatype.insight.brain.releasegraph;

import java.util.Date;

import jakarta.inject.Inject;
import jakarta.inject.Named;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.core.Response;

import com.sonatype.clm.dto.model.component.ComponentIdentifier;
import com.sonatype.insight.error.exception.BadRequestException;

import com.codahale.metrics.annotation.Timed;

@Named
@Timed
@Path(ReleaseGraphResource.RESOURCE_PATH)
public class ReleaseGraphResource
{
  public static final String RESOURCE_PATH = "rest/report/{applicationId}/{scanId}/releaseGraph";

  private static final long YEAR = 365L * 24 * 60 * 60 * 1000;

  private final ReleaseGraphService releaseGraphService;

  @Inject
  public ReleaseGraphResource(ReleaseGraphService releaseGraphService) {
    this.releaseGraphService = releaseGraphService;
  }

  @GET
  @Produces(ReleaseGraphService.CONTENT_TYPE)
  public Response getImage(@PathParam("applicationId") final String applicationPublicId,
                           @PathParam("scanId") final String scanId,
                           @QueryParam("groupId") String groupId,
                           @QueryParam("artifactId") String artifactId,
                           @QueryParam("version") String version,
                           @QueryParam("componentIdentifier") ComponentIdentifier componentIdentifier)
  {
    componentIdentifier = getComponentIdentifier(componentIdentifier, groupId, artifactId, version);
    return Response
        .ok(releaseGraphService.getImage(applicationPublicId, scanId, componentIdentifier),
            ReleaseGraphService.CONTENT_TYPE).expires(new Date(System.currentTimeMillis() + YEAR)).build();
  }

  private ComponentIdentifier getComponentIdentifier(ComponentIdentifier componentIdentifier,
                                                     String groupId,
                                                     String artifactId,
                                                     String version)
  {
    if (componentIdentifier == null) {
      // support legacy reports generated by HDS before 2.1
      if (groupId == null || artifactId == null || version == null) {
        throw new BadRequestException("Invalid component identifier");
      }
      componentIdentifier = ComponentIdentifier.createMavenCoordinates(groupId, artifactId, version);
    }
    return componentIdentifier;
  }
}
