<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="n1" Version="v1"/>
    <PackageReference Include="n2" Version="v2">
      <IncludeAssets>all</IncludeAssets>
      <ExcludeAssets>none</ExcludeAssets>
    </PackageReference>
    <Reference Include="n3, Version=v3">
      <HintPath>some\path</HintPath>
    </Reference>
    <Reference Include="n4, Version=v4"/>
    <COMReference Include="n5">
      <Guid>{2DF8D04C-5BFA-101B-BDE5-00AA0044DE52}</Guid>
      <VersionMajor>5</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>primary</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="n6">
      <VersionMajor>6</VersionMajor>
    </COMReference>
    <COMReference Include="n7"/> <!-- should not include due to missing version -->
  </ItemGroup>
</Project>
