/**
 * Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/insight/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
package com.sonatype.insight.brain.dataaccess;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import javax.sql.DataSource;

import org.codehaus.plexus.util.FileUtils;
import org.junit.After;
import org.junit.Assert;
import org.junit.Test;

import com.sonatype.insight.brain.dataaccess.ApplicationDAO;
import com.sonatype.insight.brain.db.DataSourceFactory;
import com.sonatype.insight.brain.db.OperationalDataStoreProvider;
import com.sonatype.insight.db.DatabaseConfig;

public class DatabaseAccessTest
{
    @After
    public void cleanup()
    {
        DataSourceFactory.unloadAll();
    }

    @Test
    public void testConcurrentDatabaseAccess()
        throws Exception
    {
        // Create a file database (i.e. not in memory)
        DatabaseConfig databaseConfig = new DatabaseConfig();
        databaseConfig.setDriverClassName( "org.h2.Driver" );
        databaseConfig.setUrl( "jdbc:h2:target/DatabaseTest/testConcurrentDatabaseAccess" );
        databaseConfig.setUsername( "sa" );
        databaseConfig.setPassword( "" );
        databaseConfig.setMaxConnections( 50 );
        File databaseDir = new File( "target/DatabaseTest" );
        FileUtils.deleteDirectory( databaseDir );

        OperationalDataStoreProvider.init( databaseConfig );
        DataSource dataSource = OperationalDataStoreProvider.get();
        Assert.assertNotNull( dataSource );
        Assert.assertTrue( databaseDir.exists() );
        Assert.assertTrue( new File( databaseDir, "testConcurrentDatabaseAccess.h2.db" ).exists() );

        int threadCount = 20;
        DatabaseAccessThread[] threads = new DatabaseAccessThread[threadCount];
        for ( int i = 0; i < threadCount; i++ )
        {
            threads[i] = new DatabaseAccessThread( i );
        }
        for ( int i = 0; i < threadCount; i++ )
        {
            threads[i].start();
            // threads[i].run();
        }
        for ( int i = 0; i < threadCount; i++ )
        {
            threads[i].join();
        }
        boolean success = true;
        for ( int i = 0; i < threadCount; i++ )
        {
            if ( !threads[i].errors.isEmpty() )
            {
                success = false;
                System.err.println( "Thread: " + threads[i].getName() + " errors=" + threads[i].errors.size() );
                for ( Exception error : threads[i].errors )
                {
                    System.err.println( "\t" + error.getMessage() );
                }
            }
        }

        Assert.assertTrue( success );
    }

    private static class DatabaseAccessThread
        extends Thread
    {
        private int id;

        public List<Exception> errors = new ArrayList<Exception>();

        DatabaseAccessThread( int id )
        {
            super( "DatabaseAccessThread" + id );
            this.id = id;
        }

        @Override
        public void run()
        {
            String appPublicId = "DatabaseAccessThread_AppId_" + id;
            // It is important to use a DAO for a class mapped to the database via JPA because all sql is generated by
            // JPA. See https://issues.sonatype.org/browse/INSIGHT-4062
            ApplicationDAO applicationDAO = new ApplicationDAO();
            applicationDAO.getOrInsertByPublicId( appPublicId );
            for ( int i = 0; i < 200; i++ )
            {
                try
                {
                    applicationDAO.getByPublicId( appPublicId );
                }
                catch ( Exception e )
                {
                    errors.add( e );
                    System.err.println( getName() + "iteration=" + i + " " + e.getMessage() );
                }
            }
        }
    }
}
