/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
package com.sonatype.insight.brain.dataaccess;

import java.util.ArrayList;
import java.util.List;

import com.sonatype.insight.brain.db.rule.DatabaseRuleAnnotations.H2DiskTest;
import com.sonatype.insight.brain.model.Application;
import com.sonatype.insight.brain.model.Organization;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

public class DatabaseAccessTest
    extends AbstractDbDAOTest
{
  private OrganizationDAO organizationDAO;

  private ApplicationDAO applicationDAO;

  @BeforeEach
  @Override
  public void setup() {
    super.setup();
    organizationDAO = daoFactory.createOrganizationDAO();
    applicationDAO = daoFactory.createApplicationDAO();
  }

  @Test
  @Timeout(value = 20000, unit = java.util.concurrent.TimeUnit.MILLISECONDS)
  @H2DiskTest
  public void testConcurrentDatabaseAccess() throws Exception {
    Organization org = new Organization("testConcurrentDatabaseAccess");
    organizationDAO.insert(org);
    // TODO: Delete this line once https://issues.apache.org/jira/browse/OPENJPA-2472 is resolved
    applicationDAO.insert(new Application("OPENJPA-2472", "Workaround", org.getId()));

    int threadCount = 20;
    DatabaseAccessThread[] threads = new DatabaseAccessThread[threadCount];
    for (int i = 0; i < threadCount; i++) {
      threads[i] = new DatabaseAccessThread(i, org.getId(), applicationDAO);
    }
    for (int i = 0; i < threadCount; i++) {
      threads[i].start();
      // threads[i].run();
    }
    for (int i = 0; i < threadCount; i++) {
      threads[i].join();
    }
    Exception exception = null;
    for (int i = 0; i < threadCount; i++) {
      if (!threads[i].errors.isEmpty()) {
        if (exception == null) {
          exception = threads[i].errors.get(0);
        }
        System.err.println("Thread: " + threads[i].getName() + " errors=" + threads[i].errors.size());
        for (Exception error : threads[i].errors) {
          System.err.println("\t" + error.getMessage());
        }
      }
    }
    if (exception != null) {
      throw exception;
    }
  }

  private static class DatabaseAccessThread
      extends Thread
  {
    private final int id;

    private final String orgId;

    public final List<Exception> errors = new ArrayList<>();

    private final ApplicationDAO applicationDAO;

    DatabaseAccessThread(int id, String orgId, final ApplicationDAO applicationDAO) {
      super("DatabaseAccessThread" + id);
      this.id = id;
      this.orgId = orgId;
      this.applicationDAO = applicationDAO;
    }

    @Override
    public void run() {
      String appPublicId = "DatabaseAccessThread-AppId-" + id;
      // It is important to use a DAO for a class mapped to the database via JPA because all sql is generated by
      // JPA. See https://issues.sonatype.org/browse/INSIGHT-4062
      long before = System.currentTimeMillis();
      try {
        Application application = new Application(appPublicId, appPublicId, orgId);
        applicationDAO.insert(application);
      }
      catch (Exception e) {
        System.err.println("Time: " + (System.currentTimeMillis() - before));
        System.err.println(getName() + ": " + e.getMessage());
        errors.add(e);
        e.printStackTrace();
        return;
      }
      for (int i = 0; i < 200; i++) {
        before = System.currentTimeMillis();
        try {
          applicationDAO.getByPublicId(appPublicId);
        }
        catch (Exception e) {
          System.err.println("Time: " + (System.currentTimeMillis() - before));
          System.err.println(getName() + "iteration=" + i + " " + e.getMessage());
          errors.add(e);
        }
      }
    }
  }
}
