/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
package com.sonatype.insight.brain.dataaccess;

import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.sql.DataSource;

import com.sonatype.insight.brain.common.io.FileCleaner;
import com.sonatype.insight.brain.db.DataSourceFactory;
import com.sonatype.insight.brain.db.DatamartProvider;
import com.sonatype.insight.brain.db.OperationalDataStoreProvider;
import com.sonatype.insight.brain.model.Application;
import com.sonatype.insight.brain.model.Organization;
import com.sonatype.insight.db.DatabaseConfig;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class DatabaseAccessTest
{
  @Before
  public void setup() {
    DataSourceFactory.clear_ForTestsOnly();
  }

  @After
  public void cleanup() {
    DataSourceFactory.clear_ForTestsOnly();
  }

  private void assertDataSource(DataSource dataSource, DatabaseConfig databaseConfig) throws SQLException {
    assertThat(dataSource).isNotNull();
    try (Connection conn = dataSource.getConnection()) {
      String databaseURL = conn.getMetaData().getURL();
      assertThat(databaseURL).isNotNull();
      assertThat(databaseConfig.getUrl()).startsWith(databaseURL + ";");
    }
  }

  @Test
  public void testConcurrentDatabaseAccess() throws Exception {
    // Create a file database (i.e. not in memory)
    File databaseDir = new File("target/DatabaseTest/testConcurrentDatabaseAccess");
    new FileCleaner().delete(databaseDir.getParentFile());

    DatabaseConfig odsDatabaseConfig = new DatabaseConfig();
    odsDatabaseConfig.setDriverClassName("org.h2.Driver");
    odsDatabaseConfig.setUrl("jdbc:h2:target/DatabaseTest/testConcurrentDatabaseAccess/ods"
        + ";DATABASE_TO_UPPER=FALSE;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000");
    odsDatabaseConfig.setUsername("sa");
    odsDatabaseConfig.setPassword("");
    odsDatabaseConfig.setMaxConnections(50);
    OperationalDataStoreProvider.init(odsDatabaseConfig, true);
    assertDataSource(OperationalDataStoreProvider.getDataSource(), odsDatabaseConfig);
    assertThat(databaseDir).isDirectory();
    assertThat(new File(databaseDir, "ods.h2.db")).isFile();

    DatabaseConfig dmDatabaseConfig = new DatabaseConfig();
    dmDatabaseConfig.setDriverClassName("org.h2.Driver");
    dmDatabaseConfig.setUrl("jdbc:h2:target/DatabaseTest/testConcurrentDatabaseAccess/dm"
        + ";DATABASE_TO_UPPER=FALSE;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=10000");
    dmDatabaseConfig.setUsername("sa");
    dmDatabaseConfig.setPassword("");
    dmDatabaseConfig.setMaxConnections(50);
    DatamartProvider.init(dmDatabaseConfig);
    assertDataSource(DatamartProvider.getDataSource(), dmDatabaseConfig);
    assertThat(databaseDir).isDirectory();
    assertThat(new File(databaseDir, "dm.h2.db")).isFile();

    Organization org = new Organization("testConcurrentDatabaseAccess");
    new OrganizationDAO().insert(org);
    // TODO: Delete this line once https://issues.apache.org/jira/browse/OPENJPA-2472 is resolved
    new ApplicationDAO().insert(new Application("OPENJPA-2472", "Workaround", org.getId()));

    int threadCount = 20;
    DatabaseAccessThread[] threads = new DatabaseAccessThread[threadCount];
    for (int i = 0; i < threadCount; i++) {
      threads[i] = new DatabaseAccessThread(i, org.getId());
    }
    for (int i = 0; i < threadCount; i++) {
      threads[i].start();
      // threads[i].run();
    }
    for (int i = 0; i < threadCount; i++) {
      threads[i].join();
    }
    Exception exception = null;
    for (int i = 0; i < threadCount; i++) {
      if (!threads[i].errors.isEmpty()) {
        if (exception == null) {
          exception = threads[i].errors.get(0);
        }
        System.err.println("Thread: " + threads[i].getName() + " errors=" + threads[i].errors.size());
        for (Exception error : threads[i].errors) {
          System.err.println("\t" + error.getMessage());
        }
      }
    }
    if (exception != null) {
      throw exception;
    }
  }

  private static class DatabaseAccessThread
      extends Thread
  {
    private int id;

    private String orgId;

    public List<Exception> errors = new ArrayList<>();

    DatabaseAccessThread(int id, String orgId) {
      super("DatabaseAccessThread" + id);
      this.id = id;
      this.orgId = orgId;
    }

    @Override
    public void run() {
      String appPublicId = "DatabaseAccessThread-AppId-" + id;
      // It is important to use a DAO for a class mapped to the database via JPA because all sql is generated by
      // JPA. See https://issues.sonatype.org/browse/INSIGHT-4062
      ApplicationDAO applicationDAO = new ApplicationDAO();
      long before = System.currentTimeMillis();
      try {
        Application application = new Application(appPublicId, appPublicId, orgId);
        applicationDAO.insert(application);
      }
      catch (Exception e) {
        System.err.println("Time: " + (System.currentTimeMillis() - before));
        System.err.println(getName() + ": " + e.getMessage());
        errors.add(e);
        e.printStackTrace();
        return;
      }
      for (int i = 0; i < 200; i++) {
        before = System.currentTimeMillis();
        try {
          applicationDAO.getByPublicId(appPublicId);
        }
        catch (Exception e) {
          System.err.println("Time: " + (System.currentTimeMillis() - before));
          System.err.println(getName() + "iteration=" + i + " " + e.getMessage());
          errors.add(e);
        }
      }
    }
  }
}
