/*
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2012-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2013 Sonatype, Inc. All rights reserved. Includes the
 third-party code listed at
 http://links.sonatype.com/products/clm/attributions. "Sonatype" is a
 trademark of Sonatype, Inc.
*/
(function(){function a(b){var a=this;this.options=$.extend(!0,{},c,b);this.node=$("\x3cdiv id\x3d'informationPanel' class\x3d'informationPanel fullBorderedTable'\x3e\x3cdiv style\x3d'width:99%; padding-top: 5px; padding-left: 0.5%; padding-right: 0.5%;'\x3e\x3ca class\x3d'close'\x3e\x26times;\x3c/a\x3e\x3cul class\x3d'nav nav-tabs' style\x3d'margin-bottom:0px; !important'\x3e\x3c/ul\x3e\x3cdiv class\x3d'tab-content' style\x3d'overflow:hidden'\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");$(".close",this.node).click(function(){a.hide()});
this.plugins=[];Insight.InformationPanelPlugins.sort(function(b,a){return b.prototype.priority-a.prototype.priority});$.each(Insight.InformationPanelPlugins,function(b,d){var f=$('\x3cli data-info-plugin\x3d"'+b+'"\x3e\x3ca data-target\x3d"infoPanel'+b+'" data-toggle\x3d"tab"\x3e\x3c/a\x3e\x3c/li\x3e'),c=$('\x3cdiv class\x3d"tab-pane" id\x3d"infoPanel'+b+'"\x3e\x3c/div\x3e');$("ul.nav",a.node).append(f);$("div.tab-content",a.node).append(c);a.plugins.push(new d(c,a.options))});$('a[data-toggle\x3d"tab"]',
this.node).on("show",function(b){var d;null!==b.relatedTarget&&(d=$(b.relatedTarget.parentNode).data("info-plugin"),a.plugins[d].destroy(),$("#"+$(b.relatedTarget).data("target"),a.node).hide());null!==b.target&&(d=$(b.target.parentNode).data("info-plugin"),b=$("#"+$(b.target).data("target"),a.node),b.show(),a.plugins[d].create(b,a.node))})}function e(b){b=b||{};this.priority=b.priority||512}var c={byHash:!1};a.prototype.destroy=function(){this.cleanPlugins()};a.prototype.hide=function(){this.node.detach();
this.grid.removeCellCssStyles("popout");this.cleanPlugins()};a.prototype.init=function(b){var a=this;this.grid=b;b.onClick.subscribe(function(){a.gridClickedFn.apply(a,arguments)});b.getData().onRowCountChanged.subscribe(function(){a.hide()});b.getData().onRowsChanged.subscribe(function(){a.rowChangedFn.apply(a,arguments)});$.each(this.plugins,function(a,d){d.setGrid(b)})};a.prototype.cleanPlugins=function(){$.each(this.plugins,function(b,a){a.destroy()})};a.prototype.gridClickedFn=function(b,a){var c=
this;"INPUT"!==b.target.tagName&&0===$(b.target).children("input:first").length&&(Insight.util.isNotNullOrUndefined(c.timer)?(clearTimeout(c.timer),c.timer=null):c.timer=setTimeout(function(){c.timer=null;$.each(c.plugins,function(b,f){f.setItem(c.grid.getDataItem(a.row))});c.toggle(b,a)},250))};a.prototype.getItem=function(){return this.grid.getDataItem(this.currentRow)};a.prototype.updatePanel=function(){var b=this,a=null;$.each(this.plugins,function(a,d){var f=$("li[data-info-plugin\x3d"+a+"]",
b.node);d.isVisible()?(f.show(),$("a",f).text(d.getTitle())):(f.hide(),$("#infoPanel"+a,b.node).hide(),f.hasClass("active")&&(f.removeClass("active"),$("ul.nav \x3e li:first",b.node).addClass("active")))});0===$("li.active",b.node).length&&$("li",b.node).each(function(a,b){b=$(b);if("none"!==b.css("display"))return b.addClass("active"),!1});a=$("li.active",b.node).data("info-plugin");b.plugins[a].create();$("#infoPanel"+a,b.node).show()};a.prototype.rowChangedFn=function(b,a){var c=this.currentRow,
d=this;setTimeout(function(){var a=d.grid.getSelectedRows(),b=null;Insight.util.isNotNullOrUndefined(c)&&1===a.length?c!==a[0]?(d.hide(),Insight.util.isNotNullOrUndefined(this.currentItemId)&&d.show({row:a[0],cell:1},d.grid.getCanvasNode())):(d.position(c),b=d.getItem(),$.each(d.plugins,function(a,f){f.setItem(b)}),d.updatePanel()):d.hide()},10)};a.prototype.toggle=function(a,c){this.grid.removeCellCssStyles("popout");$(this.node).is(":hidden")||this.currentRow!==c.row?this.show(this.grid.getCellFromEvent(a),
$(a.currentTarget)):this.hide()};a.prototype.show=function(a,c){var e={},d=this.grid.getCellNode(a.row,a.cell),f=$(this.grid.getCanvasNode()).parent();f.offset();f.height();var k=this;Insight.util.isNullOrUndefined(d)&&(this.grid.scrollRowIntoView(a.row),d=this.grid.getCellNode(a.row,a.cell));this.node.css("top",d.offsetParent.offsetTop+d.offsetParent.clientHeight);this.node.addClass("shadowBottom");this.node.removeClass("shadowTop");k.node.appendTo(c);this.updatePanel();k.position(a.row);k.node.show();
this.currentRow=a.row;e[this.currentRow]={};$.each(k.grid.getColumns(),function(a,b){e[k.currentRow][b.id]="popout"});k.grid.setCellCssStyles("popout",e)};a.prototype.position=function(a){var c=this.node.offset().top,e=c+this.node.height(),d=$(this.grid.getCanvasNode()).parent(),f=d.offset().top,k=f+d.height(),q=this.grid.getCellNode(a,1);Insight.util.isNullOrUndefined(q)&&(this.grid.scrollRowIntoView(a),q=this.grid.getCellNode(a,1));(e>k||c<f)&&d.scrollTop(d.scrollTop()+(this.node.offset().top-q.offsetParent.clientHeight)-
d.offset().top);this.node.css("width",d.width()-(d.get(0).scrollHeight>d.height()?this.grid.getScrollbarDimensions().width:0)-2+"px")};e.prototype.getErrorFn=function(a,c,e){return function(){var d=$(a);d.html(Insight.templates.error.render());$(".btn",d).click(function(){c.apply(e,[])})}};e.prototype.isVisible=function(){return!0};e.prototype.getTitle=function(){return""};e.prototype.setItem=function(a){this.gav=a};e.prototype.message=function(a){$(".alert",this.node).remove();a=$('\x3cdiv class\x3d"alert" style\x3d"width:92.5%"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3e\x3c/div\x3e');
$("div:first",this.node).prepend(a);return a};e.prototype.addErrorMessage=function(a){this.message(a).addClass("alert-error").append("\x3cstrong\x3eError: \x3c/strong\x3e",$("\x3cspan\x3e\x3c/span\x3e").text(a))};e.prototype.addSuccessMessage=function(a){var c=this.message(a).addClass("alert-success").append($("\x3cspan\x3e\x3c/span\x3e").text(a));setTimeout(function(){c.fadeOut("fast",function(){c.remove()})},8E3);return c};e.prototype.setGrid=function(a){this.grid=a};e.prototype.create=$.noop;e.prototype.destroy=
$.noop;$.extend(!0,window,{Insight:{InformationPanel:a,InformationPanelPlugin:e,InformationPanelPlugins:[]}})})();
(function(){function a(a,b){var d=[],f=$("\x3cdiv\x3e\x3c/div\x3e");return Insight.util.isNotNullOrUndefined(a)&&0<a.length?("object"===typeof a[0]?$.each(a,function(a,b){d.push(f.text(b.licenseName).html())}):$.each(a,function(a,b){d.push(f.text(b).html())}),'\x3cspan class\x3d"license"\x3e'+d.join(',\x3c/span\x3e \x3cspan class\x3d"license"\x3e')+"\x3c/span\x3e"):b||""}function e(c,e,d){var f="artifactInfoSecurity",k=Math.floor(c.securityThreatLevel);$(e).is(":hidden")||(0>=c.securityThreatCount?
(k="NA",f+=" artifactInfoSecurityUnspecified"):7<=k?f+=" artifactInfoSecurityCritical":4<=k?f+=" artifactInfoSecuritySevere":(0<=k||(k="Unscored"),f+=" artifactInfoSecurityModerate"),c=$.extend(c,{partial:!1,overriddenLicenses:a(c.overriddenLicenses,"-"),declaredLicenses:a(c.declaredLicenses,"-"),observedLicenses:a(c.observedLicenses,"-"),currentMatchState:d.matchState,proprietary:d.proprietary,colorCls:f,lvl:k,cataloged:c.catalogDate?HealthCheck.getAge(new Date(c.catalogDate)):null,multipleSecurity:1<
c.securityThreatCount,isManual:"Manual"===c.identificationSource}),e.html(b.render(c)),$.event.trigger("artifactInfoPanelLoading",{data:c,node:e,partialDisplay:!1,gav:d}),Insight.ComponentInformation({data:c,partialDisplay:!1}))}function c(a,b){this.node=a;this.options=b}var b;$(document).ready(function(){b=Hogan.compile($("#infoPanelComponentTemplate").html())});c.prototype=new Insight.InformationPanelPlugin({priority:1});c.prototype.create=function(){var a=this,b=a.gav,c=null,f=null,k=null,q=null,
v=function(){null!==f&&(null!==c&&b===a.gav)&&(f.securityThreatCount=0,f.securityThreatLevel=null,$.each(f.securityVulnerabilities,function(a,b){"Not Applicable"!==b.status&&(f.securityThreatCount++,Insight.util.isNotNullOrUndefined(b.severity)&&(f.securityThreatLevel=Math.max(f.securityThreatLevel,b.severity)))}),f.versions=c,e(f,a.node,b))};Insight.util.isNullOrUndefined(this.gav.groupId)||Insight.util.isNullOrUndefined(this.gav.artifactId)||Insight.util.isNullOrUndefined(this.gav.version)?this.node.html("\x3cdiv class\x3d'infoPanelText'\x3eUnknown Component\x3c/div\x3e"):
($(this.node).html('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e'),k=$.extend({},this.gav,{appId:applicationId,instanceId:instanceId}),q=Brain.ci.getComponentDetailsListUrl?Brain.ci.getComponentDetailsListUrl(k):Brain.ci.getArtifactVersionInfoUrl(k),$.getJSON(toDataUrl(Insight.toBrain(Brain.ci.getArtifactInfoUrl(k))),function(a){f=a;v()}).error(this.getErrorFn(this.node,this.create,this)),$.getJSON(toDataUrl(Insight.toBrain(q)),
function(a){c=a.list?a.list:a;v()}).error(this.getErrorFn(this.node,this.create,this)))};c.prototype.destroy=function(){this.node.empty()};c.prototype.getTitle=function(){return"Component Info"};Insight.InformationPanelPlugins.push(c)})();
(function(){function a(a,c){this.node=a;this.options=c}a.prototype=new Insight.InformationPanelPlugin({priority:48});a.prototype.isVisible=function(){return!0};a.prototype.create=function(){var a=this;this.destroy();this.gav.hash?$.getJSON(toDataUrl("partialmatched.json"),function(c){var b=null,l;for(l=0;l<c.aaData.length;l++)if(c.aaData[l].hash===a.gav.hash){b=c.aaData[l].matchDetails;break}b?($(a.node).html("\x3cdiv id\x3d'similarityTable' class\x3d'borderedTable'\x3e\x3c/div\x3e"),InsightDatatable.createSimilarityTable(b)):
$(a.node).html("\x3cdiv class\x3d'infoPanelText'\x3eNo similar matches were found for this component.\x3c/div\x3e")},this.getErrorFn(a.node,a.create,a)):$(a.node).html("\x3cdiv class\x3d'infoPanelText'\x3eNo similar matches were found for this component.\x3c/div\x3e")};a.prototype.destroy=function(){InsightDatatable.removeSimilarityTable();this.node.empty()};a.prototype.getTitle=function(){return"Similar"};Insight.InformationPanelPlugins.push(a)})();
(function(){function a(a){var b,e;if(0===a.indexOf("dependency:/"))return a=a.substring(12),b=a.lastIndexOf("/"),0>b?["Dependency "+a,""]:["Dependency "+a.substring(b+1),"Module "+a.substring(0,b)];b=a.lastIndexOf("/");if(-1===b)return[a,""];e=a.substring(b+1);a=a.substring(0,b);return[e,a]}function e(a,b){this.node=a;this.options=b}e.prototype=new Insight.InformationPanelPlugin({priority:64});e.prototype.buildView=function(c){if(0<c.length){c.sort();var b="\x3cdiv class\x3d'infoPanelText fileDetail'\x3e",
e=!1;$.each(c,function(c,d){$.each(d.pathnames,function(f,c){var d=a(c);b+="\x3cb\x3e"+d[0]+"\x3c/b\x3e";0<d[1].length&&(b+=" \x3ci\x3elocated at\x3c/i\x3e "+d[1]);b+="\x3cbr\x3e\x3cbr\x3e"});0>=d.pathnames.length&&(e=!0)});e&&(b+="Occurrences of this component cannot be listed because pathnames have been anonymized. To see all occurrences, please disable anonymization in the options of your CLM enforcement points and perform a new scan.");b+="\x3c/div\x3e";$(this.node).html(b)}else $(this.node).html("\x3cdiv class\x3d'infoPanelText'\x3eInvalid data encountered, no files are associated with this component.\x3c/div\x3e")};
e.prototype.create=function(){var a=this;a.options.byHash?this.buildView([a.gav]):$.getJSON(toDataUrl("bom.json"),function(b){var e=[];$.each(b.aaData,function(b,d){d.groupId===a.gav.groupId&&(d.artifactId===a.gav.artifactId&&d.version===a.gav.version)&&e.push(d)});a.buildView(e)},this.getErrorFn(a.node,a.create,a))};e.prototype.destroy=function(){};e.prototype.getTitle=function(){return"Occurrences"};Insight.InformationPanelPlugins.push(e)})();(function(){})();
(function(){function a(a){return null===a||"undefined"===typeof a}$.extend(!0,window,{Insight:{hasJoyride:function(){return $.fn.joyride},toBrain:function(a){return a},util:{enableTooltip:function(a){$(a).each(function(){var a=$(this).attr("data-gravity-offset")||0;a&&(a=parseInt(a,10));$(this).tipsy({fade:!0,gravity:$(this).attr("data-gravity"),offset:a,html:!0,opacity:1,delayOut:0,title:"data-tooltip"})})},getErrorMessage:function(a){var c="";return c=0===a.status||1E3<=a.status?"Network error while contacting server":
a.responseText&&0<=(a.getResponseHeader("Content-Type")||"").indexOf("text/plain")?a.responseText:a.statusText?a.statusText:"Error "+a.status},getQueryParameter:function(a){var c=0<window.location.search.length?window.location.search.substring(1).split("\x26"):[],b=null,l=null;a=a.toLowerCase();for(l=0;l<c.length;l++)if(b=c[l].split("\x3d"),b[0].toLowerCase()===a)return b[1]},isNullOrUndefined:a,isNotNullOrUndefined:function(e){return!a(e)}}}})})();
(function(){function a(a){var b={criticalCount:0,severeCount:0,moderateCount:0,noThreatCount:0};"undefined"!==typeof a.effectiveLicenseCounts?$.each(a.effectiveLicenseCounts,function(a,d){7<a?b.criticalCount+=d:3<a?b.severeCount+=d:0<a?b.moderateCount+=d:b.noThreatCount+=d}):(b.criticalCount=a.copyleftLicenseCount,b.severeCount=a.nonStandardLicenseCount+a.notProvidedLicenseCount,b.moderateCount=a.weakcopyleftLicenseCount,b.noThreatCount=a.liberalLicenseCount);b.count=b.criticalCount+b.severeCount+
b.moderateCount+b.noThreatCount;b.licenseAlerts=b.criticalCount+b.severeCount+b.moderateCount;b.multipleLicenseAlerts=1!==b.licenseAlerts;return b}function e(a){var b={criticalCount:0,severeCount:0,moderateCount:0,count:0};$.each(a.securityCounts,function(a,d){6<a?b.moderateCount+=d:3<a?b.severeCount+=d:b.criticalCount+=d;b.count+=d});b.multiple=1!==b.count;b.insecureArtifactCount=a.insecureArtifactCount;b.multipleComponents=1<b.insecureArtifactCount;return b}function c(a){var b={oldBrain:Insight.util.isNullOrUndefined(a.policyCounts),
criticalCount:0,severeCount:0,moderateCount:0};if(b.oldBrain)return b;b.policyComponentCount=a.policyComponentCount;b.multipleComponents=0<b.policyComponentCount;$.each(a.policyCounts,function(a,d){8<=a?b.criticalCount+=d:4<=a?b.severeCount+=d:1<a&&(b.moderateCount+=d)});b.multipleAlerts=1<b.criticalCount+b.severeCount+b.moderateCount?!0:!1;b.hasPolicyAlerts=0<b.criticalCount+b.severeCount+b.moderateCount?!0:!1;return b}function b(){var d=$("#summary"),f=function(a,c,f){d.empty();d.append(Insight.templates.error.render({message:Insight.util.getErrorMessage(a)}));
$("button",d).click(b)};d.html('\x3cdiv class\x3d"alert alert-info"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e');$.getJSON(toDataUrl("data.json")).success(function(b){if(null===b)f({status:0});else{var p={policy:c(b),sv:e(b),license:a(b)},v=d.is(":visible");d.hide();d.html(l.render(p));HealthCheck.barChart(b.securityCounts,{element:$("#security-chart")[0]});HealthCheck.punchCard(b.securityPunchCard,{element:$("#security-punchcard")[0]});HealthCheck.licenseChart([p.license.criticalCount/
p.license.count,p.license.severeCount/p.license.count,p.license.moderateCount/p.license.count,(p.license.count-p.license.licenseAlerts)/p.license.count],{element:$("#license-chart")[0]});HealthCheck.punchCard(b.licensePunchCard,{element:$("#license-punchcard")[0]});HealthCheck.artifactsChart(0<b.totalArtifactCount?1-b.knownArtifactCount/b.totalArtifactCount:0,{element:$("#coverage_donut")[0]});v&&d.fadeIn();Insight.util.enableTooltip($("[data-tooltip]",summary))}}).error(f)}var l,p;$(document).ready(function(){l=
Hogan.compile($("#summaryPageTemplate").html());p=Hogan.compile($("#errorTemplate").html());Hogan.compile($("#licenseEditorTemplate").html());Hogan.compile($("#svEditorTemplate").html());$.extend(!0,window,{Insight:{templates:{error:p},updateSummary:b}});$("button[data-containerid]").click(function(a){if(!$(this).hasClass("active"))switch(a=$(this).data("containerid"),$("[data-container]").css("display","none"),$("#"+a).css("display",""),InsightDatatable.destroyActiveTable(),a){case "securitycontainer":InsightDatatable.createSecurityTable();
break;case "licensecontainer":InsightDatatable.createLicenseTable();break;case "componentcontainer":InsightDatatable.createComponentTable()}});Insight.util.enableTooltip($("[data-tooltip]"));var a=$('[data-action\x3d"reevaluatePolicy"]');Brain.hasFeature("reevaluate-policy")?a.click(function(){a.find("i").attr("class","icon-white icon-time");$.getJSON("../reevaluatePolicy").success(function(){a.find("i").attr("class","icon-white icon-refresh");location.reload()}).error(function(){$(".btn-group:eq(1)").after('\x3cdiv class\x3d"alert alert-error" style\x3d"margin:5px 0"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3eThere has been an error reevaluating policy. Try running the report again.\x3c/div\x3e')})}):
a.hide();$.browser.msie&&9>$.browser.version&&$(".btn-group:eq(1)").after('\x3cdiv class\x3d"alert alert-error" style\x3d"margin:5px 0"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3eYou are using older version of Internet Explorer (IE). You may notice degraded performance and/or functionality. To address this, download and install the latest version of IE, or other modern browser (e.g. Chrome, Firefox)\x3c/div\x3e');Insight.updateSummary();Insight.hasJoyride()&&
Insight.startTour()})})();
(function(){function a(a){var b=$(window).innerHeight(),c=$(a).offset().top;a=$("#"+a.attr("id")+"Pager").height();return Math.max(150,b-c-l-a)}function e(a){$("#"+a+"container .message").remove()}function c(a,b){var c=$("#"+a+"container"),k=$("#"+a+"Table").position(),q;null!==k&&(e(a),c.append('\x3cdiv class\x3d"message" style\x3d"top:'+(k.top+70)+'px"\x3e'+b+"\x3c/div\x3e"),q=$(".message",c),q.css("left",k.left+c.outerWidth()/2-q.outerWidth()/2+"px"))}function b(b,c,f){function e(g){r.destroyed||(r.table=
new Slick.Grid("#"+b+"Table",r.dataView,f.columns,u),f.selectable&&(r.table.setSelectionModel(new Slick.RowSelectionModel),r.dataView.syncGridSelection(r.table,!0)),w.init(r.table),s.css("height",f.height||a($("#"+b+"Table"))+"px"),r.processData(g),r.initialize())}function q(a){return function(b,c,d){b=s.empty().append(Insight.templates.error.render({message:d}));$("button",b).click(a)}}function l(a){s.empty().append('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e');
a.get().done(function(b){null!=b?e(b):q(function(){l(a)})()}).fail(q(function(){l(a)}))}var w=new Slick.Data.GroupItemMetadataProvider,u=$.extend({editable:!1,enableAddRow:!1,enableCellNavigation:f.enableCellNavigation,enableColumnReorder:!1,enableTextSelectionOnCells:!0,fullWidthRows:!0,forceFitColumns:!0,rowHeight:31,explicitInitialization:!0,showHeaderRow:!f.disableFilter,multiSelect:!1,autoHeight:f.autoHeight,multiColumnSort:f.multiColumnSort},f.config||{}),r=this,s=$("#"+b+"Table");this.options=
f;this.id=b;this.dataView=new Slick.Data.DataView({groupItemMetadataProvider:w});this.filter=new Slick.Filter;$.isArray(c)?e({aaData:c}):"string"===typeof c?l({get:function(){return $.getJSON(c)}}):"object"===typeof c?l(c):console.log("Unable to load: "+c)}var l=null;$.browser&&($.browser.mozilla&&4>parseFloat($.browser.version)?l=9:$.browser.msie&&9>parseFloat($.browser.version)&&(l=15));null===l&&(l=14);b.prototype.updateHeight=function(){var b=$("#"+this.id+"Table"),c=this;b.css("height",a(b)+
"px");window.clearTimeout(this.resizeTimeout);this.resizeTimeout=window.setTimeout(function(){c.table.resizeCanvas()},50)};b.prototype.destroy=function(){this.destroyed=!0;e(this.id);$(window).unbind("resize");this.table&&(this.table.pager&&(this.table.pager.destroy(),this.table.pager=null),this.table.columnsResizedFn&&(this.table.onColumnsResized.unsubscribe(this.table.columnsResizedFn),this.table.columnsResizedFn=null),this.table.destroy())};b.prototype.initialize=function(){var a=this;this.initialized||
(this.initialized=!0,this.options.defaultSort&&($.isArray(this.options.defaultSort)?this.table.setSortColumns(this.options.defaultSort):this.table.setSortColumns([this.options.defaultSort])),$.isArray(this.options.plugins)&&$.each(this.options.plugins,function(b,c){a.table.registerPlugin(c)}),this.table.registerPlugin(new Slick.Sort),this.table.init(),this.options.disableFilter||this.table.registerPlugin(this.filter),this.table.registerPlugin(new Slick.Tipsy),$(window).resize(this.options.resizeFn||
function(){Insight.util.isNullOrUndefined(a.options.height)&&a.updateHeight()}),this.listeners&&($.each(this.listeners,function(a,b){setTimeout(b,0)}),this.listeners=null))};b.prototype.processData=function(a){var b=this;this.initialize();Insight.util.isNotNullOrUndefined(a)&&(this.options.dataProcessor&&(a.aaData=this.options.dataProcessor.call(null,a.aaData)),this.dataView.beginUpdate(),this.dataView.setItems(a.aaData),this.options.disableFilter||(this.options.externalFilters?this.dataView.setFilter(function(a,
c){var e=!0;$.each(b.options.externalFilters,function(b,d){d(a,c)||(e=!1);return e});return e&&b.filter.getFilter()(a,c)}):this.dataView.setFilter(this.filter.getFilter())),this.options.groupInfo&&this.dataView.groupBy(this.options.groupInfo.field,this.options.groupInfo.groupHeaderFn,this.options.groupInfo.groupingComparer),this.dataView.endUpdate(),this.options.groupInfo&&"collapsed"===this.options.groupInfo.initialState&&(this.dataView.beginUpdate(),$.each(this.dataView.getGroups(),function(a,c){b.dataView.collapseGroup(c.value)}),
this.dataView.endUpdate()));e(this.id);if(Insight.util.isNullOrUndefined(a)||0===a.aaData.length)c(this.id,this.options.emptyText||"None");this.options.disablePager||(this.table.pager=new Slick.Controls.Pager(this.dataView,this.table,$("#"+this.id+"TablePager")))};b.prototype.addMessage=function(a,b,c){var e=this,l=$('\x3cdiv class\x3d"alert"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3e\x3c/div\x3e');l.addClass(b);l.append("\x3cspan\x3e\x3c/span\x3e").text(a);
l.bind("closed",function(){e.updateHeight()});$("#"+e.id+"container").prepend(l);e.updateHeight();c&&setTimeout(function(){l.fadeOut("fast",function(){l.remove();e.updateHeight()})},1E3*c);return l};b.prototype.addLoadListener=function(a){this.table?setTimeout(a,0):(this.listeners=this.listeners||[],this.listeners.push(a))};b.prototype.addSuccess=function(a,b){this.addMessage(a,"alert-success",b)};b.prototype.addError=function(a,b){this.addMessage(a,"alert-error",b)};$.extend(!0,window,{Insight:{Table:b}})})();
(function(){function a(a){Insight.util.isNotNullOrUndefined(r)?a.apply(null,[r]):$.getJSON(toDataUrl("licensethreats.json")).success(function(b){r=b.aaData;a.apply(null,[r])}).error(function(b,c,g){a.apply(null,[null,"Loading license categorization: "+Insight.util.getErrorMessage(b)])})}function e(){for(var a=null,b=0;b<arguments.length;b++)for(var c=arguments[b],g=0;g<c.length;g++){var d=r[c[g]];Insight.util.isNotNullOrUndefined(d)&&(a=Math.max(d,a))}return a}function c(a){var c=b(a.effectiveLicenseThreat);
return"undefined"!==typeof c?c:Insight.util.isNotNullOrUndefined(a.overriddenLicenses)?e(a.overriddenLicenses):a.effectiveLicenseThreat}function b(a){if(0<=z.indexOf(a))return l(a)}function l(a){switch(a){case "COPYLEFT":return 10;case "NON-STANDARD":return 7;case "NOT-PROVIDED":return 6;case "WEAKCOPYLEFT":return 3;case "LIBERAL":return 0;default:return null}}function p(a,b){for(var c=[],g=null,g=0;g<b.length;g++)("Not Provided"===b[g]||-1===a.indexOf(b[g]))&&c.push(b[g]);return c}function d(a){return Insight.util.isNotNullOrUndefined(a)&&
0<a.length?a.join(", "):""}function f(a,b){var g=c(a),d=c(b),g=Insight.util.isNullOrUndefined(g)?-1:g,d=Insight.util.isNullOrUndefined(d)?-1:d;return g<d?-1:g>d?1:0}function k(a){var c=b(a);"undefined"!==typeof c&&(a=c);return Insight.util.isNullOrUndefined(a)?"unspecifiedScore":7<a?"criticalScore":3<a?"severeScore":0<a?"moderateScore":"noScore"}function q(a,b,c){if(Insight.util.isNotNullOrUndefined(a))return d(a);a=d(b);b=d(p(b,c));return a+(0<b.length?", "+b:"")}function v(a,b,g,f,y){if(Insight.util.isNotNullOrUndefined(y.overriddenLicenses))return'\x3cdiv class\x3d"'+
k(e(y.overriddenLicenses))+'"\x3e\x3ci\x3e'+d(y.overriddenLicenses)+"\x3c/i\x3e\x3c/div\x3e";a=d(y.declaredLicenses);b=d(p(y.declaredLicenses,y.observedLicenses));return'\x3cdiv class\x3d"'+k(c(y))+'"\x3e \x3cb\x3e'+a+"\x3c/b\x3e"+(0<b.length?", "+b:"")+"\x3c/div\x3e"}function w(){return x||t||m}function u(a,b){$("#"+a+"container .message").remove();$(window).unbind("resize");b.pager&&(b.pager.destroy(),b.pager=null);b.columnsResizedFn&&(b.onColumnsResized.unsubscribe(b.columnsResizedFn),b.columnsResizedFn=
null);b.destroy()}var r,s={id:"coordinates",name:"Coordinates",field:"coordinates",sortable:!0,width:295,toolTipGravity:"se",formatter:function(a,b,c,g,d){a="";switch(d.componentIdentifier.format){case "nuget":a+='\x3cimg src\x3d"public/coord-nuget.png" alt\x3d"NuGet"/\x3e ';break;case "maven":a+='\x3cimg src\x3d"public/coord-maven.png" alt\x3d"Maven"/\x3e ';break;default:a+='\x3cimg src\x3d"public/coord-unknown.png" alt\x3d"Unknown"/\x3e '}return a+$.map(d.displayName.parts,function(a){return a.value}).join("")}},
g=function(a){a=a||[];$.each(a,function(a,b){if(Insight.util.isNullOrUndefined(b.componentIdentifier))if(b.componentIdentifier={},b.displayName={},Insight.util.isNullOrUndefined(b.groupId))if(b.componentIdentifier.format="unknown",b.filenames&&0<b.filenames.length){b.displayName.parts=[];for(var c=0;c<b.filenames.length;c++)b.displayName.parts.push({field:"Filename",value:b.filenames[c]}),c<b.filenames.length-1&&b.displayName.parts.push({value:", "})}else b.displayName.parts=[{value:"(Anonymized Path) SHA1: "},
{field:"Hash",value:b.hash}];else b.componentIdentifier.format="maven",b.displayName.parts=[{field:"Group",value:b.groupId},{value:" : "},{field:"Artifact",value:b.artifactId},{value:" : "},{field:"Version",value:b.version}];b.coordinates=$.map(b.displayName.parts,function(a){return a.value}).join("")})};a($.noop);var z="UNKCAT LIBERAL WEAKCOPYLEFT NOT-PROVIDED NON-STANDARD COPYLEFT".split(" "),x=null,t=null,m=null,h=null,n=null;$.extend(!0,window,{InsightDatatable:{createAuditTable:function(a){n=
new Insight.Table("audit",a,{resizeFn:$.noop,selectable:!0,disablePager:!0,disableFilter:!0,height:250,columns:[{id:"date",name:"Date",field:"date",formatter:function(a,b,c,g,d){return dateFormat(c,"mmm d yyyy, h:MM:ss tt")},sortable:!0,width:30},{id:"user",name:"User",field:"user",toolTipGravity:"n",toolTipFn:function(a){return Insight.util.isNullOrUndefined(a.where)?$("\x3cdiv/\x3e").text("Edited report from "+a.ip).html():$("\x3cdiv/\x3e").text("Edited report in build '"+a.where+"' from "+a.ip).html()},
sortable:!0,width:20},{id:"action",name:"Action",field:"action",sortable:!0,width:20},{id:"detail",name:"Detail",field:"detail",sortable:!0,width:40},{id:"comment",name:"Comment",field:"comment",toolTipGravity:"n",toolTipFn:function(a){if(a.comment)return $("\x3cdiv/\x3e").text(a.comment).html()},sortable:!0,width:80}],defaultSort:{columnId:"date",sortAsc:!1},dataProcessor:function(a){$.each(a,function(a,b){var c=b.status,g="",e;b.id=a;b.date=new Date(b.time);switch(b.status){case "Open":c="Reopened";
break;case "Not Applicable":c="Ignored";break;case "Overridden":c="Overrode"}b.action=c;Insight.util.isNullOrUndefined(b.user)&&(b.user="anonymous");switch(b.filename){case "licenses.json":g="License ";c=b.overriddenLicenses;g=Insight.util.isNotNullOrUndefined(c)?g+("as "+d(c)):g+"Analysis";break;case "security.json":g="Vulnerability ",c=b.source,e=b.reference,Insight.util.isNotNullOrUndefined(c)&&0!==e.toUpperCase().indexOf(c.toUpperCase())&&(g+=c+"-"),g+=e}b.detail=g});return a}});$("#"+n.id+"Table").click(function(a){a.stopPropagation()})},
createComponentTable:function(){function a(b){b.preventDefault();$(this).parents("ul").children("li").removeClass("active");$(this).parents("li").addClass("active");b=$("#policy-match-state-filter li.active").text();var c=$("#policy-violation-filter li.active").text(),g={};"All"!==b&&("Proprietary"===b?g.proprietary=!0:"Error"===b?g.scanError=!0:g.matchState=b.toLowerCase());"Summary"===c?g.summary=!0:"Waived"===c?g.waived=!0:"All"===c&&(g.all=!0);m.addLoadListener(function(){m.table.getData().setFilterArgs(g);
m.table.getData().refresh()})}var b=["unknown","similar","exact"],c=new Slick.ColumnGrouping({columnId:"policyName",style:"scoreCol"}),d=c.getCellStyler(),e=c.getCellRenderer(),f=HealthCheck.getAge(earliestReleaseDate,currentDate),t=$("\x3cdiv/\x3e"),f=[{id:"policyName",name:"Policy Threat",shortName:"Name",field:"policyName",sortable:!0,width:225,styleFn:function(a,b,c,g,e){return"nopad "+d(a,b,c,g,e)},sortFn:function(a,b){var c=a.policyThreatLevel,g=b.policyThreatLevel,d=a.policyName,e=b.policyName;
return c<g?-1:c>g||d<e?1:d>e?-1:0},formatter:function(a,b,c,g,d){var f;switch(d.policyThreatLevel){case 0:f=" noScore";break;case 1:f=" ignoredScore";break;case 2:case 3:f=" moderateScore";break;case 4:case 5:case 6:case 7:f=" severeScore";break;case 8:case 9:case 10:f=" criticalScore"}return'\x3cdiv class\x3d"'+f+'"\x3e'+(0<e(a,b,c,g,d).length?t.text(c).html():"")+"\x3c/div\x3e"}},$.extend({},s,{styleFn:function(a,b,c,g,d){return d.modified||"Manual"===d.identificationSource?"modified":""},toolTipFn:function(a){var b=
"";a.modified&&(b+="\x3cli\x3ebeen manually edited.  See the audit log for details.\x3c/li\x3e");"Manual"===a.identificationSource&&(b+="\x3cli\x3ebeen claimed from an unknown or similar component.  View the Component Information Panel (CIP) for more details.\x3c/li\x3e");a.waived&&(b+="\x3cli\x3ebeen waived.\x3c/li\x3e");if(0<b.length)return"This record has...\x3cbr\x3e\x3cbr\x3e\x3cul\x3e"+b+"\x3c/ul\x3e"},formatter:function(a,b,c,g,d){var e="",e=d.waived?'\x3cimg src\x3d"flag_white.png" style\x3d"margin-right:4px" title\x3d"Violation has been waived"\x3e':
'\x3cspan style\x3d"padding-right:20px"\x3e\x3c/span\x3e';return e+s.formatter(a,b,c,g,d)}}),{id:"versions",name:"Popularity",field:"relativePopularity",sortable:!0,filterable:!1,width:85,sortFn:function(a,c){return a.matchState===b[0]?c.matchState===b[0]?0:-1:c.matchState===b[0]?1:"Manual"===a.identificationSource?a.identificationSource===c.identificationSource?0:-1:"Manual"===c.identificationSource?1:a.relativePopularity<c.relativePopularity?-1:a.relativePopularity>c.relativePopularity?1:0},formatter:function(a,
c,g,d,e){if(e.matchState===b[0]||"Manual"===e.identificationSource)return"";var f;g=Math.round(100*g);79<g?f="popularity-100":59<g?f="popularity-80":39<g?f="popularity-60":19<g?f="popularity-40":0<=g&&(f="popularity-20");return f?'\x3cdiv class\x3d"'+f+'"\x3e\x3c/div\x3e':""}},{id:"age",name:"Age",field:"age",sortable:!0,filterable:!1,width:85,sortFn:function(a,b){var c=a.age,g=b.age;if(!(void 0===c&&void 0===g)){if(void 0===c)return-1;if(void 0===g)return 1;if(c<g)return-1;if(c>g)return 1}return 0},
formatter:function(a,b,c,g,d){return void 0===c||null===c?"":359<c?(c/365).toFixed(1)+" y":30<c?Math.floor(c/30)+" m":Math.floor(c)+" d"}},{id:"releasehistory",name:"Release History",field:"groupId",sortable:!1,filterable:!1,resizable:!1,width:211,header:'\x3cdiv class\x3d"release-header"\x3e\x3ci class\x3d"icon-question-sign" title\x3d"\x3cdiv style\x3d\'background:url(release-tooltip.png);width:241px;height:78px\'\x3e\x3c/div\x3e"\x3e\x3c/i\x3e\x3cspan\x3e'+f+"\x3c/span\x3e\x3c/div\x3e",formatter:function(a,
b,c,g,d){if(null===c||"Manual"===d.identificationSource)return"No Popularity Data";var e="";$.each({groupId:d.groupId,artifactId:d.artifactId,version:d.version},function(a,b){e+="\x26"+encodeURIComponent(a)+"\x3d"+encodeURIComponent(b)});return'\x3cimg src\x3d"'+toDataUrl("release-graph/"+encodeURIComponent(d.groupId)+"/"+encodeURIComponent(d.artifactId)+"/"+encodeURIComponent(d.version)+".png")+'" alt\x3d"Release Popularity"\x3e'}}],c=[c,new Insight.InformationPanel({byHash:!0})];Brain.hasFeature("release-graph")||
(f[1].width+=f.pop().width);m=new Insight.Table("component",{get:function(){var a=$.Deferred();$.when($.getJSON(toDataUrl("policythreats.json")),$.getJSON(toDataUrl("bom.json"))).done(function(b,c){function g(a){return a.hash||"error: "+(a.pathnames||[]).join("\t")}if(null===b[0]||null===c[0])a.reject([]);else{var d={},e={},f={},m=[];$.each(c[0].aaData,function(a,b){var c=g(b);d[c]=b;e[c]=!1;f[c]=!1});b[0].version?($("#policy-violation-filter").show(),$.each(b[0].aaData,function(a,b){var c=g(b);if(!b.hash||
"null"===b.hash)return!0;b.activeViolations.length&&(e[c]=!0,b.activeViolations.sort(function(a,b){return b.policyThreatLevel-a.policyThreatLevel}),$.each(b.activeViolations,function(a,g){m.push($.extend({policyThreatLevel:g.policyThreatLevel,policyName:g.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,summary:0===a,waived:!1,all:!0},d[c]))}));b.waivedViolations.length&&(f[c]=!0,$.each(b.waivedViolations,function(a,g){m.push($.extend({policyThreatLevel:g.policyThreatLevel,
policyName:g.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,summary:!1,waived:!0,all:!0},d[c]))}))})):$.each(b[0].aaData,function(a,b){var c=g(b);if(!b.hash||"null"===b.hash)return!0;e[c]=!0;m.push($.extend({policyThreatLevel:b.policyThreatLevel,policyName:b.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,summary:!0,waived:!1,all:!0},d[c]))});$.each(e,function(a,b){b||m.push($.extend(!0,{policyThreatLevel:0,policyName:"None",summary:!0,
waived:!1,all:!1===f[a]},d[a]))});a.resolve({aaData:m})}}).fail(function(b){a.reject(b)});return a}},{columns:f,multiColumnSort:!0,selectable:!0,plugins:c,defaultSort:[{columnId:"policyName",sortAsc:!1},{columnId:"coordinates",sortAsc:!0}],externalFilters:[function(a,b){var c=!0;b&&$.each(b,function(b,g){return c=a[b]===g});return c}],dataProcessor:function(a){a=a||[];$.each(a,function(a,b){b.id=a;b.createTime&&(b.age=Math.floor(((new Date).getTime()-b.createTime)/864E5))});g(a);return a}});$("#policy-match-state-filter").unbind("click");
$("#policy-match-state-filter li a").click(a);$("#policy-violation-filter li a").click(a);$("#policy-match-state-filter li.active a").trigger("click");m.addLoadListener(function(){m.table.setSelectionModel(new Slick.RowSelectionModel);$(".release-header \x3e .icon-question-sign").tipsy({gravity:"e",html:!0,title:"title",opacity:1})})},createLicenseTable:function(a){var b=[{id:"_formattedEffectiveLicenseThreat",name:"License Threat",shortName:"Licenses",field:"_formattedEffectiveLicenseThreat",sortable:!0,
width:200,styleFn:function(){return"nopad"},sortFn:f,formatter:v},s],c=[new Insight.InformationPanel];t=new Insight.Table("license",toDataUrl("licenses.json"),{columns:b,config:a,plugins:c,defaultSort:{columnId:"_formattedEffectiveLicenseThreat",sortAsc:!1},dataProcessor:function(a){var b;for(b=0;b<a.length;b++)a[b].id=b,a[b].status=Insight.util.isNullOrUndefined(a[b].status)?"Open":a[b].status;g(a);return a}});t.addLoadListener(function(){t.table.setSelectionModel(new Slick.RowSelectionModel);t.table.getData().onRowsChanged.subscribe(function(a,
b){var c,g;b=b.rows;for(g=0;g<b.length;g++)c=t.table.getData().getItem(b[g]),c._formattedEffectiveLicenseThreat=q(c.overriddenLicenses,c.declaredLicenses,c.observedLicenses)})});return t},createSecurityTable:function(a){var b=new Slick.ColumnGrouping({columnId:"_score",style:"scoreCol"}),c=b.getCellStyler(),d=b.getCellRenderer(),e=[{id:"_score",name:"Threat Level",shortName:"Level",field:"_score",sortable:!0,width:120,toolTip:"'Threat Level' highlights the CVSS (Common Vulnerability Scoring System, version 2) base score for each listed vulnerability.",
styleFn:function(a,b,g,d,e){return"nopad "+c(a,b,g,d,e)},sortFn:function(a,b){var c=a._score,g=b._score;return!isNaN(c)&&!isNaN(g)?parseInt(c,10)-parseInt(g,10):g<c?-1:g>c?1:0},formatter:function(a,b,c,g,e){return'\x3cdiv class\x3d"'+(7<=c?" criticalScore":4<=c?" severeScore":" moderateScore")+'"\x3e'+(d(a,b,c,g,e)||"\x26nbsp;")+"\x3c/div\x3e"}},{id:"problemCode",name:"Problem Code",shortName:"Code",field:"_reference",sortable:!0,width:105,formatter:function(a,b,c,g,d){a=d._reference;d=d.url;return Insight.util.isNullOrUndefined(a)?
"":'\x3ca href\x3d"'+d+'" target\x3d"_blank"\x3e'+a+"\x3c/a\x3e"}},s],b=[b,new Insight.InformationPanel];x=new Insight.Table("security",toDataUrl("security.json"),{columns:e,config:a,defaultSort:{columnId:"_score",sortAsc:!1},dataProcessor:function(a){var b,c,d;for(d=0;d<a.length;d++)a[d].id=d,a[d]._score=Insight.util.isNullOrUndefined(a[d].score)?"Unscored":String(Math.floor(a[d].score)),b=a[d].source,c=a[d].reference,a[d]._reference=Insight.util.isNullOrUndefined(b)||0===c.toUpperCase().indexOf(b.toUpperCase())?
c:b+"-"+c,a[d].status=Insight.util.isNullOrUndefined(a[d].status)?"Open":a[d].status;g(a);return a},plugins:b});x.addLoadListener(function(){x.table.setSelectionModel(new Slick.RowSelectionModel)});return x},createSimilarityTable:function(a){h=new Insight.Table("similarity",a,{selectable:!0,disablePager:!0,disableFilter:!0,height:250,columns:[{id:"_formattedEffectiveLicenseThreat",name:"License Threat",field:"_formattedEffectiveLicenseThreat",sortable:!0,width:65,sortFn:f,formatter:v},{id:"securityCounters",
name:"Security",field:"securityCounters",sortable:!0,width:50,sortFn:function(a,b){var c=a.securityCounters.Critical-b.securityCounters.Critical;0===c&&(c=a.securityCounters.Severe-b.securityCounters.Severe);0===c&&(c=a.securityCounters.Moderate-b.securityCounters.Moderate);return c},formatter:function(a,b,c,g,d){a=d.securityCounters;var e="",f,m,t=0;b=g.width-10;c=function(a,b){var c;for(c=0;c<a&&!(t>=m);c++)e+='\x3cspan class\x3d"arrow '+b+'_arrow" style\x3d"left:'+t++*f+'px"\x3e\x3c/span\x3e'};
if(a){g=a.Critical+a.Severe+a.Moderate;for(f=0;-9<f&&(g-1)*(10+f)+10>b;f--);m=(b-10)/(10+f)+1;a.Critical&&c(a.Critical,"red");a.Severe&&c(a.Severe,"orange");a.Moderate&&c(a.Moderate,"yellow")}return'\x3cdiv style\x3d"white-space:nowrap;width:'+(0<t?10+(t-1)*(10+f):0)+'px"\x3e'+e+"\x3c/div\x3e"}},{id:"groupId",name:"Group",field:"groupId",sortable:!0,width:90},{id:"artifactId",name:"Artifact",field:"artifactId",sortable:!0,width:90},{id:"version",name:"Version",field:"version",sortable:!0,width:30}],
dataProcessor:function(a){a||(a=[]);$.each(a,function(a,b){b.id=a;b._formattedEffectiveLicenseThreat=q(b.overriddenLicenses,b.declaredLicenses,b.observedLicenses)});return a}});h.table.render();h.table.columnsResizedFn=function(){var a;for(a=0;a<h.getDataLength();a++)h.updateCell(a,h.getColumnIndex("securityCounters"))};h.table.onColumnsResized.subscribe(h.table.columnsResizedFn);$("#similarityTable").click(function(a){a.stopPropagation()})},destroyActiveTable:function(){var a=w();a&&a.destroy();
m=t=x=null},getActiveTable:w,loadLicenseThreats:a,getLicenseThreatLevelFromArray:e,getLicenseThreatClass:k,removeAuditTable:function(){Insight.util.isNotNullOrUndefined(n)&&(u("audit",n),n=null)},removeComponentTable:function(){Insight.util.isNotNullOrUndefined(m)&&(u("component",m),$("#componentcontainer ul.nav a").unbind("click"),m=null)},removeLicenseTable:function(){Insight.util.isNotNullOrUndefined(t)&&(u("license",t),t=null)},removeSecurityTable:function(){Insight.util.isNotNullOrUndefined(x)&&
(u("security",x),x=null)},removeSimilarityTable:function(){Insight.util.isNotNullOrUndefined(h)&&(u("similarity",h),h=null)}}})})();
(function(a){function e(b){function c(){f=[];a.each(b.grid.getSelectedRows(),function(a,c){f.push(b.grid.getData().getItem(c))});1===f.length?a("input,textarea,select",n).change(k).keyup(k).focusout(k):(a("input,textarea,select",n).unbind("change").unbind("keyup").unbind("focusout"),a("button[data-type\x3dupdate]",n).removeAttr("disabled"))}function e(c){var m=this,h={};c.preventDefault();a(m).attr("disabled","disabled");a("select",n).each(function(b){0===b?h.status=a(this).val():(b=!a(this).prop("disabled"),
h.overriddenLicenses=b?[a(this).val()]:null,h.overriddenLicenseThreat=b?InsightDatatable.getLicenseThreatLevelFromArray(h.overriddenLicenses):null)});h.comment=a("textarea",n).val();d({mask:h,callback:function(c){Insight.util.isNotNullOrUndefined(c)&&a(m).removeAttr("disabled");Insight.util.isNotNullOrUndefined(b.callback)&&b.callback.apply(this,arguments)},dataView:b.dataView,items:f})}b=a.extend({timestamp:(new Date).getTime()},b);var f=b.artifacts,m="#licenseselect"+b.timestamp,h="#license"+b.timestamp,
n=null,l=null,s=a.Deferred(),k=function(){var b=a("option:selected",m).val(),c=a.trim(a("textarea",n).val()),g=a("option:selected",h).val(),d=b!==(f[0].status||"Open"),c=0<c.length,e=g&&(!f[0].overriddenLicenses||f[0].overriddenLicenses[0]!==g);(g&&("Overridden"===b||"Selected"===b)||!g&&!("Overridden"===b||"Selected"===b))&&(c||d||("Overridden"===b||"Selected"===b)&&e)?a("button[data-type\x3dupdate]",n).removeAttr("disabled"):a("button[data-type\x3dupdate]",n).attr("disabled","disabled")};b.single=
Brain.ci.getArtifactLicensesUrl&&b.single;b.grid&&b.grid.onSelectedRowsChanged.subscribe(c);b.single&&a.getJSON(toDataUrl(Insight.toBrain(Brain.ci.getArtifactLicensesUrl(a.extend({appId:applicationId},f[0]))))).success(function(a){s.resolve(a)}).error(function(){});a.extend(this,{destroy:function(){b.grid&&b.grid.onSelectedRowsChanged.unsubscribe(c)},show:function(c){n=c;a(n).html(v.render(b));a("button[data-type\x3dupdate]",n).click(e);a("button[data-type\x3dcancel]",n).click(function(a){a.preventDefault();
b.cancelCallback&&b.cancelCallback.apply(this)});1===f.length&&(a("button[data-type\x3dupdate]",n).attr("disabled","disabled"),a("input,textarea,select",n).change(k).keyup(k).focusout(k),Insight.util.isNotNullOrUndefined(f[0].status)&&a("[value\x3d"+f[0].status+"]",n).attr("selected",!0));a(m,n).css("width",b.width);a(m,n).change(function(){var b=a(this),c=a(h).val()||f[0].overriddenLicenses&&f[0].overriddenLicenses[0];switch(b.val()){case "Selected":a("option",h).detach();a(h,n).attr("disabled",
!0);s.done(function(g){"Selected"===b.val()&&0<g.length&&InsightDatatable.loadLicenseThreats(function(b){var d={};a.each(g,function(a,c){d[c.licenseName]=b[c.licenseName]});InsightDatatable.populateLicenseCombo(a(h,n),d);Insight.util.isNotNullOrUndefined(c)&&a('option[value\x3d"'+c+'"]',h).attr("selected","selected");a(h,n).removeAttr("disabled")})});break;case "Overridden":a("option",h).detach();l.appendTo(h);a(h,n).removeAttr("disabled");break;default:a("option",h).detach(),a(h,n).attr("disabled",
!0)}Insight.util.isNotNullOrUndefined(c)&&a('option[value\x3d"'+c+'"]',h).attr("selected","selected");k()});p(function(c){var d=a(h,n);InsightDatatable.populateLicenseCombo(d,c);l=a("option",d);1===f.length&&(Insight.util.isNotNullOrUndefined(f[0].overriddenLicenses)&&0<f[0].overriddenLicenses.length&&a("option",d).each(function(){a(this).val()===f[0].overriddenLicenses[0]&&a(this).attr("selected",!0)}),a(m,n).trigger("change"));a(d,n).css("width",b.width)})}})}function c(b){function c(){0===m.length?
a("button[data-type\x3dupdate]",h).attr("disabled","disabled"):a("button[data-type\x3dupdate]",h).removeAttr("disabled")}function d(){m=[];a.each(b.grid.getSelectedRows(),function(a,c){m.push(b.grid.getData().getItem(c))});c()}function e(c){var d={};c.preventDefault();d.status=a("select",h).val();d.comment=a("textarea",h).val();f({mask:d,dataView:b.dataViews[0],items:m,callback:function(c){if(!Insight.util.isNotNullOrUndefined(c))for(var e=1;e<b.dataViews.length;e++)b.dataViews[e].beginUpdate(),a.each(m,
function(c,f){a.each(b.dataViews[e].getItems(),function(c,m){if(!(f.source!==m.source||f.reference!==m.reference||f.componentIdentifier.format!==m.componentIdentifier.format)){for(var h in f.componentIdentifier.coordinates)if(f.componentIdentifier.coordinates.hasOwnProperty(h)&&f.componentIdentifier.coordinates[h]!==m.componentIdentifier.coordinates[h])return;b.dataViews[e].updateItem(m.id,a.extend({},m,d));return!1}})}),b.dataViews[e].endUpdate();Insight.util.isNotNullOrUndefined(b.callback)&&b.callback.apply(this,
arguments)}})}b=a.extend({timestamp:(new Date).getTime()},b);var m=b.artifacts,h;b.grid&&b.grid.onSelectedRowsChanged.subscribe(d);a.extend(this,{destroy:function(){b.grid&&b.grid.onSelectedRowsChanged.unsubscribe(d)},show:function(d){h=d;a(h).html(w.render(b));a("button[data-type\x3dupdate]",h).click(e);a("button[data-type\x3dcancel]",h).click(function(a){a.preventDefault();b.cancelCallback&&b.cancelCallback.apply(this)});a("#svStatus"+b.timestamp,h).css("width",b.width);c()}})}function b(b,c,d,
e,f,h){var k=[],s=[];a.each(c,function(b,c){var g=a.extend({},c);a.each(d,function(a,b){g[a]=b});g.modified=!0;k.push(g)});a.merge(s,e);a.each(d,function(a,b){s.push(a)});a.ajax({type:"POST",url:"../augmentData/bom.json",data:l(k,a.merge(["modified"],q)),beforeSend:parent.beforeSendAugmentedData});a.ajax({type:"POST",url:"../augmentData/"+f,data:l(k,s),beforeSend:parent.beforeSendAugmentedData}).success(function(){b.beginUpdate();a.each(k,function(a,c){b.updateItem(c.id,c)});b.endUpdate();Insight.updateSummary();
h()}).error(function(a,b,c){c=Insight.util.getErrorMessage(a);h(c)})}function l(a,b){for(var c=[],d=0;d<a.length;d++){for(var e=a[d],f={componentIdentifier:e.componentIdentifier},d=0;d<b.length;d++)f[b[d]]=e[b[d]];c.push(f)}return JSON.stringify(c)}function p(b,c){Insight.util.isNotNullOrUndefined(u)?b.apply(null,[u]):(s.push(b),r||(r=!0,a.getJSON(toDataUrl("licenselist.json")).success(function(b){u=b.aaData;a.each(s,function(a,b){b.apply(null,[u])})}).error(function(a,b,c){b=InsightDatatable.getActiveTable();
c=Insight.util.getErrorMessage(a);null!==b?b.addError("Loading known licenses: "+c):console&&console.log("Error loading known licenses: "+c)})))}function d(c){c=a.extend({dataView:null,items:[],mask:{},callback:a.noop},c);a.isArray(c.items)||(c.items=[c.items]);b(c.dataView,c.items,c.mask,{},"licenses.json",c.callback)}function f(c){c=a.extend({dataView:null,items:[],mask:{},callback:a.noop},c);a.isArray(c.items)||(c.items=[c.items]);b(c.dataView,c.items,c.mask,k,"security.json",c.callback)}var k=
["source","reference"],q=["hash"],v,w;a(document).ready(function(){v=Hogan.compile(a("#licenseEditorTemplate").html());w=Hogan.compile(a("#svEditorTemplate").html())});var u=null,r=!1,s=[];a.extend(!0,window,{InsightDatatable:{addSecurityTableEditor:function(b){var d=b.table,e=d.getColumns(),f=new Slick.BulkEditor({editNode:a("#securityEditor"),editor:new c({width:650,grid:d,cancel:!0,artifacts:[],dataViews:[d.getData()],callback:function(c){Insight.util.isNotNullOrUndefined(c)?b.addError(c):(c=d.getSelectedRows(),
Insight.updateSummary(),1==c.length?b.addSuccess("Updated "+c.length+" security vulnerability.",60):1<c.length&&b.addSuccess("Updated "+c.length+" security vulnerabilities.",60),a("#securityEditor").slideUp({complete:function(){a(this).empty()},step:function(){b.updateHeight()}}))},cancelCallback:function(c){a("#securityEditor").empty().hide();b.updateHeight()}}),openCallback:function(){b.updateHeight()}}),e=a.merge([f.getColumnDef()],e);e[0].filterable=!1;d.setSelectionModel(new Slick.RowSelectionModel);
d.getData().syncGridSelection(d,!0);d.setColumns(e);d.registerPlugin(f)},addLicenseTableEditor:function(b){var c=b.table,d=c.getColumns(),f=new Slick.BulkEditor({editNode:a("#licenseEditor"),editor:new e({artifacts:[],width:650,cancel:!0,grid:c,dataView:c.getData(),callback:function(d){Insight.util.isNotNullOrUndefined(d)?b.addError(d):(d=c.getSelectedRows(),Insight.updateSummary(),1==d.length?b.addSuccess("Updated license for "+d.length+" component.",60):1<d.length&&b.addSuccess(c,"license","Updated license for "+
d.length+" components.",60),a("#licenseEditor").slideUp({complete:function(){a(this).empty()},step:function(){b.updateHeight()}}))},cancelCallback:function(c){a("#licenseEditor").empty().hide();b.updateHeight()}}),openCallback:function(){b.updateHeight()}}),d=a.merge([f.getColumnDef()],d);d[0].filterable=!1;c.setSelectionModel(new Slick.RowSelectionModel);c.getData().syncGridSelection(c,!0);c.setColumns(d);c.registerPlugin(f)},populateLicenseCombo:function(b,c,d){a(b).empty();var e=[];a.each(c,function(a,
b){e.push(a)});e.sort(function(a,b){a=a.toUpperCase();b=b.toUpperCase();return a>b?1:a<b?-1:0});a.each(e,function(c,e){var f=a("\x3coption\x3e\x3c/option\x3e").text(e).val(e);e===d&&f.attr("selected","selected");a(b).append(f)})},loadLicenses:p,LicenseEditor:e,SecurityEditor:c,updateLicenses:d,updateSecurity:f,updateBom:function(c){c=a.extend({dataView:null,items:[],mask:{},callback:a.noop},c);a.isArray(c.items)||(c.items=[c.items]);b(c.dataView,c.items,c.mask,q,"bom.json",c.callback)}}})})(jQuery);
(function(){function a(a,c){this.node=a;this.options=c}(function(){var a=angular.module("PolicyViolations",["CommonServices"]);a.controller("PolicyViolationsController",["$http","$scope","$q","PolicyViolationData","Messages",function(a,b,e,p,d){function f(a){var b={constraintId:a.constraintId,constraintName:a.constraintName,constraintOperator:a.operatorName,conditions:[]};angular.forEach(a.conditionFacts,function(a){b.conditions.push({conditionType:a.conditionTypeId,conditionSummary:a.summary,conditionReason:a.reason})});
return b}function k(a,b){if(b){for(var c=0;c<a.length;c++)if(a[c].actionSummary===b.actionSummary)return;a.push(b)}}function q(a,b){var c=null;$.each(b,function(){if(this.id===a.actionTypeId)return c={actionSummary:this.summary},!1});return c}function v(a){return angular.extend(a,{color:7<a.threatLevel?"red":3<a.threatLevel?"orange":1<a.threatLevel?"yellow":0<a.threatLevel?"darkblue":"blue"})}function w(){b.processedPolicyAlerts.sort(function(a,b){return b.threatLevel-a.threatLevel})}function u(a){b.alerts.push({type:"error",
msg:d.getHttpErrorMessage(a)})}function r(){e.all([a.get(CLM.path+"rest/policy/actionType"),a.get("policyalerts.json")]).then(function(a){var c=a[0].data;a=a[1].data.aaData||[];b.processedPolicyAlerts=[];angular.forEach(a,function(a,d){var e=[];angular.forEach(a.actions,function(a,b){k(e,q(a,c))});angular.forEach(a.trigger.componentFacts,function(c,d){if(c.hash===p.hash){var g=[];angular.forEach(c.constraintFacts,function(a){g.push(f(a))});b.processedPolicyAlerts.push(v({id:a.trigger.policyId,name:a.trigger.policyName,
threatLevel:a.trigger.threatLevel,groupId:c.groupId,artifactId:c.artifactId,version:c.version,hash:c.hash,constraints:g,actions:e}))}})});w()},u)}b.waiveComponent=function(a){$modal.open({templateUrl:"add-waiver-modal-tmpl",controller:"AddWaiverController",backdrop:"static",keyboard:!1,resolve:{policy:function(){return a}}})};b.viewWaivers=function(){$modal.open({templateUrl:"view-waivers-modal-tmpl",controller:"ViewWaiverController",backdrop:"static",keyboard:!1})};b.alerts=[];(function(){a.get(toDataUrl("policythreats.json")).then(function(a){a.data.version?
(a=a.data.aaData||[],b.processedPolicyAlerts=[],angular.forEach(a,function(a,c){a.hash===p.hash&&angular.forEach(a.activeViolations,function(c,d){var e=[];angular.forEach(c.actions,function(a){k(e,a)});b.processedPolicyAlerts.push(v({id:c.policyId,name:c.policyName,threatLevel:c.policyThreatLevel,groupId:a.groupId,artifactId:a.artifactId,version:a.version,hash:a.hash,constraints:c.constraints,actions:e}))})}),w()):r()},u)})()}]);a.controller("AddWaiverController",["$http","$scope","PolicyViolationData",
"Messages","policy",function(a,b,e,p,d){(function(){b.policy=d;b.component=e;b.waiverLoading=!0;a.get(CLM.path+"rest/policyWaiver/application/"+e.appId+"/applicable/context/"+b.policy.id).success(function(a){function c(a){a.children&&angular.forEach(a.children,function(a){c(a)});b.waiverTargets.push({id:a.id,name:a.name,type:a.type})}b.waiverSelectOwner=a.children&&a.children.length;b.waiverTargets=[];b.waiverLoading=!1;c(a);b.waiver={hash:e.hash,policyId:b.policy.id,ownerId:b.waiverTargets[0].id,
comment:""};b.owner={type:b.waiverTargets[0].type}}).error(function(a,c){b.waiverLoading=!1;b.waiveAssignError=p.getHttpErrorMessage(arguments)})})();b.acceptWaiveComponent=function(){b.waiverSaving=!0;b.waiveAssignError=null;a.post(CLM.path+"rest/policyWaiver/"+b.owner.type+"/"+b.waiver.ownerId,b.waiver).success(function(a){b.waiverSaving=!1;b.$close()}).error(function(a,c,d,e){b.waiverSaving=!1;b.waiveAssignError=p.getHttpErrorMessage(arguments)})}}]);a.controller("ViewWaiverController",["$scope",
"$http","PolicyViolationData","Messages",function(a,b,e,p){function d(b,d,e,l){a.appError=p.getHttpErrorMessage(arguments)}(function(){a.waiversLoading=!0;b.get(CLM.path+"rest/policyWaiver/application/"+e.appId+"/component/"+e.hash).success(function(b){a.waiversLoading=!1;a.waivers=[];angular.forEach(b.waiversByOwner,function(b,d){angular.forEach(b.waivers,function(d,e){d.type=b.ownerType;d.ownerName=b.ownerName;a.waivers.push(d)})})}).error(d)})();a.remove=function(b){a.confirmDelete=b;a.appError=
null};a.removeWaiver=function(){var e=a.confirmDelete;a.confirmDelete=null;a.appError=null;b["delete"](CLM.path+"rest/policyWaiver/"+e.type+"/"+e.ownerId+"/"+e.id).success(function(){a.waivers.splice(a.waivers.indexOf(e),1)}).error(d)}}])})();(function(){a.prototype=new Insight.InformationPanelPlugin({priority:32});a.prototype.create=function(){var a=(new Date).getTime(),c=$("\x3cdiv ng-include\x3d\"'cip-policy-violations.html'\"\x3e\x3c/div\x3e"),b=this;b.node.empty();c.appendTo(b.node);angular.module("policyViolations"+
a,[]).service("PolicyViolationData",function(){return{hash:b.gav.hash,groupId:b.gav.groupId,artifactId:b.gav.artifactId,version:b.gav.version,appId:applicationId}});angular.bootstrap(c[0],["PolicyViolations","policyViolations"+a])};a.prototype.destroy=function(){this.node.empty()};a.prototype.getTitle=function(){return"Policy"};return a})();Insight.InformationPanelPlugins.push(a);angular.module("CommonServices",[]).service("Messages",function(){return{getHttpErrorMessage:function(a){if(a){if(angular.isArray(a)||
"[object Arguments]"===a.toString())a={status:a[1],data:a[0],headers:3<=a.length?a[2]:null};var c="",c=a.headers?a.headers():null;return c=0===a.status||1E3<=a.status?"Unable to reach CLM server":a.data&&(!c||!c["content-type"]||-1===c["content-type"].indexOf("text/html"))?a.data:502===a.status?"Bad Gateway":503===a.status?"Service Unavailable":504===a.status?"Gateway Timeout":"Error "+a.status}}}})})();