INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Adobe','Adobe','Adobe','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Adobe-AFM','Adobe-AFM','Adobe-AFM','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Adobe-EULA','Adobe-EULA','Adobe-EULA','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('ATT','ATT','ATT','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Beerware','Beerware','Beerware','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Dyade','Dyade','Dyade','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('HP-DEC','HP-DEC','HP-DEC','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('IETF','IETF','IETF','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('IETF-style','IETF-style','IETF-style','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('ImageMagick','ImageMagick','ImageMagick','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('InfoSeek','InfoSeek','InfoSeek','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('IPTC','IPTC','IPTC','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('ISO-8879','ISO-8879','ISO-8879','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Java-Multi-Corp','Java-Multi-Corp','Java-Multi-Corp','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Java-WSDL-Policy','Java-WSDL-Policy','Java-WSDL-Policy','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Java-WSDL-Schema','Java-WSDL-Schema','Java-WSDL-Schema','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('JPEG','JPEG','JPEG','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('MS-IP','MS-IP','MS-IP','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('OSD','OSD','OSD','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('RedHat','RedHat','RedHat','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('RSA-Security','RSA-Security','RSA-Security','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun','Sun','Sun','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun-BCLA','Sun-BCLA','Sun-BCLA','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun-EULA','Sun-EULA','Sun-EULA','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun-IP','Sun-IP','Sun-IP','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun-Non-commercial','Sun-Non-commercial','Sun-Non-commercial','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun-Restricted','Sun-Restricted','Sun-Restricted','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun-TM','Sun-TM','Sun-TM','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Unicode','Unicode','Unicode','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Xerox','Xerox','Xerox','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Amazon','Amazon','Amazon','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('BigTribe-IP','BigTribe-IP','BigTribe-IP','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('BigTribe-IP-NoRedistribution','BigTribe-IP-NoRedistribution','BigTribe-IP-NoRedistribution','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('JSIP','JSIP','JSIP','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('JSON','JSON','JSON','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('OASIS','OASIS','OASIS','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('QuanticastTOS','QuanticastTOS','QuanticastTOS','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('USGovernmentRights','USGovernmentRights','USGovernmentRights','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('WebFX-Commercial','WebFX-Commercial','WebFX-Commercial','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('WebFX-NonCommercial','WebFX-NonCommercial','WebFX-NonCommercial','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('WernerRandelshofer','WernerRandelshofer','WernerRandelshofer','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('WS-Addressing-200403','WS-Addressing-200403','WS-Addressing-200403','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('WS-Addressing-200408','WS-Addressing-200408','WS-Addressing-200408','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('WS-I','WS-I','Web Services Interoperability','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CIP4-1.0','CIP4-1.0','CIP4 Software License, Version 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CIP4-2.0','CIP4-2.0','CIP4 Software License, Version 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CPOL-1.02','CPOL-1.02','Code Project Open License 1.02');
