INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('PHP-3.01','PHP-3.01','PHP License v3.01');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AAL','AAL','Attribution Assurance License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AFL-1.2','AFL-1.2','Academic Free License v1.2');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AFL-2.0','AFL-2.0','Academic Free License v2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AFL-2.1','AFL-2.1','Academic Free License v2.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AFL-3.0','AFL-3.0','Academic Free License v3.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AGPL-3.0','AGPL-3.0','GNU Affero General Public License v3');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ANTLR-PD','ANTLR-PD','ANTLR Software Rights Notice');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('APL-1.0','APL-1.0','Adaptive Public License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('APSL-1.0','APSL-1.0','Apple Public Source License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('APSL-1.1','APSL-1.1','Apple Public Source License 1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('APSL-1.2','APSL-1.2','Apple Public Source License 1.2');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('APSL-2.0','APSL-2.0','Apple Public Source License 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Apache-1.0','Apache-1.0','Apache License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Apache-1.1','Apache-1.1','Apache License 1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0','Apache-2.0','Apache License 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Artistic-1.0','Artistic-1.0','Artistic License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Artistic-2.0','Artistic-2.0','Artistic License 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('BSD-2-Clause','BSD-2-Clause','BSD 2-clause "Simplified" or "FreeBSD" License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('BSD-3-Clause','BSD-3-Clause','BSD 3-clause "New" or "Revised" License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('BSD-4-Clause','BSD-4-Clause','BSD 4-clause "Original" or "Old" License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('BSL-1.0','BSL-1.0','Boost Software License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CATOSL-1.1','CATOSL-1.1','Computer Associates Trusted Open Source License 1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-1.0','CC-BY-1.0','Creative Commons Attribution 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-2.0','CC-BY-2.0','Creative Commons Attribution 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-2.5','CC-BY-2.5','Creative Commons Attribution 2.5');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-3.0','CC-BY-3.0','Creative Commons Attribution 3.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-NC-1.0','CC-BY-NC-1.0','Creative Commons Attribution Non Commercial 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-NC-2.0','CC-BY-NC-2.0','Creative Commons Attribution Non Commercial 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-NC-2.5','CC-BY-NC-2.5','Creative Commons Attribution Non Commercial 2.5');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-NC-3.0','CC-BY-NC-3.0','Creative Commons Attribution Non Commercial 3.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-NC-ND-1.0','CC-BY-NC-ND-1.0','Creative Commons Attribution Non Commercial No Derivatives 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-NC-ND-2.0','CC-BY-NC-ND-2.0','Creative Commons Attribution Non Commercial No Derivatives 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-NC-ND-2.5','CC-BY-NC-ND-2.5','Creative Commons Attribution Non Commercial No Derivatives 2.5');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-NC-ND-3.0','CC-BY-NC-ND-3.0','Creative Commons Attribution Non Commercial No Derivatives 3.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-NC-SA-1.0','CC-BY-NC-SA-1.0','Creative Commons Attribution Non Commercial Share Alike 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-NC-SA-2.0','CC-BY-NC-SA-2.0','Creative Commons Attribution Non Commercial Share Alike 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-NC-SA-2.5','CC-BY-NC-SA-2.5','Creative Commons Attribution Non Commercial Share Alike 2.5');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-NC-SA-3.0','CC-BY-NC-SA-3.0','Creative Commons Attribution Non Commercial Share Alike 3.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-ND-1.0','CC-BY-ND-1.0','Creative Commons Attribution No Derivatives 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-ND-2.0','CC-BY-ND-2.0','Creative Commons Attribution No Derivatives 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-ND-2.5','CC-BY-ND-2.5','Creative Commons Attribution No Derivatives 2.5');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-ND-3.0','CC-BY-ND-3.0','Creative Commons Attribution No Derivatives 3.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-SA-1.0','CC-BY-SA-1.0','Creative Commons Attribution Share Alike 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-SA-2.0','CC-BY-SA-2.0','Creative Commons Attribution Share Alike 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-SA-2.5','CC-BY-SA-2.5','Creative Commons Attribution Share Alike 2.5');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-SA-3.0','CC-BY-SA-3.0','Creative Commons Attribution Share Alike 3.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC0-1.0','CC0-1.0','Creative Commons Zero v1.0 Universal');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-1.0','CDDL-1.0','Common Development and Distribution License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-1.1','CDDL-1.1','Common Development and Distribution License 1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CECILL-1.0','CECILL-1.0','CeCILL Free Software License Agreement v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CECILL-1.1','CECILL-1.1','CeCILL Free Software License Agreement v1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CECILL-2.0','CECILL-2.0','CeCILL Free Software License Agreement v2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CECILL-B','CECILL-B','CeCILL-B Free Software License Agreement');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CECILL-C','CECILL-C','CeCILL-C Free Software License Agreement');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ClArtistic','ClArtistic','Clarified Artistic License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CPAL-1.0','CPAL-1.0','Common Public Attribution License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CPL-1.0','CPL-1.0','Common Public License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CUA-OPL-1.0','CUA-OPL-1.0','CUA Office Public License v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ECL-1.0','ECL-1.0','Educational Community License v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ECL-2.0','ECL-2.0','Educational Community License v2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('EFL-1.0','EFL-1.0','Eiffel Forum License v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('EFL-2.0','EFL-2.0','Eiffel Forum License v2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Entessa','Entessa','Entessa Public License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0','EPL-1.0','Eclipse Public License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ErlPL-1.1','ErlPL-1.1','Erlang Public License v1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('EUDatagrid','EUDatagrid','EU DataGrid Software License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('EUPL-1.0','EUPL-1.0','European Union Public License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('EUPL-1.1','EUPL-1.1','European Union Public License 1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('eCos-2.0','eCos-2.0','eCos license version 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Fair','Fair','Fair License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Frameworx-1.0','Frameworx-1.0','Frameworx Open License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GFDL-1.1','GFDL-1.1','GNU Free Documentation License v1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GFDL-1.2','GFDL-1.2','GNU Free Documentation License v1.2');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GFDL-1.3','GFDL-1.3','GNU Free Documentation License v1.3');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-1.0','GPL-1.0','GNU General Public License v1.0 only');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0','GPL-2.0','GNU General Public License v2.0 only');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-with-autoconf-exception','GPL-2.0-with-autoconf-exception','GNU General Public License v2.0 w/Autoconf exception');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-with-bison-exception','GPL-2.0-with-bison-exception','GNU General Public License v2.0 w/Bison exception');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-with-classpath-exception','GPL-2.0-with-classpath-exception','GNU General Public License v2.0 w/Classpath exception');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-with-font-exception','GPL-2.0-with-font-exception','GNU General Public License v2.0 w/Font exception');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-with-GCC-exception','GPL-2.0-with-GCC-exception','GNU General Public License v2.0 w/GCC Runtime Library exception');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-3.0','GPL-3.0','GNU General Public License v3.0 only');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-3.0-with-autoconf-exception','GPL-3.0-with-autoconf-exception','GNU General Public License v3.0 w/Autoconf exception');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-3.0-with-GCC-exception','GPL-3.0-with-GCC-exception','GNU General Public License v3.0 w/GCC Runtime Library exception');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('gSOAP-1.3b','gSOAP-1.3b','gSOAP Public License v1.b');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('HPND','HPND','Historic Permission Notice and Disclaimer');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('IPA','IPA','IPA Font License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('IPL-1.0','IPL-1.0','IBM Public License v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ISC','ISC','ISC License (Bind, DHCP Server)');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-2.0','LGPL-2.0','GNU Library General Public License v2 only');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-2.1','LGPL-2.1','GNU Lesser General Public License v2.1 only');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-3.0','LGPL-3.0','GNU Lesser General Public License v3.0 only');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Libpng','Libpng','libpng License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('LPL-1.02','LPL-1.02','Lucent Public License v1.02 (Plan9)');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('LPPL-1.0','LPPL-1.0','LaTeX Project Public License v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('LPPL-1.1','LPPL-1.1','LaTeX Project Public License v1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('LPPL-1.2','LPPL-1.2','LaTeX Project Public License v1.2');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('LPPL-1.3c','LPPL-1.3c','LaTeX Project Public License v1.3c');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MIT','MIT','MIT license (also X11)');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MirOS','MirOS','MirOS Licence');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Motosoto','Motosoto','Motosoto License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MPL-1.0','MPL-1.0','Mozilla Public License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MPL-1.1','MPL-1.1','Mozilla Public License 1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MPL-2.0','MPL-2.0','Mozilla Public License 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-PL','MS-PL','Microsoft Public License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-RL','MS-RL','Microsoft Reciprocal License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Multics','Multics','Multics License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('NASA-1.3','NASA-1.3','NASA Open Source Agreement 1.3');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Naumen','Naumen','Naumen Public License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('NCSA','NCSA','University of Illinois/NCSA Open Source License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('NGPL','NGPL','Nethack General Public License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Nokia','Nokia','Nokia Open Source License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('NPL-1.0','NPL-1.0','Netscape Public License v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('NPL-1.1','NPL-1.1','Netscape Public License v1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('NPOSL-3.0','NPOSL-3.0','Non-Profit Open Software License 3.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('NTP','NTP','NTP License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OCLC-2.0','OCLC-2.0','OCLC Research Public License 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ODbL-1.0','ODbL-1.0','ODC Open Database License v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OFL-1.1','OFL-1.1','SIL Open Font License 1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OGTSL','OGTSL','Open Group Test Suite License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OLDAP-2.8','OLDAP-2.8','OpenLDAP Public License v2.8');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OpenSSL','OpenSSL','OpenSSL License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OSL-1.0','OSL-1.0','Open Software License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OSL-2.0','OSL-2.0','Open Software License 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OSL-2.1','OSL-2.1','Open Software License 2.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OSL-3.0','OSL-3.0','Open Software License 3.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('PDDL-1.0','PDDL-1.0','ODC Public Domain Dedication & License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('PostgreSQL','PostgreSQL','PostgreSQL License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Python-2.0','Python-2.0','Python License 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('QPL-1.0','QPL-1.0','Q Public License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('RHeCos-1.1','RHeCos-1.1','Red Hat eCos Public License v1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('RPL-1.1','RPL-1.1','Reciprocal Public License 1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('RPL-1.5','RPL-1.5','Reciprocal Public License 1.5');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('RPSL-1.0','RPSL-1.0','RealNetworks Public Source License v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('RSCPL','RSCPL','Ricoh Source Code Public License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Ruby','Ruby','Ruby License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('SAX-PD','SAX-PD','Sax Public Domain Notice');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('SimPL-2.0','SimPL-2.0','Simple Public License 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sleepycat','Sleepycat','Sleepycat License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('SPL-1.0','SPL-1.0','Sun Public License v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('SugarCRM-1.1.3','SugarCRM-1.1.3','SugarCRM Public License v1.1.3');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('VSL-1.0','VSL-1.0','Vovida Software License v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('W3C','W3C','W3C Software and Notice License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Watcom-1.0','Watcom-1.0','Sybase Open Watcom Public License 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WXwindows','WXwindows','wxWindows Library License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('XFree86-1.1','XFree86-1.1','XFree86 License 1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Xnet','Xnet','X.Net License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('YPL-1.1','YPL-1.1','Yahoo! Public License v1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Zimbra-1.3','Zimbra-1.3','Zimbra Publice License v1.3');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Zlib','Zlib','zlib License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ZPL-1.1','ZPL-1.1','Zope Public License 1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ZPL-2.0','ZPL-2.0','Zope Public License 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ZPL-2.1','ZPL-2.1','Zope Public License 2.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AGPL-1.0','AGPL-1.0','Affero General Public License v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('SMLNJ','SMLNJ','Standard ML of New Jersey License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WTFPL','WTFPL','Do What The F*ck You Want To Public License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-4.0','CC-BY-4.0','Creative Commons Attribution 4.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-SA-4.0','CC-BY-SA-4.0','Creative Commons Attribution Share Alike 4.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OPL-1.0','OPL-1.0','Open Public License v1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('SISSL-1.1','SISSL-1.1','Sun Industry Standards Source License v1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('SISSL-1.2','SISSL-1.2','Sun Industry Standards Source License v1.2');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('X11','X11','X11 License');
