INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Adobe', 'Adobe', 'Adobe');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Adobe-AFM', 'Adobe-AFM', 'Adobe-AFM');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Adobe-EULA', 'Adobe-EULA', 'Adobe-EULA');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ATT', 'ATT', 'ATT');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Beerware', 'Beerware', 'Beerware');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Dyade', 'Dyade', 'Dyade');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('HP-DEC', 'HP-DEC', 'HP-DEC');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('IETF', 'IETF', 'IETF');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('IETF-style', 'IETF-style', 'IETF-style');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ImageMagick', 'ImageMagick', 'ImageMagick');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('InfoSeek', 'InfoSeek', 'InfoSeek');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('IPTC', 'IPTC', 'IPTC');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ISO-8879', 'ISO-8879', 'ISO-8879');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Java-Multi-Corp', 'Java-Multi-Corp', 'Java-Multi-Corp');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Java-WSDL-Policy', 'Java-WSDL-Policy', 'Java-WSDL-Policy');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Java-WSDL-Schema', 'Java-WSDL-Schema', 'Java-WSDL-Schema');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('JPEG', 'JPEG', 'JPEG');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-IP', 'MS-IP', 'MS-IP');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OSD', 'OSD', 'OSD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('RedHat', 'RedHat', 'RedHat');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('RSA-Security', 'RSA-Security', 'RSA-Security');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun', 'Sun', 'Sun');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun-BCLA', 'Sun-BCLA', 'Sun-BCLA');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun-EULA', 'Sun-EULA', 'Sun-EULA');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun-IP', 'Sun-IP', 'Sun-IP');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun-Non-commercial', 'Sun-Non-commercial', 'Sun-Non-commercial');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun-Restricted', 'Sun-Restricted', 'Sun-Restricted');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun-TM', 'Sun-TM', 'Sun-TM');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Unicode', 'Unicode', 'Unicode');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Xerox', 'Xerox', 'Xerox');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Amazon', 'Amazon', 'Amazon');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('BigTribe-IP', 'BigTribe-IP', 'BigTribe-IP');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('BigTribe-IP-NoRedistribution', 'BigTribe-IP-NoRedistribution', 'BigTribe-IP-NoRedistribution');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('JSIP', 'JSIP', 'JSIP');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('JSON', 'JSON', 'JSON');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OASIS', 'OASIS', 'OASIS');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('QuanticastTOS', 'QuanticastTOS', 'QuanticastTOS');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('USGovernmentRights', 'USGovernmentRights', 'USGovernmentRights');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WebFX-Commercial', 'WebFX-Commercial', 'WebFX-Commercial');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WebFX-NonCommercial', 'WebFX-NonCommercial', 'WebFX-NonCommercial');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WernerRandelshofer', 'WernerRandelshofer', 'WernerRandelshofer');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WS-Addressing-200403', 'WS-Addressing-200403', 'WS-Addressing-200403');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WS-Addressing-200408', 'WS-Addressing-200408', 'WS-Addressing-200408');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WS-I', 'WS-I', 'Web Services Interoperability');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CIP4-1.0', 'CIP4-1.0', 'CIP4 Software License, Version 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CIP4-2.0', 'CIP4-2.0', 'CIP4 Software License, Version 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CPOL-1.02', 'CPOL-1.02', 'Code Project Open License 1.02');
