INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('UNKNOWN','Non-Standard','Raw License String Could Not Be Mapped to a Standardized SPDX License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('UNSPECIFIED','Not Provided','No License Information was Provided');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED','BSD','BSD-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Apache-UNSPECIFIED','Apache','Apache-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED','GPL','GPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED-with-classpath-exception','GPL-with-classpath-exception','GPL-Style License Not Identifiable by Sonatype w/Classpath exception');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-3.0-with-classpath-exception','GPL-3.0-with-classpath-exception','GNU General Public License v3.0 w/Classpath exception');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-UNSPECIFIED','LGPL','LGPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AFL-UNSPECIFIED','AFL','AFL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AGPL-UNSPECIFIED','AGPL','AGPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Artistic-UNSPECIFIED','Artistic','Artistic-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-SA-UNSPECIFIED','CC-BY-SA','CC-BY-SA-Style License Not Identifiable by Sonatyp');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-UNSPECIFIED','CC-BY','CC-BY-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-UNSPECIFIED','CDDL','CDDL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ECL-UNSPECIFIED','ECL','ECL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('EPL-UNSPECIFIED','EPL','EPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GFDL-UNSPECIFIED','GFDL','GFDL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MPL-UNSPECIFIED','MPL','MPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('PHP-UNSPECIFIED','PHP','PHP-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Python-UNSPECIFIED','Python','Python-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ZPL-UNSPECIFIED','ZPL','ZPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OSL-UNSPECIFIED','OSL','OSL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CECILL-UNSPECIFIED','CECILL','CeCILL Free Software Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('COMMERCIAL','COMMERCIAL','Commercial Software License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('PUBLIC-DOMAIN','Public Domain','The work has been placed in the public domain');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('No-Source-License','No Source License','No licenses found in sources');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('No-Sources','No Sources','No sources provided with component');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Not-Declared','Not Declared','No licenses declared in component descriptor');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Not-Supported','Not Supported','Observed license recognition for component repository not supported by data pipeline');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('DOCBOOK','DocBook','DocBook Software License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('InitialDevelopersPL-1.0','InitialDevelopersPL-1.0','Initial Developer''s Public License Version 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('InterbasePL-1.0','InterbasePL-1.0','InterBase Public License Version 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('JA-SIG-Collaborative','JA-SIG-Collaborative','The JA-SIG Collaborative License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Spice-1.1','Spice-1.1','Spice Software License Version 1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Web-Pages-2','MS-ASP.NET-Web-Pages-2','Microsoft ASP.NET Web Pages 2');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Web-Pages-2-Pre-Release','MS-ASP.NET-Web-Pages-2-Pre-Release','Microsoft ASP.NET Web Pages 2 - Pre-Release');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-MSN-WEBGREASE','MS-MSN-WEBGREASE','Microsoft MSN WebGrease');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-.NET-Library','MS-.NET-Library','Microsoft .NET Library');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-.NET-Library-JS','MS-.NET-Library-JS','Microsoft .NET Library JS');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-MVC-4','MS-ASP.NET-MVC-4','Microsoft ASP.NET Model View Controller 4');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-MVC-4-Pre-Release','MS-ASP.NET-MVC-4-Pre-Release','Microsoft ASP.NET Model View Controller 4 Pre-Release');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-MVC-4-Extensions-Pre-Release','MS-ASP.NET-MVC-4-Extensions-Pre-Release','Microsoft ASP.NET Model View Controller 4 Extensions Pre-Release');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-WOF','MS-ASP.NET-WOF','Microsoft ASP.NET Web Optimization Framework');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-WOF-Pre-Release','MS-ASP.NET-WOF-Pre-Release','Microsoft ASP.NET Web Optimization Framework Pre-Release');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Tools','MS-ASP.NET-Tools','Microsoft ASP.NET Tools');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Universal-Providers','MS-ASP.NET-Universal-Providers','Microsoft ASP.NET Universal Providers');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ServiceStack-License-Agreement','ServiceStack-License-Agreement','ServiceStack License Agreement');
