INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('UNKNOWN','Non-Standard','Raw License String Could Not Be Mapped to a Standardized SPDX License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('UNSPECIFIED','Not Provided','No License Information was Provided');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED','BSD','BSD-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Apache-UNSPECIFIED','Apache','Apache-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED','GPL','GPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-3.0-with-classpath-exception','GPL-3.0-with-classpath-exception','GNU General Public License v3.0 w/Classpath exception');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-UNSPECIFIED','LGPL','LGPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AFL-UNSPECIFIED','AFL','AFL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AGPL-UNSPECIFIED','AGPL','AGPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Artistic-UNSPECIFIED','Artistic','AGPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-SA-UNSPECIFIED','CC-BY-SA','CC-BY-SA-Style License Not Identifiable by Sonatyp');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-UNSPECIFIED','CC-BY','CC-BY-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-UNSPECIFIED','CDDL','CDDL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ECL-UNSPECIFIED','ECL','ECL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('EPL-UNSPECIFIED','EPL','EPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GFDL-UNSPECIFIED','GFDL','GFDL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MPL-UNSPECIFIED','MPL','MPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('PHP-UNSPECIFIED','PHP','PHP-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Python-UNSPECIFIED','Python','Python-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ZPL-UNSPECIFIED','ZPL','ZPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OSL-UNSPECIFIED','OSL','OSL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CECILL-UNSPECIFIED','CECILL','CeCILL Free Software Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('COMMERCIAL','COMMERCIAL','Commercial Software License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('PUBLIC-DOMAIN','Public Domain','The work has been placed in the public domain');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('No-Source-License','No Source License','No licenses found in sources');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('No-Sources','No Sources','No sources provided with component');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Not-Declared','Not Declared','No licenses declared in component descriptor');