INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('UNKNOWN', 'Non-Standard', 'Raw License String Could Not Be Mapped to a Standardized SPDX License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('UNSPECIFIED', 'Not Provided', 'No License Information was Provided');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED', 'BSD', 'BSD-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Apache-UNSPECIFIED', 'Apache', 'Apache-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED', 'GPL', 'GPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED-with-classpath-exception', 'GPL-with-classpath-exception', 'GPL-Style License Not Identifiable by Sonatype w/Classpath exception');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GPL-3.0-with-classpath-exception', 'GPL-3.0-with-classpath-exception', 'GNU General Public License v3.0 w/Classpath exception');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-UNSPECIFIED', 'LGPL', 'LGPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AFL-UNSPECIFIED', 'AFL', 'AFL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('AGPL-UNSPECIFIED', 'AGPL', 'AGPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Artistic-UNSPECIFIED', 'Artistic', 'Artistic-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-SA-UNSPECIFIED', 'CC-BY-SA', 'CC-BY-SA-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-UNSPECIFIED', 'CC-BY', 'CC-BY-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-UNSPECIFIED', 'CDDL', 'CDDL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ECL-UNSPECIFIED', 'ECL', 'ECL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('EPL-UNSPECIFIED', 'EPL', 'EPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('GFDL-UNSPECIFIED', 'GFDL', 'GFDL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MPL-UNSPECIFIED', 'MPL', 'MPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('PHP-UNSPECIFIED', 'PHP', 'PHP-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Python-UNSPECIFIED', 'Python', 'Python-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ZPL-UNSPECIFIED', 'ZPL', 'ZPL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OSL-UNSPECIFIED', 'OSL', 'OSL-Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CECILL-UNSPECIFIED', 'CECILL', 'CeCILL Free Software Style License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('COMMERCIAL', 'COMMERCIAL', 'Commercial Software License Not Identifiable by Sonatype');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('PUBLIC-DOMAIN', 'Public Domain', 'The work has been placed in the public domain');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('No-Source-License', 'No Source License', 'No licenses found in sources');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('No-Sources', 'No Sources', 'No sources provided with component');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Not-Declared', 'Not Declared', 'No licenses declared in component descriptor');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Not-Supported', 'Not Supported', 'Observed license recognition for component repository not supported by data pipeline');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('DOCBOOK', 'DocBook', 'DocBook Software License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('InitialDevelopersPL-1.0', 'InitialDevelopersPL-1.0', 'Initial Developer''s Public License Version 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('InterbasePL-1.0', 'InterbasePL-1.0', 'InterBase Public License Version 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('JA-SIG-Collaborative', 'JA-SIG-Collaborative', 'The JA-SIG Collaborative License');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Spice-1.1', 'Spice-1.1', 'Spice Software License Version 1.1');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Web-Pages-2', 'MS-ASP.NET-Web-Pages-2', 'Microsoft ASP.NET Web Pages 2');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Web-Pages-2-Pre-Release', 'MS-ASP.NET-Web-Pages-2-Pre-Release', 'Microsoft ASP.NET Web Pages 2 - Pre-Release');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-MSN-WEBGREASE', 'MS-MSN-WEBGREASE', 'Microsoft MSN WebGrease');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-.NET-Library', 'MS-.NET-Library', 'Microsoft .NET Library');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-.NET-Library-JS', 'MS-.NET-Library-JS', 'Microsoft .NET Library JS');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-MVC-4', 'MS-ASP.NET-MVC-4', 'Microsoft ASP.NET Model View Controller 4');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-MVC-4-Pre-Release', 'MS-ASP.NET-MVC-4-Pre-Release', 'Microsoft ASP.NET Model View Controller 4 Pre-Release');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-MVC-4-Extensions-Pre-Release', 'MS-ASP.NET-MVC-4-Extensions-Pre-Release', 'Microsoft ASP.NET Model View Controller 4 Extensions Pre-Release');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-WOF', 'MS-ASP.NET-WOF', 'Microsoft ASP.NET Web Optimization Framework');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-WOF-Pre-Release', 'MS-ASP.NET-WOF-Pre-Release', 'Microsoft ASP.NET Web Optimization Framework Pre-Release');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Tools', 'MS-ASP.NET-Tools', 'Microsoft ASP.NET Tools');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Universal-Providers', 'MS-ASP.NET-Universal-Providers', 'Microsoft ASP.NET Universal Providers');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ServiceStack-License-Agreement', 'ServiceStack-License-Agreement', 'ServiceStack License Agreement');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Android-SDK', 'Android-SDK', 'Android Software Development Kit License Agreement');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-MVC-4-Beta', 'MS-ASP.NET-MVC-4-Beta', 'Microsoft ASP.NET Model View Controller 4 Beta');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-SignalR-Client-Libraries', 'MS-ASP.NET-SignalR-Client-Libraries', 'Microsoft ASP.NET SignalR - Client Libraries');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-MVC-3-Tools-Update', 'MS-ASP.NET-MVC-3-Tools-Update', 'Microsoft ASP.NET Model View Controller 3 ToolsUpdate');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-RxJS-.NET-Libraries', 'MS-RxJS-.NET-Libraries', 'Microsoft Reactive Extensions for JavaScript and .NET Libraries');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-Roslyn-CTP-EULA', 'MS-Roslyn-CTP-EULA', 'Microsoft \"Roslyn\" CTP EULA');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-.NET-Compiler-Platform-Redist-Preview', 'MS-.NET-Compiler-Platform-Redist-Preview', 'Microsoft .NET Compiler Platform Redistributable Packages Preview');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ADAL', 'MS-ADAL', 'Microsoft Active Directory Authentication Library (ADAL)');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Web-Pages', 'MS-ASP.NET-Web-Pages', 'Microsoft ASP.NET Web Pages');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CuteSoft.net', 'CuteSoft.net', 'CuteSoft.net');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CodeSmith-Generator', 'CodeSmith-Generator', 'CodeSmith Generator License Agreement');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Adobe', 'Adobe', 'Adobe');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Adobe-AFM', 'Adobe-AFM', 'Adobe-AFM');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Adobe-EULA', 'Adobe-EULA', 'Adobe-EULA');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ATT', 'ATT', 'ATT');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Beerware', 'Beerware', 'Beerware');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Dyade', 'Dyade', 'Dyade');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('HP-DEC', 'HP-DEC', 'HP-DEC');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('IETF', 'IETF', 'IETF');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('IETF-style', 'IETF-style', 'IETF-style');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ImageMagick', 'ImageMagick', 'ImageMagick');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('InfoSeek', 'InfoSeek', 'InfoSeek');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('IPTC', 'IPTC', 'IPTC');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('ISO-8879', 'ISO-8879', 'ISO-8879');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Java-Multi-Corp', 'Java-Multi-Corp', 'Java-Multi-Corp');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Java-WSDL-Policy', 'Java-WSDL-Policy', 'Java-WSDL-Policy');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Java-WSDL-Schema', 'Java-WSDL-Schema', 'Java-WSDL-Schema');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('JPEG', 'JPEG', 'JPEG');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('MS-IP', 'MS-IP', 'MS-IP');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OSD', 'OSD', 'OSD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('RedHat', 'RedHat', 'RedHat');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('RSA-Security', 'RSA-Security', 'RSA-Security');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun', 'Sun', 'Sun');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun-BCLA', 'Sun-BCLA', 'Sun-BCLA');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun-EULA', 'Sun-EULA', 'Sun-EULA');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun-IP', 'Sun-IP', 'Sun-IP');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun-Non-commercial', 'Sun-Non-commercial', 'Sun-Non-commercial');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun-Restricted', 'Sun-Restricted', 'Sun-Restricted');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Sun-TM', 'Sun-TM', 'Sun-TM');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Unicode', 'Unicode', 'Unicode');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Xerox', 'Xerox', 'Xerox');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Amazon', 'Amazon', 'Amazon');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('BigTribe-IP', 'BigTribe-IP', 'BigTribe-IP');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('BigTribe-IP-NoRedistribution', 'BigTribe-IP-NoRedistribution', 'BigTribe-IP-NoRedistribution');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('JSIP', 'JSIP', 'JSIP');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('JSON', 'JSON', 'JSON');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('OASIS', 'OASIS', 'OASIS');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('QuanticastTOS', 'QuanticastTOS', 'QuanticastTOS');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('USGovernmentRights', 'USGovernmentRights', 'USGovernmentRights');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WebFX-Commercial', 'WebFX-Commercial', 'WebFX-Commercial');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WebFX-NonCommercial', 'WebFX-NonCommercial', 'WebFX-NonCommercial');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WernerRandelshofer', 'WernerRandelshofer', 'WernerRandelshofer');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WS-Addressing-200403', 'WS-Addressing-200403', 'WS-Addressing-200403');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WS-Addressing-200408', 'WS-Addressing-200408', 'WS-Addressing-200408');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('WS-I', 'WS-I', 'Web Services Interoperability');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CIP4-1.0', 'CIP4-1.0', 'CIP4 Software License, Version 1.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CIP4-2.0', 'CIP4-2.0', 'CIP4 Software License, Version 2.0');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('CPOL-1.02', 'CPOL-1.02', 'Code Project Open License 1.02');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Telerik-UI-for-FiddlerCore-Embedded-Engine', 'Telerik-UI-for-FiddlerCore-Embedded-Engine', 'Telerik End User License Agreement for FiddlerCore Embedded Engine');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Telerik-UI-for-ASP.NET-MVC', 'Telerik-UI-for-ASP.NET-MVC', 'End User License Agreement for Progress Telerik UI for ASP.NET MVC');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Telerik-JustMock-Free-Edition', 'Telerik-JustMock-Free-Edition', 'Progress Telerik JustMock Free Edition');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Oracle-OTN-Distribution', 'Oracle-OTN-Distribution', 'Oracle Technology Network License Agreement Distribution');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Oracle-OTN', 'Oracle-OTN', 'Oracle Technology Network License Agreement');
INSERT INTO license (license_id, shortDisplayName, longDisplayName) VALUES ('Rebex-EULA-1.4', 'Rebex-EULA-1.4', 'Rebex General End User License 1.4');
