INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('PHP-3.01','PHP-3.01');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('AAL','AAL');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('AFL-1.2','AFL-1.2');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('AFL-2.0','AFL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('AFL-2.1','AFL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('AFL-3.0','AFL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('AGPL-3.0','AGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ANTLR-PD','ANTLR-PD');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('APL-1.0','APL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('APSL-1.0','APSL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('APSL-1.1','APSL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('APSL-1.2','APSL-1.2');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('APSL-2.0','APSL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-1.0','Apache-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-1.1','Apache-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0','Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Artistic-1.0','Artistic-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Artistic-2.0','Artistic-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-2-Clause','BSD-2-Clause');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-3-Clause','BSD-3-Clause');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-4-Clause','BSD-4-Clause');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSL-1.0','BSL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CATOSL-1.1','CATOSL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-1.0','CC-BY-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-2.0','CC-BY-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-2.5','CC-BY-2.5');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-3.0','CC-BY-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-NC-1.0','CC-BY-NC-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-NC-2.0','CC-BY-NC-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-NC-2.5','CC-BY-NC-2.5');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-NC-3.0','CC-BY-NC-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-NC-ND-1.0','CC-BY-NC-ND-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-NC-ND-2.0','CC-BY-NC-ND-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-NC-ND-2.5','CC-BY-NC-ND-2.5');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-NC-ND-3.0','CC-BY-NC-ND-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-NC-SA-1.0','CC-BY-NC-SA-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-NC-SA-2.0','CC-BY-NC-SA-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-NC-SA-2.5','CC-BY-NC-SA-2.5');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-NC-SA-3.0','CC-BY-NC-SA-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-ND-1.0','CC-BY-ND-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-ND-2.0','CC-BY-ND-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-ND-2.5','CC-BY-ND-2.5');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-ND-3.0','CC-BY-ND-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-SA-1.0','CC-BY-SA-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-SA-2.0','CC-BY-SA-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-SA-2.5','CC-BY-SA-2.5');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-SA-3.0','CC-BY-SA-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC0-1.0','CC0-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-1.0','CDDL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-1.1','CDDL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CECILL-1.0','CECILL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CECILL-1.1','CECILL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CECILL-2.0','CECILL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CECILL-B','CECILL-B');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CECILL-C','CECILL-C');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ClArtistic','ClArtistic');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CPAL-1.0','CPAL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CPL-1.0','CPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CUA-OPL-1.0','CUA-OPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ECL-1.0','ECL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ECL-2.0','ECL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EFL-1.0','EFL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EFL-2.0','EFL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Entessa','Entessa');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0','EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ErlPL-1.1','ErlPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EUDatagrid','EUDatagrid');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EUPL-1.0','EUPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EUPL-1.1','EUPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('eCos-2.0','eCos-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Fair','Fair');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Frameworx-1.0','Frameworx-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GFDL-1.1','GFDL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GFDL-1.2','GFDL-1.2');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GFDL-1.3','GFDL-1.3');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-1.0','GPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-1.0+','GPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-1.0+','GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-1.0+','GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0','GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+','GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+','GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-with-autoconf-exception','GPL-2.0-with-autoconf-exception');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-with-bison-exception','GPL-2.0-with-bison-exception');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-with-classpath-exception','GPL-2.0-with-classpath-exception');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-with-font-exception','GPL-2.0-with-font-exception');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-with-GCC-exception','GPL-2.0-with-GCC-exception');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-3.0','GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-3.0+','GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-3.0-with-autoconf-exception','GPL-3.0-with-autoconf-exception');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-3.0-with-GCC-exception','GPL-3.0-with-GCC-exception');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('gSOAP-1.3b','gSOAP-1.3b');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('HPND','HPND');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('IPA','IPA');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('IPL-1.0','IPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ISC','ISC');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.0','LGPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.0+','LGPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.0+','LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.0+','LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.1','LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.1+','LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.1+','LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-3.0','LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-3.0+','LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Libpng','Libpng');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LPL-1.02','LPL-1.02');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LPPL-1.0','LPPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LPPL-1.1','LPPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LPPL-1.2','LPPL-1.2');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LPPL-1.3c','LPPL-1.3c');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('MIT','MIT');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('MirOS','MirOS');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Motosoto','Motosoto');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('MPL-1.0','MPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('MPL-1.1','MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('MPL-2.0','MPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('MS-PL','MS-PL');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('MS-RL','MS-RL');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Multics','Multics');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('NASA-1.3','NASA-1.3');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Naumen','Naumen');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('NCSA','NCSA');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('NGPL','NGPL');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Nokia','Nokia');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('NPL-1.0','NPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('NPL-1.1','NPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('NPOSL-3.0','NPOSL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('NTP','NTP');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('OCLC-2.0','OCLC-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ODbL-1.0','ODbL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('OFL-1.1','OFL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('OGTSL','OGTSL');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('OLDAP-2.8','OLDAP-2.8');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('OpenSSL','OpenSSL');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('OSL-1.0','OSL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('OSL-2.0','OSL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('OSL-2.1','OSL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('OSL-3.0','OSL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('PDDL-1.0','PDDL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('PostgreSQL','PostgreSQL');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Python-2.0','Python-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('QPL-1.0','QPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('RHeCos-1.1','RHeCos-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('RPL-1.5','RPL-1.5');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('RPSL-1.0','RPSL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('RSCPL','RSCPL');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Ruby','Ruby');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('SAX-PD','SAX-PD');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('SimPL-2.0','SimPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Sleepycat','Sleepycat');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('SPL-1.0','SPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('SugarCRM-1.1.3','SugarCRM-1.1.3');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('VSL-1.0','VSL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('W3C','W3C');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Watcom-1.0','Watcom-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('WXwindows','WXwindows');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('XFree86-1.1','XFree86-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Xnet','Xnet');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('YPL-1.1','YPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Zimbra-1.3','Zimbra-1.3');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Zlib','Zlib');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ZPL-1.1','ZPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ZPL-2.0','ZPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ZPL-2.1','ZPL-2.1');

INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('UNKNOWN','UNKNOWN');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('UNSPECIFIED','UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED','BSD-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0+','Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-UNSPECIFIED','Apache-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-UNSPECIFIED','GPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-3.0-with-classpath-exception','GPL-3.0-with-classpath-exception');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-UNSPECIFIED','LGPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('AFL-UNSPECIFIED','AFL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('AGPL-3.0+','AGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('AGPL-UNSPECIFIED','AGPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Artistic-UNSPECIFIED','Artistic-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-SA-UNSPECIFIED','CC-BY-SA-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CC-BY-UNSPECIFIED','CC-BY-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-UNSPECIFIED','CDDL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ECL-UNSPECIFIED','ECL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0+','EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GFDL-1.2+','GFDL-1.2');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GFDL-1.2+','GFDL-1.3');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GFDL-UNSPECIFIED','GFDL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('MPL-1.1+','MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('MPL-1.1+','MPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('MPL-UNSPECIFIED','MPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('PHP-UNSPECIFIED','PHP-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Python-UNSPECIFIED','Python-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ZPL-UNSPECIFIED','ZPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('OSL-UNSPECIFIED','OSL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CECILL-UNSPECIFIED','CECILL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('COMMERCIAL','COMMERCIAL');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-1.0-GPL-2.0','CDDL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-1.0-GPL-2.0','GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-1.1-GPL-2.0','CDDL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-1.1-GPL-2.0','GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-1.0-GPL-2.0-CPE','CDDL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-1.0-GPL-2.0-CPE','GPL-2.0-with-classpath-exception');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-1.1-GPL-2.0-CPE','CDDL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-1.1-GPL-2.0-CPE','GPL-2.0-with-classpath-exception');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('JRUBY-CPL-GPL-LGPL','CPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('JRUBY-CPL-GPL-LGPL','GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('JRUBY-CPL-GPL-LGPL','GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('JRUBY-CPL-GPL-LGPL','LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('JRUBY-CPL-GPL-LGPL','LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('PUBLIC-DOMAIN','PUBLIC-DOMAIN');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-EPL-1.0', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-EPL-1.0', 'EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-GPL-UNSPECIFIED', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-GPL-UNSPECIFIED', 'GPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-GPL-2.0', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-GPL-2.0', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-GPL-2.0+', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-GPL-2.0+', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-GPL-2.0+', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-GPL-3.0', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-GPL-3.0', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-GPL-3.0+', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-GPL-3.0+', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.1+-MPL-1.1', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.1+-MPL-1.1', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.1+-MPL-1.1', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.1+-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-UNSPECIFIED', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-UNSPECIFIED', 'LGPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.0', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.0', 'LGPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.0+', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.0+', 'LGPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.0+', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.0+', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.1', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.1', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.1+', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.1+', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-2.1+', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-3.0', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-3.0', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-3.0+', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0-LGPL-3.0+', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0+-GPL-2.0+-LGPL-2.1+', 'Apache-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0+-GPL-2.0+-LGPL-2.1+', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0+-GPL-2.0+-LGPL-2.1+', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0+-GPL-2.0+-LGPL-2.1+', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Apache-2.0+-GPL-2.0+-LGPL-2.1+', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-UNSPECIFIED', 'BSD-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-UNSPECIFIED', 'GPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-2.0', 'BSD-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-2.0', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-2.0+', 'BSD-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-2.0+', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-2.0+', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-3.0', 'BSD-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-3.0', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-3.0+', 'BSD-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-3.0+', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-UNSPECIFIED-MIT', 'BSD-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-UNSPECIFIED-MIT', 'GPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-GPL-UNSPECIFIED-MIT', 'MIT');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-EPL-1.0', 'BSD-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-UNSPECIFIED-EPL-1.0', 'EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-3-Clause-EPL-1.0', 'BSD-3-Clause');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('BSD-3-Clause-EPL-1.0', 'EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-GPL-2.0-with-classpath-exception', 'CDDL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CDDL-GPL-2.0-with-classpath-exception', 'GPL-2.0-with-classpath-exception');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CPL-1.0-GPL-2.0+-LGPL-2.1+', 'CPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CPL-1.0-GPL-2.0+-LGPL-2.1+', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CPL-1.0-GPL-2.0+-LGPL-2.1+', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CPL-1.0-GPL-2.0+-LGPL-2.1+', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('CPL-1.0-GPL-2.0+-LGPL-2.1+', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-UNSPECIFIED', 'EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-UNSPECIFIED', 'LGPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-2.0', 'EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-2.0', 'LGPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-2.0+', 'EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-2.0+', 'LGPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-2.0+', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-2.0+', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-2.1', 'EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-2.1', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-2.1+', 'EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-2.1+', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-2.1+', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-3.0', 'EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-3.0', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-3.0+', 'EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-3.0+', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-3.0+-MPL-1.1', 'EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-3.0+-MPL-1.1', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-LGPL-3.0+-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-MPL-1.1', 'EPL-1.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('EPL-1.0-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-UNSPECIFIED-MIT', 'GPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-UNSPECIFIED-MIT', 'MIT');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-MIT', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-MIT', 'MIT');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-UNSPECIFIED-MPL-1.1', 'GPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-UNSPECIFIED-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-MPL-1.1', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-MPL-1.1', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-MPL-1.1', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-3.0-MPL-1.1', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-3.0-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-3.0+-MPL-1.1', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-3.0+-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-LGPL-2.1', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-LGPL-2.1', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-LGPL-2.1-MPL-1.1', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-LGPL-2.1-MPL-1.1', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0-LGPL-2.1-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1+', 'GPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1+', 'GPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1+', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1+', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1+', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1+', 'MPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-UNSPECIFIED-MPL-1.1', 'LGPL-UNSPECIFIED');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-UNSPECIFIED-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.0-MPL-1.1', 'LGPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.0-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.0+-MPL-1.1', 'LGPL-2.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.0+-MPL-1.1', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.0+-MPL-1.1', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.0+-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.1-MPL-1.1', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.1-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.1+-MPL-1.1', 'LGPL-2.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.1+-MPL-1.1', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-2.1+-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-3.0-MPL-1.1', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-3.0-MPL-1.1', 'MPL-1.1');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-3.0+-MPL-1.1', 'LGPL-3.0');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('LGPL-3.0+-MPL-1.1', 'MPL-1.1');
