INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('UNKNOWN','Non-Standard','Raw License String Could Not Be Mapped to a Standardized SPDX License');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('UNSPECIFIED','Not Provided','No License Information was Provided');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED','BSD','BSD-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0+','Apache-2.0+','Apache License 2.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-UNSPECIFIED','Apache','Apache-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED','GPL','GPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-3.0-with-classpath-exception','GPL-3.0-with-classpath-exception','GNU General Public License v3.0 w/Classpath exception');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-UNSPECIFIED','LGPL','LGPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('AFL-UNSPECIFIED','AFL','AFL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('AGPL-3.0+','AGPL-3.0+','GNU Affero General Public License v3 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('AGPL-UNSPECIFIED','AGPL','AGPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Artistic-UNSPECIFIED','Artistic','AGPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-SA-UNSPECIFIED','CC-BY-SA','CC-BY-SA-Style License Not Identifiable by Sonatyp');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-UNSPECIFIED','CC-BY','CC-BY-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-UNSPECIFIED','CDDL','CDDL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('ECL-UNSPECIFIED','ECL','ECL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0+','EPL-1.0+','Eclipse Public License 1.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-UNSPECIFIED','EPL','EPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GFDL-1.2+','GFDL-1.2+','GNU Free Documentation License v1.2');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GFDL-UNSPECIFIED','GFDL','GFDL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MIT-UNSPECIFIED','MIT-UNSPECIFIED','MIT-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MPL-1.1+','MPL-1.1+','Mozilla Public License 1.1 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MPL-UNSPECIFIED','MPL','MPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('PHP-UNSPECIFIED','PHP','PHP-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Python-UNSPECIFIED','Python','Python-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('W3C-UNSPECIFIED','W3C-UNSPECIFIED','W3C-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('ZPL-UNSPECIFIED','ZPL','ZPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('OSL-UNSPECIFIED','OSL','OSL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CECILL-UNSPECIFIED','CECILL','CeCILL Free Software Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('COMMERCIAL','COMMERCIAL','Commercial Software License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-1.0-GPL-2.0','CDDL-1.0 or GPL-2.0','Dual License Consisting of CDDL-1.0 and GPL-2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-1.1-GPL-2.0','CDDL-1.1 or GPL-2.0','Dual License Consisting of CDDL-1.1 and GPL-2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-1.0-GPL-2.0-CPE','CDDL-1.0 or GPL-2.0-CPE','Dual License Consisting of CDDL-1.0 and GPL-2.0-with-classpath exception');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-1.1-GPL-2.0-CPE','CDDL-1.1 or GPL-2.0-CPE','Dual License Consisting of CDDL-1.1 and GPL-2.0-with-classpath exception');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('JRUBY-CPL-GPL-LGPL','JRUBY-CPL-GPL-LGPL','JRuby is Tri-Licensed - CPL-1.0, GPL-2.0+, LGPL-2.1+');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('PUBLIC-DOMAIN','Public Domain','The work has been placed in the public domain');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-EPL-1.0', 'Apache-2.0 or EPL-1.0', 'Dual License Consisting of Apache License 2.0 and Eclipse Public License 1.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-GPL-UNSPECIFIED', 'Apache-2.0 or GPL', 'Dual License Consisting of Apache 2.0 and GPL-style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-GPL-2.0', 'Apache-2.0 or GPL-2.0', 'Dual License Consisting of Apache 2.0 and GPL 2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-GPL-2.0+', 'Apache-2.0 or GPL-2.0+', 'Dual License Consisting of Apache 2.0 and GPL 2.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-GPL-3.0', 'Apache-2.0 or GPL-3.0', 'Dual License Consisting of Apache 2.0 and GPL 3.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-GPL-3.0+', 'Apache-2.0 or GPL-3.0+', 'Dual License Consisting of Apache 2.0 and GPL 3.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-2.1+-MPL-1.1', 'Apache-2.0 or LGPL-2.1+ or MPL-1.1', 'Triple License Consisting of Apache 2.0, LGPL 2.1 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-UNSPECIFIED', 'Apache-2.0 or LGPL', 'Dual License Consisting of Apache 2.0 and LGPL-style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-2.0', 'Apache-2.0 or LGPL-2.0', 'Dual License Consisting of Apache 2.0 and LGPL 2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-2.0+', 'Apache-2.0 or LGPL-2.0+', 'Dual License Consisting of Apache 2.0 and LGPL 2.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-2.1', 'Apache-2.0 or LGPL-2.1', 'Dual License Consisting of Apache 2.0 and LGPL 2.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-2.1+', 'Apache-2.0 or LGPL-2.1+', 'Dual License Consisting of Apache 2.0 and LGPL 2.1 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-3.0', 'Apache-2.0 or LGPL-3.0', 'Dual License Consisting of Apache 2.0 and LGPL 3.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-3.0+', 'Apache-2.0 or LGPL-3.0+', 'Dual License Consisting of Apache 2.0 and LGPL 3.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0+-GPL-2.0+-LGPL-2.1+', 'Apache-2.0+ or GPL-2.0+ or LGPL-2.1+', 'Triple License Consisting of Apache 2.0, GPL 2.0 or later and LGPL 2.1 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-GPL-UNSPECIFIED', 'BSD or GPL', 'Dual License Consisting of BSD-Style License Not Identifiable by Sonatype and GPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-GPL-2.0', 'BSD or GPL-2.0', 'Dual License Consisting of BSD-Style License Not Identifiable by Sonatype and GPL 2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-GPL-2.0+', 'BSD or GPL-2.0+', 'Dual License Consisting of BSD-Style License Not Identifiable by Sonatype and GPL 2.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-GPL-3.0', 'BSD or GPL-3.0', 'Dual License Consisting of BSD-Style License Not Identifiable by Sonatype and GPL 3.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-GPL-3.0+', 'BSD or GPL-3.0+', 'Dual License Consisting of BSD-Style License Not Identifiable by Sonatype and GPL 3.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-GPL-UNSPECIFIED-MIT', 'BSD or GPL or MIT', 'Triple License Consisting of BSD-Style License Not Identifiable by Sonatype, GPL-Style License Not Identifiable by Sonatype and MIT');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-EPL-1.0', 'BSD or EPL-1.0', 'Dual License Consisting of BSD-Style License Not Identifiable by Sonatype and Eclipse Public License 1.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-3-Clause-EPL-1.0', 'BSD-3-Clause or EPL-1.0', 'Dual License Consisting of New BSD License and Eclipse Public License 1.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-GPL-2.0-with-classpath-exception', 'CDDL or GPL-2.0-with-classpath-exception', 'Dual License Consisting of CDDL 1.0 and GPL 2.0 or later with classpath exception');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CPL-1.0-GPL-2.0+-LGPL-2.1+', 'CPL-1.0 or GPL-2.0+ or LGPL-2.1+', 'Triple License Consisting of CPL 1.0, GPL 2.0 or later and LGPL 2.1 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-UNSPECIFIED', 'EPL-1.0 or LGPL', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL-style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-2.0', 'EPL-1.0 or LGPL-2.0', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL 2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-2.0+', 'EPL-1.0 or LGPL-2.0+', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL 2.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-2.1', 'EPL-1.0 or LGPL-2.1', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL 2.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-2.1+', 'EPL-1.0 or LGPL-2.1+', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL 2.1 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-3.0', 'EPL-1.0 or LGPL-3.0', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL 3.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-3.0+', 'EPL-1.0 or LGPL-3.0+', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL 3.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-3.0+-MPL-1.1', 'EPL-1.0 or LGPL-3.0+ or MPL-1.1', 'Triple License Consisting of Eclipse Public License 1.0, LGPL 3.0 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-MPL-1.1', 'EPL-1.0 or MPL-1.1', 'Dual License Consisting of Eclipse Public License 1.0 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED-MIT', 'GPL or MIT', 'Dual License Consisting of GPL-Style License Not Identifiable by Sonatype and MIT');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-MIT', 'GPL-2.0 or MIT', 'Dual License Consisting of GPL 2.0 and MIT');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED-MPL-1.1', 'GPL or MPL-1.1', 'Dual License Consisting of GPL-Style License Not Identifiable by Sonatype and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-MPL-1.1', 'GPL-2.0 or MPL-1.1', 'Dual License Consisting of GPL 2.0 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0+-MPL-1.1', 'GPL-2.0+ or MPL-1.1', 'Dual License Consisting of GPL 2.0 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-3.0-MPL-1.1', 'GPL-3.0 or MPL-1.1', 'Dual License Consisting of GPL 3.0 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-3.0+-MPL-1.1', 'GPL-3.0+ or MPL-1.1', 'Dual License Consisting of GPL 3.0 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-LGPL-2.1', 'GPL-2.0 or LGPL-2.1', 'Dual License Consisting of GPL 2.0 and LGPL 2.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-LGPL-2.1-MPL-1.1', 'GPL-2.0 or LGPL-2.1 or MPL-1.1', 'Triple License Consisting of GPL 2.0, LGPL 2.1 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1', 'GPL-2.0+ or LGPL-2.1+ or MPL-1.1', 'Triple License Consisting of GPL 2.0 or later, LGPL 2.1 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1+', 'GPL-2.0+ or LGPL-2.1+ or MPL-1.1+', 'Triple License Consisting of GPL 2.0 or later, LGPL 2.1 or later and Mozilla Public License 1.1 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-UNSPECIFIED-MPL-1.1', 'LGPL or MPL-1.1', 'Dual License Consisting of LGPL-Style License Not Identifiable by Sonatype and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-2.0-MPL-1.1', 'LGPL-2.0 or MPL-1.1', 'Dual License Consisting of LGPL 2.0 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-2.0+-MPL-1.1', 'LGPL-2.0+ or MPL-1.1', 'Dual License Consisting of LGPL 2.0 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-2.1-MPL-1.1', 'LGPL-2.1 or MPL-1.1', 'Dual License Consisting of LGPL 2.1 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-2.1+-MPL-1.1', 'LGPL-2.1+ or MPL-1.1', 'Dual License Consisting of LGPL 2.1 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-3.0-MPL-1.1', 'LGPL-3.0 or MPL-1.1', 'Dual License Consisting of LGPL 3.0 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-3.0+-MPL-1.1', 'LGPL-3.0+ or MPL-1.1', 'Dual License Consisting of LGPL 3.0 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('AFL-2.1-BSD-3-Clause','AFL-2.1 or BSD-3-Clause','Dual License Consisting of Academic Free License v2.1 and New BSD License');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('AFL-2.1+-BSD-3-Clause','AFL-2.1+ or BSD-3-Clause','Dual License Consisting of Academic Free License v2.1 or later and New BSD License');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('No-Source-License','No Source License','No licenses found in sources');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('No-Sources','No Sources','No sources provided with component');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Not-Declared','Not Declared','No licenses declared in component descriptor');

