INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('UNKNOWN','Non-Standard','Raw License String Could Not Be Mapped to a Standardized SPDX License');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('UNSPECIFIED','Not Provided','No License Information was Provided');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED','BSD','BSD-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0+','Apache-2.0+','Apache License 2.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-UNSPECIFIED','Apache','Apache-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED','GPL','GPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED-with-classpath-exception','GPL-with-classpath-exception','GPL-Style License Not Identifiable by Sonatype w/Classpath exception');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-3.0-with-classpath-exception','GPL-3.0-with-classpath-exception','GNU General Public License v3.0 w/Classpath exception');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-UNSPECIFIED','LGPL','LGPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('AFL-UNSPECIFIED','AFL','AFL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('AGPL-3.0+','AGPL-3.0+','GNU Affero General Public License v3 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('AGPL-UNSPECIFIED','AGPL','AGPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Artistic-UNSPECIFIED','Artistic','Artistic-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-SA-UNSPECIFIED','CC-BY-SA','CC-BY-SA-Style License Not Identifiable by Sonatyp');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CC-BY-UNSPECIFIED','CC-BY','CC-BY-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-UNSPECIFIED','CDDL','CDDL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('ECL-UNSPECIFIED','ECL','ECL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0+','EPL-1.0+','Eclipse Public License 1.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-UNSPECIFIED','EPL','EPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GFDL-1.2+','GFDL-1.2+','GNU Free Documentation License v1.2');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GFDL-UNSPECIFIED','GFDL','GFDL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MPL-1.1+','MPL-1.1+','Mozilla Public License 1.1 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MPL-UNSPECIFIED','MPL','MPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('PHP-UNSPECIFIED','PHP','PHP-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Python-UNSPECIFIED','Python','Python-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('ZPL-UNSPECIFIED','ZPL','ZPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('OSL-UNSPECIFIED','OSL','OSL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CECILL-UNSPECIFIED','CECILL','CeCILL Free Software Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('COMMERCIAL','COMMERCIAL','Commercial Software License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-1.0-GPL-2.0','CDDL-1.0 or GPL-2.0','Dual License Consisting of CDDL-1.0 and GPL-2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-1.1-GPL-2.0','CDDL-1.1 or GPL-2.0','Dual License Consisting of CDDL-1.1 and GPL-2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-1.0-GPL-2.0-CPE','CDDL-1.0 or GPL-2.0-CPE','Dual License Consisting of CDDL-1.0 and GPL-2.0-with-classpath exception');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-1.1-GPL-2.0-CPE','CDDL-1.1 or GPL-2.0-CPE','Dual License Consisting of CDDL-1.1 and GPL-2.0-with-classpath exception');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('JRUBY-CPL-GPL-LGPL','JRUBY-CPL-GPL-LGPL','JRuby is Tri-Licensed - CPL-1.0, GPL-2.0+, LGPL-2.1+');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('PUBLIC-DOMAIN','Public Domain','The work has been placed in the public domain');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-EPL-1.0', 'Apache-2.0 or EPL-1.0', 'Dual License Consisting of Apache License 2.0 and Eclipse Public License 1.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-GPL-UNSPECIFIED', 'Apache-2.0 or GPL', 'Dual License Consisting of Apache 2.0 and GPL-style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-GPL-2.0', 'Apache-2.0 or GPL-2.0', 'Dual License Consisting of Apache 2.0 and GPL 2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-GPL-2.0+', 'Apache-2.0 or GPL-2.0+', 'Dual License Consisting of Apache 2.0 and GPL 2.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-GPL-3.0', 'Apache-2.0 or GPL-3.0', 'Dual License Consisting of Apache 2.0 and GPL 3.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-GPL-3.0+', 'Apache-2.0 or GPL-3.0+', 'Dual License Consisting of Apache 2.0 and GPL 3.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-2.1+-MPL-1.1', 'Apache-2.0 or LGPL-2.1+ or MPL-1.1', 'Triple License Consisting of Apache 2.0, LGPL 2.1 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-UNSPECIFIED', 'Apache-2.0 or LGPL', 'Dual License Consisting of Apache 2.0 and LGPL-style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-2.0', 'Apache-2.0 or LGPL-2.0', 'Dual License Consisting of Apache 2.0 and LGPL 2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-2.0+', 'Apache-2.0 or LGPL-2.0+', 'Dual License Consisting of Apache 2.0 and LGPL 2.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-2.1', 'Apache-2.0 or LGPL-2.1', 'Dual License Consisting of Apache 2.0 and LGPL 2.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-2.1+', 'Apache-2.0 or LGPL-2.1+', 'Dual License Consisting of Apache 2.0 and LGPL 2.1 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-3.0', 'Apache-2.0 or LGPL-3.0', 'Dual License Consisting of Apache 2.0 and LGPL 3.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0-LGPL-3.0+', 'Apache-2.0 or LGPL-3.0+', 'Dual License Consisting of Apache 2.0 and LGPL 3.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0+-GPL-2.0+-LGPL-2.1+', 'Apache-2.0+ or GPL-2.0+ or LGPL-2.1+', 'Triple License Consisting of Apache 2.0, GPL 2.0 or later and LGPL 2.1 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-GPL-UNSPECIFIED', 'BSD or GPL', 'Dual License Consisting of BSD-Style License Not Identifiable by Sonatype and GPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-GPL-2.0', 'BSD or GPL-2.0', 'Dual License Consisting of BSD-Style License Not Identifiable by Sonatype and GPL 2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-GPL-2.0+', 'BSD or GPL-2.0+', 'Dual License Consisting of BSD-Style License Not Identifiable by Sonatype and GPL 2.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-GPL-3.0', 'BSD or GPL-3.0', 'Dual License Consisting of BSD-Style License Not Identifiable by Sonatype and GPL 3.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-GPL-3.0+', 'BSD or GPL-3.0+', 'Dual License Consisting of BSD-Style License Not Identifiable by Sonatype and GPL 3.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-GPL-UNSPECIFIED-MIT', 'BSD or GPL or MIT', 'Triple License Consisting of BSD-Style License Not Identifiable by Sonatype, GPL-Style License Not Identifiable by Sonatype and MIT');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-UNSPECIFIED-EPL-1.0', 'BSD or EPL-1.0', 'Dual License Consisting of BSD-Style License Not Identifiable by Sonatype and Eclipse Public License 1.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('BSD-3-Clause-EPL-1.0', 'BSD-3-Clause or EPL-1.0', 'Dual License Consisting of New BSD License and Eclipse Public License 1.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-GPL-2.0-with-classpath-exception', 'CDDL or GPL-2.0-with-classpath-exception', 'Dual License Consisting of CDDL 1.0 and GPL 2.0 or later with classpath exception');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CPL-1.0-GPL-2.0+-LGPL-2.1+', 'CPL-1.0 or GPL-2.0+ or LGPL-2.1+', 'Triple License Consisting of CPL 1.0, GPL 2.0 or later and LGPL 2.1 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-UNSPECIFIED', 'EPL-1.0 or LGPL', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL-style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-2.0', 'EPL-1.0 or LGPL-2.0', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL 2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-2.0+', 'EPL-1.0 or LGPL-2.0+', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL 2.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-2.1', 'EPL-1.0 or LGPL-2.1', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL 2.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-2.1+', 'EPL-1.0 or LGPL-2.1+', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL 2.1 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-3.0', 'EPL-1.0 or LGPL-3.0', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL 3.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-3.0+', 'EPL-1.0 or LGPL-3.0+', 'Dual License Consisting of Eclipse Public License 1.0 and LGPL 3.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-LGPL-3.0+-MPL-1.1', 'EPL-1.0 or LGPL-3.0+ or MPL-1.1', 'Triple License Consisting of Eclipse Public License 1.0, LGPL 3.0 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('EPL-1.0-MPL-1.1', 'EPL-1.0 or MPL-1.1', 'Dual License Consisting of Eclipse Public License 1.0 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED-MIT', 'GPL or MIT', 'Dual License Consisting of GPL-Style License Not Identifiable by Sonatype and MIT');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-MIT', 'GPL-2.0 or MIT', 'Dual License Consisting of GPL 2.0 and MIT');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED-MPL-1.1', 'GPL or MPL-1.1', 'Dual License Consisting of GPL-Style License Not Identifiable by Sonatype and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-MPL-1.1', 'GPL-2.0 or MPL-1.1', 'Dual License Consisting of GPL 2.0 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0+-MPL-1.1', 'GPL-2.0+ or MPL-1.1', 'Dual License Consisting of GPL 2.0 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-3.0-MPL-1.1', 'GPL-3.0 or MPL-1.1', 'Dual License Consisting of GPL 3.0 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-3.0+-MPL-1.1', 'GPL-3.0+ or MPL-1.1', 'Dual License Consisting of GPL 3.0 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-LGPL-2.1', 'GPL-2.0 or LGPL-2.1', 'Dual License Consisting of GPL 2.0 and LGPL 2.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0-LGPL-2.1-MPL-1.1', 'GPL-2.0 or LGPL-2.1 or MPL-1.1', 'Triple License Consisting of GPL 2.0, LGPL 2.1 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1', 'GPL-2.0+ or LGPL-2.1+ or MPL-1.1', 'Triple License Consisting of GPL 2.0 or later, LGPL 2.1 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-2.0+-LGPL-2.1+-MPL-1.1+', 'GPL-2.0+ or LGPL-2.1+ or MPL-1.1+', 'Triple License Consisting of GPL 2.0 or later, LGPL 2.1 or later and Mozilla Public License 1.1 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-UNSPECIFIED-MPL-1.1', 'LGPL or MPL-1.1', 'Dual License Consisting of LGPL-Style License Not Identifiable by Sonatype and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-2.0-MPL-1.1', 'LGPL-2.0 or MPL-1.1', 'Dual License Consisting of LGPL 2.0 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-2.0+-MPL-1.1', 'LGPL-2.0+ or MPL-1.1', 'Dual License Consisting of LGPL 2.0 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-2.1-MPL-1.1', 'LGPL-2.1 or MPL-1.1', 'Dual License Consisting of LGPL 2.1 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-2.1+-MPL-1.1', 'LGPL-2.1+ or MPL-1.1', 'Dual License Consisting of LGPL 2.1 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-3.0-MPL-1.1', 'LGPL-3.0 or MPL-1.1', 'Dual License Consisting of LGPL 3.0 and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('LGPL-3.0+-MPL-1.1', 'LGPL-3.0+ or MPL-1.1', 'Dual License Consisting of LGPL 3.0 or later and Mozilla Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('AFL-2.1-BSD-3-Clause','AFL-2.1 or BSD-3-Clause','Dual License Consisting of Academic Free License v2.1 and New BSD License');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('AFL-2.1+-BSD-3-Clause','AFL-2.1+ or BSD-3-Clause','Dual License Consisting of Academic Free License v2.1 or later and New BSD License');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('AFL-2.1-GPL-2.0+','AFL-2.1 or GPL-2.0+','Dual License Consisting of Academic Free License 2.1 and GPL 2.0 or later');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('No-Source-License','No Source License','No licenses found in sources');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('No-Sources','No Sources','No sources provided with component');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Not-Declared','Not Declared','No licenses declared in component descriptor');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Not-Supported','Not Supported','Observed license recognition for component repository not supported by data pipeline');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Apache-2.0+-BSD-UNSPECIFIED-EPL-1.0+-GPL-2.0','Apache-2.0+ or BSD or EPL-1.0+ or GPL-2.0','Quadruple License Consisting of Apache 2.0 or later, BSD, EPL-1.0 or later, and GPL 2.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CDDL-1.0-BSD-3-Clause','CDDL-1.0 or BSD-3-Clause','Dual License Consisting of CDDL-1.0 and New BSD License');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('CECILL-C-LGPL-3.0','CECILL-C or LGPL-3.0','Dual License Consisting of CECILL-C and LGPL 3.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('GPL-UNSPECIFIED-NPL-1.1','GPL or NPL-1.1','Dual License Consisting of GPL-Style License Not Identifiable by Sonatype and Netscape Public License 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('SPL-1.0-LGPL-UNSPECIFIED','SPL-1.0 or LGPL','Dual License Consisting of Sun Public License 1.0 and LGPL-Style License Not Identifiable by Sonatype');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('DOCBOOK','DocBook','DocBook Software License');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('InitialDevelopersPL-1.0','InitialDevelopersPL-1.0','Initial Developer''s Public License Version 1.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('InterbasePL-1.0','InterbasePL-1.0','InterBase Public License Version 1.0');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('JA-SIG-Collaborative','JA-SIG-Collaborative','The JA-SIG Collaborative License');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Spice-1.1','Spice-1.1','Spice Software License Version 1.1');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Web-Pages-2','MS-ASP.NET-Web-Pages-2','Microsoft ASP.NET Web Pages 2');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Web-Pages-2-Pre-Release','MS-ASP.NET-Web-Pages-2-Pre-Release','Microsoft ASP.NET Web Pages 2 - Pre-Release');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-MSN-WEBGREASE','MS-MSN-WEBGREASE','Microsoft MSN WebGrease');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-.NET-Library','MS-.NET-Library','Microsoft .NET Library');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-.NET-Library-JS','MS-.NET-Library-JS','Microsoft .NET Library JS');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-MVC-4','MS-ASP.NET-MVC-4','Microsoft ASP.NET Model View Controller 4');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-MVC-4-Pre-Release','MS-ASP.NET-MVC-4-Pre-Release','Microsoft ASP.NET Model View Controller 4 Pre-Release');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-MVC-4-Extensions-Pre-Release','MS-ASP.NET-MVC-4-Extensions-Pre-Release','Microsoft ASP.NET Model View Controller 4 Extensions Pre-Release');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-WOF','MS-ASP.NET-WOF','Microsoft ASP.NET Web Optimization Framework');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-WOF-Pre-Release','MS-ASP.NET-WOF-Pre-Release','Microsoft ASP.NET Web Optimization Framework Pre-Release');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Tools','MS-ASP.NET-Tools','Microsoft ASP.NET Tools');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-ASP.NET-Universal-Providers','MS-ASP.NET-Universal-Providers','Microsoft ASP.NET Universal Providers');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('ServiceStack-License-Agreement','ServiceStack-License-Agreement','ServiceStack License Agreement');
