-- since 1.84
CREATE TABLE component_category (
  component_category_id varchar(1000) NOT NULL,
  path varchar(1000) NOT NULL,
  CONSTRAINT component_category_pk PRIMARY KEY (component_category_id),
  CONSTRAINT component_category_path_uk UNIQUE (path)
);

INSERT INTO component_category (component_category_id, path) VALUES ('2', 'Analytics');
INSERT INTO component_category (component_category_id, path) VALUES ('5', 'Analytics/Application Analytics');
INSERT INTO component_category (component_category_id, path) VALUES ('3', 'Analytics/Business Intelligence');
INSERT INTO component_category (component_category_id, path) VALUES ('4', 'Analytics/Web Analytics');
INSERT INTO component_category (component_category_id, path) VALUES ('128', 'Application and Server Management');
INSERT INTO component_category (component_category_id, path) VALUES ('164', 'Application Product Development Platform');
INSERT INTO component_category (component_category_id, path) VALUES ('22', 'Audio and Video Management');
INSERT INTO component_category (component_category_id, path) VALUES ('23', 'Audio and Video Management/Graphics and Image Processing');
INSERT INTO component_category (component_category_id, path) VALUES ('7', 'Big Data');
INSERT INTO component_category (component_category_id, path) VALUES ('168', 'Big Data/Data Analytics');
INSERT INTO component_category (component_category_id, path) VALUES ('143', 'Big Data/Databases');
INSERT INTO component_category (component_category_id, path) VALUES ('8', 'Big Data/Machine Learning');
INSERT INTO component_category (component_category_id, path) VALUES ('142', 'Big Data/Parallel Data Processing');
INSERT INTO component_category (component_category_id, path) VALUES ('119', 'Boot loader');
INSERT INTO component_category (component_category_id, path) VALUES ('10', 'Build Tools');
INSERT INTO component_category (component_category_id, path) VALUES ('11', 'Build Tools/Code Analysis');
INSERT INTO component_category (component_category_id, path) VALUES ('12', 'Build Tools/Compilers');
INSERT INTO component_category (component_category_id, path) VALUES ('13', 'Build Tools/Dependency Resolution');
INSERT INTO component_category (component_category_id, path) VALUES ('14', 'Build Tools/Packaging');
INSERT INTO component_category (component_category_id, path) VALUES ('15', 'Build Tools/Project Generation');
INSERT INTO component_category (component_category_id, path) VALUES ('16', 'Build Tools/Source Control System Integration');
INSERT INTO component_category (component_category_id, path) VALUES ('17', 'Build Tools/Task Automation');
INSERT INTO component_category (component_category_id, path) VALUES ('127', 'Business Intelligence and Process Management');
INSERT INTO component_category (component_category_id, path) VALUES ('166', 'Captcha Generator');
INSERT INTO component_category (component_category_id, path) VALUES ('18', 'Cloud Computing');
INSERT INTO component_category (component_category_id, path) VALUES ('19', 'Configuration Utilities and Frameworks');
INSERT INTO component_category (component_category_id, path) VALUES ('123', 'Configuration Utilities and Frameworks/Rules Engine');
INSERT INTO component_category (component_category_id, path) VALUES ('20', 'Console');
INSERT INTO component_category (component_category_id, path) VALUES ('21', 'Content Management');
INSERT INTO component_category (component_category_id, path) VALUES ('158', 'Customer Relationship Management(CRM)');
INSERT INTO component_category (component_category_id, path) VALUES ('159', 'Customer Relationship Management(CRM)/Security');
INSERT INTO component_category (component_category_id, path) VALUES ('36', 'Data Management');
INSERT INTO component_category (component_category_id, path) VALUES ('37', 'Data Management/Caching');
INSERT INTO component_category (component_category_id, path) VALUES ('38', 'Data Management/Database');
INSERT INTO component_category (component_category_id, path) VALUES ('43', 'Data Management/Database Access');
INSERT INTO component_category (component_category_id, path) VALUES ('44', 'Data Management/Database Access/Drivers');
INSERT INTO component_category (component_category_id, path) VALUES ('45', 'Data Management/Database Access/ODM Framework');
INSERT INTO component_category (component_category_id, path) VALUES ('46', 'Data Management/Database Access/OGM Framework');
INSERT INTO component_category (component_category_id, path) VALUES ('47', 'Data Management/Database Access/ORM Framework');
INSERT INTO component_category (component_category_id, path) VALUES ('48', 'Data Management/Database Access/Persistence');
INSERT INTO component_category (component_category_id, path) VALUES ('49', 'Data Management/Database Access/Transaction Managers');
INSERT INTO component_category (component_category_id, path) VALUES ('39', 'Data Management/Database/Memory');
INSERT INTO component_category (component_category_id, path) VALUES ('40', 'Data Management/Database/NoSQL Databases');
INSERT INTO component_category (component_category_id, path) VALUES ('41', 'Data Management/Database/RDBMS Databases');
INSERT INTO component_category (component_category_id, path) VALUES ('42', 'Data Management/Database/RDS');
INSERT INTO component_category (component_category_id, path) VALUES ('25', 'Data Processors');
INSERT INTO component_category (component_category_id, path) VALUES ('26', 'Data Processors/Format');
INSERT INTO component_category (component_category_id, path) VALUES ('133', 'Data Processors/Format/Avro');
INSERT INTO component_category (component_category_id, path) VALUES ('134', 'Data Processors/Format/CSS');
INSERT INTO component_category (component_category_id, path) VALUES ('135', 'Data Processors/Format/CSV');
INSERT INTO component_category (component_category_id, path) VALUES ('27', 'Data Processors/Format/HTML');
INSERT INTO component_category (component_category_id, path) VALUES ('28', 'Data Processors/Format/JSON');
INSERT INTO component_category (component_category_id, path) VALUES ('29', 'Data Processors/Format/PDF');
INSERT INTO component_category (component_category_id, path) VALUES ('136', 'Data Processors/Format/RSS and Atom');
INSERT INTO component_category (component_category_id, path) VALUES ('137', 'Data Processors/Format/Text');
INSERT INTO component_category (component_category_id, path) VALUES ('30', 'Data Processors/Format/XML');
INSERT INTO component_category (component_category_id, path) VALUES ('31', 'Data Processors/Format/XPath');
INSERT INTO component_category (component_category_id, path) VALUES ('32', 'Data Processors/Format/YAML');
INSERT INTO component_category (component_category_id, path) VALUES ('33', 'Data Processors/Templating');
INSERT INTO component_category (component_category_id, path) VALUES ('35', 'Data Processors/Templating/AsciiDoc');
INSERT INTO component_category (component_category_id, path) VALUES ('34', 'Data Processors/Templating/Markdown');
INSERT INTO component_category (component_category_id, path) VALUES ('50', 'Data Protocols');
INSERT INTO component_category (component_category_id, path) VALUES ('51', 'Data Protocols/Clients');
INSERT INTO component_category (component_category_id, path) VALUES ('52', 'Data Protocols/Clients/Email');
INSERT INTO component_category (component_category_id, path) VALUES ('53', 'Data Protocols/Clients/FTP');
INSERT INTO component_category (component_category_id, path) VALUES ('54', 'Data Protocols/Clients/HTTP');
INSERT INTO component_category (component_category_id, path) VALUES ('124', 'Data Protocols/Clients/SMS');
INSERT INTO component_category (component_category_id, path) VALUES ('125', 'Data Protocols/Clients/SNMP');
INSERT INTO component_category (component_category_id, path) VALUES ('55', 'Data Protocols/Clients/SOAP');
INSERT INTO component_category (component_category_id, path) VALUES ('56', 'Data Protocols/Clients/SSH and SFTP');
INSERT INTO component_category (component_category_id, path) VALUES ('57', 'Data Protocols/Servers');
INSERT INTO component_category (component_category_id, path) VALUES ('58', 'Data Protocols/Servers/Email');
INSERT INTO component_category (component_category_id, path) VALUES ('59', 'Data Protocols/Servers/FTP');
INSERT INTO component_category (component_category_id, path) VALUES ('60', 'Data Protocols/Servers/HTTP');
INSERT INTO component_category (component_category_id, path) VALUES ('61', 'Data Protocols/Servers/SOAP');
INSERT INTO component_category (component_category_id, path) VALUES ('62', 'Data Protocols/Servers/SSH and SFTP');
INSERT INTO component_category (component_category_id, path) VALUES ('63', 'Data Transport');
INSERT INTO component_category (component_category_id, path) VALUES ('64', 'Data Transport/JMX');
INSERT INTO component_category (component_category_id, path) VALUES ('138', 'Data Transport/Remoting');
INSERT INTO component_category (component_category_id, path) VALUES ('126', 'Data Transport/VoIP and Telephony');
INSERT INTO component_category (component_category_id, path) VALUES ('65', 'Data Visualization');
INSERT INTO component_category (component_category_id, path) VALUES ('66', 'Data Visualization/Graph Visualization');
INSERT INTO component_category (component_category_id, path) VALUES ('162', 'Data Warehouse');
INSERT INTO component_category (component_category_id, path) VALUES ('67', 'Date and Time Utilities');
INSERT INTO component_category (component_category_id, path) VALUES ('68', 'Dependency Injection and Aspect-Oriented');
INSERT INTO component_category (component_category_id, path) VALUES ('69', 'Desktop Productivity');
INSERT INTO component_category (component_category_id, path) VALUES ('70', 'Developer Tools');
INSERT INTO component_category (component_category_id, path) VALUES ('71', 'Developer Tools/IDE Components');
INSERT INTO component_category (component_category_id, path) VALUES ('163', 'Developer Tools/Java Specifications');
INSERT INTO component_category (component_category_id, path) VALUES ('72', 'Distributed Computing');
INSERT INTO component_category (component_category_id, path) VALUES ('24', 'Document Management');
INSERT INTO component_category (component_category_id, path) VALUES ('73', 'Documentation');
INSERT INTO component_category (component_category_id, path) VALUES ('74', 'Enterprise Integration');
INSERT INTO component_category (component_category_id, path) VALUES ('75', 'Expression Language');
INSERT INTO component_category (component_category_id, path) VALUES ('76', 'File Utilities');
INSERT INTO component_category (component_category_id, path) VALUES ('77', 'File Utilities/Compression');
INSERT INTO component_category (component_category_id, path) VALUES ('78', 'File Utilities/File IO');
INSERT INTO component_category (component_category_id, path) VALUES ('79', 'File Utilities/Virtual Filesystem');
INSERT INTO component_category (component_category_id, path) VALUES ('160', 'Flowchart');
INSERT INTO component_category (component_category_id, path) VALUES ('149', 'Gaming');
INSERT INTO component_category (component_category_id, path) VALUES ('121', 'Graphics');
INSERT INTO component_category (component_category_id, path) VALUES ('83', 'GUI');
INSERT INTO component_category (component_category_id, path) VALUES ('84', 'GUI/Desktop');
INSERT INTO component_category (component_category_id, path) VALUES ('85', 'GUI/Mobile');
INSERT INTO component_category (component_category_id, path) VALUES ('117', 'Internationalization');
INSERT INTO component_category (component_category_id, path) VALUES ('118', 'Jvm Language');
INSERT INTO component_category (component_category_id, path) VALUES ('116', 'Language');
INSERT INTO component_category (component_category_id, path) VALUES ('165', 'License Management');
INSERT INTO component_category (component_category_id, path) VALUES ('169', 'Localization');
INSERT INTO component_category (component_category_id, path) VALUES ('80', 'Logging');
INSERT INTO component_category (component_category_id, path) VALUES ('81', 'Logging/Bridges');
INSERT INTO component_category (component_category_id, path) VALUES ('152', 'Mail');
INSERT INTO component_category (component_category_id, path) VALUES ('153', 'Mail/Client');
INSERT INTO component_category (component_category_id, path) VALUES ('154', 'Mail/Server');
INSERT INTO component_category (component_category_id, path) VALUES ('82', 'Math and Science Calculation');
INSERT INTO component_category (component_category_id, path) VALUES ('141', 'Math and Science Calculation/Geo');
INSERT INTO component_category (component_category_id, path) VALUES ('148', 'Misc');
INSERT INTO component_category (component_category_id, path) VALUES ('6', 'Monitoring and Management');
INSERT INTO component_category (component_category_id, path) VALUES ('139', 'Monitoring and Management/Configuration Management');
INSERT INTO component_category (component_category_id, path) VALUES ('9', 'Monitoring and Management/Parallel Data Processing');
INSERT INTO component_category (component_category_id, path) VALUES ('140', 'Monitoring and Management/Scheduling');
INSERT INTO component_category (component_category_id, path) VALUES ('161', 'MULTI-PROJECT');
INSERT INTO component_category (component_category_id, path) VALUES ('86', 'Network Management');
INSERT INTO component_category (component_category_id, path) VALUES ('87', 'Network Management/Proxies');
INSERT INTO component_category (component_category_id, path) VALUES ('88', 'Networking Utilities');
INSERT INTO component_category (component_category_id, path) VALUES ('157', 'Operating System');
INSERT INTO component_category (component_category_id, path) VALUES ('113', 'Other');
INSERT INTO component_category (component_category_id, path) VALUES ('120', 'Payment');
INSERT INTO component_category (component_category_id, path) VALUES ('156', 'Product Analytics');
INSERT INTO component_category (component_category_id, path) VALUES ('146', 'Programming');
INSERT INTO component_category (component_category_id, path) VALUES ('89', 'Programming Language Utilites');
INSERT INTO component_category (component_category_id, path) VALUES ('90', 'Programming Language Utilites/Android');
INSERT INTO component_category (component_category_id, path) VALUES ('129', 'Programming Language Utilites/Annotations');
INSERT INTO component_category (component_category_id, path) VALUES ('91', 'Programming Language Utilites/Bytecode and ASM Utilities');
INSERT INTO component_category (component_category_id, path) VALUES ('131', 'Programming Language Utilites/Ceylon');
INSERT INTO component_category (component_category_id, path) VALUES ('132', 'Programming Language Utilites/Clojure');
INSERT INTO component_category (component_category_id, path) VALUES ('92', 'Programming Language Utilites/Collections');
INSERT INTO component_category (component_category_id, path) VALUES ('93', 'Programming Language Utilites/Concurrency Utilities');
INSERT INTO component_category (component_category_id, path) VALUES ('130', 'Programming Language Utilites/Encoder and Decoder');
INSERT INTO component_category (component_category_id, path) VALUES ('94', 'Programming Language Utilites/OSGi Libraries');
INSERT INTO component_category (component_category_id, path) VALUES ('95', 'Programming Language Utilites/Reflection');
INSERT INTO component_category (component_category_id, path) VALUES ('147', 'Programming/Regular Expression');
INSERT INTO component_category (component_category_id, path) VALUES ('114', 'Robotics');
INSERT INTO component_category (component_category_id, path) VALUES ('145', 'Sample-Demo-Example');
INSERT INTO component_category (component_category_id, path) VALUES ('96', 'Search Engines');
INSERT INTO component_category (component_category_id, path) VALUES ('97', 'Security');
INSERT INTO component_category (component_category_id, path) VALUES ('144', 'Security/Administration');
INSERT INTO component_category (component_category_id, path) VALUES ('98', 'Security/Authentication');
INSERT INTO component_category (component_category_id, path) VALUES ('167', 'Security/Authentication and Authorization');
INSERT INTO component_category (component_category_id, path) VALUES ('99', 'Security/Authorization');
INSERT INTO component_category (component_category_id, path) VALUES ('100', 'Security/Credential Management');
INSERT INTO component_category (component_category_id, path) VALUES ('101', 'Security/Cryptography');
INSERT INTO component_category (component_category_id, path) VALUES ('102', 'Security/Identity Management');
INSERT INTO component_category (component_category_id, path) VALUES ('103', 'Security/Validation');
INSERT INTO component_category (component_category_id, path) VALUES ('151', 'Server');
INSERT INTO component_category (component_category_id, path) VALUES ('122', 'Social Media');
INSERT INTO component_category (component_category_id, path) VALUES ('104', 'Software Development Kit');
INSERT INTO component_category (component_category_id, path) VALUES ('155', 'Software Maintenance');
INSERT INTO component_category (component_category_id, path) VALUES ('1', 'Sonatype');
INSERT INTO component_category (component_category_id, path) VALUES ('105', 'Test and Quality Management');
INSERT INTO component_category (component_category_id, path) VALUES ('106', 'Test and Quality Management/Assertion');
INSERT INTO component_category (component_category_id, path) VALUES ('107', 'Test and Quality Management/Mocking Utilities');
INSERT INTO component_category (component_category_id, path) VALUES ('108', 'Test and Quality Management/Testing Utilities and Frameworks');
INSERT INTO component_category (component_category_id, path) VALUES ('115', 'Virtualization');
INSERT INTO component_category (component_category_id, path) VALUES ('109', 'Web Application Container');
INSERT INTO component_category (component_category_id, path) VALUES ('110', 'Web Frameworks');
INSERT INTO component_category (component_category_id, path) VALUES ('111', 'Web Frameworks/Client');
INSERT INTO component_category (component_category_id, path) VALUES ('170', 'Web Frameworks/Rest');
INSERT INTO component_category (component_category_id, path) VALUES ('173', 'Web Frameworks/Rest/Client');
INSERT INTO component_category (component_category_id, path) VALUES ('171', 'Web Frameworks/Rest/Server');
INSERT INTO component_category (component_category_id, path) VALUES ('112', 'Web Frameworks/Server');
INSERT INTO component_category (component_category_id, path) VALUES ('150', 'Workflow');
