INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Adobe','Adobe','Adobe','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Adobe-AFM','Adobe-AFM','Adobe-AFM','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Adobe-EULA','Adobe-EULA','Adobe-EULA','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('ATT','ATT','ATT','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Beerware','Beerware','Beerware','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Boost','Boost','Boost','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('DOCBOOK','DOCBOOK','DOCBOOK','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Dyade','Dyade','Dyade','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('HP-DEC','HP-DEC','HP-DEC','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('IETF','IETF','IETF','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('IETF-style','IETF-style','IETF-style','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('ImageMagick','ImageMagick','ImageMagick','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('InfoSeek','InfoSeek','InfoSeek','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('IPTC','IPTC','IPTC','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('ISO-8879','ISO-8879','ISO-8879','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Java-Multi-Corp','Java-Multi-Corp','Java-Multi-Corp','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Java-WSDL-Policy','Java-WSDL-Policy','Java-WSDL-Policy','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Java-WSDL-Schema','Java-WSDL-Schema','Java-WSDL-Schema','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('JPEG','JPEG','JPEG','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('MS-IP','MS-IP','MS-IP','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('OSD','OSD','OSD','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('RedHat','RedHat','RedHat','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('RSA-Security','RSA-Security','RSA-Security','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun','Sun','Sun','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun-BCLA','Sun-BCLA','Sun-BCLA','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun-EULA','Sun-EULA','Sun-EULA','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun-IP','Sun-IP','Sun-IP','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun-Non-commercial','Sun-Non-commercial','Sun-Non-commercial','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun-Restricted','Sun-Restricted','Sun-Restricted','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Sun-TM','Sun-TM','Sun-TM','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Unicode','Unicode','Unicode','NON-STANDARD');
INSERT INTO license (license_id, shortDisplayName, longDisplayName, license_category_id) VALUES ('Xerox','Xerox','Xerox','NON-STANDARD');

INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Adobe','Adobe','Adobe');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Adobe-AFM','Adobe-AFM','Adobe-AFM');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Adobe-EULA','Adobe-EULA','Adobe-EULA');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('ATT','ATT','ATT');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Beerware','Beerware','Beerware');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Boost','Boost','Boost');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('DOCBOOK','DOCBOOK','DOCBOOK');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Dyade','Dyade','Dyade');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('HP-DEC','HP-DEC','HP-DEC');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('IETF','IETF','IETF');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('IETF-style','IETF-style','IETF-style');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('ImageMagick','ImageMagick','ImageMagick');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('InfoSeek','InfoSeek','InfoSeek');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('IPTC','IPTC','IPTC');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('ISO-8879','ISO-8879','ISO-8879');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Java-Multi-Corp','Java-Multi-Corp','Java-Multi-Corp');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Java-WSDL-Policy','Java-WSDL-Policy','Java-WSDL-Policy');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Java-WSDL-Schema','Java-WSDL-Schema','Java-WSDL-Schema');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('JPEG','JPEG','JPEG');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('MS-IP','MS-IP','MS-IP');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('OSD','OSD','OSD');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('RedHat','RedHat','RedHat');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('RSA-Security','RSA-Security','RSA-Security');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Sun','Sun','Sun');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Sun-BCLA','Sun-BCLA','Sun-BCLA');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Sun-EULA','Sun-EULA','Sun-EULA');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Sun-IP','Sun-IP','Sun-IP');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Sun-Non-commercial','Sun-Non-commercial','Sun-Non-commercial');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Sun-Restricted','Sun-Restricted','Sun-Restricted');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Sun-TM','Sun-TM','Sun-TM');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Unicode','Unicode','Unicode');
INSERT INTO multi_license (multi_license_id, shortDisplayName, longDisplayName) VALUES ('Xerox','Xerox','Xerox');

INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Adobe','Adobe');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Adobe-AFM','Adobe-AFM');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Adobe-EULA','Adobe-EULA');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ATT','ATT');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Beerware','Beerware');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Boost','Boost');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('DOCBOOK','DOCBOOK');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Dyade','Dyade');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('HP-DEC','HP-DEC');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('IETF','IETF');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('IETF-style','IETF-style');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ImageMagick','ImageMagick');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('InfoSeek','InfoSeek');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('IPTC','IPTC');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('ISO-8879','ISO-8879');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Java-Multi-Corp','Java-Multi-Corp');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Java-WSDL-Policy','Java-WSDL-Policy');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Java-WSDL-Schema','Java-WSDL-Schema');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('JPEG','JPEG');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('MS-IP','MS-IP');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('OSD','OSD');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('RedHat','RedHat');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('RSA-Security','RSA-Security');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Sun','Sun');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Sun-BCLA','Sun-BCLA');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Sun-EULA','Sun-EULA');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Sun-IP','Sun-IP');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Sun-Non-commercial','Sun-Non-commercial');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Sun-Restricted','Sun-Restricted');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Sun-TM','Sun-TM');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Unicode','Unicode');
INSERT INTO multi_license_license (multi_license_id, license_id) VALUES ('Xerox','Xerox');
