# TODO unset this property; choosing false for now to simplify development of org/policy import on first-run
csrfProtection: ${CSRF_PROTECTION:-false}

# WARNING: DO NOT DISABLE - used only internal facing and development systems only
cspEnabled: ${CSP_ENABLED:-true}

# Directory for data files.
sonatypeWork: ${SONATYPE_WORK:-./sonatype-work/clm-server}

enableDefaultPasswordWarning: ${ENABLE_DEFAULT_PASSWORD_WARNING:-false}

# Base URL of the Sonatype CLM server for user facing links back to the server.
# If a mail server is configured, then the baseUrl setting must also be enabled and correct as otherwise notification emails cannot be sent.
baseUrl: ${BASE_URL:-http://localhost}

# HTTP Strict Transport Security (HSTS) is supported using dropwizard-web configuration
# HSTS headers are enabled by default, uncomment web: section below and set enabled: false to disable
# Refer to https://github.com/dropwizard/dropwizard-web#supports for detailed configuration guide
#web:
#  hsts:
#    enabled: ${HSTS_ENABLED:-true}
#    maxAge: 365 days
#    includeSubDomains: true

# HTTP-specific options.
server:
  applicationContextPath: ${SERVER_APPLICATION_CONTEXT_PATH:-/}

  applicationConnectors:
    - type: ${SERVER_APPLICATION_CONNECTOR_TYPE:-http}

      # The port on which the HTTP server listens for service requests.
      # Because Java cannot drop privileges in a POSIX system, these
      # ports cannot be in the range 1-1024. A port value of 0 will
      # make the OS use an arbitrary unused port.
      port: ${SERVER_APPLICATION_CONNECTOR_PORT:-8070}

      # The hostname of the interface to which the application HTTP server socket
      # will be bound. If omitted, the socket will listen on all
      # interfaces.
      #bindHost: 127.0.0.1  # only bind to loopback

  adminConnectors:
    - type: ${SERVER_ADMIN_CONNECTOR_TYPE:-http}

      # The port on which the HTTP server listens for administrative
      # requests. Subject to the same limitations as "port".
      port: ${SERVER_ADMIN_CONNECTOR_PORT:-8071}

      # The hostname of the interface to which the admin HTTP server socket
      # will be bound. If omitted, the socket will listen on all
      # interfaces.
      #bindHost: 127.0.0.1  # only bind to loopback

  # HTTP request log settings.
  requestLog:
    type: ${REQUEST_LOG_TYPE:-classic}
    timeZone: ${REQUEST_LOG_TIMEZONE:-UTC}
    appenders:
      # Settings for logging to the console.
      - type: console
        logFormat: '${REQUEST_LOG_FORMAT:-%clientHost %l %user [%date] "%requestURL" %statusCode %bytesSent %elapsedTime "%header{User-Agent}"}'
      - type: file
        threshold: ${REQUEST_LOG_FILE_THRESHOLD:-OFF}
        currentLogFilename: "${REQUEST_LOG_FILE_NAME:-/var/log/nexus-iq-server/request.log}"
        archivedLogFilenamePattern: "${REQUEST_LOG_ARCHIVED_FILENAME_PATTERN:-/var/log/nexus-iq-server/request-%d.log.gz}"
        archivedFileCount: ${REQUEST_LOG_ARCHIVED_FILE_COUNT:-5}

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: ${DEFAULT_LOGGING_LEVEL:-INFO}

  # Logger-specific settings.
  loggers:
    com.sonatype.insight.scan: ${LOGGER_INSIGHT_SCAN_LEVEL:-INFO}
    eu.medsea.mimeutil.MimeUtil2: ${LOGGER_MIMEUTIL2_LEVEL:-INFO}
    org.apache.http: ${LOGGER_HTTP_LEVEL:-INFO}
    org.apache.http.wire: ${LOGGER_HTTP_WIRE_LEVEL:-ERROR}
    org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter: ${LOGGER_AUTHENTICATION_FILTER_LEVEL:-INFO}
    org.eclipse.birt.report.engine.layout.pdf.font.FontConfigReader: ${LOGGER_FONT_CONFIG_READER_LEVEL:-WARN}
    org.eclipse.jetty: ${LOGGER_ECLIPSE_JETTY_LEVEL:-INFO}
    org.postgresql.jdbc.PgConnection: INFO
    org.quartz: INFO
    org.zeroturnaround.exec: INFO
  appenders:
  - type: console
    threshold: ${LOGGER_CONSOLE_THRESHOLD:-INFO}
    logFormat: "${LOGGER_CONSOLE_LOG_FORMAT:-%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger  - %msg%n}"
  - type: file
    threshold: ${LOGGER_FILE_THRESHOLD:-ALL}
    currentLogFilename: "${LOGGER_FILE_NAME:-/var/log/nexus-iq-server/clm-server.log}"
    archivedLogFilenamePattern: "${LOGGER_FILE_ARCHIVED_FILENAME_PATTERN:-/var/log/nexus-iq-server/clm-server-%d.log.gz}"
    logFormat: "${LOGGER_FILE_LOG_FORMAT:-%d{'yyyy-MM-dd HH:mm:ss,SSSZ'} %level [%thread] %X{username} %logger  - %msg%n}"
    archivedFileCount: ${LOGGER_FILE_ARCHIVED_FILE_COUNT:-5}
createSampleData: ${CREATE_SAMPLE_DATA:-true}
  
database:
  type: ${DATABASE_TYPE:-postgresql}
  hostname: ${DATABASE_HOSTNAME}
  port: ${DATABASE_PORT:-5432}
  name: ${DATABASE_NAME:-postgres}
  username: ${DATABASE_USERNAME:-postgres}
  password: ${DATABASE_PASSWORD}
