#
# Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
# Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
# "Sonatype" is a trademark of Sonatype, Inc.
#

ARG SONATYPE_WORK="/sonatype-work"
ARG IQ_HOME="/opt/sonatype/nexus-iq-server"
ARG CONFIG_HOME="/etc/nexus-iq-server"
ARG LOGS_HOME="/var/log/nexus-iq-server"

ARG SONATYPE_PRIVATE_REGISTRY=sonatype.repo.sonatype.app/docker-all

FROM $SONATYPE_PRIVATE_REGISTRY/chainguard/wolfi-base AS builder

ARG SONATYPE_WORK
ARG IQ_HOME
ARG CONFIG_HOME
ARG LOGS_HOME

# Prepare os dependencies to be copied to runtime stage
COPY ./package-copy.sh /tmp/
RUN chmod +x /tmp/package-copy.sh && /tmp/package-copy.sh git curl tini

# Create folders & set permissions
RUN mkdir -p ${IQ_HOME} \
    && mkdir -p ${SONATYPE_WORK} \
    && mkdir -p ${CONFIG_HOME} \
    && mkdir -p ${LOGS_HOME} \
    && chmod 0755 "/opt/sonatype" ${IQ_HOME} \
    && chmod 0755 ${CONFIG_HOME} \
    && chmod 0755 ${LOGS_HOME}

# Copy config
COPY config.yml ${CONFIG_HOME}/

# Include IQ server jar
COPY target/insight-brain-service-*.jar ${IQ_HOME}/nexus-iq-server.jar

############################
# Final stage
############################

FROM $SONATYPE_PRIVATE_REGISTRY/sonatype-infosec/jdk-fips:openjdk-17

ARG IQ_SERVER_VERSION

ARG SONATYPE_WORK
ARG IQ_HOME
ARG CONFIG_HOME
ARG LOGS_HOME

# Copy prepared os dependencies content to its destination
COPY --from=builder --chown=65532:65532 /tmp/package-content /

# Copy SONATYPE_WORK from builder
COPY --from=builder --chown=65532:65532 ${SONATYPE_WORK} ${SONATYPE_WORK}

# Copy IQ_HOME from builder
COPY --from=builder --chown=65532:65532 ${IQ_HOME} ${IQ_HOME}

# Copy CONFIG_HOME from builder
COPY --from=builder --chown=65532:65532 ${CONFIG_HOME} ${CONFIG_HOME}

# Copy LOGS_HOME from builder
COPY --from=builder --chown=65532:65532 ${LOGS_HOME} ${LOGS_HOME}

# This is where we will store persistent data
VOLUME ${SONATYPE_WORK}
VOLUME ${LOGS_HOME}

# Expose the ports
EXPOSE 8070
EXPOSE 8071

# Extend JDK_JAVA_OPTIONS
ENV JDK_JAVA_OPTIONS="${JDK_JAVA_OPTIONS} \
  -Dgit.without.shell=true \
  -Djava.util.prefs.userRoot=${SONATYPE_WORK}/javaprefs \
  -XX:+AlwaysPreTouch -XX:+CrashOnOutOfMemoryError -XshowSettings:vm"

ENV SONATYPE_INTERNAL_HOST_SYSTEM=Docker

LABEL vendor=Sonatype \
  maintainer="IQ Team" \
  com.sonatype.name="Nexus IQ Server fips image" \
  version="${IQ_SERVER_VERSION}"

# Wire up health check
HEALTHCHECK CMD curl --fail --silent --show-error http://localhost:8071/healthcheck || exit 1

WORKDIR ${IQ_HOME}

ENTRYPOINT ["tini", "--", "java", "-jar", "/opt/sonatype/nexus-iq-server/nexus-iq-server.jar"]

CMD ["server", "/etc/nexus-iq-server/config.yml"]
