/*
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/oss/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
*/
(function(){function w(e,a,c){c=$.extend({},I,c);var d=2*c.fontSize,f=0.6*a.length*c.fontSize,l=c.height/2-d/2,m=c.leftPadding+(c.width-c.leftPadding-c.rightPadding-f)/2;e.add(pv.Bar).top(l).left(m).lineWidth(0).height(d).width(f).strokeStyle(u).fillStyle(u);e.add(pv.Dot).top(l+d/2).left(m).radius(d/2).lineWidth(0).strokeStyle(u).fillStyle(u);e.add(pv.Dot).top(l+d/2).left(m+f).radius(d/2).lineWidth(0).strokeStyle(u).fillStyle(u);e.add(pv.Label).top(l+d/2).left(m+f/2).width(f).font("normal "+(c.fontSize+
1)+"px arial").textAlign("center").textBaseline("middle").text(a)}var x="#0047b2",y="#F7941E",z="#F5C649",A="#DB2852",E="#9D9D9D",B="#b71218",C="#c67a22",D="#ddbe18",v="#84858a",s="#f7fbfe",u="#cee8fb",F="#dee6f3",G=!1,H,J={height:50,width:50,lineWidth:1.5,innerRadius:9,outerRadius:21,outerRadiusStep:0,showLabels:!1,fillColors:["#FDDD03","#8DC63E"],strokeColors:["#3A983F"],textColors:["white"]},K={height:193,width:235,innerRadius:30,outerRadius:60,outerRadiusStep:7,fontSize:16,showLabels:!0,lineWidth:1},
L={width:267,height:183,fontSize:9},I={fontSize:9,leftPadding:0,rightPadding:0};H=function(){function e(b){if("number"===typeof b){if(8<=b)return 0;if(4<=b)return 1;if(0<b)return 2;if(0===b)return 3}else if("string"===typeof b){if("COPYLEFT"===b)return 0;if("NOT-PROVIDED"===b||"NON-STANDARD"===b)return 1;if("WEAKCOPYLEFT"===b)return 2;if("LIBERAL"===b)return 3}return 4}function a(b){var g={versions:[],versionPopularity:[],majorRevIndices:[],conflictVersions:[],effectiveLicenses:[],securityLevels:[[],
[],[]]};$.each(b.versions,function(a,c){var d=!1,n=!1,f=!1;g.versions.push(c.version);g.versionPopularity.push(c.popularity||c.relativePopularity||0);b.version===c.version&&(g.currentVersionIndex=a);c.majorRevisionStep&&g.majorRevIndices.push(a);g.effectiveLicenses.push(e(c.effectiveLicenseThreat||c.licenseThreatLevel));c.securityThreats?(-1!==$.inArray("Critical",c.securityThreats)&&g.securityLevels[0].push(a),-1!==$.inArray("Severe",c.securityThreats)&&g.securityLevels[1].push(a),-1!==$.inArray("Moderate",
c.securityThreats)&&g.securityLevels[2].push(a)):c.securityVulnerabilities&&0<c.securityVulnerabilities.length&&($.each(c.securityVulnerabilities,function(b,g){var a=e(g.severity);d=d||0===a;n=n||1===a;f=f||2<=a}),d&&g.securityLevels[0].push(a),n&&g.securityLevels[1].push(a),f&&g.securityLevels[2].push(a))});return g}function c(b){return function(g){return(b.barGap+b.barWidth)*g+b.barGap}}function d(b,g,a,c){var d=!1,e=!1,f=0,k=function(b){var a=g.transform().translate(b,0);b=f+b;10>b&&-10<c.width-
c.contentWidth+b?(f=b,g.transform(a).render()):e=d=!1},h=function(){d&&(k(10),setTimeout(h,100))},l=function(){e&&(k(-10),setTimeout(l,100))};a.add(pv.Dot).left(c.contentWidth-7).top(15+c.height/2).fillStyle(s).strokeStyle(v).angle(-Math.PI/2).shape("triangle").lineWidth(1).size(30).cursor("pointer").events("all").event("mouseover",function(){this.fillStyle(v).render()}).event("mouseout",function(){this.fillStyle(s).render();e=!1}).event("mousedown",function(){e=!0;setTimeout(l,0)}).event("mouseup",
function(){e=!1});a.add(pv.Dot).left(7).top(15+c.height/2).fillStyle(s).strokeStyle(v).angle(Math.PI/2).shape("triangle").lineWidth(1).size(30).cursor("pointer").event("all").events("all").event("mouseover",function(){this.fillStyle(v).render()}).event("mouseout",function(){this.fillStyle(s).render();d=!1}).event("mousedown",function(){d=!0;setTimeout(h,0)}).event("mouseup",function(){d=!1});return k}function f(b,g){var a=b.add(pv.Panel).def("i",-1),d=a.add(pv.Bar),e=d.anchor("bottom").add(pv.Label).visible(!1).textBaseline("top"),
f=c(g),k=null;d.data(g.data.versions).width(g.spacer-1).left(function(){return g.left+f(this.index)-1}).top(g.topPadding).height(q.partialDisplay?g.height:g.height-20).lineWidth(0).strokeStyle(s).fillStyle("transparent").events("all").event("mouseover",function(){a.i(this.index);this.render();e.visible(function(b){return a.i()===this.index}).textAlign(0===this.index?"left":this.index===g.data.versions.length-1?"right":"center").render()}).event("mouseout",function(){a.i(-1);this.render();e.visible(!1).render()}).fillStyle(function(b){return a.i()===
this.index?pv.color("rgba(153, 204, 255, 0.5)"):this.index===k?pv.color("rgba(10, 10, 10, 0.15)"):"transparent"}).strokeStyle(function(b){return this.index===k?pv.color("rgba(10, 10, 10, 0.5)"):pv.color("rgba(255, 255, 255,0.1)")}).lineWidth(1);g.selectable&&(k=g.data.currentVersionIndex,d.event("click",function(){g.versionClick(this.data());k=this.index;this.render()}),d.event("dblclick",function(){g.versionDblClick(this.data())}))}function l(b,g){var a=g.data,d=1,e=a.versionPopularity.length,f=
c(g),k=b.add(pv.Panel),h=g.barHeight-3;k.width(g.width).height(g.barHeight).top(g.top).left(g.left);$.each(a.versionPopularity,function(b,a){d=Math.max(d,a)});d=1/d;$.each(a.majorRevIndices,function(b,g){if(g>a.currentVersionIndex)return e=g,!1});k.add(pv.Bar).data(a.versionPopularity).width(g.barWidth).left(function(){return f(this.index)}).height(function(b){return h*b*d+3}).bottom(0).fillStyle(function(b){return this.index<a.currentVersionIndex?"#a8a9ad":this.index>=e?"#6d97d0":this.index===a.currentVersionIndex?
"#58585a":"#8bc73e"});k.add(pv.Rule).width(g.contentActualWidth+g.barGap).bottom(0).left(0).strokeStyle("#949599");g.top+=g.barHeight+g.spacer;return b}function m(b,a){b.add(pv.Panel).width(a.width).top(a.top).height(a.spacer).left(3).add(pv.Bar).top(1).data(a.vGridLines).width(a.barWidth+a.barGap-1.5).height(a.barWidth+a.barGap-1.5).left(function(){return this.data()-2}).fillStyle("#edf1f4")}function r(b,a){b.add(pv.Panel).width(a.width).top(a.top).height(a.spacer).left(a.left).add(pv.Bar).top(a.barGap/
2).data(a.data.effectiveLicenses).width(a.barWidth).height(a.barWidth).left(function(){return c(a)(this.index)}).fillStyle(function(b){switch(b){case 0:return A;case 1:return y;case 2:return z;case 3:return x;default:return E}}).strokeStyle(function(b){switch(b){case 0:return A;case 1:return y;case 2:return z;case 3:return x;default:return E}});a.top+=2*a.spacer;return b}function p(b,a){$.each(a.data.securityLevels,function(d,e){var k=b.add(pv.Panel).width(a.width).top(a.top).height(a.spacer).left(a.left),
f=v,h=E;switch(d){case 0:h=A;f=B;break;case 1:h=y;f=C;break;case 2:h=z,f=D}k.add(pv.Dot).data(e).left(function(b){return a.barWidth/2+c(a)(b)+1}).radius(a.barWidth/2-0.5).fillStyle(h).strokeStyle(f).angle(-Math.PI/2).shape("triangle");a.top+=a.spacer});return b}function h(b){var a=[],c=$("#aiVersionChartContainer"),e,h,n,t;b=$.extend({},q,b);if(0!==c.length){$.each(k,function(a,c){b[a]=c.call(k,b)});c.height(b.actualHeight);c=(new pv.Panel).canvas("aiVersionChartLabels").height(b.actualHeight).width(b.labelWidth).fillStyle(s).strokeStyle(s);
n=(new pv.Panel).canvas("aiVersionChartViz").overflow("hidden").height(b.actualHeight).width(b.contentWidth).fillStyle(s).strokeStyle(s);b.panning&&(e=n,n=e.add(pv.Panel).overflow("hidden").height(b.actualHeight).width(b.contentWidth-30).fillStyle(s).strokeStyle(s).left(15));for(t=0;t<=b.spacer*b.contentRows;t+=b.spacer)a.push(t);n.add(pv.Rule).data(a).left(0).width(b.width).top(function(a){return a+b.topPadding}).height(1).strokeStyle(F).strokeDasharray("1 1");b.vGridLines=[0];for(t=(b.width/2-1)%
b.spacer-b.spacer/2-0.5;t<b.width;t+=b.spacer)b.vGridLines.push(t);n.add(pv.Rule).data(b.vGridLines).left(function(b){return b}).height(b.height-b.topPadding).top(b.top).strokeStyle(F).strokeDasharray("1 1");$.each(b.partialDisplay?[]:[5,7,8,9],function(a,c){m(n,$.extend({},b,{top:b.top+(c-1)*b.spacer}))});0!==b.versionCount&&(n.add(pv.Rule).left(b.width/2-1).top(b.topPadding).height(b.height-b.topPadding).strokeStyle("#949599"),n.add(pv.Label).left(b.width/2-70).top(15).textAlign("center").text("Older"),
n.add(pv.Label).left(b.width/2).top(15).textAlign("center").text("This Version"),n.add(pv.Label).left(b.width/2+70).top(15).textAlign("center").text("Newer"));c.add(pv.Label).left(0).top(b.top+b.labelTop).textAlign("left").text("Popularity");b.top+=1;l(n,b);b.partialDisplay||(c.add(pv.Label).left(0).top(b.top+10).textAlign("left").text("License Risk"),r(n,b),c.add(pv.Label).left(0).top(b.top+10).textAlign("left").text("Security Alerts"),p(n,b));0===b.versionCount?(w(n,"No Data",{width:b.contentWidth,
height:b.actualHeight}),c.render(),n.render()):(f(n,b),b.panning&&(h=d(c,n,e,b),b.contentWidth-=15),c.render(),n.render(),b.panning&&h(-(b.width/2-b.contentWidth+b.contentWidth/2)))}}var q={partialDisplay:!1,selectable:!1,barGap:3,barWidth:8,contentWidth:375,labelTop:14,labelWidth:100,topPadding:20,vizPadding:6,versionClick:$.noop,versionDblClick:$.noop},k={actualHeight:function(b){return this.height(b)+11+this.bottomPadding(b)},barHeight:function(b){return 3*(b.barWidth+b.barGap)-1},height:function(b){return b.topPadding+
this.contentRows(b)*(b.barWidth+b.barGap)+1},contentRows:function(b){return b.partialDisplay?4:10},bottomPadding:function(b){return b.partialDisplay?20:0},versionCount:function(b){return b.data.versions?b.data.versions.length:0},contentActualWidth:function(b){return(b.barWidth+b.barGap)*this.versionCount(b)},width:function(b){var a=b.data.currentVersionIndex;return 0<a?Math.max(b.contentWidth,2*((b.barWidth+b.barGap)*(Math.max(a,b.data.versions.length-a)+1)-b.barGap)):b.contentWidth},panning:function(b){return this.width(b)>
b.contentWidth},left:function(b){var a=b.data.currentVersionIndex;return 0>a?0:this.width(b)/2-(a*(b.barWidth+b.barGap)+b.barWidth/2+b.barWidth/2)},spacer:function(a){return a.barGap+a.barWidth},top:function(a){return a.topPadding}};return function(b){b.data=a(b.data);h(b)}}();$.extend(!0,window,{HealthCheck:{getAge:function(e,a){var c,d;c=(a?a.getTime():(new Date).getTime())-e.getTime();if(31104E6<c)c/=31104E6,d="year";else if(2592E6<c)c/=2592E6,d="month";else if(864E5<c)c/=864E5,d="day";else if(36E5<
c)c/=36E5,d="hour";else if(6E4<c)c/=6E4,d="minute";else return"some seconds";c=Math.floor(c);1<c&&(d+="s");return c+" "+d},artifactsChart:function(e,a){a=$.extend({},J,a);a.visTop=a.height/2;a.visLeft=a.width/2;a.h=a.height;a.w=a.width;this.donutChart([e,1-e],a)},licenseChart:function(e,a){a=$.extend({},K,a);if(0!==Math.max.apply(null,e))a.h=a.height,a.w=a.width,a.visTop=a.h/2+5,a.visLeft=a.w/2-3.5,a.fillColors=3===e.length?["#ed1b24","#ffde15",x]:["#ed1b24","#f89520","#ffde15",x],a.strokeColors=
3===e.length?[B,D,"#6185b7"]:[B,C,D,"#6185b7"],a.textColors=3===e.length?["#9d0c11","#83740d","white"]:["#9d0c11",C,"#83740d","white"],this.donutChart(e,a);else{var c=(new pv.Panel).width(a.width).height(a.height);null!=a.element&&c.canvas(a.element);w(c,"No Licenses Found",{height:a.height,width:a.width});c.render()}},donutChart:function(e,a){var c=0,d=[],f=[],l=[],m=[],r=-1,p=0,h,q,k,b;for(k=0;k<e.length;k++)0<e[k]&&(c+=e[k],d.push(e[k]),f.push(a.fillColors[k%a.fillColors.length]),l.push(a.strokeColors[k%
a.strokeColors.length]),m.push(a.textColors[k%a.textColors.length]));q=d.length-1;for(k=0;k<d.length;k++){if(0>r||d[k]>=d[r])r=k;b=0.01*c-d[k];0<b&&(d[k]=0.01*c,p+=b)}d[r]-=p;r=(new pv.Panel).width(a.w).height(a.h);null!=a.element&&r.canvas(a.element);h=r.add(pv.Wedge).data(d).left(a.visLeft).top(a.visTop).outerRadius(function(){return a.outerRadius+(q-this.index)*a.outerRadiusStep}).innerRadius(a.innerRadius).angle(function(a){return 2*(a/c)*Math.PI}).fillStyle(pv.colors(f).by(function(){return this.index})).lineWidth(function(b){return 0<
b?a.lineWidth:0}).strokeStyle(pv.colors(l).by(function(){return this.index}));a.showLabels&&h.add(pv.Label).left(function(){return 1===this.index&&0.61>h.angle()?a.visLeft+(this.innerRadius()-5)*Math.cos(h.midAngle()):a.visLeft+(this.outerRadius()+3)*Math.cos(h.midAngle())}).top(function(){return 1===this.index&&0.61>h.angle()?a.visTop+(this.innerRadius()-5)*Math.sin(h.midAngle()):a.visTop+(this.outerRadius()+3)*Math.sin(h.midAngle())}).font("bold "+a.fontSize+"px arial").text(function(a){return 0===
a||this.index===d.length-1?"":Math.round(100*(a/c))+"%"}).textStyle(pv.colors(m).by(function(){return this.index})).textAlign(function(){var a=0>h.midAngle()?2*Math.PI+h.midAngle():h.midAngle();return 2===this.index&&a>1.5*Math.PI?"left":0.31>Math.abs(a%Math.PI-Math.PI/2)?"center":1===this.index&&0.61>h.angle()?a>Math.PI/2&&a<1.5*Math.PI?"left":"right":a>Math.PI/2&&a<1.5*Math.PI?"right":"left"}).textBaseline(function(){var a=0>h.midAngle()?2*Math.PI+h.midAngle():h.midAngle();return 0.31>Math.abs((a+
Math.PI/2)%Math.PI-Math.PI/2)?"middle":1===this.index&&0.61>h.angle()?a>Math.PI?"top":"bottom":a>Math.PI?"bottom":"top"});r.render()},barChart:function(e,a){a=$.extend({},L,a);var c=e[0],d=!($.browser.msie||$.browser.mozilla&&4>$.browser.version),f=0,l=2*a.fontSize,m=5*a.fontSize,r=pv.Scale.ordinal(pv.range(e.length)).splitBanded(0,a.height-l,0.6),p,h,q;!0!==G&&(G=!0,p=document.createElement("div"),p.setAttribute("style","height:0px;width:0px;"),p.innerHTML="\x3csvg xmlns\x3d'http://www.w3.org/2000/svg' version\x3d'1.1'\x3e\x3cdefs\x3e\x3clinearGradient id\x3d'orangebar' x1\x3d'0%' x2\x3d'0%' y1\x3d'0%' y2\x3d'100%'\x3e\x3cstop offset\x3d'0%' style\x3d'stop-color:rgb(199,122,32);stop-opacity:1'\x3e\x3c/stop\x3e\x3cstop offset\x3d'100%' style\x3d'stop-color:rgb(248,149,32);stop-opacity:1'\x3e\x3c/stop\x3e\x3c/linearGradient\x3e\x3clinearGradient id\x3d'redbar' x1\x3d'0%' x2\x3d'0%' y1\x3d'0%' y2\x3d'100%'\x3e\x3cstop offset\x3d'0%' style\x3d'stop-color:rgb(190,31,36);stop-opacity:1'\x3e\x3c/stop\x3e\x3cstop offset\x3d'100%' style\x3d'stop-color:rgb(235,32,38);stop-opacity:1'\x3e\x3c/stop\x3e\x3c/linearGradient\x3e\x3clinearGradient id\x3d'yellowbar' x1\x3d'0%' x2\x3d'0%' y1\x3d'0%' y2\x3d'100%'\x3e\x3cstop offset\x3d'0%' style\x3d'stop-color:rgb(209,186,30);stop-opacity:1'\x3e\x3c/stop\x3e\x3cstop offset\x3d'100%' style\x3d'stop-color:rgb(255,222,29);stop-opacity:1'\x3e\x3c/stop\x3e\x3c/linearGradient\x3e\x3c/defs\x3e\x3c/svg\x3e",
document.body.firstChild?document.body.insertBefore(p,document.body.firstChild):document.body.appendChild(p));for(p=1;p<e.length;p++)c=Math.max(c,e[p]);p=0===c;f=function(){var a=[1,2,5,10,20,25,50,100,200,250,500,1E3,2E3,2500,5E3],b=[9,9,9,9,8,8,8,8,6,6,6,5,5,4,4],d;for(d=0;d<a.length;d++)if(c/a[d]<=b[d])return a[d];return a[a.length-1]}();c=0===c%f?c+f:Math.ceil(c/f)*f;h=pv.Scale.linear(0,c).range(0,a.width-m-10);q=(new pv.Panel).width(a.width).height(a.height);null!=a.element&&q.canvas(a.element);
q.add(pv.Panel).width(a.width-m).height(a.height-l-5).top(l+5).left(m).fillStyle(s).strokeStyle("#F2F5F8");q.add(pv.Label).text("Threat").top(a.fontSize-1).left(a.fontSize/2).font("normal "+a.fontSize+"px arial").textStyle("#575757").events("all").event("mouseover",pv.Behavior.tipsy({fade:!0,gravity:"w",html:!0,opacity:1,offset:35,title:function(){return"Sonatype utilizes the base score from the Common Vulnerability Scoring System, version 2."}})).textAlign("left").textBaseline("middle");q.add(pv.Label).text("Level").top(2*
a.fontSize-1).left(a.fontSize/2+3).font("normal "+a.fontSize+"px arial").textStyle("#575757").textAlign("left").textBaseline("middle");q.add(pv.Bar).data(e).top(function(){return l+r(this.index)}).text(function(a){return a}).event("mouseover",pv.Behavior.tipsy({fade:!0,gravity:"w",html:!0,opacity:1})).height(r.range().band).left(m).width(h).fillStyle(function(a){return 3>this.index?d?"url(#redbar)":"rgb(234,32,44)":7>this.index?d?"url(#orangebar)":"rgb(248,149,32)":d?"url(#yellowbar)":"rgb(255,222,29)"}).anchor("left").add(pv.Label).textAlign("center").left(m/
2).width(m).font("normal "+a.fontSize+"px arial").textStyle("#575757").strokeStyle("#575757").text(function(){return 10-this.index});f=pv.range(0,c+f,f);q.add(pv.Rule).data(f).top(l+5).left(function(a){return m+h(a)}).strokeStyle("#f1f4f9").add(pv.Rule).top(l).height(5).strokeStyle("#575757").anchor("top").add(pv.Label).text(h.tickFormat).font("normal "+a.fontSize+"px arial").textStyle("#575757");p&&w(q,"No Vulnerabilities Found",{width:a.width,height:a.height,rightPadding:10,leftPadding:m});q.render()},
punchCard:function(e,a){e=e||[];a=a||{};var c=[],d=-1,f,l,m;if(5<e.length){c=e.splice(5,e.length-5);for(f=0;f<c.length;f++)for(l=0;l<c[f].length;l++)e[4][l]+=c[f][l]}$.each(e,function(a,c){$.each(c,function(a,c){d=Math.max(d,c)})});l=(new pv.Panel).width(107).height(180);null!=a.element&&l.canvas(a.element);l.add(pv.Label).text("Dependency Depth").right(0).top(3).font("9px arial").textStyle("#575757").textAlign("right").textBaseline("top");for(f=0;5>f;f++)l.add(pv.Label).text(4<=f&&0<c.length?"5+":
f+1).font("9px arial").textStyle("#575757").left(3).top(36+32*f).textBaseline("middle");m=l.add(pv.Panel).bottom(0).right(0).width(87).height(160).strokeStyle("#eef2fb").fillStyle(s);for(f=1;5>f;f++)m.add(pv.Rule).strokeStyle("#eef2fb").top(32*f);$.each(e,function(a,c){$.each(c,function(c,e){0<e&&m.add(pv.Dot).data([e]).left(function(a){return 16+28*c}).top(16+32*a).size(function(a){return 144*(a/d)}).fillStyle(function(a){return 0===c?A:1===c?y:z}).strokeStyle(function(a){return 0===c?B:1===c?C:
D})})});0===e.length&&w(m,"No Components",{height:160,width:87});l.render()}},Insight:{ComponentInformation:H}})})();