
#
# Copyright (c) 2019-present Sonatype, Inc. All rights reserved.
# Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
# "Sonatype" is a trademark of Sonatype, Inc.
#

# https://hub.docker.com/_/python
FROM python:3.7-alpine

# no external python libraries needed at present, uncomment when requirements.txt present
#COPY requirements.txt ./
#RUN pip install --no-cache-dir -r requirements.txt
