
-repackageclasses zz

-dontusemixedcaseclassnames

-dontoptimize
-dontshrink
-dontnote

-dontwarn org.slf4j.**
-dontwarn ch.qos.logback.**
-dontwarn com.google.**
-dontwarn com.thoughtworks.xstream.**
-dontwarn de.schlichtherle.**
-dontwarn javax.enterprise.**
-dontwarn javax.mail.**
-dontwarn org.apache.**
-dontwarn org.bouncycastle.**
-dontwarn org.eclipse.sisu.**
-dontwarn org.osgi.**
-dontwarn org.junit.**
-dontwarn org.testng.**
-dontwarn junit.**
-dontwarn org.owasp.dependencycheck.**
-dontwarn org.joda.convert.**
-dontwarn org.tartarus.**
-dontwarn com.sun.**
-dontwarn org.jruby.**

# 3rd party stuff excluded from obfuscation
-keep class !com.sonatype.insight.**,!org.objectweb.** { *; }

# CLI entries
-keep public class com.sonatype.insight.scan.cli.PolicyEvaluatorCli { *; }
-keep public class com.sonatype.insight.scan.cli.TwistlockPolicyEvaluatorCli { *; }

# Logging support
-keep public class com.sonatype.insight.scan.cli.MarkerFilter { *; }

# DTOs used by XStream to build the scan report XML
-keepclassmembers public class com.sonatype.insight.scan.model.* { *; }

# DTO used to parse the JSON response from the server
-keepclassmembers public class com.sonatype.clm.dto.model.** { *; }

# DTO used to export result data
-keepclassmembers class com.sonatype.insight.brain.client.ResultData { *; }

-renamesourcefileattribute SourceFile
-keepattributes *Annotation*,Exceptions,InnerClasses,EnclosingMethod,Signature,SourceFile,LineNumberTable

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

