# Directory for data files.
sonatypeWork: ./sonatype-work/clm-server

# Base URL of the Sonatype CLM server for user facing links back to the server.
#baseUrl: http://localhost:8070/

# HTTP-specific options.
http:

  # The port on which the HTTP server listens for service requests.
  # Because Java cannot drop privileges in a POSIX system, these
  # ports cannot be in the range 1-1024. A port value of 0 will
  # make the OS use an arbitrary unused port.
  port: 8070

  # The port on which the HTTP server listens for administrative
  # requests. Subject to the same limitations as "port".
  adminPort: 8071

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: DEBUG

  # Logger-specific levels.
  loggers:
    "eu.medsea.mimeutil.MimeUtil2": INFO
    "org.apache.http": INFO
    "org.eclipse.jetty": INFO

  # Settings for logging to stdout.
  console:

    # If true, write log statements to stdout.
    enabled: true

    # Do not display log statements below this threshold to stdout.
    threshold: INFO

  # Settings for logging to a file.
  file:

    # If true, write log statements to a file.
    enabled: true

    # Do not write log statements below this threshold to the file.
    threshold: ALL

    # The file to which current statements will be logged.
    currentLogFilename: ./log/clm-server.log

    # When the log file rotates, the archived log will be renamed to this and gzipped. The
    # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
    # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
    #
    # If archive is true, this must be specified.
    archivedLogFilenamePattern: ./log/clm-server-%d.log.gz

    # The number of archived files to keep.
    archivedFileCount: 5