/*
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2012-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
*/
(function(){function a(a){var d=this;this.options=$.extend(!0,{},e,a);this.node=$("\x3cdiv id\x3d'informationPanel' class\x3d'informationPanel fullBorderedTable'\x3e\x3cdiv style\x3d'width:99%; padding-top: 5px; padding-left: 0.5%; padding-right: 0.5%;'\x3e\x3ca class\x3d'close'\x3e\x26times;\x3c/a\x3e\x3cul class\x3d'nav nav-tabs' style\x3d'margin-bottom:0px; !important'\x3e\x3c/ul\x3e\x3cdiv class\x3d'tab-content' style\x3d'overflow:hidden'\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");$(".close",this.node).click(function(){d.hide()});
this.plugins=[];Insight.InformationPanelPlugins.sort(function(a,b){return a.prototype.priority-b.prototype.priority});$.each(Insight.InformationPanelPlugins,function(a,b){var c=$('\x3cli data-info-plugin\x3d"'+a+'"\x3e\x3ca data-target\x3d"infoPanel'+a+'" data-toggle\x3d"tab"\x3e\x3c/a\x3e\x3c/li\x3e'),f=$('\x3cdiv class\x3d"tab-pane" id\x3d"infoPanel'+a+'"\x3e\x3c/div\x3e');$("ul.nav",d.node).append(c);$("div.tab-content",d.node).append(f);d.plugins.push(new b(f,d.options))});$('a[data-toggle\x3d"tab"]',
this.node).on("show",function(a){var b;null!==a.relatedTarget&&(b=$(a.relatedTarget.parentNode).data("info-plugin"),d.plugins[b].destroy(),$("#"+$(a.relatedTarget).data("target"),d.node).hide());null!==a.target&&(b=$(a.target.parentNode).data("info-plugin"),a=$("#"+$(a.target).data("target"),d.node),a.show(),d.plugins[b].create(a,d.node))})}function g(a){a=a||{};this.priority=a.priority||512}var e={byHash:!1};a.prototype.destroy=function(){this.cleanPlugins()};a.prototype.hide=function(){this.node.detach();
this.grid.removeCellCssStyles("popout");this.cleanPlugins()};a.prototype.init=function(a){var d=this;this.grid=a;a.onClick.subscribe(function(){d.gridClickedFn.apply(d,arguments)});a.getData().onRowCountChanged.subscribe(function(){d.hide()});a.getData().onRowsChanged.subscribe(function(){d.rowChangedFn.apply(d,arguments)});$.each(this.plugins,function(d,b){b.setGrid(a)})};a.prototype.cleanPlugins=function(){$.each(this.plugins,function(a,d){d.destroy()})};a.prototype.gridClickedFn=function(a,d){var e=
this;"INPUT"!==a.target.tagName&&0===$(a.target).children("input:first").length&&(Insight.util.isNotNullOrUndefined(e.timer)?(clearTimeout(e.timer),e.timer=null):e.timer=setTimeout(function(){e.timer=null;$.each(e.plugins,function(a,c){c.setItem(e.grid.getDataItem(d.row))});e.toggle(a,d)},250))};a.prototype.getItem=function(){return this.grid.getDataItem(this.currentRow)};a.prototype.updatePanel=function(){var a=this,d=null;$.each(this.plugins,function(d,b){var c=$("li[data-info-plugin\x3d"+d+"]",
a.node);b.isVisible()?(c.show(),$("a",c).text(b.getTitle())):(c.hide(),$("#infoPanel"+d,a.node).hide(),c.hasClass("active")&&(c.removeClass("active"),$("ul.nav \x3e li:first",a.node).addClass("active")))});0===$("li.active",a.node).length&&$("li",a.node).each(function(a,b){b=$(b);if("none"!==b.css("display"))return b.addClass("active"),!1});d=$("li.active",a.node).data("info-plugin");a.plugins[d].create();$("#infoPanel"+d,a.node).show()};a.prototype.rowChangedFn=function(a,d){var e=this.currentRow,
b=this;setTimeout(function(){var a=b.grid.getSelectedRows(),d=null;Insight.util.isNotNullOrUndefined(e)&&1===a.length?e!==a[0]?(b.hide(),Insight.util.isNotNullOrUndefined(this.currentItemId)&&b.show({row:a[0],cell:1},b.grid.getCanvasNode())):(b.position(e),d=b.getItem(),$.each(b.plugins,function(a,c){c.setItem(d)}),b.updatePanel()):b.hide()},10)};a.prototype.toggle=function(a,d){this.grid.removeCellCssStyles("popout");$(this.node).is(":hidden")||this.currentRow!==d.row?this.show(this.grid.getCellFromEvent(a),
$(a.currentTarget)):this.hide()};a.prototype.show=function(a,d){var e={},b=this.grid.getCellNode(a.row,a.cell),c=$(this.grid.getCanvasNode()).parent();c.offset();c.height();var l=this;Insight.util.isNullOrUndefined(b)&&(this.grid.scrollRowIntoView(a.row),b=this.grid.getCellNode(a.row,a.cell));this.node.css("top",b.offsetParent.offsetTop+b.offsetParent.clientHeight);this.node.addClass("shadowBottom");this.node.removeClass("shadowTop");l.node.appendTo(d);this.updatePanel();l.position(a.row);l.node.show();
this.currentRow=a.row;e[this.currentRow]={};$.each(l.grid.getColumns(),function(a,c){e[l.currentRow][c.id]="popout"});l.grid.setCellCssStyles("popout",e)};a.prototype.position=function(a){var d=this.node.offset().top,e=d+this.node.height(),b=$(this.grid.getCanvasNode()).parent(),c=b.offset().top,l=c+b.height(),g=this.grid.getCellNode(a,1);Insight.util.isNullOrUndefined(g)&&(this.grid.scrollRowIntoView(a),g=this.grid.getCellNode(a,1));(e>l||d<c)&&b.scrollTop(b.scrollTop()+(this.node.offset().top-g.offsetParent.clientHeight)-
b.offset().top);this.node.css("width",b.width()-(b.get(0).scrollHeight>b.height()?this.grid.getScrollbarDimensions().width:0)-2+"px")};g.prototype.getErrorFn=function(a,d,e){return function(){var b=$(a);b.html(Insight.templates.error.render());$(".btn",b).click(function(){d.apply(e,[])})}};g.prototype.isVisible=function(){return!0};g.prototype.getTitle=function(){return""};g.prototype.setItem=function(a){this.gav=a};g.prototype.message=function(a){$(".alert",this.node).remove();a=$('\x3cdiv class\x3d"alert" style\x3d"width:92.5%"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3e\x3c/div\x3e');
$("div:first",this.node).prepend(a);return a};g.prototype.addErrorMessage=function(a){this.message(a).addClass("alert-error").append("\x3cstrong\x3eError: \x3c/strong\x3e",$("\x3cspan\x3e\x3c/span\x3e").text(a))};g.prototype.addSuccessMessage=function(a){var d=this.message(a).addClass("alert-success").append($("\x3cspan\x3e\x3c/span\x3e").text(a));setTimeout(function(){d.fadeOut("fast",function(){d.remove()})},8E3);return d};g.prototype.setGrid=function(a){this.grid=a};g.prototype.create=$.noop;g.prototype.destroy=
$.noop;$.extend(!0,window,{Insight:{InformationPanel:a,InformationPanelPlugin:g,InformationPanelPlugins:[]}})})();
(function(){function a(a,e){var b=[],c=$("\x3cdiv\x3e\x3c/div\x3e");return Insight.util.isNotNullOrUndefined(a)&&0<a.length?("object"===typeof a[0]?$.each(a,function(a,d){b.push(c.text(d.licenseName).html())}):$.each(a,function(a,d){b.push(c.text(d).html())}),'\x3cspan class\x3d"license"\x3e'+b.join(',\x3c/span\x3e \x3cspan class\x3d"license"\x3e')+"\x3c/span\x3e"):e||""}function g(d,e,b){var c="artifactInfoSecurity",g=Math.floor(d.securityThreatLevel);$(e).is(":hidden")||(0>=d.securityThreatCount?
(g="NA",c+=" artifactInfoSecurityUnspecified"):8<=g?c+=" artifactInfoSecurityCritical":4<=g?c+=" artifactInfoSecuritySevere":(0<=g||(g="Unscored"),c+=" artifactInfoSecurityModerate"),d=$.extend(d,{partial:!1,overriddenLicenses:a(d.overriddenLicenses,"-"),declaredLicenses:a(d.declaredLicenses,"-"),observedLicenses:a(d.observedLicenses,"-"),currentMatchState:b.matchState,proprietary:b.proprietary,colorCls:c,lvl:g,cataloged:d.catalogDate?HealthCheck.getAge(new Date(d.catalogDate)):null,multipleSecurity:1<
d.securityThreatCount,isManual:"Manual"===d.identificationSource}),e.html(f.render(d)),$.event.trigger("artifactInfoPanelLoading",{data:d,node:e,partialDisplay:!1,gav:b}),Insight.ComponentInformation({data:d,partialDisplay:!1}))}function e(a,e){this.node=a;this.options=e}var f;$(document).ready(function(){f=Hogan.compile($("#infoPanelComponentTemplate").html())});e.prototype=new Insight.InformationPanelPlugin({priority:1});e.prototype.create=Brain.ci&&Brain.ci.getArtifactVersionInfoUrl?function(){var a=
this,e=a.gav,b=null,c=null,f=null,k=null,s=function(){null!==c&&(null!==b&&e===a.gav)&&(c.securityThreatCount=0,c.securityThreatLevel=null,$.each(c.securityVulnerabilities,function(a,b){"Not Applicable"!==b.status&&(c.securityThreatCount++,Insight.util.isNotNullOrUndefined(b.severity)&&(c.securityThreatLevel=Math.max(c.securityThreatLevel,b.severity)))}),c.versions=b,g(c,a.node,e))};Insight.util.isNullOrUndefined(this.gav.groupId)||Insight.util.isNullOrUndefined(this.gav.artifactId)||Insight.util.isNullOrUndefined(this.gav.version)?
this.node.html("\x3cdiv class\x3d'infoPanelText'\x3eUnknown Component\x3c/div\x3e"):($(this.node).html('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e'),f=$.extend({},this.gav,{appId:applicationId,instanceId:instanceId}),k=Brain.ci.getComponentDetailsListUrl?Brain.ci.getComponentDetailsListUrl(f):Brain.ci.getArtifactVersionInfoUrl(f),$.getJSON(Insight.toBrain(Brain.ci.getArtifactInfoUrl(f)),function(a){c=
a;s()}).error(this.getErrorFn(this.node,this.create,this)),$.getJSON(Insight.toBrain(k),function(a){b=a.list?a.list:a;s()}).error(this.getErrorFn(this.node,this.create,this)))}:function(){var a=this,e=a.gav;Insight.util.isNullOrUndefined(this.gav.groupId)||Insight.util.isNullOrUndefined(this.gav.artifactId)||Insight.util.isNullOrUndefined(this.gav.version)?this.node.html("\x3cdiv class\x3d'infoPanelText'\x3eUnknown Artifact\x3c/div\x3e"):($(this.node).html('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e'),
$.getJSON("../artifactDetails/"+reportId+"?groupId\x3d"+this.gav.groupId+"\x26artifactId\x3d"+this.gav.artifactId+"\x26version\x3d"+this.gav.version,function(b){a.gav===e&&g(b,$(a.node),e)}).error(this.getErrorFn(this.node,this.create,this)))};e.prototype.destroy=function(){this.node.empty()};e.prototype.getTitle=function(){return"Component Info"};Insight.InformationPanelPlugins.push(e)})();
(function(){function a(a,e){this.node=a;this.options=e}a.prototype=new Insight.InformationPanelPlugin({priority:32});a.prototype.isVisible=function(){return"unknown"!==this.gav.matchState&&Brain.hasFeature("policy-violations")};a.prototype.create=function(){var a=(new Date).getTime(),e=$('\x3cdiv id\x3d"policy-violations-'+a+'"\x3e\x3c/div\x3e'),f=this,d=function(){Insight.PolicyViolations?Insight.PolicyViolations(e,applicationId,f.gav.hash):setTimeout(d,1E3)};this.node.empty();e.appendTo(this.node);
d()};a.prototype.destroy=function(){this.node.empty()};a.prototype.getTitle=function(){return"Policy"};Insight.InformationPanelPlugins.push(a)})();
(function(){function a(a,e){this.node=a;this.options=e}a.prototype=new Insight.InformationPanelPlugin({priority:48});a.prototype.isVisible=function(){return!0};a.prototype.create=function(){var a=this;this.destroy();this.gav.hash?$.getJSON("partialmatched.json",function(e){var f=null,d;for(d=0;d<e.aaData.length;d++)if(e.aaData[d].hash===a.gav.hash){f=e.aaData[d].matchDetails;break}f?($(a.node).html("\x3cdiv id\x3d'similarityTable' class\x3d'borderedTable'\x3e\x3c/div\x3e"),InsightDatatable.createSimilarityTable(f)):
$(a.node).html("\x3cdiv class\x3d'infoPanelText'\x3eNo similar matches were found for this component.\x3c/div\x3e")},this.getErrorFn(a.node,a.create,a)):$(a.node).html("\x3cdiv class\x3d'infoPanelText'\x3eNo similar matches were found for this component.\x3c/div\x3e")};a.prototype.destroy=function(){InsightDatatable.removeSimilarityTable();this.node.empty()};a.prototype.getTitle=function(){return"Similar"};Insight.InformationPanelPlugins.push(a)})();
(function(){function a(a){var f,d;if(0===a.indexOf("dependency:/"))return a=a.substring(12),f=a.lastIndexOf("/"),0>f?["Dependency "+a,""]:["Dependency "+a.substring(f+1),"Module "+a.substring(0,f)];f=a.lastIndexOf("/");if(-1===f)return[a,""];d=a.substring(f+1);a=a.substring(0,f);return[d,a]}function g(a,f){this.node=a;this.options=f}g.prototype=new Insight.InformationPanelPlugin({priority:64});g.prototype.buildView=function(e){if(0<e.length){e.sort();var f="\x3cdiv class\x3d'infoPanelText fileDetail'\x3e",
d=!1;$.each(e,function(e,b){$.each(b.pathnames,function(c,b){var d=a(b);f+="\x3cb\x3e"+d[0]+"\x3c/b\x3e";0<d[1].length&&(f+=" \x3ci\x3elocated at\x3c/i\x3e "+d[1]);f+="\x3cbr\x3e\x3cbr\x3e"});0>=b.pathnames.length&&(d=!0)});d&&(f+="Occurrences of this component cannot be listed because pathnames have been anonymized. To see all occurrences, please disable anonymization in the options of your CLM enforcement points and perform a new scan.");f+="\x3c/div\x3e";$(this.node).html(f)}else $(this.node).html("\x3cdiv class\x3d'infoPanelText'\x3eInvalid data encountered, no files are associated with this component.\x3c/div\x3e")};
g.prototype.create=function(){var a=this;a.options.byHash?this.buildView([a.gav]):$.getJSON("bom.json",function(f){var d=[];$.each(f.aaData,function(f,b){b.groupId===a.gav.groupId&&(b.artifactId===a.gav.artifactId&&b.version===a.gav.version)&&d.push(b)});a.buildView(d)},this.getErrorFn(a.node,a.create,a))};g.prototype.destroy=function(){};g.prototype.getTitle=function(){return"Occurrences"};Insight.InformationPanelPlugins.push(g)})();
(function(){function a(a,f,d,g,b,c,l,k){Insight.util.isNotNullOrUndefined(a[d])?g.call(k,{aaData:l.getData().getItems()},!0):$.getJSON(f,function(a){g.call(this,a,!1)}).error(c)}function g(a){var f=$(a.getCanvasNode()).parents("[data-container\x3dtrue]").attr("id"),d,f=f.substring(0,f.length-9);"component"===f&&(d=a.getSelectedRows(),1===d.length&&(f=a.getData(),f.beginUpdate(),a=a.getDataItem(d[0]),a.modified=!0,f.updateItem(a.id,a),f.endUpdate()))}(function(){function e(a,e){this.node=a;this.options=
e}var f=null;$(document).ready(function(){f=Hogan.compile($("#infoPanelLicenseEditor").html())});e.prototype=new Insight.InformationPanelPlugin({priority:80});e.prototype.toLicense=function(d,e){var b=this;a(this.gav,"licenses.json","effectiveLicenses",function(a,e){$.each(a.aaData,function(a,c){if(c.groupId===b.gav.groupId&&c.artifactId===b.gav.artifactId&&c.version===b.gav.version)return d.call(b,c,e),!1})},d,e,this.grid,this)};e.prototype.isVisible=function(){return"unknown"!==this.gav.matchState||
"Manual"!==this.gav.identificationSource};e.prototype.create=function(){this.destroy();var a=(new Date).getTime(),e=$('\x3cdiv id\x3d"licenseEditor'+a+'"\x3e\x3c/div\x3e').appendTo(this.node),b=this;this.toLicense(function(c,l){var k={timestamp:a,width:400,callback:function(a){Insight.util.isNullOrUndefined(a)?(g(b.grid),b.addSuccessMessage("Updated license for "+c.groupId+":"+c.artifactId+":"+c.version)):b.addErrorMessage(a)},single:!0};l?(k.dataView=b.grid.getData(),k.artifacts=[b.gav]):(k.dataView=
new Slick.Data.DataView,c.id=0,k.dataView.setItems([c]),k.artifacts=[c]);$(e).html(f.render({timestamp:a}));b.licenseEditor=new InsightDatatable.LicenseEditor(k);b.licenseEditor.show($("#editor"+a,b.node));InsightDatatable.loadLicenseThreats(function(a){var b="",b=b+'\x3cli class\x3d"nav-header"\x3eDeclared Licenses\x3c/li\x3e';$.each(c.declaredLicenses,function(c,d){b+='\x3cli class\x3d"license"\x3e\x3cdiv class\x3d"'+InsightDatatable.getLicenseThreatClass(a[d])+'"\x3e '+d+"\x3c/div\x3e\x3c/li\x3e"});
b+='\x3cli class\x3d"divider"\x3e\x3c/li\x3e\x3cli class\x3d"nav-header"\x3eObserved Licenses\x3c/li\x3e';$.each(c.observedLicenses,function(c,d){b+='\x3cli class\x3d"license"\x3e\x3cdiv class\x3d"'+InsightDatatable.getLicenseThreatClass(a[d])+'"\x3e '+d+"\x3c/div\x3e\x3c/li\x3e"});$(b).appendTo($("#licenseList",e))})},this.getErrorFn(this.node,this.create,this))};e.prototype.destroy=function(){$("a",this.node).unbind("click");this.licenseEditor&&this.licenseEditor.destroy();this.node.empty()};e.prototype.getTitle=
function(){return"Edit License"};Insight.InformationPanelPlugins.push(e)})();(function(){function e(a,e){this.node=a;this.options=e}var f=null;$(document).ready(function(){f=Hogan.compile($("#infoPanelSecurityEditor").html())});e.prototype=new Insight.InformationPanelPlugin({priority:96});e.prototype.toSV=function(d,e){var b=this;a(this.gav,"security.json","reference",function(a,e){var f=[];$.each(a.aaData,function(a,c){c.groupId===b.gav.groupId&&(c.artifactId===b.gav.artifactId&&c.version===b.gav.version)&&
f.push($.extend({},c,{id:a}))});d.call(this,f,e)},d,e,this.grid,this)};e.prototype.isVisible=function(){return"unknown"!==this.gav.matchState&&"Manual"!==this.gav.identificationSource};e.prototype.create=function(){this.destroy();var a=(new Date).getTime(),e=$('\x3cdiv id\x3d"svEditor'+a+'" style\x3d"width:100%"\x3e\x3c/div\x3e').appendTo(this.node),b=this,c;this.toSV(function(l,k){var s="sv"+a,t=new Slick.CheckboxSelectColumn,r={timestamp:a,width:300,callback:function(a){Insight.util.isNullOrUndefined(a)?
(g(b.grid),a=c.table.getSelectedRows(),1===a.length?b.addSuccessMessage("Updated "+a.length+" security vulnerability."):1<a.length&&b.addSuccessMessage("Updated "+a.length+" security vulnerabilities.")):b.addErrorMessage(a)},artifacts:[]};$(e).html(f.render({timestamp:a}));c=new Insight.Table(s,l,{resizeFn:$.noop,height:"220px",width:"100%",disableFilter:!0,selectable:!0,dataProcessor:function(a){var d,h,e;for(e=0;e<a.length;e++)a[e].id=e,a[e]._score=Insight.util.isNullOrUndefined(a[e].score)?"Unscored":
String(Math.floor(a[e].score)),d=a[e].source,h=a[e].reference,a[e]._reference=Insight.util.isNullOrUndefined(d)||0===h.toUpperCase().indexOf(d.toUpperCase())?h:d+"-"+h;k&&setTimeout(function(){$.each(a,function(a,e){if(e.source===b.gav.source&&e.reference===b.gav.reference)return c.table.setSelectedRows([c.table.getData().getRowById(e.id)]),!1})},1);return a},defaultSort:{columnId:"_score",sortAsc:!1},plugins:[t],columns:[t.getColumnDefinition(),{id:"_score",name:"Threat Level",field:"_score",sortable:!0,
width:90,minWidth:90,toolTip:"'Threat Level' highlights the CVSS (Common Vulnerability Scoring System, version 2) base score for each listed vulnerability.",styleFn:function(a,b,c,e,d){return"nopad"},sortFn:function(a,b){var c=a._score,e=b._score;return!isNaN(c)&&!isNaN(e)?parseInt(c)-parseInt(e):e<c?-1:e>c?1:0},formatter:function(a,c,b,e,d){return'\x3cdiv class\x3d"'+(8<=b?" criticalScore":4<=b?" severeScore":" moderateScore")+'"\x3e'+(b||"\x26nbsp;")+"\x3c/div\x3e"}},{id:"problemCode",name:"Problem Code",
field:"_reference",sortable:!0,width:90,minWidth:90,formatter:function(a,b,c,e,d){a=d._reference;d=d.url;return Insight.util.isNullOrUndefined(a)?"":'\x3ca href\x3d"'+d+'" target\x3d"_blank"\x3e'+a+"\x3c/a\x3e"}},{id:"status",name:"Status",field:"status",sortable:!0,width:90,minWidth:90,sortFn:function(a,b){a=Insight.util.isNotNullOrUndefined(a.status)?a.status:"Open";b=Insight.util.isNotNullOrUndefined(b.status)?b.status:"Open";return a>b?1:a<b?-1:0},formatter:function(a,b,c,e,d){return Insight.util.isNotNullOrUndefined(c)?
c:"Open"}}]});$.extend(r,{dataViews:[c.table.getData()],grid:c.table});$("#"+s+"Table").data("data-slickgrid",c.table).attr("data-slickgrid",!0).click(function(a){"A"===a.target.nodeName&&window.open($(a.target).attr("href"),"_blank");return!1});k&&r.dataViews.push(this.grid.getData());(new InsightDatatable.SecurityEditor(r)).show("#editor"+a)},this.getErrorFn(this.node,this.create,this))};e.prototype.destroy=function(){$("[data-slickgrid]",this.node).each(function(){$(this).data("data-slickgrid").destroy()});
this.node.empty()};e.prototype.getTitle=function(){return"Edit Vulnerabilities"};Insight.InformationPanelPlugins.push(e)})()})();
(function(){function a(a,e){this.node=a;this.options=e}a.prototype=new Insight.InformationPanelPlugin({priority:112});a.prototype.isVisible=function(){return"unknown"!==this.gav.matchState&&Brain.hasFeature("labels")};a.prototype.create=function(){var a=(new Date).getTime(),e=$('\x3cdiv id\x3d"labels-'+a+'"\x3e\x3c/div\x3e'),f=this,d=function(){Insight.LabelEditor?Insight.LabelEditor(e,applicationId,f.gav.hash,f.gav):setTimeout(d,1E3)};this.node.empty();e.appendTo(this.node);d()};a.prototype.destroy=
function(){this.node.empty()};a.prototype.getTitle=function(){return"Labels"};Insight.InformationPanelPlugins.push(a)})();
(function(){function a(a){a.html("\x3cdiv style\x3d'width:99%;padding:7px 0 5px 1%;vertical-align:-12px;'\x3eNo changes were found for this component.\x3c/div\x3e")}function g(a,f){this.node=a;this.options=f}g.prototype=new Insight.InformationPanelPlugin({priority:99999});g.prototype.isVisible=function(){return"unknown"!==this.gav.matchState};g.prototype.create=function(){var e=this;this.gav.artifactId?$.getJSON("../auditLog/licenses.json+security.json","key\x3d"+JSON.stringify(this.gav,["hash","groupId",
"artifactId","version"]),function(f){f?(e.node.html('\x3cdiv id\x3d"auditTable" class\x3d"borderedTable"\x3e\x3c/div\x3e'),InsightDatatable.createAuditTable(f.aaData)):a(e.node)}).error(this.getErrorFn(this.node,this.create,this)):a(this.node)};g.prototype.destroy=function(){InsightDatatable.removeAuditTable();this.node.empty()};g.prototype.getTitle=function(){return"Audit Log"};Insight.InformationPanelPlugins.push(g)})();
(function(){function a(a){return null===a||"undefined"===typeof a}$.extend(!0,window,{Insight:{toBrain:function(a){return"/"===a.charAt(0)?"../brain"+a:"../brain/"+a},util:{enableTooltip:function(a){$(a).each(function(){var a=$(this).attr("data-gravity-offset")||0;a&&(a=parseInt(a,10));$(this).tipsy({fade:!0,gravity:$(this).attr("data-gravity"),offset:a,html:!0,opacity:1,delayOut:0,title:"data-tooltip"})})},getErrorMessage:function(a){var e="";return e=0===a.status||1E3<=a.status?"Network error while contacting server":
a.responseText&&0<=(a.getResponseHeader("Content-Type")||"").indexOf("text/plain")?a.responseText:a.statusText?a.statusText:"Error "+a.status},getQueryParameter:function(a){var e=0<window.location.search.length?window.location.search.substring(1).split("\x26"):[],f=null,d=null;a=a.toLowerCase();for(d=0;d<e.length;d++)if(f=e[d].split("\x3d"),f[0].toLowerCase()===a)return f[1]},isNullOrUndefined:a,isNotNullOrUndefined:function(g){return!a(g)}}}})})();
(function(){function a(a){var c={criticalCount:0,severeCount:0,moderateCount:0,noThreatCount:0};"undefined"!==typeof a.effectiveLicenseCounts?$.each(a.effectiveLicenseCounts,function(a,b){7<a?c.criticalCount+=b:3<a?c.severeCount+=b:0<a?c.moderateCount+=b:c.noThreatCount+=b}):(c.criticalCount=a.copyleftLicenseCount,c.severeCount=a.nonStandardLicenseCount+a.notProvidedLicenseCount,c.moderateCount=a.weakcopyleftLicenseCount,c.noThreatCount=a.liberalLicenseCount);c.count=c.criticalCount+c.severeCount+
c.moderateCount+c.noThreatCount;c.licenseAlerts=c.criticalCount+c.severeCount+c.moderateCount;c.multipleLicenseAlerts=1!==c.licenseAlerts;return c}function g(a){var c={criticalCount:0,severeCount:0,moderateCount:0,count:0};$.each(a.securityCounts,function(a,b){6<a?c.moderateCount+=b:2<a?c.severeCount+=b:c.criticalCount+=b;c.count+=b});c.multiple=1!==c.count;c.insecureArtifactCount=a.insecureArtifactCount;c.multipleComponents=1<c.insecureArtifactCount;return c}function e(a){var c={oldBrain:Insight.util.isNullOrUndefined(a.policyCounts),
criticalCount:0,severeCount:0,moderateCount:0};if(c.oldBrain)return c;c.policyComponentCount=a.policyComponentCount;c.multipleComponents=0<c.policyComponentCount;$.each(a.policyCounts,function(a,b){8<=a?c.criticalCount+=b:4<=a?c.severeCount+=b:1<a&&(c.moderateCount+=b)});c.multipleAlerts=1<c.criticalCount+c.severeCount+c.moderateCount?!0:!1;c.hasPolicyAlerts=0<c.criticalCount+c.severeCount+c.moderateCount?!0:!1;return c}function f(){var b=$("#summary"),c=function(a,c,d){b.empty();b.append(Insight.templates.error.render({message:Insight.util.getErrorMessage(a)}));
$("button",b).click(f)};b.html('\x3cdiv class\x3d"alert alert-info"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e');$.getJSON("data.json").success(function(f){if(null===f)c({status:0});else{var k={policy:e(f),sv:g(f),license:a(f)},u=b.is(":visible");b.hide();b.html(d.render(k));HealthCheck.barChart(f.securityCounts,{element:$("#security-chart")[0]});HealthCheck.punchCard(f.securityPunchCard,{element:$("#security-punchcard")[0]});HealthCheck.licenseChart([k.license.criticalCount/k.license.count,
k.license.severeCount/k.license.count,k.license.moderateCount/k.license.count,(k.license.count-k.license.licenseAlerts)/k.license.count],{element:$("#license-chart")[0]});HealthCheck.punchCard(f.licensePunchCard,{element:$("#license-punchcard")[0]});0<f.totalArtifactCount?HealthCheck.artifactsChart(1-f.knownArtifactCount/f.totalArtifactCount,{element:$("#coverage_donut")[0]}):HealthCheck.artifactsChart(0);u&&b.fadeIn();Insight.util.enableTooltip($("[data-tooltip]",summary))}}).error(c)}var d,u;$(document).ready(function(){d=
Hogan.compile($("#summaryPageTemplate").html());u=Hogan.compile($("#errorTemplate").html());Hogan.compile($("#licenseEditorTemplate").html());Hogan.compile($("#svEditorTemplate").html());$.extend(!0,window,{Insight:{templates:{error:u},updateSummary:f}});$("button[data-containerid]").click(function(a){if(!$(this).hasClass("active")){a=$(this).data("containerid");var b;$("[data-container]").css("display","none");$("#"+a).css("display","");InsightDatatable.destroyActiveTable();switch(a){case "securitycontainer":b=
InsightDatatable.createSecurityTable({headerRowHeight:30});b.addLoadListener(function(){InsightDatatable.addSecurityTableEditor(b)});break;case "licensecontainer":b=InsightDatatable.createLicenseTable({headerRowHeight:30});b.addLoadListener(function(){InsightDatatable.addLicenseTableEditor(b)});break;case "componentcontainer":InsightDatatable.createComponentTable()}}});Insight.util.enableTooltip($("[data-tooltip]"));var a=$('[data-action\x3d"reevaluatePolicy"]');Brain.hasFeature("reevaluate-policy")?
a.click(function(){a.find("i").attr("class","icon-white icon-time");$.getJSON("../reevaluatePolicy").success(function(){a.find("i").attr("class","icon-white icon-refresh");location.reload()}).error(function(){$(".btn-group:eq(1)").after('\x3cdiv class\x3d"alert alert-error" style\x3d"margin:5px 0"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3eThere has been an error reevaluating policy. Try running the report again.\x3c/div\x3e')})}):a.hide();$.browser.msie&&9>
$.browser.version&&$(".btn-group:eq(1)").after('\x3cdiv class\x3d"alert alert-error" style\x3d"margin:5px 0"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3eYou are using older version of Internet Explorer (IE). You may notice degraded performance and/or functionality. To address this, download and install the latest version of IE, or other modern browser (e.g. Chrome, Firefox)\x3c/div\x3e');Insight.updateSummary()})})();
(function(){function a(a){var b=$(window).innerHeight(),c=$(a).offset().top;a=$("#"+a.attr("id")+"Pager").height();return Math.max(150,b-c-d-a)}function g(a){$("#"+a+"container .message").remove()}function e(a,b){var c=$("#"+a+"container"),d=$("#"+a+"Table").position(),e;null!==d&&(g(a),c.append('\x3cdiv class\x3d"message" style\x3d"top:'+(d.top+70)+'px"\x3e'+b+"\x3c/div\x3e"),e=$(".message",c),e.css("left",d.left+c.outerWidth()/2-e.outerWidth()/2+"px"))}function f(d,b,c){function e(b){q.destroyed||
(q.table=new Slick.Grid("#"+d+"Table",q.dataView,c.columns,r),c.selectable&&(q.table.setSelectionModel(new Slick.RowSelectionModel),q.dataView.syncGridSelection(q.table,!0)),t.init(q.table),x.css("height",c.height||a($("#"+d+"Table"))+"px"),q.processData(b),q.initialize())}function f(a){return function(b,c,d){b=x.empty().append(Insight.templates.error.render({message:d}));$("button",b).click(a)}}function g(a){x.empty().append('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e');
a.get().done(function(b){null!=b?e(b):f(function(){g(a)})()}).fail(f(function(){g(a)}))}var t=new Slick.Data.GroupItemMetadataProvider,r=$.extend({editable:!1,enableAddRow:!1,enableCellNavigation:c.enableCellNavigation,enableColumnReorder:!1,enableTextSelectionOnCells:!0,fullWidthRows:!0,forceFitColumns:!0,rowHeight:31,explicitInitialization:!0,showHeaderRow:!c.disableFilter,multiSelect:!1,autoHeight:c.autoHeight,multiColumnSort:c.multiColumnSort},c.config||{}),q=this,x=$("#"+d+"Table");this.options=
c;this.id=d;this.dataView=new Slick.Data.DataView({groupItemMetadataProvider:t});this.filter=new Slick.Filter;$.isArray(b)?e({aaData:b}):"string"===typeof b?g({get:function(){return $.getJSON(b)}}):"object"===typeof b?g(b):console.log("Unable to load: "+b)}var d=null;$.browser&&($.browser.mozilla&&4>parseFloat($.browser.version)?d=9:$.browser.msie&&9>parseFloat($.browser.version)&&(d=15));null===d&&(d=14);f.prototype.updateHeight=function(){var d=$("#"+this.id+"Table"),b=this;d.css("height",a(d)+
"px");window.clearTimeout(this.resizeTimeout);this.resizeTimeout=window.setTimeout(function(){b.table.resizeCanvas()},50)};f.prototype.destroy=function(){this.destroyed=!0;g(this.id);$(window).unbind("resize");this.table&&(this.table.pager&&(this.table.pager.destroy(),this.table.pager=null),this.table.columnsResizedFn&&(this.table.onColumnsResized.unsubscribe(this.table.columnsResizedFn),this.table.columnsResizedFn=null),this.table.destroy())};f.prototype.initialize=function(){var a=this;this.initialized||
(this.initialized=!0,this.options.defaultSort&&($.isArray(this.options.defaultSort)?this.table.setSortColumns(this.options.defaultSort):this.table.setSortColumns([this.options.defaultSort])),$.isArray(this.options.plugins)&&$.each(this.options.plugins,function(b,c){a.table.registerPlugin(c)}),this.table.registerPlugin(new Slick.Sort),this.table.init(),this.options.disableFilter||this.table.registerPlugin(this.filter),this.table.registerPlugin(new Slick.Tipsy),$(window).resize(this.options.resizeFn||
function(){Insight.util.isNullOrUndefined(a.options.height)&&a.updateHeight()}),this.listeners&&($.each(this.listeners,function(a,c){setTimeout(c,0)}),this.listeners=null))};f.prototype.processData=function(a){var b=this;this.initialize();Insight.util.isNotNullOrUndefined(a)&&(this.options.dataProcessor&&(a.aaData=this.options.dataProcessor.call(null,a.aaData)),this.dataView.beginUpdate(),this.dataView.setItems(a.aaData),this.options.disableFilter||(this.options.externalFilters?this.dataView.setFilter(function(a,
d){var e=!0;$.each(b.options.externalFilters,function(b,f){f(a,d)||(e=!1);return e});return e&&b.filter.getFilter()(a,d)}):this.dataView.setFilter(this.filter.getFilter())),this.options.groupInfo&&this.dataView.groupBy(this.options.groupInfo.field,this.options.groupInfo.groupHeaderFn,this.options.groupInfo.groupingComparer),this.dataView.endUpdate(),this.options.groupInfo&&"collapsed"===this.options.groupInfo.initialState&&(this.dataView.beginUpdate(),$.each(this.dataView.getGroups(),function(a,d){b.dataView.collapseGroup(d.value)}),
this.dataView.endUpdate()));g(this.id);if(Insight.util.isNullOrUndefined(a)||0===a.aaData.length)e(this.id,this.options.emptyText||"None");this.options.disablePager||(this.table.pager=new Slick.Controls.Pager(this.dataView,this.table,$("#"+this.id+"TablePager")))};f.prototype.addMessage=function(a,b,c){var d=this,e=$('\x3cdiv class\x3d"alert"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3e\x3c/div\x3e');e.addClass(b);e.append("\x3cspan\x3e\x3c/span\x3e").text(a);
e.bind("closed",function(){d.updateHeight()});$("#"+d.id+"container").prepend(e);d.updateHeight();c&&setTimeout(function(){e.fadeOut("fast",function(){e.remove();d.updateHeight()})},1E3*c);return e};f.prototype.addLoadListener=function(a){this.table?setTimeout(a,0):(this.listeners=this.listeners||[],this.listeners.push(a))};f.prototype.addSuccess=function(a,b){this.addMessage(a,"alert-success",b)};f.prototype.addError=function(a,b){this.addMessage(a,"alert-error",b)};$.extend(!0,window,{Insight:{Table:f}})})();
(function(){function a(a){Insight.util.isNotNullOrUndefined(q)?a.apply(null,[q]):$.getJSON("licensethreats.json").success(function(b){q=b.aaData;a.apply(null,[q])}).error(function(b,c,d){a.apply(null,[null,"Loading license categorization: "+Insight.util.getErrorMessage(b)])})}function g(){for(var a=null,b=0;b<arguments.length;b++)for(var c=arguments[b],d=0;d<c.length;d++){var e=q[c[d]];Insight.util.isNotNullOrUndefined(e)&&(a=Math.max(e,a))}return a}function e(a){var b=f(a.effectiveLicenseThreat);
return"undefined"!==typeof b?b:Insight.util.isNotNullOrUndefined(a.overriddenLicenses)?g(a.overriddenLicenses):a.effectiveLicenseThreat}function f(a){if(0<=h.indexOf(a))return d(a)}function d(a){switch(a){case "COPYLEFT":return 10;case "NON-STANDARD":return 7;case "NOT-PROVIDED":return 6;case "WEAKCOPYLEFT":return 3;case "LIBERAL":return 0;default:return null}}function u(a,b){for(var c=[],d=null,d=0;d<b.length;d++)("Not Provided"===b[d]||-1===a.indexOf(b[d]))&&c.push(b[d]);return c}function b(a){return Insight.util.isNotNullOrUndefined(a)&&
0<a.length?a.join(", "):""}function c(a,b){var c=e(a),d=e(b),c=Insight.util.isNullOrUndefined(c)?-1:c,d=Insight.util.isNullOrUndefined(d)?-1:d;return c<d?-1:c>d?1:0}function l(a){var b=f(a);"undefined"!==typeof b&&(a=b);return Insight.util.isNullOrUndefined(a)?"unspecifiedScore":7<a?"criticalScore":3<a?"severeScore":0<a?"moderateScore":"noScore"}function k(a,c,d){if(Insight.util.isNotNullOrUndefined(a))return b(a);a=b(c);c=b(u(c,d));return a+(0<c.length?", "+c:"")}function s(a,c,d,f,h){if(Insight.util.isNotNullOrUndefined(h.overriddenLicenses))return'\x3cdiv class\x3d"'+
l(g(h.overriddenLicenses))+'"\x3e\x3ci\x3e'+b(h.overriddenLicenses)+"\x3c/i\x3e\x3c/div\x3e";a=b(h.declaredLicenses);c=b(u(h.declaredLicenses,h.observedLicenses));return'\x3cdiv class\x3d"'+l(e(h))+'"\x3e \x3cb\x3e'+a+"\x3c/b\x3e"+(0<c.length?", "+c:"")+"\x3c/div\x3e"}function t(){return z||v||w}function r(a,b){$("#"+a+"container .message").remove();$(window).unbind("resize");b.pager&&(b.pager.destroy(),b.pager=null);b.columnsResizedFn&&(b.onColumnsResized.unsubscribe(b.columnsResizedFn),b.columnsResizedFn=
null);b.destroy()}var q,x={preReleaseStrings:["alpha","beta","milestone","rc","snapshot"],isPrerelease:function(a){var b=null;a=a.toLowerCase();if(Insight.util.isNotNullOrUndefined(a)&&(1===a.length||!isNaN(parseFloat(a.charAt(1)))))switch(a.charAt(0)){case "a":case "b":case "m":return!0}for(b=0;b<this.preReleaseStrings.length;b++)if(a.substr(0,this.preReleaseStrings[b].length)==this.preReleaseStrings[b])return!0;return!1},versionItemCompare:function(a,b){if(Insight.util.isNullOrUndefined(a))return-this.versionItemCompare(b,
a);var c=parseInt(a,10),d=parseInt(b,10);return Insight.util.isNullOrUndefined(b)?this.isPrerelease(a)?-1:1:!isNaN(c)&&!isNaN(d)?c===d?0:c>d?1:-1:!isNaN(c)||!isNaN(d)?isNaN(c)?this.isPrerelease(a)?-1:1:this.isPrerelease(b)?1:-1:a<b?-1:a>b?1:0},compare:function(a,b){var c=null,c=/(\w+)/g,d=null,e=null;if(Insight.util.isNullOrUndefined(a))return Insight.util.isNullOrUndefined(b)?0:-1;if(Insight.util.isNullOrUndefined(b))return 1;d=a.match(c);e=b.match(c);for(c=0;c<Math.max(d.length,e.length);c++)switch(this.versionItemCompare(d[c],
e[c])){case 1:return 1;case -1:return-1}return 0}};a($.noop);var h="UNKCAT LIBERAL WEAKCOPYLEFT NOT-PROVIDED NON-STANDARD COPYLEFT".split(" "),z=null,v=null,w=null,p=null,n=null;$.extend(!0,window,{InsightDatatable:{createAuditTable:function(a){n=new Insight.Table("audit",a,{resizeFn:$.noop,selectable:!0,disablePager:!0,disableFilter:!0,height:250,columns:[{id:"date",name:"Date",field:"date",formatter:function(a,b,c,d,e){return dateFormat(c,"mmm d yyyy, h:MM:ss tt")},sortable:!0,width:30},{id:"user",
name:"User",field:"user",toolTipGravity:"n",toolTipFn:function(a){return Insight.util.isNullOrUndefined(a.where)?$("\x3cdiv/\x3e").text("Edited report from "+a.ip).html():$("\x3cdiv/\x3e").text("Edited report in build '"+a.where+"' from "+a.ip).html()},sortable:!0,width:20},{id:"action",name:"Action",field:"action",sortable:!0,width:20},{id:"detail",name:"Detail",field:"detail",sortable:!0,width:40},{id:"comment",name:"Comment",field:"comment",toolTipGravity:"n",toolTipFn:function(a){if(a.comment)return $("\x3cdiv/\x3e").text(a.comment).html()},
sortable:!0,width:80}],defaultSort:{columnId:"date",sortAsc:!1},dataProcessor:function(a){$.each(a,function(a,c){var d=c.status,e="",h;c.id=a;c.date=new Date(c.time);switch(c.status){case "Open":d="Reopened";break;case "Not Applicable":d="Ignored";break;case "Overridden":d="Overrode"}c.action=d;Insight.util.isNullOrUndefined(c.user)&&(c.user="anonymous");switch(c.filename){case "licenses.json":e="License ";d=c.overriddenLicenses;e=Insight.util.isNotNullOrUndefined(d)?e+("as "+b(d)):e+"Analysis";break;
case "security.json":e="Vulnerability ",d=c.source,h=c.reference,Insight.util.isNotNullOrUndefined(d)&&0!==h.toUpperCase().indexOf(d.toUpperCase())&&(e+=d+"-"),e+=h}c.detail=e});return a}});$("#"+n.id+"Table").click(function(a){a.stopPropagation()})},createComponentTable:function(){function a(b){b.preventDefault();$(this).parents("ul").children("li").removeClass("active");$(this).parents("li").addClass("active");b=$("#policy-match-state-filter li.active").text();var c=$("#policy-violation-filter li.active").text(),
d={};"All"!==b&&("Proprietary"===b?d.proprietary=!0:"Error"===b?d.scanError=!0:d.matchState=b.toLowerCase());"Summary"===c?d.summary=!0:"Waived"===c?d.waived=!0:"All"===c&&(d.all=!0);w.addLoadListener(function(){w.table.getData().setFilterArgs(d);w.table.getData().refresh()})}var b=["unknown","similar","exact"],c=new Slick.ColumnGrouping({columnId:"policyName",style:"scoreCol"}),d=c.getCellStyler(),e=c.getCellRenderer(),h=HealthCheck.getAge(earliestReleaseDate,currentDate),f=$("\x3cdiv/\x3e"),h=[{id:"policyName",
name:"Policy Threat",shortName:"Name",field:"policyName",sortable:!0,width:225,styleFn:function(a,b,c,e,h){return"nopad "+d(a,b,c,e,h)},sortFn:function(a,b){var c=a.policyThreatLevel,d=b.policyThreatLevel,e=a.policyName,h=b.policyName;return c<d?-1:c>d||e<h?1:e>h?-1:0},formatter:function(a,b,c,d,h){var g;switch(h.policyThreatLevel){case 0:g=" noScore";break;case 1:g=" ignoredScore";break;case 2:case 3:g=" moderateScore";break;case 4:case 5:case 6:case 7:g=" severeScore";break;case 8:case 9:case 10:g=
" criticalScore"}return'\x3cdiv class\x3d"'+g+'"\x3e'+(0<e(a,b,c,d,h).length?f.text(c).html():"")+"\x3c/div\x3e"}},{id:"coordinates",name:"Coordinates",field:"coordinates",sortable:!0,width:295,toolTipGravity:"se",styleFn:function(a,b,c,d,e){return e.modified||"Manual"===e.identificationSource?"modified":""},toolTipFn:function(a){var b="";a.modified&&(b+="\x3cli\x3ebeen manually edited.  See the audit log for details.\x3c/li\x3e");"Manual"===a.identificationSource&&(b+="\x3cli\x3ebeen claimed from an unknown or similar component.  View the Component Information Panel (CIP) for more details.\x3c/li\x3e");
a.waived&&(b+="\x3cli\x3ebeen waived.\x3c/li\x3e");if(0<b.length)return"This record has...\x3cbr\x3e\x3cbr\x3e\x3cul\x3e"+b+"\x3c/ul\x3e"},formatter:function(a,b,c,d,e){a="";a=e.waived?'\x3cimg src\x3d"flag_white.png" style\x3d"margin-right:4px" title\x3d"Violation has been waived"\x3e':'\x3cspan style\x3d"padding-right:20px"\x3e\x3c/span\x3e';Insight.util.isNotNullOrUndefined(e.groupId)?a+='\x3cimg src\x3d"public/coord-gav.png" alt\x3d"GAV"/\x3e \x3cspan\x3e'+e.groupId+" \x3cstrong\x3e:\x3c/strong\x3e "+
e.artifactId+" \x3cstrong\x3e:\x3c/strong\x3e "+e.version+"\x3c/span\x3e":(a+='\x3cimg src\x3d"public/coord-file.png" alt\x3d"File"/\x3e ',b=e.filenames.join(", "),a+=b?b:"(Anonymized Path) SHA1: "+e.hash);return a}},{id:"versions",name:"Popularity",field:"relativePopularity",sortable:!0,filterable:!1,width:85,sortFn:function(a,c){return a.matchState===b[0]?c.matchState===b[0]?0:-1:c.matchState===b[0]?1:"Manual"===a.identificationSource?a.identificationSource===c.identificationSource?0:-1:"Manual"===
c.identificationSource?1:a.relativePopularity<c.relativePopularity?-1:a.relativePopularity>c.relativePopularity?1:0},formatter:function(a,c,d,e,h){if(h.matchState===b[0]||"Manual"===h.identificationSource)return"";var f;d=Math.round(100*d);79<d?f="popularity-100":59<d?f="popularity-80":39<d?f="popularity-60":19<d?f="popularity-40":0<=d&&(f="popularity-20");return f?'\x3cdiv class\x3d"'+f+'"\x3e\x3c/div\x3e':""}},{id:"age",name:"Age",field:"age",sortable:!0,filterable:!1,width:85,sortFn:function(a,
b){var c=a.age,d=b.age;if(!(void 0===c&&void 0===d)){if(void 0===c)return-1;if(void 0===d)return 1;if(c<d)return-1;if(c>d)return 1}return 0},formatter:function(a,b,c,d,e){return void 0===c||null===c?"":359<c?(c/365).toFixed(1)+" y":30<c?Math.floor(c/30)+" m":Math.floor(c)+" d"}},{id:"releasehistory",name:"Release History",field:"groupId",sortable:!1,filterable:!1,resizable:!1,width:211,header:'\x3cdiv class\x3d"release-header"\x3e\x3ci class\x3d"icon-question-sign" title\x3d"\x3cdiv style\x3d\'background:url(release-tooltip.png);width:241px;height:78px\'\x3e\x3c/div\x3e"\x3e\x3c/i\x3e\x3cspan\x3e'+
h+"\x3c/span\x3e\x3c/div\x3e",formatter:function(a,b,c,d,e){if(null===c||"Manual"===e.identificationSource)return"No Popularity Data";var h="";$.each({groupId:e.groupId,artifactId:e.artifactId,version:e.version},function(a,b){h+="\x26"+encodeURIComponent(a)+"\x3d"+encodeURIComponent(b)});return'\x3cimg src\x3d"../brain/rest/report/'+applicationId+"/"+reportId+"/releaseGraph?"+h.substring(1)+'" alt\x3d"Release Popularity"\x3e'}}],c=[c,new Insight.InformationPanel({byHash:!0})];Brain.hasFeature("release-graph")||
(h[1].width+=h.pop().width);w=new Insight.Table("component",{get:function(){var a=$.Deferred();$.when($.getJSON("policythreats.json"),$.getJSON("bom.json")).done(function(b,c){function d(a){return a.hash||"error: "+(a.pathnames||[]).join("\t")}if(null===b[0]||null===c[0])a.reject([]);else{var e={},h={},f={},g=[];$.each(c[0].aaData,function(a,b){var c=d(b);e[c]=b;h[c]=!1;f[c]=!1});b[0].version?($("#policy-violation-filter").show(),$.each(b[0].aaData,function(a,b){var c=d(b);if(!b.hash||"null"===b.hash)return!0;
b.activeViolations.length&&(h[c]=!0,b.activeViolations.sort(function(a,b){return b.policyThreatLevel-a.policyThreatLevel}),$.each(b.activeViolations,function(a,d){g.push($.extend({policyThreatLevel:d.policyThreatLevel,policyName:d.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,summary:0===a,waived:!1,all:!0},e[c]))}));b.waivedViolations.length&&(f[c]=!0,$.each(b.waivedViolations,function(a,d){g.push($.extend({policyThreatLevel:d.policyThreatLevel,policyName:d.policyName,
groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,summary:!1,waived:!0,all:!0},e[c]))}))})):$.each(b[0].aaData,function(a,b){var c=d(b);if(!b.hash||"null"===b.hash)return!0;h[c]=!0;g.push($.extend({policyThreatLevel:b.policyThreatLevel,policyName:b.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,summary:!0,waived:!1,all:!0},e[c]))});$.each(h,function(a,b){b||g.push($.extend(!0,{policyThreatLevel:0,policyName:"None",summary:!0,waived:!1,all:!1===
f[a]},e[a]))});a.resolve({aaData:g})}}).fail(function(b){a.reject(b)});return a}},{columns:h,multiColumnSort:!0,selectable:!0,plugins:c,defaultSort:[{columnId:"policyName",sortAsc:!1},{columnId:"coordinates",sortAsc:!0}],externalFilters:[function(a,b){var c=!0;b&&$.each(b,function(b,d){return c=a[b]===d});return c}],dataProcessor:function(a){a=a||[];$.each(a,function(a,b){b.id=a;b.createTime&&(b.age=Math.floor(((new Date).getTime()-b.createTime)/864E5));Insight.util.isNotNullOrUndefined(b.groupId)?
b.coordinates=b.groupId+":"+b.artifactId+":"+b.version:b.coordinates=b.filenames.join(", ")});return a}});$("#policy-match-state-filter").unbind("click");$("#policy-match-state-filter li a").click(a);$("#policy-violation-filter li a").click(a);$("#policy-match-state-filter li.active a").trigger("click");w.addLoadListener(function(){$(".release-header \x3e .icon-question-sign").tipsy({gravity:"e",html:!0,title:"title",opacity:1})})},createLicenseTable:function(a){var b=[{id:"_formattedEffectiveLicenseThreat",
name:"License Threat",shortName:"Licenses",field:"_formattedEffectiveLicenseThreat",sortable:!0,width:200,styleFn:function(){return"nopad"},sortFn:c,formatter:s},{id:"groupId",name:"Group",field:"groupId",sortable:!0,width:300,cssClass:"gridcell"},{id:"artifactId",name:"Artifact",field:"artifactId",sortable:!0,width:300,cssClass:"gridcell"},{id:"version",name:"Version",field:"version",sortable:!0,width:150,sortFn:function(a,b){return x.compare(a.version,b.version)}},{id:"status",name:"Status",field:"status",
sortable:!0,width:150}],d=[new Insight.InformationPanel];v=new Insight.Table("license","licenses.json",{columns:b,config:a,plugins:d,defaultSort:{columnId:"_formattedEffectiveLicenseThreat",sortAsc:!1},dataProcessor:function(a){var b;for(b=0;b<a.length;b++)a[b].id=b,a[b].status=Insight.util.isNullOrUndefined(a[b].status)?"Open":a[b].status;return a}});v.addLoadListener(function(){v.table.getData().onRowsChanged.subscribe(function(a,b){var c,d;b=b.rows;for(d=0;d<b.length;d++)c=v.table.getData().getItem(b[d]),
c._formattedEffectiveLicenseThreat=k(c.overriddenLicenses,c.declaredLicenses,c.observedLicenses)})});return v},createSecurityTable:function(a){var b=new Slick.ColumnGrouping({columnId:"_score",style:"scoreCol"}),c=b.getCellStyler(),d=b.getCellRenderer(),b=[b,new Insight.InformationPanel];return z=new Insight.Table("security","security.json",{columns:[{id:"_score",name:"Threat Level",shortName:"Level",field:"_score",sortable:!0,width:120,toolTip:"'Threat Level' highlights the CVSS (Common Vulnerability Scoring System, version 2) base score for each listed vulnerability.",
styleFn:function(a,b,d,e,h){return"nopad "+c(a,b,d,e,h)},sortFn:function(a,b){var c=a._score,d=b._score;return!isNaN(c)&&!isNaN(d)?parseInt(c,10)-parseInt(d,10):d<c?-1:d>c?1:0},formatter:function(a,b,c,e,h){return'\x3cdiv class\x3d"'+(8<=c?" criticalScore":4<=c?" severeScore":" moderateScore")+'"\x3e'+(d(a,b,c,e,h)||"\x26nbsp;")+"\x3c/div\x3e"}},{id:"problemCode",name:"Problem Code",shortName:"Code",field:"_reference",sortable:!0,width:105,formatter:function(a,b,c,d,e){a=e._reference;e=e.url;return Insight.util.isNullOrUndefined(a)?
"":'\x3ca href\x3d"'+e+'" target\x3d"_blank"\x3e'+a+"\x3c/a\x3e"}},{id:"groupId",name:"Group",field:"groupId",sortable:!0,width:255},{id:"artifactId",name:"Artifact",field:"artifactId",sortable:!0,width:250},{id:"version",name:"Version",field:"version",sortable:!0,width:200,sortFn:function(a,b){return x.compare(a.version,b.version)}},{id:"status",name:"Status",field:"status",sortable:!0,width:200}],config:a,defaultSort:{columnId:"_score",sortAsc:!1},dataProcessor:function(a){var b,c,d;for(d=0;d<a.length;d++)a[d].id=
d,a[d]._score=Insight.util.isNullOrUndefined(a[d].score)?"Unscored":String(Math.floor(a[d].score)),b=a[d].source,c=a[d].reference,a[d]._reference=Insight.util.isNullOrUndefined(b)||0===c.toUpperCase().indexOf(b.toUpperCase())?c:b+"-"+c,a[d].status=Insight.util.isNullOrUndefined(a[d].status)?"Open":a[d].status;return a},plugins:b})},createSimilarityTable:function(a){p=new Insight.Table("similarity",a,{selectable:!0,disablePager:!0,disableFilter:!0,height:250,columns:[{id:"_formattedEffectiveLicenseThreat",
name:"License Threat",field:"_formattedEffectiveLicenseThreat",sortable:!0,width:65,sortFn:c,formatter:s},{id:"securityCounters",name:"Security",field:"securityCounters",sortable:!0,width:50,sortFn:function(a,b){var c=a.securityCounters.Critical-b.securityCounters.Critical;0===c&&(c=a.securityCounters.Severe-b.securityCounters.Severe);0===c&&(c=a.securityCounters.Moderate-b.securityCounters.Moderate);return c},formatter:function(a,b,c,d,e){a=e.securityCounters;var h="",f,g,p=0;b=d.width-10;c=function(a,
b){var c;for(c=0;c<a&&!(p>=g);c++)h+='\x3cspan class\x3d"arrow '+b+'_arrow" style\x3d"left:'+p++*f+'px"\x3e\x3c/span\x3e'};if(a){d=a.Critical+a.Severe+a.Moderate;for(f=0;-9<f&&(d-1)*(10+f)+10>b;f--);g=(b-10)/(10+f)+1;a.Critical&&c(a.Critical,"red");a.Severe&&c(a.Severe,"orange");a.Moderate&&c(a.Moderate,"yellow")}return'\x3cdiv style\x3d"white-space:nowrap;width:'+(0<p?10+(p-1)*(10+f):0)+'px"\x3e'+h+"\x3c/div\x3e"}},{id:"groupId",name:"Group",field:"groupId",sortable:!0,width:90},{id:"artifactId",
name:"Artifact",field:"artifactId",sortable:!0,width:90},{id:"version",name:"Version",field:"version",sortable:!0,width:30}],dataProcessor:function(a){a||(a=[]);$.each(a,function(a,b){b.id=a;b._formattedEffectiveLicenseThreat=k(b.overriddenLicenses,b.declaredLicenses,b.observedLicenses)});return a}});p.table.render();p.table.columnsResizedFn=function(){var a;for(a=0;a<p.getDataLength();a++)p.updateCell(a,p.getColumnIndex("securityCounters"))};p.table.onColumnsResized.subscribe(p.table.columnsResizedFn);
$("#similarityTable").click(function(a){a.stopPropagation()})},destroyActiveTable:function(){var a=t();a&&a.destroy();w=v=z=null},getActiveTable:t,loadLicenseThreats:a,getLicenseThreatLevelFromArray:g,getLicenseThreatClass:l,removeAuditTable:function(){Insight.util.isNotNullOrUndefined(n)&&(r("audit",n),n=null)},removeComponentTable:function(){Insight.util.isNotNullOrUndefined(w)&&(r("component",w),$("#componentcontainer ul.nav a").unbind("click"),w=null)},removeLicenseTable:function(){Insight.util.isNotNullOrUndefined(v)&&
(r("license",v),v=null)},removeSecurityTable:function(){Insight.util.isNotNullOrUndefined(z)&&(r("security",z),z=null)},removeSimilarityTable:function(){Insight.util.isNotNullOrUndefined(p)&&(r("similarity",p),p=null)}}})})();
(function(a){function g(b){function c(){f=[];a.each(b.grid.getSelectedRows(),function(a,c){f.push(b.grid.getData().getItem(c))});1===f.length?a("input,textarea,select",m).change(y).keyup(y).focusout(y):(a("input,textarea,select",m).unbind("change").unbind("keyup").unbind("focusout"),a("button[data-type\x3dupdate]",m).removeAttr("disabled"))}function e(c){var d=this,g={};c.preventDefault();a(d).attr("disabled","disabled");a("select",m).each(function(b){0===b?g.status=a(this).val():(b=!a(this).prop("disabled"),
g.overriddenLicenses=b?[a(this).val()]:null,g.overriddenLicenseThreat=b?InsightDatatable.getLicenseThreatLevelFromArray(g.overriddenLicenses):null)});g.comment=a("textarea",m).val();u({mask:g,callback:function(c){Insight.util.isNotNullOrUndefined(c)&&a(d).removeAttr("disabled");Insight.util.isNotNullOrUndefined(b.callback)&&b.callback.apply(this,arguments)},dataView:b.dataView,items:f})}b=a.extend({timestamp:(new Date).getTime()},b);var f=b.artifacts,g="#licenseselect"+b.timestamp,n="#license"+b.timestamp,
m=null,k=null,l=a.Deferred(),y=function(){var b=a("option:selected",g).val(),c=a.trim(a("textarea",m).val()),d=a("option:selected",n).val(),e=b!==(f[0].status||"Open"),c=0<c.length,h=d&&(!f[0].overriddenLicenses||f[0].overriddenLicenses[0]!==d);(d&&("Overridden"===b||"Selected"===b)||!d&&!("Overridden"===b||"Selected"===b))&&(c||e||("Overridden"===b||"Selected"===b)&&h)?a("button[data-type\x3dupdate]",m).removeAttr("disabled"):a("button[data-type\x3dupdate]",m).attr("disabled","disabled")};b.single=
Brain.ci.getArtifactLicensesUrl&&b.single;b.grid&&b.grid.onSelectedRowsChanged.subscribe(c);b.single&&a.getJSON(Insight.toBrain(Brain.ci.getArtifactLicensesUrl(a.extend({appId:applicationId},f[0])))).success(function(a){l.resolve(a)}).error(function(){});a.extend(this,{destroy:function(){b.grid&&b.grid.onSelectedRowsChanged.unsubscribe(c)},show:function(c){m=c;a(m).html(s.render(b));a("button[data-type\x3dupdate]",m).click(e);a("button[data-type\x3dcancel]",m).click(function(a){a.preventDefault();
b.cancelCallback&&b.cancelCallback.apply(this)});1===f.length&&(a("button[data-type\x3dupdate]",m).attr("disabled","disabled"),a("input,textarea,select",m).change(y).keyup(y).focusout(y),Insight.util.isNotNullOrUndefined(f[0].status)&&a("[value\x3d"+f[0].status+"]",m).attr("selected",!0));a(g,m).css("width",b.width);a(g,m).change(function(){var b=a(this),c=a(n).val()||f[0].overriddenLicenses&&f[0].overriddenLicenses[0];switch(b.val()){case "Selected":a("option",n).detach();a(n,m).attr("disabled",
!0);l.done(function(d){"Selected"===b.val()&&0<d.length&&InsightDatatable.loadLicenseThreats(function(b){var e={};a.each(d,function(a,c){e[c.licenseName]=b[c.licenseName]});InsightDatatable.populateLicenseCombo(a(n,m),e);Insight.util.isNotNullOrUndefined(c)&&a('option[value\x3d"'+c+'"]',n).attr("selected","selected");a(n,m).removeAttr("disabled")})});break;case "Overridden":a("option",n).detach();k.appendTo(n);a(n,m).removeAttr("disabled");break;default:a("option",n).detach(),a(n,m).attr("disabled",
!0)}Insight.util.isNotNullOrUndefined(c)&&a('option[value\x3d"'+c+'"]',n).attr("selected","selected");y()});d(function(c){var d=a(n,m);InsightDatatable.populateLicenseCombo(d,c);k=a("option",d);1===f.length&&(Insight.util.isNotNullOrUndefined(f[0].overriddenLicenses)&&0<f[0].overriddenLicenses.length&&a("option",d).each(function(){a(this).val()===f[0].overriddenLicenses[0]&&a(this).attr("selected",!0)}),a(g,m).trigger("change"));a(d,m).css("width",b.width)})}})}function e(c){function d(){0===g.length?
a("button[data-type\x3dupdate]",n).attr("disabled","disabled"):a("button[data-type\x3dupdate]",n).removeAttr("disabled")}function e(){g=[];a.each(c.grid.getSelectedRows(),function(a,b){g.push(c.grid.getData().getItem(b))});d()}function f(d){var e={};d.preventDefault();e.status=a("select",n).val();e.comment=a("textarea",n).val();b({mask:e,dataView:c.dataViews[0],items:g,callback:function(b){if(!Insight.util.isNotNullOrUndefined(b))for(var d=1;d<c.dataViews.length;d++)c.dataViews[d].beginUpdate(),a.each(g,
function(b,f){a.each(c.dataViews[d].getItems(),function(b,g){for(var p=0;p<l.length;p++)if(f[l[p]]!==g[l[p]])return;c.dataViews[d].updateItem(g.id,a.extend({},g,e));return!1})}),c.dataViews[d].endUpdate();Insight.util.isNotNullOrUndefined(c.callback)&&c.callback.apply(this,arguments)}})}c=a.extend({timestamp:(new Date).getTime()},c);var g=c.artifacts,n;c.grid&&c.grid.onSelectedRowsChanged.subscribe(e);a.extend(this,{destroy:function(){c.grid&&c.grid.onSelectedRowsChanged.unsubscribe(e)},show:function(b){n=
b;a(n).html(t.render(c));a("button[data-type\x3dupdate]",n).click(f);a("button[data-type\x3dcancel]",n).click(function(a){a.preventDefault();c.cancelCallback&&c.cancelCallback.apply(this)});a("#svStatus"+c.timestamp,n).css("width",c.width);d()}})}function f(b,c,d,e,f,g){var m=[],l=[];a.each(c,function(b,c){var e=a.extend({},c);a.each(d,function(a,b){e[a]=b});e.modified=!0;m.push(e)});a.merge(l,e);a.each(d,function(a,b){l.push(a)});a.ajax({type:"POST",url:"../augmentData/bom.json",data:JSON.stringify(m,
a.merge(["modified"],k)),beforeSend:parent.beforeSendAugmentedData});a.ajax({type:"POST",url:"../augmentData/"+f,data:JSON.stringify(m,l),beforeSend:parent.beforeSendAugmentedData}).success(function(){b.beginUpdate();a.each(m,function(a,c){b.updateItem(c.id,c)});b.endUpdate();Insight.updateSummary();g()}).error(function(a,b,c){c=Insight.util.getErrorMessage(a);g(c)})}function d(b,c){Insight.util.isNotNullOrUndefined(r)?b.apply(null,[r]):(x.push(b),q||(q=!0,a.getJSON("licenselist.json").success(function(b){r=
b.aaData;a.each(x,function(a,b){b.apply(null,[r])})}).error(function(a,b,c){b=InsightDatatable.getActiveTable();c=Insight.util.getErrorMessage(a);null!==b?b.addError("Loading known licenses: "+c):console&&console.log("Error loading known licenses: "+c)})))}function u(b){b=a.extend({dataView:null,items:[],mask:{},callback:a.noop},b);a.isArray(b.items)||(b.items=[b.items]);f(b.dataView,b.items,b.mask,c,"licenses.json",b.callback)}function b(b){b=a.extend({dataView:null,items:[],mask:{},callback:a.noop},
b);a.isArray(b.items)||(b.items=[b.items]);f(b.dataView,b.items,b.mask,l,"security.json",b.callback)}var c=["groupId","artifactId","version"],l=["groupId","artifactId","version","source","reference"],k=["hash","groupId","artifactId","version"],s,t;a(document).ready(function(){s=Hogan.compile(a("#licenseEditorTemplate").html());t=Hogan.compile(a("#svEditorTemplate").html())});var r=null,q=!1,x=[];a.extend(!0,window,{InsightDatatable:{addSecurityTableEditor:function(b){var c=b.table,d=c.getColumns(),
f=new Slick.BulkEditor({editNode:a("#securityEditor"),editor:new e({width:650,grid:c,cancel:!0,artifacts:[],dataViews:[c.getData()],callback:function(d){Insight.util.isNotNullOrUndefined(d)?b.addError(d):(d=c.getSelectedRows(),Insight.updateSummary(),1==d.length?b.addSuccess("Updated "+d.length+" security vulnerability.",60):1<d.length&&b.addSuccess("Updated "+d.length+" security vulnerabilities.",60),a("#securityEditor").slideUp({complete:function(){a(this).empty()},step:function(){b.updateHeight()}}))},
cancelCallback:function(c){a("#securityEditor").empty().hide();b.updateHeight()}}),openCallback:function(){b.updateHeight()}}),d=a.merge([f.getColumnDef()],d);d[0].filterable=!1;c.setSelectionModel(new Slick.RowSelectionModel);c.getData().syncGridSelection(c,!0);c.setColumns(d);c.registerPlugin(f)},addLicenseTableEditor:function(b){var c=b.table,d=c.getColumns(),e=new Slick.BulkEditor({editNode:a("#licenseEditor"),editor:new g({artifacts:[],width:650,cancel:!0,grid:c,dataView:c.getData(),callback:function(d){Insight.util.isNotNullOrUndefined(d)?
b.addError(d):(d=c.getSelectedRows(),Insight.updateSummary(),1==d.length?b.addSuccess("Updated license for "+d.length+" component.",60):1<d.length&&b.addSuccess(c,"license","Updated license for "+d.length+" components.",60),a("#licenseEditor").slideUp({complete:function(){a(this).empty()},step:function(){b.updateHeight()}}))},cancelCallback:function(c){a("#licenseEditor").empty().hide();b.updateHeight()}}),openCallback:function(){b.updateHeight()}}),d=a.merge([e.getColumnDef()],d);d[0].filterable=
!1;c.setSelectionModel(new Slick.RowSelectionModel);c.getData().syncGridSelection(c,!0);c.setColumns(d);c.registerPlugin(e)},populateLicenseCombo:function(b,c,d){a(b).empty();var e=[];a.each(c,function(a,b){e.push(a)});e.sort(function(a,b){a=a.toUpperCase();b=b.toUpperCase();return a>b?1:a<b?-1:0});a.each(e,function(c,e){var f=a("\x3coption\x3e\x3c/option\x3e").text(e).val(e);e===d&&f.attr("selected","selected");a(b).append(f)})},loadLicenses:d,LicenseEditor:g,SecurityEditor:e,updateLicenses:u,updateSecurity:b,
updateBom:function(b){b=a.extend({dataView:null,items:[],mask:{},callback:a.noop},b);a.isArray(b.items)||(b.items=[b.items]);f(b.dataView,b.items,b.mask,k,"bom.json",b.callback)}}})})(jQuery);