/*
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2012-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
*/
(function(){function c(a){var d=this;this.options=$.extend(!0,{},f,a);this.node=$("\x3cdiv id\x3d'informationPanel' class\x3d'informationPanel fullBorderedTable'\x3e\x3cdiv style\x3d'width:99%; padding-top: 5px; padding-left: 0.5%; padding-right: 0.5%;'\x3e\x3ca class\x3d'close'\x3e\x26times;\x3c/a\x3e\x3cul class\x3d'nav nav-tabs' style\x3d'margin-bottom:0px; !important'\x3e\x3c/ul\x3e\x3cdiv class\x3d'tab-content' style\x3d'overflow:hidden'\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");$(".close",this.node).click(function(){d.hide()});
this.plugins=[];Insight.InformationPanelPlugins.sort(function(a,e){return a.prototype.priority-e.prototype.priority});$.each(Insight.InformationPanelPlugins,function(a,e){var b=$('\x3cli data-info-plugin\x3d"'+a+'"\x3e\x3ca data-target\x3d"infoPanel'+a+'" data-toggle\x3d"tab"\x3e\x3c/a\x3e\x3c/li\x3e'),k=$('\x3cdiv class\x3d"tab-pane" id\x3d"infoPanel'+a+'"\x3e\x3c/div\x3e');$("ul.nav",d.node).append(b);$("div.tab-content",d.node).append(k);d.plugins.push(new e(k,d.options))});$('a[data-toggle\x3d"tab"]',
this.node).on("show",function(a){var e;null!==a.relatedTarget&&(e=$(a.relatedTarget.parentNode).data("info-plugin"),d.plugins[e].destroy(),$("#"+$(a.relatedTarget).data("target"),d.node).hide());null!==a.target&&(e=$(a.target.parentNode).data("info-plugin"),a=$("#"+$(a.target).data("target"),d.node),a.show(),d.plugins[e].create(a,d.node))})}function h(a){a=a||{};this.priority=a.priority||512}var f={byHash:!1};c.prototype.destroy=function(){this.cleanPlugins()};c.prototype.hide=function(){this.node.detach();
this.grid.removeCellCssStyles("popout");this.cleanPlugins()};c.prototype.init=function(a){var d=this;this.grid=a;a.onClick.subscribe(function(){d.gridClickedFn.apply(d,arguments)});a.getData().onRowCountChanged.subscribe(function(){d.hide()});a.getData().onRowsChanged.subscribe(function(){d.rowChangedFn.apply(d,arguments)});$.each(this.plugins,function(d,e){e.setGrid(a)})};c.prototype.cleanPlugins=function(){$.each(this.plugins,function(a,d){d.destroy()})};c.prototype.gridClickedFn=function(a,d){var g=
this;"INPUT"!==a.target.tagName&&0===$(a.target).children("input:first").length&&(Insight.util.isNotNullOrUndefined(g.timer)?(clearTimeout(g.timer),g.timer=null):g.timer=setTimeout(function(){g.timer=null;$.each(g.plugins,function(a,b){b.setItem(g.grid.getDataItem(d.row))});g.toggle(a,d)},250))};c.prototype.getItem=function(){return this.grid.getDataItem(this.currentRow)};c.prototype.updatePanel=function(){var a=this,d=null;$.each(this.plugins,function(d,e){var b=$("li[data-info-plugin\x3d"+d+"]",
a.node);e.isVisible()?(b.show(),$("a",b).text(e.getTitle())):(b.hide(),$("#infoPanel"+d,a.node).hide(),b.hasClass("active")&&(b.removeClass("active"),$("ul.nav \x3e li:first",a.node).addClass("active")))});0===$("li.active",a.node).length&&$("li",a.node).each(function(a,e){e=$(e);if("none"!==e.css("display"))return e.addClass("active"),!1});d=$("li.active",a.node).data("info-plugin");a.plugins[d].create();$("#infoPanel"+d,a.node).show()};c.prototype.rowChangedFn=function(a,d){var g=this.currentRow,
e=this;setTimeout(function(){var b=e.grid.getSelectedRows(),a=null;Insight.util.isNotNullOrUndefined(g)&&1===b.length?g!==b[0]?(e.hide(),Insight.util.isNotNullOrUndefined(this.currentItemId)&&e.show({row:b[0],cell:1},e.grid.getCanvasNode())):(e.position(g),a=e.getItem(),$.each(e.plugins,function(b,e){e.setItem(a)}),e.updatePanel()):e.hide()},10)};c.prototype.toggle=function(a,d){this.grid.removeCellCssStyles("popout");$(this.node).is(":hidden")||this.currentRow!==d.row?this.show(this.grid.getCellFromEvent(a),
$(a.currentTarget)):this.hide()};c.prototype.show=function(a,d){var g={},e=this.grid.getCellNode(a.row,a.cell),b=$(this.grid.getCanvasNode()).parent();b.offset();b.height();var k=this;Insight.util.isNullOrUndefined(e)&&(this.grid.scrollRowIntoView(a.row),e=this.grid.getCellNode(a.row,a.cell));this.node.css("top",e.offsetParent.offsetTop+e.offsetParent.clientHeight);this.node.addClass("shadowBottom");this.node.removeClass("shadowTop");k.node.appendTo(d);this.updatePanel();k.position(a.row);k.node.show();
this.currentRow=a.row;g[this.currentRow]={};$.each(k.grid.getColumns(),function(b,a){g[k.currentRow][a.id]="popout"});k.grid.setCellCssStyles("popout",g)};c.prototype.position=function(a){var d=this.node.offset().top,g=d+this.node.height(),e=$(this.grid.getCanvasNode()).parent(),b=e.offset().top,k=b+e.height(),c=this.grid.getCellNode(a,1);Insight.util.isNullOrUndefined(c)&&(this.grid.scrollRowIntoView(a),c=this.grid.getCellNode(a,1));(g>k||d<b)&&e.scrollTop(e.scrollTop()+(this.node.offset().top-c.offsetParent.clientHeight)-
e.offset().top);this.node.css("width",e.width()-(e.get(0).scrollHeight>e.height()?this.grid.getScrollbarDimensions().width:0)-2+"px")};h.prototype.getErrorFn=function(a,d,g){return function(){var e=$(a);e.html(Insight.templates.error.render());$(".btn",e).click(function(){d.apply(g,[])})}};h.prototype.isVisible=function(){return!0};h.prototype.getTitle=function(){return""};h.prototype.setItem=function(a){Insight.util.isNullOrUndefined(a.componentIdentifier)&&(Insight.util.isNotNullOrUndefined(a.groupId)&&
Insight.util.isNotNullOrUndefined(a.artifactId)&&Insight.util.isNotNullOrUndefined(a.version))&&(a.componentIdentifier={format:"maven",coordinates:{groupId:a.groupId,artifactId:a.artifactId,version:a.version}});this.gav=this.component=a};h.prototype.message=function(a){$(".alert",this.node).remove();a=$('\x3cdiv class\x3d"alert" style\x3d"width:92.5%"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3e\x3c/div\x3e');$("div:first",this.node).prepend(a);return a};h.prototype.addErrorMessage=
function(a){this.message(a).addClass("alert-error").append("\x3cstrong\x3eError: \x3c/strong\x3e",$("\x3cspan\x3e\x3c/span\x3e").text(a))};h.prototype.addSuccessMessage=function(a){var d=this.message(a).addClass("alert-success").append($("\x3cspan\x3e\x3c/span\x3e").text(a));setTimeout(function(){d.fadeOut("fast",function(){d.remove()})},8E3);return d};h.prototype.setGrid=function(a){this.grid=a};h.prototype.create=$.noop;h.prototype.destroy=$.noop;$.extend(!0,window,{Insight:{InformationPanel:c,
InformationPanelPlugin:h,InformationPanelPlugins:[]}})})();
(function(){function c(a,g){var e=[];return Insight.util.isNotNullOrUndefined(a)&&0<a.length?("object"===typeof a[0]?$.each(a,function(a,d){e.push(Insight.util.encodeHtml(d.licenseName))}):$.each(a,function(a,d){e.push(Insight.util.encodeHtml(d))}),'\x3cspan class\x3d"license"\x3e'+e.join(',\x3c/span\x3e \x3cspan class\x3d"license"\x3e')+"\x3c/span\x3e"):g||""}function h(d,g,e){var b="artifactInfoSecurity",k=Math.floor(d.securityThreatLevel);$(g).is(":hidden")||(0>=d.securityThreatCount?(k="NA",b+=
" artifactInfoSecurityUnspecified"):7<=k?b+=" artifactInfoSecurityCritical":4<=k?b+=" artifactInfoSecuritySevere":(0<=k||(k="Unscored"),b+=" artifactInfoSecurityModerate"),d=$.extend(d,{partial:!1,overriddenLicenses:c(d.overriddenLicenses,"-"),declaredLicenses:c(d.declaredLicenses,"-"),observedLicenses:c(d.observedLicenses,"-"),currentMatchState:e.matchState,proprietary:e.proprietary,colorCls:b,lvl:k,cataloged:d.catalogDate?HealthCheck.getAge(new Date(d.catalogDate)):null,multipleSecurity:1<d.securityThreatCount,
isManual:"Manual"===d.identificationSource}),g.html(a.render(d)),Insight.ComponentInformation({data:d,partialDisplay:!1}))}function f(a,g){this.node=a;this.options=g}var a;$(document).ready(function(){a=Hogan.compile($("#infoPanelComponentTemplate").html())});f.prototype=new Insight.InformationPanelPlugin({priority:1});f.prototype.create=Brain.ci&&Brain.ci.getArtifactVersionInfoUrl?function(){var a=this,g=a.component,e=null,b=null,k=null,c=null,f=function(){null!==b&&(null!==e&&g===a.component)&&
(b.securityThreatCount=0,b.securityThreatLevel=null,$.each(b.securityVulnerabilities,function(a,e){"Not Applicable"!==e.status&&(b.securityThreatCount++,Insight.util.isNotNullOrUndefined(e.severity)&&(b.securityThreatLevel=Math.max(b.securityThreatLevel,e.severity)))}),b.versions=e,h(b,a.node,g))};Insight.util.isNullOrUndefined(this.component.componentIdentifier)?this.node.html("\x3cdiv class\x3d'infoPanelText'\x3eUnknown Component\x3c/div\x3e"):($(this.node).html('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e'),
k=$.extend({},this.component,{appId:applicationId,instanceId:instanceId}),c=Brain.ci.getComponentDetailsListUrl?Brain.ci.getComponentDetailsListUrl(k):Brain.ci.getArtifactVersionInfoUrl(k),$.getJSON(Insight.toBrain(Brain.ci.getArtifactInfoUrl(k)),function(a){b=a;f()}).error(this.getErrorFn(this.node,this.create,this)),$.getJSON(Insight.toBrain(c),function(a){e=a.list?a.list:a;f()}).error(this.getErrorFn(this.node,this.create,this)))}:function(){var a=this,g=a.component;Insight.util.isNullOrUndefined(this.component.componentIdentifier)?
this.node.html("\x3cdiv class\x3d'infoPanelText'\x3eUnknown Artifact\x3c/div\x3e"):($(this.node).html('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e'),$.getJSON("../artifactDetails/"+reportId+"?groupId\x3d"+this.component.groupId+"\x26artifactId\x3d"+this.component.artifactId+"\x26version\x3d"+this.component.version,function(e){a.component===g&&h(e,$(a.node),g)}).error(this.getErrorFn(this.node,
this.create,this)))};f.prototype.destroy=function(){this.node.empty()};f.prototype.getTitle=function(){return"Component Info"};Insight.InformationPanelPlugins.push(f)})();
(function(){function c(c,f){this.node=c;this.options=f}c.prototype=new Insight.InformationPanelPlugin({priority:32});c.prototype.isVisible=function(){return"unknown"!==this.component.matchState&&Brain.hasFeature("policy-violations")};c.prototype.create=function(){var c=(new Date).getTime(),f=$('\x3cdiv id\x3d"policy-violations-'+c+'"\x3e\x3c/div\x3e'),a=this,d=function(){Insight.PolicyViolations?Insight.PolicyViolations(f,applicationId,a.component.hash):setTimeout(d,1E3)};this.node.empty();f.appendTo(this.node);
d()};c.prototype.destroy=function(){this.node.empty()};c.prototype.getTitle=function(){return"Policy"};Insight.InformationPanelPlugins.push(c)})();
(function(){function c(c,f){this.node=c;this.options=f}c.prototype=new Insight.InformationPanelPlugin({priority:48});c.prototype.isVisible=function(){return!0};c.prototype.create=function(){var c=this;this.destroy();this.component.hash?$.getJSON("partialmatched.json",function(f){var a=null,d;for(d=0;d<f.aaData.length;d++)if(f.aaData[d].hash===c.component.hash){a=f.aaData[d].matchDetails;break}a?($(c.node).html("\x3cdiv id\x3d'similarityTable' class\x3d'borderedTable'\x3e\x3c/div\x3e"),InsightDatatable.createSimilarityTable(a)):
$(c.node).html("\x3cdiv class\x3d'infoPanelText'\x3eNo similar matches were found for this component.\x3c/div\x3e")},this.getErrorFn(c.node,c.create,c)):$(c.node).html("\x3cdiv class\x3d'infoPanelText'\x3eNo similar matches were found for this component.\x3c/div\x3e")};c.prototype.destroy=function(){InsightDatatable.removeSimilarityTable();this.node.empty()};c.prototype.getTitle=function(){return"Similar"};Insight.InformationPanelPlugins.push(c)})();
(function(){function c(c){var a,d;if(0===c.indexOf("dependency:/"))return c=c.substring(12),a=c.lastIndexOf("/"),0>a?["Dependency "+c,""]:["Dependency "+c.substring(a+1),"Module "+c.substring(0,a)];a=c.lastIndexOf("/");if(-1===a)return[c,""];d=c.substring(a+1);c=c.substring(0,a);return[d,c]}function h(c,a){this.node=c;this.options=a}h.prototype=new Insight.InformationPanelPlugin({priority:64});h.prototype.buildView=function(f){if(0<f.length){f.sort();var a="\x3cdiv class\x3d'infoPanelText fileDetail'\x3e",
d=!1;$.each(f,function(g,e){$.each(e.pathnames,function(b,e){var d=c(e);a+="\x3cb\x3e"+Insight.util.encodeHtml(d[0])+"\x3c/b\x3e";0<d[1].length&&(a+=" \x3ci\x3elocated at\x3c/i\x3e "+Insight.util.encodeHtml(d[1]));a+="\x3cbr\x3e\x3cbr\x3e"});0>=e.pathnames.length&&(d=!0)});d&&(a+="Occurrences of this component cannot be listed because pathnames have been anonymized. To see all occurrences, please disable anonymization in the options of your CLM enforcement points and perform a new scan.");a+="\x3c/div\x3e";
$(this.node).html(a)}else $(this.node).html("\x3cdiv class\x3d'infoPanelText'\x3eInvalid data encountered, no files are associated with this component.\x3c/div\x3e")};h.prototype.create=function(){var c=this;c.options.byHash?this.buildView([c.component]):$.getJSON("bom.json",function(a){var d=[];$.each(a.aaData,function(a,e){Insight.util.componentsEqual(e,c.component)&&d.push(e)});c.buildView(d)},this.getErrorFn(c.node,c.create,c))};h.prototype.destroy=function(){};h.prototype.getTitle=function(){return"Occurrences"};
Insight.InformationPanelPlugins.push(h)})();
(function(){function c(c,f,a,d,g,e,b,k){Insight.util.isNotNullOrUndefined(c[a])?d.call(k,{aaData:b.getData().getItems()},!0):$.getJSON(f,function(a){d.call(this,a,!1)}).error(e)}(function(){function h(a,d){this.node=a;this.options=d}var f=null;$(document).ready(function(){f=Hogan.compile($("#infoPanelSecurityEditor").html())});h.prototype=new Insight.InformationPanelPlugin({priority:96});h.prototype.toSV=function(a,d){var g=this;c(g.component,"security.json","reference",function(e,b){var d=[];$.each(e.aaData,
function(a,b){Insight.util.componentsEqual(b,g.component)&&d.push($.extend({},b,{id:a}))});a.call(this,d,b)},a,d,this.grid,this)};h.prototype.isVisible=function(){return"unknown"!==this.component.matchState&&"Manual"!==this.component.identificationSource};h.prototype.create=function(){this.destroy();var a=(new Date).getTime(),d=$('\x3cdiv id\x3d"svEditor'+a+'" style\x3d"width:100%"\x3e\x3c/div\x3e').appendTo(this.node),c=this,e;this.toSV(function(b,k){var x="sv"+a,h=new Slick.CheckboxSelectColumn,
q={timestamp:a,width:300,callback:function(a){if(Insight.util.isNullOrUndefined(a)){a=c.grid;var b=$(a.getCanvasNode()).parents("[data-container\x3dtrue]").attr("id"),d,b=b.substring(0,b.length-9);"component"===b&&(d=a.getSelectedRows(),1===d.length&&(b=a.getData(),b.beginUpdate(),a=a.getDataItem(d[0]),a.modified=!0,b.updateItem(a.id,a),b.endUpdate()));a=e.table.getSelectedRows();1===a.length?c.addSuccessMessage("Updated "+a.length+" security vulnerability."):1<a.length&&c.addSuccessMessage("Updated "+
a.length+" security vulnerabilities.")}else c.addErrorMessage(a)},artifacts:[]};$(d).html(f.render({timestamp:a}));var l=[h.getColumnDefinition(),{id:"_score",name:"Threat Level",field:"_score",sortable:!0,width:90,minWidth:90,toolTip:"'Threat Level' highlights the CVSS (Common Vulnerability Scoring System, version 2) base score for each listed vulnerability.",styleFn:function(a,b,e,d,c){return"nopad"},sortFn:function(a,b){var e=a._score,d=b._score;return!isNaN(e)&&!isNaN(d)?parseInt(e)-parseInt(d):
d<e?-1:d>e?1:0},formatter:function(a,b,e,d,c){return'\x3cdiv class\x3d"'+(7<=e?" criticalScore":4<=e?" severeScore":" moderateScore")+'"\x3e'+(e||"\x26nbsp;")+"\x3c/div\x3e"}},{id:"problemCode",name:"Problem Code",field:"_reference",sortable:!0,width:90,minWidth:90,formatter:Insight.util.showVulnerabilityDetail()?null:function(a,b,e,d,c){a=c._reference;c=c.url;return Insight.util.isNullOrUndefined(a)?"":'\x3ca href\x3d"'+c+'" target\x3d"_blank"\x3e'+a+"\x3c/a\x3e"}}];Insight.util.showVulnerabilityDetail()&&
l.push({id:"info",name:"Info",field:"source",sortable:!1,width:30,minWidth:30,formatter:function(a,b,e,d,c){return'\x3cdiv\x3e\x3cbutton type\x3d"button" class\x3d"btn vulnerability-info-button"\x3e\x3c/button\x3e\x3c/div\x3e'}});l.push({id:"status",name:"Status",field:"status",sortable:!0,width:Insight.util.showVulnerabilityDetail()?60:90,minWidth:Insight.util.showVulnerabilityDetail()?60:90,sortFn:function(a,b){a=Insight.util.isNotNullOrUndefined(a.status)?a.status:"Open";b=Insight.util.isNotNullOrUndefined(b.status)?
b.status:"Open";return a>b?1:a<b?-1:0},formatter:function(a,b,e,d,c){return Insight.util.isNotNullOrUndefined(e)?e:"Open"}});e=new Insight.Table(x,b,{resizeFn:$.noop,height:"220px",width:"100%",disableFilter:!0,selectable:!0,dataProcessor:function(a){for(var b=0;b<a.length;b++)a[b].id=b,a[b]._score=Insight.util.isNullOrUndefined(a[b].score)?"Unscored":String(Math.floor(a[b].score)),a[b]._reference=Insight.util.toSvReference(a[b].source,a[b].reference);k&&setTimeout(function(){$.each(a,function(a,
b){if(b.source===c.component.source&&b.reference===c.component.reference)return e.table.setSelectedRows([e.table.getData().getRowById(b.id)]),!1})},1);return a},defaultSort:{columnId:"_score",sortAsc:!1},plugins:[h],columns:l,handlers:[{event:"onClick",handler:function(a,b){var e=$(a.target);if(e.hasClass("vulnerability-info-button")){var d=b.grid.getDataItem(b.row);Insight.util.showSvModal(d.source,d.reference,d.componentIdentifier,d.hash)}else"A"===a.target.nodeName&&window.open($(a.target).attr("href"),
"_blank");e.is(":checkbox")||a.stopPropagation()}}]});$.extend(q,{dataViews:[e.table.getData()],grid:e.table});k&&q.dataViews.push(this.grid.getData());(new InsightDatatable.SecurityEditor(q)).show("#editor"+a)},this.getErrorFn(this.node,this.create,this))};h.prototype.destroy=function(){$("[data-slickgrid]",this.node).each(function(){$(this).data("data-slickgrid").destroy()});this.node.empty()};h.prototype.getTitle=function(){return"Edit Vulnerabilities"};Insight.InformationPanelPlugins.push(h)})()})();
(function(){function c(c,f){this.node=c;this.options=f}c.prototype=new Insight.InformationPanelPlugin({priority:112});c.prototype.isVisible=function(){return"unknown"!==this.component.matchState&&Brain.hasFeature("labels")};c.prototype.create=function(){var c=(new Date).getTime(),f=$('\x3cdiv id\x3d"labels-'+c+'"\x3e\x3c/div\x3e'),a=this,d=function(){Insight.LabelEditor?Insight.LabelEditor(f,applicationId,a.component.hash,a.component):setTimeout(d,1E3)};this.node.empty();f.appendTo(this.node);d()};
c.prototype.destroy=function(){this.node.empty()};c.prototype.getTitle=function(){return"Labels"};Insight.InformationPanelPlugins.push(c)})();
(function(){function c(c){c.html("\x3cdiv style\x3d'width:99%;padding:7px 0 5px 1%;vertical-align:-12px;'\x3eNo changes were found for this component.\x3c/div\x3e")}function h(c,a){this.node=c;this.options=a}h.prototype=new Insight.InformationPanelPlugin({priority:99999});h.prototype.isVisible=function(){return"unknown"!==this.component.matchState};h.prototype.create=function(){var h=this,a=function(a){a?(h.node.html('\x3cdiv id\x3d"auditTable" class\x3d"borderedTable"\x3e\x3c/div\x3e'),InsightDatatable.createAuditTable(a.aaData)):
c(h.node)};Brain.hasFeature("component-identifier")&&Insight.util.isNotNullOrUndefined(this.component.componentIdentifier)?$.getJSON("../auditLog/licenses.json+security.json","key\x3d"+JSON.stringify({hash:this.component.hash,componentIdentifier:this.component.componentIdentifier}),a).error(this.getErrorFn(this.node,this.create,this)):Insight.util.isNotNullOrUndefined(this.component.groupId)?$.getJSON("../auditLog/licenses.json+security.json","key\x3d"+JSON.stringify(this.component,["hash","groupId",
"artifactId","version"]),a).error(this.getErrorFn(this.node,this.create,this)):c(this.node)};h.prototype.destroy=function(){InsightDatatable.removeAuditTable();this.node.empty()};h.prototype.getTitle=function(){return"Audit Log"};Insight.InformationPanelPlugins.push(h)})();
(function(){function c(a){return null===a||"undefined"===typeof a}function h(a,d,c,e){var b=$("#sv-info-modal .modal-body");a&&d?(b.empty(),b.append("\x3cp\x3eLoading vulnerability detail content\x3c/p\x3e"),f&&"pending"===f.state()&&f.reject("reject"),f=$.getJSON(Insight.toBrain(Brain.getVulnerabilityDetailUrl(a,d,c,e))).done(function(a){b.empty();b.append(a.htmlDetails)}).fail(function(k){"reject"!==k&&(b.empty(),b.append(Insight.templates.error.render()),$(".btn",b).click(function(){h(a,d,c,e)}))})):
(b.empty(),b.append("Unable to construct url for vulnerability detail content."));$("#sv-info-modal").modal("show")}var f;$.extend(!0,window,{Insight:{toBrain:function(a){return"/"===a.charAt(0)?"../brain"+a:"../brain/"+a},util:{enableTooltip:function(a){$(a).each(function(){var a=$(this).attr("data-gravity-offset")||0;a&&(a=parseInt(a,10));$(this).tipsy({fade:!0,gravity:$(this).attr("data-gravity"),offset:a,html:!0,opacity:1,delayOut:0,title:"data-tooltip"})})},getErrorMessage:function(a){var c=
"";return c=0===a.status||1E3<=a.status?"Network error while contacting server":a.responseText&&0<=(a.getResponseHeader("Content-Type")||"").indexOf("text/plain")?a.responseText:a.statusText?a.statusText:"Error "+a.status},getQueryParameter:function(a){var c=0<window.location.search.length?window.location.search.substring(1).split("\x26"):[],g=null,e=null;a=a.toLowerCase();for(e=0;e<c.length;e++)if(g=c[e].split("\x3d"),g[0].toLowerCase()===a)return g[1]},isNullOrUndefined:c,isNotNullOrUndefined:function(a){return!c(a)},
componentsEqual:function(a,c){if(Insight.util.isNullOrUndefined(a.componentIdentifier))return a.groupId===c.groupId&&a.artifactId===c.artifactId&&a.version===c.version;if(Insight.util.isNullOrUndefined(c.componentIdentifier)||a.componentIdentifier.format!==c.componentIdentifier.format||a.componentIdentifier.coordinates.length!==c.componentIdentifier.coordinates.length)return!1;for(var g in a.componentIdentifier.coordinates)if(a.componentIdentifier.coordinates.hasOwnProperty(g)&&a.componentIdentifier.coordinates[g]!==
c.componentIdentifier.coordinates[g])return!1;return!0},toSvReference:function(a,c){var g=Insight.util.isNullOrUndefined(a)?"":a.toUpperCase(),e=Insight.util.isNullOrUndefined(c)?"":c.toUpperCase();return 0>e.indexOf(g)?g+"-"+e:e},showSvModal:h,showVulnerabilityDetail:function(){return Brain.getVulnerabilityDetailUrl},encodeHtml:function(){var a=$("\x3cdiv/\x3e");return function(c){return a.text(c).html()}}()}}})})();
(function(){function c(a){var b={criticalCount:0,severeCount:0,moderateCount:0,noThreatCount:0};$.each(a.effectiveLicenseCounts,function(a,c){7<a?b.criticalCount+=c:3<a?b.severeCount+=c:0<a?b.moderateCount+=c:b.noThreatCount+=c});b.count=b.criticalCount+b.severeCount+b.moderateCount+b.noThreatCount;b.licenseAlerts=b.criticalCount+b.severeCount+b.moderateCount;b.multipleLicenseAlerts=1!==b.licenseAlerts;return b}function h(a){var b={criticalCount:0,severeCount:0,moderateCount:0,count:0};$.each(a.securityCounts,
function(a,c){6<a?b.moderateCount+=c:3<a?b.severeCount+=c:b.criticalCount+=c;b.count+=c});b.multiple=1!==b.count;b.insecureArtifactCount=a.insecureArtifactCount;b.multipleComponents=1<b.insecureArtifactCount;return b}function f(a){var b={criticalCount:0,severeCount:0,moderateCount:0};b.policyComponentCount=a.policyComponentCount;b.multipleComponents=0<b.policyComponentCount;$.each(a.policyCounts,function(a,c){8<=a?b.criticalCount+=c:4<=a?b.severeCount+=c:1<a&&(b.moderateCount+=c)});b.multipleAlerts=
1<b.criticalCount+b.severeCount+b.moderateCount?!0:!1;b.hasPolicyAlerts=0<b.criticalCount+b.severeCount+b.moderateCount?!0:!1;return b}function a(){var e=$("#summary"),b=function(b,c,d){e.empty();e.append(Insight.templates.error.render({message:Insight.util.getErrorMessage(b)}));$("button",e).click(a)};e.html('\x3cdiv class\x3d"alert alert-info"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e');$.getJSON("data.json").success(function(a){if(null===a)b({status:0});else{var g=$.extend(a,{policy:f(a),
sv:h(a),license:c(a),knownComponentCount:a.knownArtifactCount,totalComponentCount:a.totalArtifactCount,percentKnownComponents:a.totalArtifactCount?Math.round(100*a.knownArtifactCount/a.totalArtifactCount):0,multipleKnown:1!=a.knownArtifactCount}),y=e.is(":visible");e.hide();e.html(d.render(g));HealthCheck.barChart(a.securityCounts,{element:$("#security-chart")[0]});HealthCheck.punchCard(a.securityPunchCard,{element:$("#security-punchcard")[0]});HealthCheck.licenseChart([g.license.criticalCount/g.license.count,
g.license.severeCount/g.license.count,g.license.moderateCount/g.license.count,(g.license.count-g.license.licenseAlerts)/g.license.count],{element:$("#license-chart")[0]});HealthCheck.punchCard(a.licensePunchCard,{element:$("#license-punchcard")[0]});HealthCheck.artifactsChart(0<a.totalArtifactCount?1-a.knownArtifactCount/a.totalArtifactCount:0,{element:$("#coverage_donut")[0]});y&&e.fadeIn();Insight.util.enableTooltip($("[data-tooltip]",summary))}}).error(b)}var d,g;$(document).ready(function(){d=
Hogan.compile($("#summaryPageTemplate").html());g=Hogan.compile($("#errorTemplate").html());$.extend(!0,window,{Insight:{templates:{error:g},updateSummary:a}});$("button[data-containerid]").click(function(a){if(!$(this).hasClass("active")){a=$(this).data("containerid");var c;$("[data-container]").css("display","none");$("#"+a).css("display","");InsightDatatable.destroyActiveTable();switch(a){case "securitycontainer":c=InsightDatatable.createSecurityTable({headerRowHeight:30});c.addLoadListener(function(){InsightDatatable.addSecurityTableEditor(c)});
break;case "licensecontainer":c=InsightDatatable.createLicenseTable({headerRowHeight:30});break;case "componentcontainer":InsightDatatable.createComponentTable()}}});Insight.util.enableTooltip($("[data-tooltip]"));var c=$('[data-action\x3d"reevaluatePolicy"]');Brain.hasFeature("reevaluate-policy")?c.click(function(){c.find("i").attr("class","icon-white icon-time");$.ajax({type:Brain.getCurrentReportReevaluateUrl?"POST":"GET",url:Brain.getCurrentReportReevaluateUrl?Brain.getCurrentReportReevaluateUrl():
"../reevaluatePolicy",headers:Brain.getCsrfHeaders?Brain.getCsrfHeaders():{}}).success(function(){c.find("i").attr("class","icon-white icon-refresh");location.reload()}).error(function(){$(".btn-group:eq(1)").after('\x3cdiv class\x3d"alert alert-error" style\x3d"margin:5px 0"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3eThere has been an error reevaluating policy. Try running the report again.\x3c/div\x3e')})}):c.hide();$.browser.msie&&9>$.browser.version&&$(".btn-group:eq(1)").after('\x3cdiv class\x3d"alert alert-error" style\x3d"margin:5px 0"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3eYou are using older version of Internet Explorer (IE). You may notice degraded performance and/or functionality. To address this, download and install the latest version of IE, or other modern browser (e.g. Chrome, Firefox)\x3c/div\x3e');
Insight.updateSummary()})})();
(function(){function c(a){var c=$(window).innerHeight(),b=$(a).offset().top;a=$("#"+a.attr("id")+"Pager").height();return Math.max(150,c-b-d-a)}function h(a){$("#"+a+"container .message").remove()}function f(a,c){var b=$("#"+a+"container"),d=$("#"+a+"Table").position(),f;null!==d&&(h(a),b.append('\x3cdiv class\x3d"message" style\x3d"top:'+(d.top+70)+'px"\x3e'+c+"\x3c/div\x3e"),f=$(".message",b),f.css("left",d.left+b.outerWidth()/2-f.outerWidth()/2+"px"))}function a(a,e,b){function d(e){if(!m.destroyed){m.table=
new Slick.Grid("#"+a+"Table",m.dataView,b.columns,l);if(b.handlers)for(var f=0;f<b.handlers.length;f++)m.table[b.handlers[f].event].subscribe(b.handlers[f].handler);b.selectable&&(m.table.setSelectionModel(new Slick.RowSelectionModel),m.dataView.syncGridSelection(m.table,!0));q.init(m.table);n.css("height",b.height||c($("#"+a+"Table"))+"px");m.processData(e);m.initialize()}}function h(a){return function(b,c,e){b=n.empty().append(Insight.templates.error.render({message:e}));$("button",b).click(a)}}
function f(a){n.empty().append('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e');a.get().done(function(b){null!=b?d(b):h(function(){f(a)})()}).fail(h(function(){f(a)}))}var q=new Slick.Data.GroupItemMetadataProvider,l=$.extend({editable:!1,enableAddRow:!1,enableCellNavigation:b.enableCellNavigation,enableColumnReorder:!1,enableTextSelectionOnCells:!0,fullWidthRows:!0,forceFitColumns:!0,rowHeight:31,
explicitInitialization:!0,showHeaderRow:!b.disableFilter,multiSelect:!1,autoHeight:b.autoHeight,multiColumnSort:b.multiColumnSort},b.config||{}),m=this,n=$("#"+a+"Table");this.options=b;this.id=a;this.dataView=new Slick.Data.DataView({groupItemMetadataProvider:q});this.filter=new Slick.Filter;$.isArray(e)?d({aaData:e}):"string"===typeof e?f({get:function(){return $.getJSON(e)}}):"object"===typeof e?f(e):console.log("Unable to load: "+e)}var d=null;$.browser&&($.browser.mozilla&&4>parseFloat($.browser.version)?
d=9:$.browser.msie&&9>parseFloat($.browser.version)&&(d=15));null===d&&(d=14);a.prototype.updateHeight=function(){var a=$("#"+this.id+"Table"),e=this;a.css("height",c(a)+"px");window.clearTimeout(this.resizeTimeout);this.resizeTimeout=window.setTimeout(function(){e.table.resizeCanvas()},50)};a.prototype.destroy=function(){this.destroyed=!0;h(this.id);$(window).unbind("resize");this.table&&(this.table.pager&&(this.table.pager.destroy(),this.table.pager=null),this.table.columnsResizedFn&&(this.table.onColumnsResized.unsubscribe(this.table.columnsResizedFn),
this.table.columnsResizedFn=null),this.table.destroy())};a.prototype.initialize=function(){var a=this;this.initialized||(this.initialized=!0,this.options.defaultSort&&($.isArray(this.options.defaultSort)?this.table.setSortColumns(this.options.defaultSort):this.table.setSortColumns([this.options.defaultSort])),$.isArray(this.options.plugins)&&$.each(this.options.plugins,function(c,b){a.table.registerPlugin(b)}),this.table.registerPlugin(new Slick.Sort),this.table.init(),this.options.disableFilter||
this.table.registerPlugin(this.filter),this.table.registerPlugin(new Slick.Tipsy),$(window).resize(this.options.resizeFn||function(){Insight.util.isNullOrUndefined(a.options.height)&&a.updateHeight()}),this.listeners&&($.each(this.listeners,function(a,b){setTimeout(b,0)}),this.listeners=null))};a.prototype.processData=function(a){var c=this;this.initialize();Insight.util.isNotNullOrUndefined(a)&&(this.options.dataProcessor&&(a.aaData=this.options.dataProcessor.call(null,a.aaData)),this.dataView.beginUpdate(),
this.dataView.setItems(a.aaData),this.options.disableFilter||(this.options.externalFilters?this.dataView.setFilter(function(a,d){var g=!0;$.each(c.options.externalFilters,function(c,e){e(a,d)||(g=!1);return g});return g&&c.filter.getFilter()(a,d)}):this.dataView.setFilter(this.filter.getFilter())),this.options.groupInfo&&this.dataView.groupBy(this.options.groupInfo.field,this.options.groupInfo.groupHeaderFn,this.options.groupInfo.groupingComparer),this.dataView.endUpdate(),this.options.groupInfo&&
"collapsed"===this.options.groupInfo.initialState&&(this.dataView.beginUpdate(),$.each(this.dataView.getGroups(),function(a,d){c.dataView.collapseGroup(d.value)}),this.dataView.endUpdate()));h(this.id);if(Insight.util.isNullOrUndefined(a)||0===a.aaData.length)f(this.id,this.options.emptyText||"None");this.options.disablePager||(this.table.pager=new Slick.Controls.Pager(this.dataView,this.table,$("#"+this.id+"TablePager")))};a.prototype.addMessage=function(a,c,b){var d=this,f=$('\x3cdiv class\x3d"alert"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3e\x3c/div\x3e');
f.addClass(c);f.append("\x3cspan\x3e\x3c/span\x3e").text(a);f.bind("closed",function(){d.updateHeight()});$("#"+d.id+"container").prepend(f);d.updateHeight();b&&setTimeout(function(){f.fadeOut("fast",function(){f.remove();d.updateHeight()})},1E3*b);return f};a.prototype.addLoadListener=function(a){this.table?setTimeout(a,0):(this.listeners=this.listeners||[],this.listeners.push(a))};a.prototype.addSuccess=function(a,c){this.addMessage(a,"alert-success",c)};a.prototype.addError=function(a,c){this.addMessage(a,
"alert-error",c)};$.extend(!0,window,{Insight:{Table:a}})})();
(function(){function c(a){Insight.util.isNotNullOrUndefined(m)?a.apply(null,[m]):$.getJSON("licensethreats.json").success(function(b){m=b.aaData;a.apply(null,[m])}).error(function(b,c,d){a.apply(null,[null,"Loading license categorization: "+Insight.util.getErrorMessage(b)])})}function h(){for(var a=null,b=0;b<arguments.length;b++)for(var c=arguments[b],d=0;d<c.length;d++){var e=m[c[d]];Insight.util.isNotNullOrUndefined(e)&&(a=Math.max(e,a))}return a}function f(b){var c=a(b.effectiveLicenseThreat);
return"undefined"!==typeof c?c:Insight.util.isNotNullOrUndefined(b.overriddenLicenses)?h(b.overriddenLicenses):b.effectiveLicenseThreat}function a(a){if(0<=A.indexOf(a))return d(a)}function d(a){switch(a){case "COPYLEFT":return 10;case "NON-STANDARD":return 7;case "NOT-PROVIDED":return 6;case "WEAKCOPYLEFT":return 3;case "LIBERAL":return 0;default:return null}}function g(a,b){for(var c=[],d=null,d=0;d<b.length;d++)("Not Provided"===b[d]||-1===a.indexOf(b[d]))&&c.push(b[d]);return c}function e(a){return Insight.util.isNotNullOrUndefined(a)&&
0<a.length?a.join(", "):""}function b(a,b){var c=f(a),d=f(b),c=Insight.util.isNullOrUndefined(c)?-1:c,d=Insight.util.isNullOrUndefined(d)?-1:d;return c<d?-1:c>d?1:0}function k(b){var c=a(b);"undefined"!==typeof c&&(b=c);return Insight.util.isNullOrUndefined(b)?"unspecifiedScore":7<b?"criticalScore":3<b?"severeScore":0<b?"moderateScore":"ignoredScore"}function x(a,b,c){if(Insight.util.isNotNullOrUndefined(a))return e(a);a=e(b);b=e(g(b,c));return a+(0<b.length?", "+b:"")}function y(a,b,c,d,u){if(Insight.util.isNotNullOrUndefined(u.overriddenLicenses))return'\x3cdiv class\x3d"'+
k(h(u.overriddenLicenses))+'"\x3e\x3ci\x3e'+e(u.overriddenLicenses)+"\x3c/i\x3e\x3c/div\x3e";a=e(u.declaredLicenses);b=e(g(u.declaredLicenses,u.observedLicenses));return'\x3cdiv class\x3d"'+k(f(u))+'"\x3e \x3cb\x3e'+a+"\x3c/b\x3e"+(0<b.length?", "+b:"")+"\x3c/div\x3e"}function q(){return v||p||s}function l(a,b){$("#"+a+"container .message").remove();$(window).unbind("resize");b.pager&&(b.pager.destroy(),b.pager=null);b.columnsResizedFn&&(b.onColumnsResized.unsubscribe(b.columnsResizedFn),b.columnsResizedFn=
null);b.destroy()}var m,n={id:"coordinates",name:"Component",field:"coordinates",sortable:!0,width:295,toolTipGravity:"se",formatter:function(a,b,c,d,e){return(e.componentIdentifier?'\x3cimg src\x3d"public/coord-component.png" title\x3d"'+e.componentIdentifier.format+'"/\x3e ':'\x3cimg src\x3d"public/coord-unknown.png" alt\x3d"Unknown"/\x3e ')+Insight.util.encodeHtml($.map(e.displayName.parts,function(a){return a.value}).join(""))}},t=function(a){a=a||[];$.each(a,function(a,b){Insight.util.isNullOrUndefined(b.componentIdentifier)&&
Insight.util.isNotNullOrUndefined(b.groupId)&&(b.componentIdentifier={format:"maven",coordinates:{groupId:b.groupId,artifactId:b.artifactId,version:b.version}});if(Insight.util.isNullOrUndefined(b.displayName))if(b.displayName={},Insight.util.isNotNullOrUndefined(b.componentIdentifier)){var c=b.componentIdentifier.coordinates;switch(b.componentIdentifier.format){case "maven":b.displayName.parts=[{field:"Group",value:c.groupId},{value:" : "},{field:"Artifact",value:c.artifactId},{value:" : "},{field:"Version",
value:c.version}];break;case "nuget":b.displayName.parts=[{field:"ID",value:c.packageId},{value:" "},{field:"Version",value:c.version}];break;default:b.displayName.parts=[];for(var d in c)c.hasOwnProperty(d)&&(b.displayName.parts.push({field:d,value:c[d]}),b.displayName.parts.push({value:" : "}));b.displayName.parts.pop()}}else if(b.filenames&&0<b.filenames.length){b.displayName.parts=[];for(c=0;c<b.filenames.length;c++)b.displayName.parts.push({field:"Filename",value:b.filenames[c]}),c<b.filenames.length-
1&&b.displayName.parts.push({value:", "})}else b.displayName.parts=[{value:"(Anonymized Path) SHA1: "},{field:"Hash",value:b.hash}];b.coordinates=$.map(b.displayName.parts,function(a){return a.value}).join("")})};c($.noop);var A="UNKCAT LIBERAL WEAKCOPYLEFT NOT-PROVIDED NON-STANDARD COPYLEFT".split(" "),v=null,p=null,s=null,r=null,w=null;$.extend(!0,window,{InsightDatatable:{createAuditTable:function(a){w=new Insight.Table("audit",a,{resizeFn:$.noop,selectable:!0,disablePager:!0,disableFilter:!0,
height:250,columns:[{id:"date",name:"Date",field:"date",formatter:function(a,b,c,d,e){return dateFormat(c,"mmm d yyyy, h:MM:ss tt")},sortable:!0,width:30},{id:"user",name:"User",field:"user",toolTipGravity:"n",toolTipFn:function(a){return Insight.util.isNullOrUndefined(a.where)?Insight.util.encodeHtml("Edited report from "+a.ip):Insight.util.encodeHtml("Edited report in build '"+a.where+"' from "+a.ip)},sortable:!0,width:20},{id:"action",name:"Action",field:"action",sortable:!0,width:20},{id:"detail",
name:"Detail",field:"detail",sortable:!0,width:40},{id:"comment",name:"Comment",field:"comment",toolTipGravity:"n",toolTipFn:function(a){if(a.comment)return Insight.util.encodeHtml(a.comment)},sortable:!0,width:80}],defaultSort:{columnId:"date",sortAsc:!1},dataProcessor:function(a){$.each(a,function(a,b){var c=b.status,d="",z;b.id=a;b.date=new Date(b.time);switch(b.status){case "Open":c="Reopened";break;case "Not Applicable":c="Ignored";break;case "Overridden":c="Overrode"}b.action=c;Insight.util.isNullOrUndefined(b.user)&&
(b.user="anonymous");switch(b.filename){case "licenses.json":d="License ";c=b.overriddenLicenses;d=Insight.util.isNotNullOrUndefined(c)?d+("as "+e(c)):d+"Analysis";break;case "security.json":d="Vulnerability ",c=b.source,z=b.reference,Insight.util.isNotNullOrUndefined(c)&&0!==z.toUpperCase().indexOf(c.toUpperCase())&&(d+=c+"-"),d+=z}b.detail=d});return a}});$("#"+w.id+"Table").click(function(a){a.stopPropagation()})},createComponentTable:function(){function a(b){b.preventDefault();$(this).parents("ul").children("li").removeClass("active");
$(this).parents("li").addClass("active");b=$("#policy-match-state-filter li.active").text();var c=$("#policy-violation-filter li.active").text(),d={};"All"!==b&&("Proprietary"===b?d.proprietary=!0:"Error"===b?d.scanError=!0:d.matchState=b.toLowerCase());"Summary"===c?d.summary=!0:"Waived"===c?d.waived=!0:"All"===c&&(d.all=!0);s.addLoadListener(function(){s.table.getData().setFilterArgs(d);s.table.getData().refresh()})}var b=["unknown","similar","exact"],c=new Slick.ColumnGrouping({columnId:"policyName",
style:"scoreCol"}),d=c.getCellStyler(),e=c.getCellRenderer(),f=HealthCheck.getAge(earliestReleaseDate,currentDate),f=[{id:"policyName",name:"Policy Threat",shortName:"Name",field:"policyName",sortable:!0,width:225,styleFn:function(a,b,c,e,f){return"nopad "+d(a,b,c,e,f)},sortFn:function(a,b){var c=a.policyThreatLevel,d=b.policyThreatLevel,e=a.policyName,f=b.policyName;return c<d?-1:c>d||e<f?1:e>f?-1:0},formatter:function(a,b,c,d,f){var g;switch(f.policyThreatLevel){case 0:g=" noScore";break;case 1:g=
" ignoredScore";break;case 2:case 3:g=" moderateScore";break;case 4:case 5:case 6:case 7:g=" severeScore";break;case 8:case 9:case 10:g=" criticalScore"}return'\x3cdiv class\x3d"'+g+'"\x3e'+(0<e(a,b,c,d,f).length?Insight.util.encodeHtml(c):"")+"\x3c/div\x3e"}},$.extend({},n,{styleFn:function(a,b,c,d,e){return e.modified||"Manual"===e.identificationSource?"modified":""},toolTipFn:function(a){var b="";a.modified&&(b+="\x3cli\x3ebeen manually edited.  See the audit log for details.\x3c/li\x3e");"Manual"===
a.identificationSource&&(b+="\x3cli\x3ebeen claimed from an unknown or similar component.  View the Component Information Panel (CIP) for more details.\x3c/li\x3e");a.waived&&(b+="\x3cli\x3ebeen waived.\x3c/li\x3e");if(0<b.length)return"This record has...\x3cbr\x3e\x3cbr\x3e\x3cul\x3e"+b+"\x3c/ul\x3e"},formatter:function(a,b,c,d,e){var f="",f=e.waived?'\x3cimg src\x3d"flag_white.png" style\x3d"margin-right:4px" title\x3d"Violation has been waived"\x3e':'\x3cspan style\x3d"padding-right:20px"\x3e\x3c/span\x3e';
return f+n.formatter(a,b,c,d,e)}}),{id:"versions",name:"Popularity",field:"relativePopularity",sortable:!0,filterable:!1,width:85,sortFn:function(a,c){return a.matchState===b[0]?c.matchState===b[0]?0:-1:c.matchState===b[0]?1:"Manual"===a.identificationSource?a.identificationSource===c.identificationSource?0:-1:"Manual"===c.identificationSource?1:a.relativePopularity<c.relativePopularity?-1:a.relativePopularity>c.relativePopularity?1:0},formatter:function(a,c,d,e,f){if(f.matchState===b[0]||"Manual"===
f.identificationSource)return"";var g;d=Math.round(100*d);79<d?g="popularity-100":59<d?g="popularity-80":39<d?g="popularity-60":19<d?g="popularity-40":0<=d&&(g="popularity-20");return g?'\x3cdiv class\x3d"'+g+'"\x3e\x3c/div\x3e':""}},{id:"age",name:"Age",field:"age",sortable:!0,filterable:!1,width:85,sortFn:function(a,b){var c=a.age,d=b.age;if(!(void 0===c&&void 0===d)){if(void 0===c)return-1;if(void 0===d)return 1;if(c<d)return-1;if(c>d)return 1}return 0},formatter:function(a,b,c,d,e){return void 0===
c||null===c?"":359<c?(c/365).toFixed(1)+" y":30<c?Math.floor(c/30)+" m":Math.floor(c)+" d"}},{id:"releasehistory",name:"Release History",field:"componentIdentifier",sortable:!1,filterable:!1,resizable:!1,width:211,header:'\x3cdiv class\x3d"release-header"\x3e\x3ci class\x3d"icon-question-sign" title\x3d"\x3cdiv style\x3d\'background:url(release-tooltip.png);width:241px;height:78px\'\x3e\x3c/div\x3e"\x3e\x3c/i\x3e\x3cspan\x3e'+f+"\x3c/span\x3e\x3c/div\x3e",formatter:function(a,b,c,d,e){if(null===c||
"Manual"===e.identificationSource)return"No Popularity Data";a={componentIdentifier:JSON.stringify(e.componentIdentifier),groupId:e.groupId,artifactId:e.artifactId,version:e.version};var f="";$.each(a,function(a,b){f+="\x26"+encodeURIComponent(a)+"\x3d"+encodeURIComponent(b)});return'\x3cimg src\x3d"../brain/rest/report/'+applicationId+"/"+reportId+"/releaseGraph?"+f.substring(1)+'" alt\x3d"Release Popularity"\x3e'}}],c=[c,new Insight.InformationPanel({byHash:!0})];Brain.hasFeature("release-graph")||
(f[1].width+=f.pop().width);s=new Insight.Table("component",{get:function(){var a=$.Deferred();$.when($.getJSON("policythreats.json"),$.getJSON("bom.json")).done(function(b,c){function d(a){return a.hash||"error: "+(a.pathnames||[]).join("\t")}if(null===b[0]||null===c[0])a.reject([]);else{var e={},f={},g={},h=[];$.each(c[0].aaData,function(a,b){var c=d(b);e[c]=b;f[c]=!1;g[c]=!1});b[0].version?($("#policy-violation-filter").show(),$.each(b[0].aaData,function(a,b){var c=d(b);if(!b.hash||"null"===b.hash)return!0;
b.activeViolations.length&&(f[c]=!0,b.activeViolations.sort(function(a,b){return b.policyThreatLevel-a.policyThreatLevel}),$.each(b.activeViolations,function(a,d){h.push($.extend({policyThreatLevel:d.policyThreatLevel,policyName:d.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,componentIdentifier:b.componentIdentifier,summary:0===a,waived:!1,all:!0},e[c]))}));b.waivedViolations.length&&(g[c]=!0,$.each(b.waivedViolations,function(a,d){h.push($.extend({policyThreatLevel:d.policyThreatLevel,
policyName:d.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,componentIdentifier:b.componentIdentifier,summary:!1,waived:!0,all:!0},e[c]))}))})):$.each(b[0].aaData,function(a,b){var c=d(b);if(!b.hash||"null"===b.hash)return!0;f[c]=!0;h.push($.extend({policyThreatLevel:b.policyThreatLevel,policyName:b.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,summary:!0,waived:!1,all:!0},e[c]))});$.each(f,function(a,b){b||h.push($.extend(!0,
{policyThreatLevel:0,policyName:"None",summary:!0,waived:!1,all:!1===g[a]},e[a]))});a.resolve({aaData:h})}}).fail(function(b){a.reject(b)});return a}},{columns:f,multiColumnSort:!0,selectable:!0,plugins:c,defaultSort:[{columnId:"policyName",sortAsc:!1},{columnId:"coordinates",sortAsc:!0}],externalFilters:[function(a,b){var c=!0;b&&$.each(b,function(b,d){return c=a[b]===d});return c}],dataProcessor:function(a){a=a||[];$.each(a,function(a,b){b.id=a;b.createTime&&(b.age=Math.floor(((new Date).getTime()-
b.createTime)/864E5))});t(a);return a}});$("#policy-match-state-filter").unbind("click");$("#policy-match-state-filter li a").click(a);$("#policy-violation-filter li a").click(a);$("#policy-match-state-filter li.active a").trigger("click");s.addLoadListener(function(){$(".release-header \x3e .icon-question-sign").tipsy({gravity:"e",html:!0,title:"title",opacity:1})})},createLicenseTable:function(a){var c=[{id:"_formattedEffectiveLicenseThreat",name:"License Threat",shortName:"Licenses",field:"_formattedEffectiveLicenseThreat",
sortable:!0,width:200,styleFn:function(){return"nopad"},sortFn:b,formatter:y,toolTipGravity:"w",toolTipFn:function(a){var b=e(a.declaredLicenses),c=e(a.observedLicenses),d=e(a.overriddenLicenses),b="\x3ctable class\x3d'license-tooltip'\x3e"+("\x3ctr\x3e\x3ctd\x3eDeclared:\x3c/td\x3e\x3ctd\x3e"+b+"\x3c/td\x3e\x3c/tr\x3e")+("\x3ctr\x3e\x3ctd\x3eObserved:\x3c/td\x3e\x3ctd\x3e"+c+"\x3c/td\x3e\x3c/tr\x3e"),b=b+("\x3ctr\x3e\x3ctd\x3eOverridden:\x3c/td\x3e\x3ctd\x3e"+("Overridden"===a.status?d:"-")+"\x3c/td\x3e\x3c/tr\x3e"),
b=b+("\x3ctr\x3e\x3ctd\x3eSelected:\x3c/td\x3e\x3ctd\x3e"+("Selected"===a.status?d:"-")+"\x3c/td\x3e\x3c/tr\x3e");return b+="\x3c/table\x3e"}},n,{id:"status",name:"Status",field:"status",sortable:!0,width:150}],d=[new Insight.InformationPanel];p=new Insight.Table("license","licenses.json",{columns:c,config:a,plugins:d,defaultSort:{columnId:"_formattedEffectiveLicenseThreat",sortAsc:!1},dataProcessor:function(a){var b;for(b=0;b<a.length;b++)a[b].id=b,a[b].status=Insight.util.isNullOrUndefined(a[b].status)?
"Open":a[b].status;t(a);return a}});p.addLoadListener(function(){p.table.setSelectionModel(new Slick.RowSelectionModel);p.table.getData().syncGridSelection(p.table,!0);p.table.getData().onRowsChanged.subscribe(function(a,b){var c,d;b=b.rows;for(d=0;d<b.length;d++)c=p.table.getData().getItem(b[d]),c._formattedEffectiveLicenseThreat=x(c.overriddenLicenses,c.declaredLicenses,c.observedLicenses)})});return p},createSecurityTable:function(a){var b=new Slick.ColumnGrouping({columnId:"_score",style:"scoreCol"}),
c=b.getCellStyler(),d=b.getCellRenderer(),e=[{id:"_score",name:"Threat Level",shortName:"Level",field:"_score",sortable:!0,width:120,toolTip:"'Threat Level' highlights the CVSS (Common Vulnerability Scoring System, version 2) base score for each listed vulnerability.",styleFn:function(a,b,d,e,f){return"nopad "+c(a,b,d,e,f)},sortFn:function(a,b){var c=a._score,d=b._score;return!isNaN(c)&&!isNaN(d)?parseInt(c,10)-parseInt(d,10):d<c?-1:d>c?1:0},formatter:function(a,b,c,e,f){return'\x3cdiv class\x3d"'+
(7<=c?" criticalScore":4<=c?" severeScore":" moderateScore")+'"\x3e'+(d(a,b,c,e,f)||"\x26nbsp;")+"\x3c/div\x3e"}},{id:"problemCode",name:"Problem Code",shortName:"Code",field:"_reference",sortable:!0,width:105,formatter:function(a,b,c,d,e){a=e._reference;return Insight.util.isNullOrUndefined(a)?"":Insight.util.showVulnerabilityDetail()?'\x3ca href\x3d"javascript:void(0);" class\x3d"vulnerability-info-link"\x3e'+a+"\x3c/a\x3e":'\x3ca href\x3d"'+e.url+'" target\x3d"_blank"\x3e'+a+"\x3c/a\x3e"}},n,{id:"status",
name:"Status",field:"status",sortable:!0,width:200}],b=[b,new Insight.InformationPanel],f=[];Insight.util.showVulnerabilityDetail()&&f.push({event:"onClick",handler:function(a,b){if($(a.target).hasClass("vulnerability-info-link")){a.stopPropagation();var c=b.grid.getDataItem(b.row);Insight.util.showSvModal(c.source,c.reference,c.componentIdentifier,c.hash);return!1}return!0}});return v=new Insight.Table("security","security.json",{columns:e,config:a,defaultSort:{columnId:"_score",sortAsc:!1},dataProcessor:function(a){for(var b=
0;b<a.length;b++)a[b].id=b,a[b]._score=Insight.util.isNullOrUndefined(a[b].score)?"Unscored":String(Math.floor(a[b].score)),a[b]._reference=Insight.util.toSvReference(a[b].source,a[b].reference),a[b].status=Insight.util.isNullOrUndefined(a[b].status)?"Open":a[b].status;t(a);return a},plugins:b,handlers:f})},createSimilarityTable:function(a){var c=[{id:"_formattedEffectiveLicenseThreat",name:"License Threat",field:"_formattedEffectiveLicenseThreat",sortable:!0,width:65,sortFn:b,formatter:y},{id:"securityCounters",
name:"Security",field:"securityCounters",sortable:!0,width:50,sortFn:function(a,b){var c=a.securityCounters.Critical-b.securityCounters.Critical;0===c&&(c=a.securityCounters.Severe-b.securityCounters.Severe);0===c&&(c=a.securityCounters.Moderate-b.securityCounters.Moderate);return c},formatter:function(a,b,c,d,e){a=e.securityCounters;var f="",g,h,k=0;b=d.width-10;c=function(a,b){var c;for(c=0;c<a&&!(k>=h);c++)f+='\x3cspan class\x3d"arrow '+b+'_arrow" style\x3d"left:'+k++*g+'px"\x3e\x3c/span\x3e'};
if(a){d=a.Critical+a.Severe+a.Moderate;for(g=0;-9<g&&(d-1)*(10+g)+10>b;g--);h=(b-10)/(10+g)+1;a.Critical&&c(a.Critical,"red");a.Severe&&c(a.Severe,"orange");a.Moderate&&c(a.Moderate,"yellow")}return'\x3cdiv style\x3d"white-space:nowrap;width:'+(0<k?10+(k-1)*(10+g):0)+'px"\x3e'+f+"\x3c/div\x3e"}},$.extend({},n,{width:210})];r=new Insight.Table("similarity",a,{selectable:!0,disablePager:!0,disableFilter:!0,height:250,columns:c,dataProcessor:function(a){a||(a=[]);$.each(a,function(a,b){b.id=a;b._formattedEffectiveLicenseThreat=
x(b.overriddenLicenses,b.declaredLicenses,b.observedLicenses)});t(a);return a}});r.table.render();r.table.columnsResizedFn=function(){var a;for(a=0;a<r.getDataLength();a++)r.updateCell(a,r.getColumnIndex("securityCounters"))};r.table.onColumnsResized.subscribe(r.table.columnsResizedFn);$("#similarityTable").click(function(a){a.stopPropagation()})},destroyActiveTable:function(){var a=q();a&&a.destroy();s=p=v=null},getActiveTable:q,loadLicenseThreats:c,getLicenseThreatLevelFromArray:h,getLicenseThreatClass:k,
removeAuditTable:function(){Insight.util.isNotNullOrUndefined(w)&&(l("audit",w),w=null)},removeComponentTable:function(){Insight.util.isNotNullOrUndefined(s)&&(l("component",s),$("#componentcontainer ul.nav a").unbind("click"),s=null)},removeLicenseTable:function(){Insight.util.isNotNullOrUndefined(p)&&(l("license",p),p=null)},removeSecurityTable:function(){Insight.util.isNotNullOrUndefined(v)&&(l("security",v),v=null)},removeSimilarityTable:function(){Insight.util.isNotNullOrUndefined(r)&&(l("similarity",
r),r=null)}}})})();
(function(c){function h(a,d,e,h,q,l){var m=[],n=[],t=Brain.getCsrfHeaders?Brain.getCsrfHeaders():{};c.each(d,function(a,b){var d=c.extend({},b);c.each(e,function(a,b){d[a]=b});d.modified=!0;m.push(d)});c.merge(n,h);c.each(e,function(a,b){n.push(a)});c.ajax({type:"POST",url:"../augmentData/bom.json",data:f(m,c.merge(["modified"],g)),headers:t});c.ajax({type:"POST",url:"../augmentData/"+q,data:f(m,n),headers:t}).success(function(){a.beginUpdate();c.each(m,function(c,d){a.updateItem(d.id,d)});a.endUpdate();
Insight.updateSummary();l()}).error(function(a,b,c){c=Insight.util.getErrorMessage(a);l(c)})}function f(a,c){for(var d=[],e=0;e<a.length;e++){var f=a[e],g={componentIdentifier:f.componentIdentifier};Insight.util.isNotNullOrUndefined(f.componentIdentifier)&&"maven"===f.componentIdentifier.format&&(g.groupId=f.componentIdentifier.coordinates.groupId,g.artifactId=f.componentIdentifier.coordinates.artifactId,g.version=f.componentIdentifier.coordinates.version);for(var h=0;h<c.length;h++)g[c[h]]=f[c[h]];
d.push(g)}return JSON.stringify(d)}function a(a){a=c.extend({dataView:null,items:[],mask:{},callback:c.noop},a);c.isArray(a.items)||(a.items=[a.items]);h(a.dataView,a.items,a.mask,d,"security.json",a.callback)}var d=["source","reference"],g=["hash"],e;c(document).ready(function(){e=Hogan.compile(c("#svEditorTemplate").html())});c.extend(!0,window,{InsightDatatable:{addSecurityTableEditor:function(a){a=a.table;var c=a.getColumns();a.setSelectionModel(new Slick.RowSelectionModel);a.getData().syncGridSelection(a,
!0);a.setColumns(c)},SecurityEditor:function(b){function d(){0===h.length?c("button[data-type\x3dupdate]",l).attr("disabled","disabled"):c("button[data-type\x3dupdate]",l).removeAttr("disabled")}function f(){h=[];c.each(b.grid.getSelectedRows(),function(a,c){h.push(b.grid.getData().getItem(c))});d()}function g(d){var e={};d.preventDefault();e.status=c("select",l).val();e.comment=c("textarea",l).val();a({mask:e,dataView:b.dataViews[0],items:h,callback:function(a){if(!Insight.util.isNotNullOrUndefined(a))for(var d=
1;d<b.dataViews.length;d++)b.dataViews[d].beginUpdate(),c.each(h,function(a,f){c.each(b.dataViews[d].getItems(),function(a,g){if(!(f.source!==g.source||f.reference!==g.reference||f.componentIdentifier.format!==g.componentIdentifier.format)){for(var h in f.componentIdentifier.coordinates)if(f.componentIdentifier.coordinates.hasOwnProperty(h)&&f.componentIdentifier.coordinates[h]!==g.componentIdentifier.coordinates[h])return;b.dataViews[d].updateItem(g.id,c.extend({},g,e));return!1}})}),b.dataViews[d].endUpdate();
Insight.util.isNotNullOrUndefined(b.callback)&&b.callback.apply(this,arguments)}})}b=c.extend({timestamp:(new Date).getTime()},b);var h=b.artifacts,l;b.grid&&b.grid.onSelectedRowsChanged.subscribe(f);c.extend(this,{destroy:function(){b.grid&&b.grid.onSelectedRowsChanged.unsubscribe(f)},show:function(a){l=a;c(l).html(e.render(b));c("button[data-type\x3dupdate]",l).click(g);c("button[data-type\x3dcancel]",l).click(function(a){a.preventDefault();b.cancelCallback&&b.cancelCallback.apply(this)});c("#svStatus"+
b.timestamp,l).css("width",b.width);d()}})},updateSecurity:a}})})(jQuery);