/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
package com.sonatype.insight.brain.dataaccess.repository;

import java.util.List;
import java.util.Objects;
import java.util.Set;

import com.sonatype.insight.brain.dataaccess.AbstractOperationalSqlDAO;
import com.sonatype.insight.brain.dataaccess.OwnerDAO;
import com.sonatype.insight.brain.db.datastore.OperationalDataStore;
import com.sonatype.insight.brain.model.InvalidNameException;
import com.sonatype.insight.brain.model.NameHelper;
import com.sonatype.insight.brain.model.repository.ManagerType;
import com.sonatype.insight.brain.model.repository.RepositoryManager;
import com.sonatype.insight.dataaccess.TransactionContext;
import com.sonatype.insight.error.exception.NotFoundException;

import jakarta.inject.Inject;
import jakarta.inject.Named;
import jakarta.inject.Provider;
import jakarta.inject.Singleton;
import org.apache.commons.lang3.StringUtils;
import org.jooq.Record;
import org.jooq.Table;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static com.sonatype.insight.brain.jooq.generated.ods.tables.OwnerAncestor.OWNER_ANCESTOR;
import static com.sonatype.insight.brain.jooq.generated.ods.tables.Repository.REPOSITORY;
import static com.sonatype.insight.brain.jooq.generated.ods.tables.RepositoryManager.REPOSITORY_MANAGER;

@Named
@Singleton
public class RepositoryManagerDAO
    extends AbstractOperationalSqlDAO<RepositoryManager>
{
  private static final Logger log = LoggerFactory.getLogger(RepositoryManagerDAO.class);

  private final Provider<OwnerDAO> ownerDAOProvider;

  @Inject
  public RepositoryManagerDAO(
      final OperationalDataStore operationalDataStore,
      final Provider<OwnerDAO> ownerDAOProvider)
  {
    super(operationalDataStore);
    this.ownerDAOProvider = ownerDAOProvider;
  }

  @Override
  public Table<?> getJooqTable() {
    return REPOSITORY_MANAGER;
  }

  public RepositoryManager getByInstanceId(String instanceId) {
    try (TransactionContext tx = createTransactionContext()) {
      return getByInstanceId(tx, instanceId);
    }
  }

  private RepositoryManager getByInstanceId(TransactionContext tx, String instanceId) {
    return toEntity(tx.dsl()
        .selectFrom(REPOSITORY_MANAGER)
        .where(REPOSITORY_MANAGER.INSTANCE_ID.eq(instanceId))
        .fetchOne());
  }

  /**
   * @since 1.161
   */
  public RepositoryManager getByInstanceIdNotNull(String instanceId) {
    try (TransactionContext tx = createTransactionContext()) {
      return getByInstanceIdNotNull(tx, instanceId);
    }
  }

  public RepositoryManager getByInstanceIdNotNull(TransactionContext tx, String instanceId) {
    RepositoryManager repositoryManager = getByInstanceId(tx, instanceId);
    if (repositoryManager == null) {
      throw new NotFoundException("Cannot find a repository manager with instance ID " + instanceId + ".");
    }
    return repositoryManager;
  }

  private void validateName(RepositoryManager repositoryManager) {
    // We default the name to the instance ID if the name was not set.
    // So we need to accept any instance ID as name, and only validate the name if it is set to something different from
    // the instance ID.
    if (!Objects.equals(repositoryManager.getInstanceId(), repositoryManager.getName())) {
      NameHelper.validate("Name", repositoryManager.getName(), NameHelper.MAX_NAME_LENGTH_APP_ORG);
    }
  }

  /**
   * Validates that instanceId is not null or blank for non-virtual repository managers.
   * Virtual managers have their instanceId generated by the server, so null is valid initially.
   */
  private void validateInstanceId(RepositoryManager repositoryManager) {
    Objects.requireNonNull(repositoryManager, "repositoryManager");
    // Virtual managers have instanceId generated server-side, so skip validation
    if (repositoryManager.getManagerType() == ManagerType.VIRTUAL) {
      return;
    }
    if (StringUtils.isBlank(repositoryManager.getInstanceId())) {
      throw new InvalidRepositoryManagerException("The repository manager instance ID cannot be null or empty.");
    }
  }

  public RepositoryManager getByRelatedOrganizationId(String organizationId) {
    try (TransactionContext tx = createTransactionContext()) {
      return getByRelatedOrganizationId(tx, organizationId);
    }
  }

  private RepositoryManager getByRelatedOrganizationId(TransactionContext tx, String organizationId) {
    return toEntity(tx.dsl()
        .selectFrom(REPOSITORY_MANAGER)
        .where(REPOSITORY_MANAGER.RELATED_ORGANIZATION_ID.eq(organizationId))
        .fetchOne());
  }

  @Override
  public void insert(TransactionContext tx, RepositoryManager repositoryManager) {
    validateInstanceId(repositoryManager);
    validateName(repositoryManager);

    if (getByInstanceId(tx, repositoryManager.getInstanceId()) != null) {
      throw new InvalidRepositoryManagerException("There is already a repository manager with instance ID "
          + repositoryManager.getInstanceId() + ".");
    }

    if (repositoryManager.getName() != null
        && getByName(tx, repositoryManager.getName()) != null)
    {
      throw new InvalidNameException(repositoryManager.getName() + " is already used as a name.");
    }

    super.insert(tx, repositoryManager);
  }

  @Override
  public void update(TransactionContext tx, RepositoryManager repositoryManager) {
    validateInstanceId(repositoryManager);
    validateName(repositoryManager);

    RepositoryManager existingRepositoryManager = getByInstanceId(tx, repositoryManager.getInstanceId());
    if (existingRepositoryManager != null && !existingRepositoryManager.getId().equals(repositoryManager.getId())) {
      throw new InvalidRepositoryManagerException("There is already a repository manager with instance ID "
          + repositoryManager.getInstanceId() + ".");
    }

    if (repositoryManager.getName() != null) {
      RepositoryManager foundByNameRepositoryManager = getByName(tx,
          repositoryManager.getName());
      if (foundByNameRepositoryManager != null && !repositoryManager.getId()
          .equals(foundByNameRepositoryManager.getId()))
      {
        throw new InvalidNameException(
            repositoryManager.getName() + " is already used as a name.");
      }
    }

    super.update(tx, repositoryManager);
  }

  public RepositoryManager getByName(TransactionContext tx, String name) {
    name = NameHelper.normalize(name);
    return toEntity(tx.dsl()
        .selectFrom(REPOSITORY_MANAGER)
        .where(REPOSITORY_MANAGER.NAME_LOWERCASE_NO_WHITESPACE.eq(name))
        .fetchOne());
  }

  @Override
  public void delete(TransactionContext tx, RepositoryManager repositoryManager) {
    long start = System.currentTimeMillis();

    // Cascade to owned entities
    ownerDAOProvider.get().cascadeDelete(tx, repositoryManager);

    super.delete(tx, repositoryManager);

    long duration = System.currentTimeMillis() - start;
    if (duration > 500) {
      log.debug("Deleted repository manager with id {} in {} ms.", repositoryManager.getId(), duration);
    }
  }

  /**
   * @since 1.160
   */
  public List<RepositoryManager> getUnconfigured() {
    try (TransactionContext tx = createTransactionContext()) {
      return tx.dsl()
          .selectFrom(REPOSITORY_MANAGER)
          .where(REPOSITORY_MANAGER.CONFIGURED.eq(false))
          .fetch(this::toEntity);
    }
  }

  public RepositoryManager getByName(String name) {
    try (TransactionContext tx = createTransactionContext()) {
      return getByName(tx, name);
    }
  }

  /**
   * @return the RepositoryManager that either has the specified id or is the parent of a repository with that id
   */
  public RepositoryManager getByIdOrRepositoryId(String ownerId) {
    try (TransactionContext tx = createTransactionContext()) {
      return getByIdOrRepositoryId(tx, ownerId);
    }
  }

  public RepositoryManager getByIdOrRepositoryId(TransactionContext tx, String ownerId) {
    Record record = tx.dsl()
        .select(REPOSITORY_MANAGER.fields())
        .from(REPOSITORY_MANAGER)
        .join(OWNER_ANCESTOR)
        .on(REPOSITORY_MANAGER.REPOSITORY_MANAGER_ID.eq(OWNER_ANCESTOR.ANCESTOR_ID))
        .where(OWNER_ANCESTOR.OWNER_ID.eq(ownerId)
            .and(OWNER_ANCESTOR.OWNER_TYPE.in("REPOSITORY", "REPOSITORY_MANAGER")))
        .fetchOne();
    return record != null ? toEntity(record.into(REPOSITORY_MANAGER)) : null;
  }

  public List<RepositoryManager> getByRepositoryIds(Set<String> repositoryIds) {
    return getListWithSqlInClause(repositoryIds, inClauseValuesPartition -> {
      try (TransactionContext tx = createTransactionContext()) {
        return tx.dsl()
            .select(REPOSITORY_MANAGER.fields())
            .from(REPOSITORY_MANAGER)
            .join(REPOSITORY)
            .on(REPOSITORY_MANAGER.REPOSITORY_MANAGER_ID.eq(REPOSITORY.REPOSITORY_MANAGER_ID))
            .where(REPOSITORY.REPOSITORY_ID.in(inClauseValuesPartition))
            .fetch(r -> toEntity(r.into(REPOSITORY_MANAGER)));
      }
    });
  }

  public List<RepositoryManager> getByIds(Set<String> repositoryManagerIds) {
    return getListWithSqlInClause(repositoryManagerIds, inClauseValuesPartition -> {
      try (TransactionContext tx = createTransactionContext()) {
        return tx.dsl()
            .selectFrom(REPOSITORY_MANAGER)
            .where(REPOSITORY_MANAGER.REPOSITORY_MANAGER_ID.in(inClauseValuesPartition))
            .fetch(this::toEntity);
      }
    });
  }

  @Override
  public Class<RepositoryManager> getEntityClass() {
    return RepositoryManager.class;
  }
}
