/*
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2012-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
*/
(function(){function c(a){var e=this;this.options=$.extend(!0,{},h,a);this.node=$("\x3cdiv id\x3d'informationPanel' class\x3d'informationPanel fullBorderedTable'\x3e\x3cdiv style\x3d'width:99%; padding-top: 5px; padding-left: 0.5%; padding-right: 0.5%;'\x3e\x3ca class\x3d'close'\x3e\x26times;\x3c/a\x3e\x3cul class\x3d'nav nav-tabs' style\x3d'margin-bottom:0px; !important'\x3e\x3c/ul\x3e\x3cdiv class\x3d'tab-content' style\x3d'overflow:hidden'\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");$(".close",this.node).click(function(){e.hide()});
this.plugins=[];Insight.InformationPanelPlugins.sort(function(a,d){return a.prototype.priority-d.prototype.priority});$.each(Insight.InformationPanelPlugins,function(a,d){var b=$('\x3cli data-info-plugin\x3d"'+a+'" class\x3d"tm-cip-nav-'+d.name+'"\x3e\x3ca data-target\x3d"infoPanel'+a+'" data-toggle\x3d"tab"\x3e\x3c/a\x3e\x3c/li\x3e'),k=$('\x3cdiv class\x3d"tab-pane" id\x3d"infoPanel'+a+'" class\x3d"tm-cip-content-'+d.name+'"\x3e\x3c/div\x3e');$("ul.nav",e.node).append(b);$("div.tab-content",e.node).append(k);
e.plugins.push(new d(k,e.options))});$('a[data-toggle\x3d"tab"]',this.node).on("show",function(a){var d;null!==a.relatedTarget&&(d=$(a.relatedTarget.parentNode).data("info-plugin"),e.plugins[d].destroy(),$("#"+$(a.relatedTarget).data("target"),e.node).hide());null!==a.target&&(d=$(a.target.parentNode).data("info-plugin"),a=$("#"+$(a.target).data("target"),e.node),a.show(),e.plugins[d].create(a,e.node))})}function g(a){a=a||{};this.priority=a.priority||512}var h={byHash:!1};c.prototype.destroy=function(){this.cleanPlugins()};
c.prototype.hide=function(){this.node.detach();this.grid.removeCellCssStyles("popout");this.cleanPlugins()};c.prototype.init=function(a){var e=this;this.grid=a;a.onClick.subscribe(function(){e.gridClickedFn.apply(e,arguments)});a.getData().onRowCountChanged.subscribe(function(){e.hide()});a.getData().onRowsChanged.subscribe(function(){e.rowChangedFn.apply(e,arguments)});$.each(this.plugins,function(f,d){d.setGrid(a)})};c.prototype.cleanPlugins=function(){$.each(this.plugins,function(a,e){e.destroy()})};
c.prototype.gridClickedFn=function(a,e){var f=this;"INPUT"!==a.target.tagName&&0===$(a.target).children("input:first").length&&(Insight.util.isNotNullOrUndefined(f.timer)?(clearTimeout(f.timer),f.timer=null):f.timer=setTimeout(function(){f.timer=null;$.each(f.plugins,function(a,b){b.setItem(f.grid.getDataItem(e.row))});f.toggle(a,e)},250))};c.prototype.getItem=function(){return this.grid.getDataItem(this.currentRow)};c.prototype.updatePanel=function(){var a=this,e=null;$.each(this.plugins,function(f,
d){var b=$("li[data-info-plugin\x3d"+f+"]",a.node);d.isVisible()?(b.show(),$("a",b).text(d.getTitle())):(b.hide(),$("#infoPanel"+f,a.node).hide(),b.hasClass("active")&&(b.removeClass("active"),$("ul.nav \x3e li:first",a.node).addClass("active")))});0===$("li.active",a.node).length&&$("li",a.node).each(function(a,d){d=$(d);if("none"!==d.css("display"))return d.addClass("active"),!1});e=$("li.active",a.node).data("info-plugin");a.plugins[e].create();$("#infoPanel"+e,a.node).show()};c.prototype.rowChangedFn=
function(a,e){var f=this.currentRow,d=this;setTimeout(function(){var a=d.grid.getSelectedRows(),k=null;Insight.util.isNotNullOrUndefined(f)&&1===a.length?f!==a[0]?(d.hide(),Insight.util.isNotNullOrUndefined(this.currentItemId)&&d.show({row:a[0],cell:1},d.grid.getCanvasNode())):(d.position(f),k=d.getItem(),$.each(d.plugins,function(a,b){b.setItem(k)}),d.updatePanel()):d.hide()},10)};c.prototype.toggle=function(a,e){this.grid.removeCellCssStyles("popout");$(this.node).is(":hidden")||this.currentRow!==
e.row?this.show(this.grid.getCellFromEvent(a),$(a.currentTarget)):this.hide()};c.prototype.show=function(a,e){var f={},d=this.grid.getCellNode(a.row,a.cell),b=$(this.grid.getCanvasNode()).parent();b.offset();b.height();var k=this;Insight.util.isNullOrUndefined(d)&&(this.grid.scrollRowIntoView(a.row),d=this.grid.getCellNode(a.row,a.cell));this.node.css("top",d.offsetParent.offsetTop+d.offsetParent.clientHeight);this.node.addClass("shadowBottom");this.node.removeClass("shadowTop");k.node.appendTo(e);
this.updatePanel();k.position(a.row);k.node.show();this.currentRow=a.row;f[this.currentRow]={};$.each(k.grid.getColumns(),function(a,b){f[k.currentRow][b.id]="popout"});k.grid.setCellCssStyles("popout",f)};c.prototype.position=function(a){var e=this.node.offset().top,f=e+this.node.height(),d=$(this.grid.getCanvasNode()).parent(),b=d.offset().top,k=b+d.height(),x=this.grid.getCellNode(a,1);Insight.util.isNullOrUndefined(x)&&(this.grid.scrollRowIntoView(a),x=this.grid.getCellNode(a,1));(f>k||e<b)&&
d.scrollTop(d.scrollTop()+(this.node.offset().top-x.offsetParent.clientHeight)-d.offset().top);this.node.css("width",d.width()-(d.get(0).scrollHeight>d.height()?this.grid.getScrollbarDimensions().width:0)-2+"px")};g.prototype.getErrorFn=function(a,e,f){return function(){var d=$(a);d.html(Insight.templates.error.render());$(".btn",d).click(function(){e.apply(f,[])})}};g.prototype.isVisible=function(){return!0};g.prototype.getTitle=function(){return""};g.prototype.setItem=function(a){Insight.util.isNullOrUndefined(a.componentIdentifier)&&
Insight.util.isNotNullOrUndefined(a.groupId)&&Insight.util.isNotNullOrUndefined(a.artifactId)&&Insight.util.isNotNullOrUndefined(a.version)&&(a.componentIdentifier={format:"maven",coordinates:{groupId:a.groupId,artifactId:a.artifactId,version:a.version}});this.gav=this.component=a};g.prototype.message=function(a){$(".alert",this.node).remove();a=$('\x3cdiv class\x3d"alert" style\x3d"width:92.5%"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3e\x3c/div\x3e');$("div:first",
this.node).prepend(a);return a};g.prototype.addErrorMessage=function(a){this.message(a).addClass("alert-error").append("\x3cstrong\x3eError: \x3c/strong\x3e",$("\x3cspan\x3e\x3c/span\x3e").text(a))};g.prototype.addSuccessMessage=function(a){var e=this.message(a).addClass("alert-success").append($("\x3cspan\x3e\x3c/span\x3e").text(a));setTimeout(function(){e.fadeOut("fast",function(){e.remove()})},8E3);return e};g.prototype.setGrid=function(a){this.grid=a};g.prototype.create=$.noop;g.prototype.destroy=
$.noop;$.extend(!0,window,{Insight:{InformationPanel:c,InformationPanelPlugin:g,InformationPanelPlugins:[]}})})();
(function(){function c(a){return"../artifactDetails/"+reportId+"?groupId\x3d"+a.groupId+"\x26artifactId\x3d"+a.artifactId+"\x26version\x3d"+a.version}function g(a,d){var b=[];return Insight.util.isNotNullOrUndefined(a)&&0<a.length?("object"===typeof a[0]?$.each(a,function(a,d){b.push(Insight.util.encodeHtml(d.licenseName))}):$.each(a,function(a,d){b.push(Insight.util.encodeHtml(d))}),'\x3cspan class\x3d"license"\x3e'+b.join(',\x3c/span\x3e \x3cspan class\x3d"license"\x3e')+"\x3c/span\x3e"):d||""}
function h(a,d,b){var k="artifactInfoSecurity",c=Math.floor(a.securityThreatLevel);$(d).is(":hidden")||(0>=a.securityThreatCount?(c="NA",k+=" artifactInfoSecurityUnspecified"):7<=c?k+=" artifactInfoSecurityCritical":4<=c?k+=" artifactInfoSecuritySevere":(0<=c||(c="Unscored"),k+=" artifactInfoSecurityModerate"),a=$.extend(a,{partial:!1,overriddenLicenses:g(a.overriddenLicenses,"-"),declaredLicenses:g(a.declaredLicenses,"-"),observedLicenses:g(a.observedLicenses,"-"),currentMatchState:b.matchState,
proprietary:b.proprietary,colorCls:k,lvl:c,cataloged:a.catalogDate?HealthCheck.getAge(new Date(a.catalogDate)):null,multipleSecurity:1<a.securityThreatCount,isManual:"Manual"===a.identificationSource}),d.html(e.render(a)),Insight.ComponentInformation({data:a,partialDisplay:!1}))}function a(a,d){this.node=a;this.options=d}var e;$(document).ready(function(){e=Hogan.compile($("#infoPanelComponentTemplate").html())});a.prototype=new Insight.InformationPanelPlugin({priority:1});a.prototype.create=Brain.ci&&
Brain.ci.getArtifactVersionInfoUrl?function(){var a=this,d=a.component,b=null,k=null,e=null,c=null,g=function(){null!==k&&null!==b&&d===a.component&&(k.securityThreatCount=0,k.securityThreatLevel=null,$.each(k.securityVulnerabilities,function(a,b){"Not Applicable"!==b.status&&(k.securityThreatCount++,Insight.util.isNotNullOrUndefined(b.severity)&&(k.securityThreatLevel=Math.max(k.securityThreatLevel,b.severity)))}),k.versions=b,h(k,a.node,d))};Insight.util.isNullOrUndefined(this.component.componentIdentifier)?
this.node.html("\x3cdiv class\x3d'infoPanelText'\x3eUnknown Component\x3c/div\x3e"):($(this.node).html('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e'),e=$.extend({},this.component,{appId:applicationId,instanceId:instanceId}),c=Brain.ci.getComponentDetailsListUrl?Brain.ci.getComponentDetailsListUrl(e):Brain.ci.getArtifactVersionInfoUrl(e),$.getJSON(Insight.toBrain(Brain.ci.getArtifactInfoUrl(e)),
function(a){k=a;g()}).error(this.getErrorFn(this.node,this.create,this)),$.getJSON(Insight.toBrain(c),function(a){b=a.list?a.list:a;g()}).error(this.getErrorFn(this.node,this.create,this)))}:function(){var a=this,d=a.component;Insight.util.isNullOrUndefined(this.component.componentIdentifier)?this.node.html("\x3cdiv class\x3d'infoPanelText'\x3eUnknown Artifact\x3c/div\x3e"):($(this.node).html('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e'),
$.getJSON(c(this.component),function(b){a.component===d&&h(b,$(a.node),d)}).error(this.getErrorFn(this.node,this.create,this)))};a.prototype.destroy=function(){this.node.empty()};a.prototype.getTitle=function(){return"Component Info"};Insight.InformationPanelPlugins.push(a)})();
(function(){function c(c,h){this.node=c;this.options=h}c.prototype=new Insight.InformationPanelPlugin({priority:32});c.prototype.isVisible=function(){return"unknown"!==this.component.matchState&&Brain.hasFeature("policy-violations")};c.prototype.create=function(){var c=(new Date).getTime(),h=$('\x3cdiv id\x3d"policy-violations-'+c+'"\x3e\x3c/div\x3e'),a=this,e=function(){Insight.PolicyViolations?Insight.PolicyViolations(h,applicationId,a.component.hash):setTimeout(e,1E3)};this.node.empty();h.appendTo(this.node);
e()};c.prototype.destroy=function(){this.node.empty()};c.prototype.getTitle=function(){return"Policy"};Insight.InformationPanelPlugins.push(c)})();
(function(){function c(c,h){this.node=c;this.options=h}c.prototype=new Insight.InformationPanelPlugin({priority:48});c.prototype.isVisible=function(){return!0};c.prototype.create=function(){var c=this;this.destroy();this.component.hash?$.getJSON("partialmatched.json",function(h){var a=null,e;for(e=0;e<h.aaData.length;e++)if(h.aaData[e].hash===c.component.hash){a=h.aaData[e].matchDetails;break}a?($(c.node).html("\x3cdiv id\x3d'similarityTable' class\x3d'borderedTable'\x3e\x3c/div\x3e"),InsightDatatable.createSimilarityTable(a)):
$(c.node).html("\x3cdiv class\x3d'infoPanelText'\x3eNo similar matches were found for this component.\x3c/div\x3e")},this.getErrorFn(c.node,c.create,c)):$(c.node).html("\x3cdiv class\x3d'infoPanelText'\x3eNo similar matches were found for this component.\x3c/div\x3e")};c.prototype.destroy=function(){InsightDatatable.removeSimilarityTable();this.node.empty()};c.prototype.getTitle=function(){return"Similar"};Insight.InformationPanelPlugins.push(c)})();
(function(){function c(c){var a,e;if(0===c.indexOf("dependency:/"))return c=c.substring(12),a=c.lastIndexOf("/"),0>a?["Dependency "+c,""]:["Dependency "+c.substring(a+1),"Module "+c.substring(0,a)];a=c.lastIndexOf("/");if(-1===a)return[c,""];e=c.substring(a+1);c=c.substring(0,a);return[e,c]}function g(c,a){this.node=c;this.options=a}g.prototype=new Insight.InformationPanelPlugin({priority:64});g.prototype.buildView=function(g){if(0<g.length){g.sort();var a="\x3cdiv class\x3d'infoPanelText fileDetail'\x3e",
e=!1;$.each(g,function(f,d){$.each(d.pathnames,function(b,d){var e=c(d);a+="\x3cb\x3e"+Insight.util.encodeHtml(e[0])+"\x3c/b\x3e";0<e[1].length&&(a+=" \x3ci\x3elocated at\x3c/i\x3e "+Insight.util.encodeHtml(e[1]));a+="\x3cbr\x3e\x3cbr\x3e"});0>=d.pathnames.length&&(e=!0)});e&&(a+="Occurrences of this component cannot be listed because pathnames have been anonymized. To see all occurrences, please disable anonymization in the options of your CLM enforcement points and perform a new scan.");a+="\x3c/div\x3e";
$(this.node).html(a)}else $(this.node).html("\x3cdiv class\x3d'infoPanelText'\x3eInvalid data encountered, no files are associated with this component.\x3c/div\x3e")};g.prototype.create=function(){var c=this;c.options.byHash?this.buildView([c.component]):$.getJSON("bom.json",function(a){var e=[];$.each(a.aaData,function(a,d){Insight.util.componentsEqual(d,c.component)&&e.push(d)});c.buildView(e)},this.getErrorFn(c.node,c.create,c))};g.prototype.destroy=function(){};g.prototype.getTitle=function(){return"Occurrences"};
Insight.InformationPanelPlugins.push(g)})();
(function(){function c(c,h,a,e,f,d,b,k){Insight.util.isNotNullOrUndefined(c[a])?e.call(k,{aaData:b.getData().getItems()},!0):$.getJSON(h,function(a){e.call(this,a,!1)}).error(d)}(function(){function g(a,c){this.node=a;this.options=c}var h=null;$(document).ready(function(){h=Hogan.compile($("#infoPanelSecurityEditor").html())});g.prototype=new Insight.InformationPanelPlugin({priority:96});g.prototype.toSV=function(a,e){var f=this;c(f.component,"security.json","reference",function(d,b){var c=[];$.each(d.aaData,
function(a,b){Insight.util.componentsEqual(b,f.component)&&c.push($.extend({},b,{id:a}))});a.call(this,c,b)},a,e,this.grid,this)};g.prototype.isVisible=function(){return"unknown"!==this.component.matchState&&"Manual"!==this.component.identificationSource};g.prototype.create=function(){this.destroy();var a=(new Date).getTime(),c=$('\x3cdiv id\x3d"svEditor'+a+'" style\x3d"width:100%"\x3e\x3c/div\x3e').appendTo(this.node),f=this,d;this.toSV(function(b,k){var g="sv"+a,v=new Slick.CheckboxSelectColumn,
r={timestamp:a,width:300,callback:function(a){if(Insight.util.isNullOrUndefined(a)){a=f.grid;var b=$(a.getCanvasNode()).parents("[data-container\x3dtrue]").attr("id"),c,b=b.substring(0,b.length-9);"component"===b&&(c=a.getSelectedRows(),1===c.length&&(b=a.getData(),b.beginUpdate(),a=a.getDataItem(c[0]),a.modified=!0,b.updateItem(a.id,a),b.endUpdate()));a=d.table.getSelectedRows();1===a.length?f.addSuccessMessage("Updated "+a.length+" security vulnerability."):1<a.length&&f.addSuccessMessage("Updated "+
a.length+" security vulnerabilities.")}else f.addErrorMessage(a)},artifacts:[]};$(c).html(h.render({timestamp:a}));var l=[v.getColumnDefinition(),{id:"_score",name:"Threat Level",field:"_score",sortable:!0,width:90,minWidth:90,toolTip:"'Threat Level' highlights the CVSS (Common Vulnerability Scoring System, version 2) base score for each listed vulnerability.",styleFn:function(a,b,d,c,e){return"nopad"},sortFn:function(a,b){var d=a._score,c=b._score;return isNaN(d)||isNaN(c)?c<d?-1:c>d?1:0:parseInt(d)-
parseInt(c)},formatter:function(a,b,d,c,e){return'\x3cdiv class\x3d"'+(7<=d?" criticalScore":4<=d?" severeScore":" moderateScore")+'"\x3e'+(d||"\x26nbsp;")+"\x3c/div\x3e"}},{id:"problemCode",name:"Problem Code",field:"_reference",sortable:!0,width:90,minWidth:90,formatter:Insight.util.showVulnerabilityDetail()?null:function(a,b,d,c,e){a=e._reference;e=e.url;return Insight.util.isNullOrUndefined(a)?"":'\x3ca href\x3d"'+e+'" target\x3d"_blank"\x3e'+a+"\x3c/a\x3e"}}];Insight.util.showVulnerabilityDetail()&&
l.push({id:"info",name:"Info",field:"source",sortable:!1,width:30,minWidth:30,formatter:function(a,b,d,c,e){return'\x3cdiv\x3e\x3cbutton type\x3d"button" class\x3d"btn vulnerability-info-button"\x3e\x3c/button\x3e\x3c/div\x3e'}});l.push({id:"status",name:"Status",field:"status",sortable:!0,width:Insight.util.showVulnerabilityDetail()?60:90,minWidth:Insight.util.showVulnerabilityDetail()?60:90,sortFn:function(a,b){a=Insight.util.isNotNullOrUndefined(a.status)?a.status:"Open";b=Insight.util.isNotNullOrUndefined(b.status)?
b.status:"Open";return a>b?1:a<b?-1:0},formatter:function(a,b,d,c,e){return Insight.util.isNotNullOrUndefined(d)?d:"Open"}});d=new Insight.Table(g,b,{resizeFn:$.noop,height:"220px",width:"100%",disableFilter:!0,selectable:!0,dataProcessor:function(a){for(var b=0;b<a.length;b++)a[b].id=b,a[b]._score=Insight.util.isNullOrUndefined(a[b].score)?"Unscored":String(Math.floor(a[b].score)),a[b]._reference=Insight.util.toSvReference(a[b].source,a[b].reference);k&&setTimeout(function(){$.each(a,function(a,
b){if(b.source===f.component.source&&b.reference===f.component.reference)return d.table.setSelectedRows([d.table.getData().getRowById(b.id)]),!1})},1);return a},defaultSort:{columnId:"_score",sortAsc:!1},plugins:[v],columns:l,handlers:[{event:"onClick",handler:function(a,b){var d=$(a.target);if(d.hasClass("vulnerability-info-button")){var c=b.grid.getDataItem(b.row);Insight.util.showSvModal(c.source,c.reference,c.componentIdentifier,c.hash)}else"A"===a.target.nodeName&&window.open($(a.target).attr("href"),
"_blank");d.is(":checkbox")||a.stopPropagation()}}]});$.extend(r,{dataViews:[d.table.getData()],grid:d.table});k&&r.dataViews.push(this.grid.getData());(new InsightDatatable.SecurityEditor(r)).show("#editor"+a)},this.getErrorFn(this.node,this.create,this))};g.prototype.destroy=function(){$("[data-slickgrid]",this.node).each(function(){$(this).data("data-slickgrid").destroy()});this.node.empty()};g.prototype.getTitle=function(){return"Edit Vulnerabilities"};Insight.InformationPanelPlugins.push(g)})()})();
(function(){function c(c,h){this.node=c;this.options=h}c.prototype=new Insight.InformationPanelPlugin({priority:112});c.prototype.isVisible=function(){return"unknown"!==this.component.matchState&&Brain.hasFeature("labels")};c.prototype.create=function(){var c=(new Date).getTime(),h=$('\x3cdiv id\x3d"labels-'+c+'"\x3e\x3c/div\x3e'),a=this,e=function(){Insight.LabelEditor?Insight.LabelEditor(h,applicationId,a.component.hash,a.component):setTimeout(e,1E3)};this.node.empty();h.appendTo(this.node);e()};
c.prototype.destroy=function(){this.node.empty()};c.prototype.getTitle=function(){return"Labels"};Insight.InformationPanelPlugins.push(c)})();
(function(){function c(c){c.html("\x3cdiv style\x3d'width:99%;padding:7px 0 5px 1%;vertical-align:-12px;'\x3eNo changes were found for this component.\x3c/div\x3e")}function g(c,a){this.node=c;this.options=a}g.prototype=new Insight.InformationPanelPlugin({priority:99999});g.prototype.isVisible=function(){return"unknown"!==this.component.matchState};g.prototype.create=function(){var g=this,a=function(a){a?(g.node.html('\x3cdiv id\x3d"auditTable" class\x3d"borderedTable"\x3e\x3c/div\x3e'),InsightDatatable.createAuditTable(a.aaData)):
c(g.node)};Brain.hasFeature("component-identifier")&&Insight.util.isNotNullOrUndefined(this.component.componentIdentifier)?$.getJSON("../auditLog/licenses.json+security.json","key\x3d"+JSON.stringify({hash:this.component.hash,componentIdentifier:this.component.componentIdentifier}),a).error(this.getErrorFn(this.node,this.create,this)):Insight.util.isNotNullOrUndefined(this.component.groupId)?$.getJSON("../auditLog/licenses.json+security.json","key\x3d"+JSON.stringify(this.component,["hash","groupId",
"artifactId","version"]),a).error(this.getErrorFn(this.node,this.create,this)):c(this.node)};g.prototype.destroy=function(){InsightDatatable.removeAuditTable();this.node.empty()};g.prototype.getTitle=function(){return"Audit Log"};Insight.InformationPanelPlugins.push(g)})();
(function(){function c(a){return null===a||"undefined"===typeof a}function g(a,c,f,d){var b=$("#sv-info-modal .modal-body");a&&c?(b.empty(),b.append("\x3cp\x3eLoading vulnerability detail content\x3c/p\x3e"),h&&"pending"===h.state()&&h.reject("reject"),h=$.getJSON(Insight.toBrain(Brain.getVulnerabilityDetailUrl(a,c,f,d))).done(function(a){b.empty();b.append(a.htmlDetails)}).fail(function(k){"reject"!==k&&(b.empty(),b.append(Insight.templates.error.render()),$(".btn",b).click(function(){g(a,c,f,d)}))})):
(b.empty(),b.append("Unable to construct url for vulnerability detail content."));$("#sv-info-modal").modal("show")}var h;$.extend(!0,window,{Insight:{toBrain:function(a){return"/"===a.charAt(0)?"../brain"+a:"../brain/"+a},util:{enableTooltip:function(a){$(a).each(function(){var a=$(this).attr("data-gravity-offset")||0;a&&(a=parseInt(a,10));$(this).tipsy({fade:!0,gravity:$(this).attr("data-gravity"),offset:a,html:!0,opacity:1,delayOut:0,title:"data-tooltip"})})},getErrorMessage:function(a){var c=
"";return c=0===a.status||1E3<=a.status?"Network error while contacting server":a.responseText&&0<=(a.getResponseHeader("Content-Type")||"").indexOf("text/plain")?a.responseText:a.statusText?a.statusText:"Error "+a.status},getQueryParameter:function(a){var c=0<window.location.search.length?window.location.search.substring(1).split("\x26"):[],f=null,d=null;a=a.toLowerCase();for(d=0;d<c.length;d++)if(f=c[d].split("\x3d"),f[0].toLowerCase()===a)return f[1]},isNullOrUndefined:c,isNotNullOrUndefined:function(a){return!c(a)},
componentsEqual:function(a,c){if(Insight.util.isNullOrUndefined(a.componentIdentifier)&&Insight.util.isNullOrUndefined(c.componentIdentifier))return a.groupId===c.groupId&&a.artifactId===c.artifactId&&a.version===c.version;if(Insight.util.isNullOrUndefined(a.componentIdentifier)||Insight.util.isNullOrUndefined(c.componentIdentifier)||a.componentIdentifier.format!==c.componentIdentifier.format||a.componentIdentifier.coordinates.length!==c.componentIdentifier.coordinates.length)return!1;for(var f in a.componentIdentifier.coordinates)if(a.componentIdentifier.coordinates.hasOwnProperty(f)&&
a.componentIdentifier.coordinates[f]!==c.componentIdentifier.coordinates[f])return!1;return!0},toSvReference:function(a,c){var f=Insight.util.isNullOrUndefined(a)?"":a.toUpperCase(),d=Insight.util.isNullOrUndefined(c)?"":c.toUpperCase();return 0>d.indexOf(f)?f+"-"+d:d},showSvModal:g,showVulnerabilityDetail:function(){return Brain.getVulnerabilityDetailUrl},encodeHtml:function(){var a=$("\x3cdiv/\x3e");return function(c){return a.text(c).html()}}()}}})})();
(function(){function c(a){var b={criticalCount:0,severeCount:0,moderateCount:0,noThreatCount:0};$.each(a.effectiveLicenseCounts,function(a,c){7<a?b.criticalCount+=c:3<a?b.severeCount+=c:0<a?b.moderateCount+=c:b.noThreatCount+=c});b.count=b.criticalCount+b.severeCount+b.moderateCount+b.noThreatCount;b.licenseAlerts=b.criticalCount+b.severeCount+b.moderateCount;b.multipleLicenseAlerts=1!==b.licenseAlerts;return b}function g(a){var b={criticalCount:0,severeCount:0,moderateCount:0,count:0};$.each(a.securityCounts,
function(a,c){6<a?b.moderateCount+=c:3<a?b.severeCount+=c:b.criticalCount+=c;b.count+=c});b.multiple=1!==b.count;b.insecureArtifactCount=a.insecureArtifactCount;b.multipleComponents=1<b.insecureArtifactCount;return b}function h(a){var b={criticalCount:0,severeCount:0,moderateCount:0};b.policyComponentCount=a.policyComponentCount;b.multipleComponents=0<b.policyComponentCount;$.each(a.policyCounts,function(a,c){8<=a?b.criticalCount+=c:4<=a?b.severeCount+=c:1<a&&(b.moderateCount+=c)});b.multipleAlerts=
1<b.criticalCount+b.severeCount+b.moderateCount?!0:!1;b.hasPolicyAlerts=0<b.criticalCount+b.severeCount+b.moderateCount?!0:!1;b.grandfatheredPolicyViolationCount=a.grandfatheredPolicyViolationCount;b.grandfathering=void 0!==b.grandfatheredPolicyViolationCount;b.multipleGrandfatheredViolations=1!==b.grandfatheredPolicyViolationCount;return b}function a(){var d=$("#summary"),b=function(b,c,e){d.empty();d.append(Insight.templates.error.render({message:Insight.util.getErrorMessage(b)}));$("button",d).click(a)};
d.html('\x3cdiv class\x3d"alert alert-info"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e');$.getJSON("data.json").success(function(a){if(null===a)b({status:0});else{var f=$.extend(a,{policy:h(a),sv:g(a),license:c(a),knownComponentCount:a.knownArtifactCount,totalComponentCount:a.totalArtifactCount,percentKnownComponents:a.totalArtifactCount?Math.round(100*a.knownArtifactCount/a.totalArtifactCount):0,multipleKnown:1!=a.knownArtifactCount}),v=d.is(":visible");d.hide();d.html(e.render(f));HealthCheck.barChart(a.securityCounts,
{element:$("#security-chart")[0]});HealthCheck.punchCard(a.securityPunchCard,{element:$("#security-punchcard")[0]});HealthCheck.licenseChart([f.license.criticalCount/f.license.count,f.license.severeCount/f.license.count,f.license.moderateCount/f.license.count,(f.license.count-f.license.licenseAlerts)/f.license.count],{element:$("#license-chart")[0]});HealthCheck.punchCard(a.licensePunchCard,{element:$("#license-punchcard")[0]});HealthCheck.artifactsChart(0<a.totalArtifactCount?1-a.knownArtifactCount/
a.totalArtifactCount:0,{element:$("#coverage_donut")[0]});v&&d.fadeIn();Insight.util.enableTooltip($("[data-tooltip]",summary))}}).error(b)}var e,f;$(document).ready(function(){e=Hogan.compile($("#summaryPageTemplate").html());f=Hogan.compile($("#errorTemplate").html());$.extend(!0,window,{Insight:{templates:{error:f},updateSummary:a}});$("button[data-containerid]").click(function(a){if(!$(this).hasClass("active")){a=$(this).data("containerid");var c;$("[data-container]").css("display","none");$("#"+
a).css("display","");InsightDatatable.destroyActiveTable();switch(a){case "securitycontainer":c=InsightDatatable.createSecurityTable({headerRowHeight:30});c.addLoadListener(function(){InsightDatatable.addSecurityTableEditor(c)});break;case "licensecontainer":c=InsightDatatable.createLicenseTable({headerRowHeight:30});break;case "componentcontainer":InsightDatatable.createComponentTable({headerRowHeight:30})}}});Insight.util.enableTooltip($("[data-tooltip]"));var c=$('[data-action\x3d"reevaluatePolicy"]');
Brain.hasFeature("reevaluate-policy")?c.click(function(){c.find("i").attr("class","icon-white icon-time");$.ajax({type:Brain.getCurrentReportReevaluateUrl?"POST":"GET",url:Brain.getCurrentReportReevaluateUrl?Brain.getCurrentReportReevaluateUrl():"../reevaluatePolicy",headers:Brain.getCsrfHeaders?Brain.getCsrfHeaders():{}}).success(function(){c.find("i").attr("class","icon-white icon-refresh");location.reload()}).error(function(){$(".btn-group:eq(1)").after('\x3cdiv class\x3d"alert alert-error" style\x3d"margin:5px 0"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3eThere has been an error reevaluating policy. Try running the report again.\x3c/div\x3e')})}):
c.hide();$.browser.msie&&9>$.browser.version&&$(".btn-group:eq(1)").after('\x3cdiv class\x3d"alert alert-error" style\x3d"margin:5px 0"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3eYou are using older version of Internet Explorer (IE). You may notice degraded performance and/or functionality. To address this, download and install the latest version of IE, or other modern browser (e.g. Chrome, Firefox)\x3c/div\x3e');Insight.updateSummary()})})();
(function(){function c(a){var c=$(window).innerHeight(),b=$(a).offset().top;a=$("#"+a.attr("id")+"Pager").height();return Math.max(150,c-b-e-a)}function g(a){$("#"+a+"container .message").remove()}function h(a,c){var b=$("#"+a+"container"),e=$("#"+a+"Table").position(),h;null!==e&&(g(a),b.append('\x3cdiv class\x3d"message" style\x3d"top:'+(e.top+70)+'px"\x3e'+c+"\x3c/div\x3e"),h=$(".message",b),h.css("left",e.left+b.outerWidth()/2-h.outerWidth()/2+"px"))}function a(a,d,b){function e(d){if(!m.destroyed){m.table=
new Slick.Grid("#"+a+"Table",m.dataView,b.columns,l);if(b.handlers)for(var k=0;k<b.handlers.length;k++)m.table[b.handlers[k].event].subscribe(b.handlers[k].handler);b.selectable&&(m.table.setSelectionModel(new Slick.RowSelectionModel),m.dataView.syncGridSelection(m.table,!0));r.init(m.table);p.css("height",b.height||c($("#"+a+"Table"))+"px");m.processData(d);m.initialize()}}function g(a){return function(b,c,d){b=p.empty().append(Insight.templates.error.render({message:d}));$("button",b).click(a)}}
function h(a){p.empty().append('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e');a.get().done(function(b){null!=b?e(b):g(function(){h(a)})()}).fail(g(function(){h(a)}))}var r=new Slick.Data.GroupItemMetadataProvider,l=$.extend({editable:!1,enableAddRow:!1,enableCellNavigation:b.enableCellNavigation,enableColumnReorder:!1,enableTextSelectionOnCells:!0,fullWidthRows:!0,forceFitColumns:!0,rowHeight:31,
explicitInitialization:!0,showHeaderRow:!b.disableFilter,multiSelect:!1,autoHeight:b.autoHeight,multiColumnSort:b.multiColumnSort},b.config||{}),m=this,p=$("#"+a+"Table");this.options=b;this.id=a;this.dataView=new Slick.Data.DataView({groupItemMetadataProvider:r});this.filter=new Slick.Filter;$.isArray(d)?e({aaData:d}):"string"===typeof d?h({get:function(){return $.getJSON(d)}}):"object"===typeof d?h(d):console.log("Unable to load: "+d)}var e=null;$.browser&&($.browser.mozilla&&4>parseFloat($.browser.version)?
e=9:$.browser.msie&&9>parseFloat($.browser.version)&&(e=15));null===e&&(e=14);a.prototype.updateHeight=function(){var a=$("#"+this.id+"Table"),d=this;a.css("height",c(a)+"px");window.clearTimeout(this.resizeTimeout);this.resizeTimeout=window.setTimeout(function(){d.table.resizeCanvas()},50)};a.prototype.destroy=function(){this.destroyed=!0;g(this.id);$(window).unbind("resize");this.table&&(this.table.pager&&(this.table.pager.destroy(),this.table.pager=null),this.table.columnsResizedFn&&(this.table.onColumnsResized.unsubscribe(this.table.columnsResizedFn),
this.table.columnsResizedFn=null),this.table.destroy())};a.prototype.initialize=function(){var a=this;this.initialized||(this.initialized=!0,this.options.defaultSort&&($.isArray(this.options.defaultSort)?this.table.setSortColumns(this.options.defaultSort):this.table.setSortColumns([this.options.defaultSort])),$.isArray(this.options.plugins)&&$.each(this.options.plugins,function(c,b){a.table.registerPlugin(b)}),this.table.registerPlugin(new Slick.Sort),this.table.init(),this.options.disableFilter||
this.table.registerPlugin(this.filter),this.table.registerPlugin(new Slick.Tipsy),$(window).resize(this.options.resizeFn||function(){Insight.util.isNullOrUndefined(a.options.height)&&a.updateHeight()}),this.listeners&&($.each(this.listeners,function(a,b){setTimeout(b,0)}),this.listeners=null))};a.prototype.processData=function(a){var c=this;this.initialize();Insight.util.isNotNullOrUndefined(a)&&(this.options.dataProcessor&&(a.aaData=this.options.dataProcessor.call(null,a.aaData)),this.dataView.beginUpdate(),
this.dataView.setItems(a.aaData),this.options.disableFilter||(this.options.externalFilters?this.dataView.setFilter(function(a,e){var f=!0;$.each(c.options.externalFilters,function(c,d){d(a,e)||(f=!1);return f});return f&&c.filter.getFilter()(a,e)}):this.dataView.setFilter(this.filter.getFilter())),this.options.groupInfo&&this.dataView.groupBy(this.options.groupInfo.field,this.options.groupInfo.groupHeaderFn,this.options.groupInfo.groupingComparer),this.dataView.endUpdate(),this.options.groupInfo&&
"collapsed"===this.options.groupInfo.initialState&&(this.dataView.beginUpdate(),$.each(this.dataView.getGroups(),function(a,e){c.dataView.collapseGroup(e.value)}),this.dataView.endUpdate()));g(this.id);(Insight.util.isNullOrUndefined(a)||0===a.aaData.length)&&h(this.id,this.options.emptyText||"None");this.options.disablePager||(this.table.pager=new Slick.Controls.Pager(this.dataView,this.table,$("#"+this.id+"TablePager")))};a.prototype.addMessage=function(a,c,b){var e=this,g=$('\x3cdiv class\x3d"alert"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3e\x3c/div\x3e');
g.addClass(c);g.append("\x3cspan\x3e\x3c/span\x3e").text(a);g.bind("closed",function(){e.updateHeight()});$("#"+e.id+"container").prepend(g);e.updateHeight();b&&setTimeout(function(){g.fadeOut("fast",function(){g.remove();e.updateHeight()})},1E3*b);return g};a.prototype.addLoadListener=function(a){this.table?setTimeout(a,0):(this.listeners=this.listeners||[],this.listeners.push(a))};a.prototype.addSuccess=function(a,c){this.addMessage(a,"alert-success",c)};a.prototype.addError=function(a,c){this.addMessage(a,
"alert-error",c)};$.extend(!0,window,{Insight:{Table:a}})})();
(function(){function c(a){Insight.util.isNotNullOrUndefined(m)?a.apply(null,[m]):$.getJSON("licensethreats.json").success(function(b){m=b.aaData;a.apply(null,[m])}).error(function(b,c,d){a.apply(null,[null,"Loading license categorization: "+Insight.util.getErrorMessage(b)])})}function g(){for(var a=null,b=0;b<arguments.length;b++)for(var c=arguments[b],d=0;d<c.length;d++){var e=m[c[d]];Insight.util.isNotNullOrUndefined(e)&&(a=Math.max(e,a))}return a}function h(b){var c=a(b.effectiveLicenseThreat);
return"undefined"!==typeof c?c:Insight.util.isNotNullOrUndefined(b.overriddenLicenses)?g(b.overriddenLicenses):b.effectiveLicenseThreat}function a(a){if(0<=B.indexOf(a))return e(a)}function e(a){switch(a){case "COPYLEFT":return 10;case "NON-STANDARD":return 7;case "NOT-PROVIDED":return 6;case "WEAKCOPYLEFT":return 3;case "LIBERAL":return 0;default:return null}}function f(a,b){var c=[];b=b||[];for(var d=0;d<b.length;d++)"Not Provided"!==b[d]&&-1!==a.indexOf(b[d])||c.push(b[d]);return c}function d(a){return Insight.util.isNotNullOrUndefined(a)&&
0<a.length?a.join(", "):""}function b(a,b){var c=h(a),d=h(b),c=Insight.util.isNullOrUndefined(c)?-1:c,d=Insight.util.isNullOrUndefined(d)?-1:d;return c<d?-1:c>d?1:0}function k(b){var c=a(b);"undefined"!==typeof c&&(b=c);return Insight.util.isNullOrUndefined(b)?"unspecifiedScore":7<b?"criticalScore":3<b?"severeScore":0<b?"moderateScore":"ignoredScore"}function x(a,b,c){if(Insight.util.isNotNullOrUndefined(a))return d(a);a=d(b);b=d(f(b,c));return a+(0<b.length?", "+b:"")}function v(a,b,c,e,n){if(Insight.util.isNotNullOrUndefined(n.overriddenLicenses))return'\x3cdiv class\x3d"'+
k(g(n.overriddenLicenses))+'"\x3e\x3ci\x3e'+d(n.overriddenLicenses)+"\x3c/i\x3e\x3c/div\x3e";a=d(n.declaredLicenses);b=d(f(n.declaredLicenses,n.observedLicenses));return'\x3cdiv class\x3d"'+k(h(n))+'"\x3e \x3cb\x3e'+a+"\x3c/b\x3e"+(0<b.length?", "+b:"")+"\x3c/div\x3e"}function r(){return y||q||u}function l(a,b){$("#"+a+"container .message").remove();$(window).unbind("resize");b.pager&&(b.pager.destroy(),b.pager=null);b.columnsResizedFn&&(b.onColumnsResized.unsubscribe(b.columnsResizedFn),b.columnsResizedFn=
null);b.destroy()}var m,p={id:"coordinates",name:"Component",field:"coordinates",sortable:!0,width:295,toolTipGravity:"se",formatter:function(a,b,c,d,e){return(e.componentIdentifier?'\x3cimg src\x3d"public/coord-component.png" title\x3d"'+e.componentIdentifier.format+'"/\x3e ':'\x3cimg src\x3d"public/coord-unknown.png" alt\x3d"Unknown"/\x3e ')+Insight.util.encodeHtml($.map(e.displayName.parts,function(a){return a.value}).join(""))}},w=function(a){a=a||[];$.each(a,function(a,b){Insight.util.isNullOrUndefined(b.componentIdentifier)&&
Insight.util.isNotNullOrUndefined(b.groupId)&&(b.componentIdentifier={format:"maven",coordinates:{groupId:b.groupId,artifactId:b.artifactId,version:b.version}});if(Insight.util.isNullOrUndefined(b.displayName))if(b.displayName={},Insight.util.isNotNullOrUndefined(b.componentIdentifier)){var c=b.componentIdentifier.coordinates;switch(b.componentIdentifier.format){case "maven":b.displayName.parts=[{field:"Group",value:c.groupId},{value:" : "},{field:"Artifact",value:c.artifactId},{value:" : "},{field:"Version",
value:c.version}];break;case "nuget":b.displayName.parts=[{field:"ID",value:c.packageId},{value:" "},{field:"Version",value:c.version}];break;default:b.displayName.parts=[];for(var d in c)c.hasOwnProperty(d)&&(b.displayName.parts.push({field:d,value:c[d]}),b.displayName.parts.push({value:" : "}));b.displayName.parts.pop()}}else if(b.filenames&&0<b.filenames.length)for(b.displayName.parts=[],c=0;c<b.filenames.length;c++)b.displayName.parts.push({field:"Filename",value:b.filenames[c]}),c<b.filenames.length-
1&&b.displayName.parts.push({value:", "});else b.displayName.parts=[{value:"(Anonymized Path) SHA1: "},{field:"Hash",value:b.hash}];b.coordinates=$.map(b.displayName.parts,function(a){return a.value}).join("")})};c($.noop);var B="UNKCAT LIBERAL WEAKCOPYLEFT NOT-PROVIDED NON-STANDARD COPYLEFT".split(" "),y=null,q=null,u=null,t=null,z=null;$.extend(!0,window,{InsightDatatable:{createAuditTable:function(a){z=new Insight.Table("audit",a,{resizeFn:$.noop,selectable:!0,disablePager:!0,disableFilter:!0,
height:250,columns:[{id:"date",name:"Date",field:"date",formatter:function(a,b,c,d,e){return dateFormat(c,"mmm d yyyy, h:MM:ss tt")},sortable:!0,width:30},{id:"user",name:"User",field:"user",toolTipGravity:"n",toolTipFn:function(a){return Insight.util.isNullOrUndefined(a.where)?Insight.util.encodeHtml("Edited report from "+a.ip):Insight.util.encodeHtml("Edited report in build '"+a.where+"' from "+a.ip)},sortable:!0,width:20},{id:"action",name:"Action",field:"action",sortable:!0,width:20},{id:"detail",
name:"Detail",field:"detail",sortable:!0,width:40},{id:"comment",name:"Comment",field:"comment",toolTipGravity:"n",toolTipFn:function(a){if(a.comment)return Insight.util.encodeHtml(a.comment)},sortable:!0,width:80}],defaultSort:{columnId:"date",sortAsc:!1},dataProcessor:function(a){$.each(a,function(a,b){var c=b.status,e="",g;b.id=a;b.date=new Date(b.time);switch(b.status){case "Open":c="Reopened";break;case "Not Applicable":c="Ignored";break;case "Overridden":c="Overrode"}b.action=c;Insight.util.isNullOrUndefined(b.user)&&
(b.user="anonymous");switch(b.filename){case "licenses.json":e="License ";c=b.overriddenLicenses;e=Insight.util.isNotNullOrUndefined(c)?e+("as "+d(c)):e+"Analysis";break;case "security.json":e="Vulnerability ",c=b.source,g=b.reference,Insight.util.isNotNullOrUndefined(c)&&0!==g.toUpperCase().indexOf(c.toUpperCase())&&(e+=c+"-"),e+=g}b.detail=e});return a}});$("#"+z.id+"Table").click(function(a){a.stopPropagation()})},createComponentTable:function(a){function b(a){a.preventDefault();$(this).parents("ul").children("li").removeClass("active");
$(this).parents("li").addClass("active");a=$("#policy-match-state-filter li.active").text();var c=$("#policy-violation-filter li.active").text(),d={};"All"!==a&&("Proprietary"===a?d.proprietary=!0:"Error"===a?d.scanError=!0:d.matchState=a.toLowerCase());"Summary"===c?d.summary=!0:"Waived"===c?d.waived=!0:"All"===c?d.all=!0:"Legacy"===c&&(d.grandfathered=!0);u.addLoadListener(function(){u.table.getData().setFilterArgs(d);u.table.getData().refresh()})}var c=["unknown","similar","exact"],d=new Slick.ColumnGrouping({columnId:"policyName",
style:"scoreCol"}),e=d.getCellStyler(),g=d.getCellRenderer(),f=HealthCheck.getAge(earliestReleaseDate,currentDate),f=[{id:"policyName",name:"Policy Threat",shortName:"Name",field:"policyName",sortable:!0,width:200,styleFn:function(a,b,c,d,f){return"nopad "+e(a,b,c,d,f)},sortFn:function(a,b){var c=a.policyThreatLevel,d=b.policyThreatLevel,e=a.policyName,f=b.policyName;return c<d?-1:c>d||e<f?1:e>f?-1:0},formatter:function(a,b,c,d,e){var f;switch(e.policyThreatLevel){case 0:f=" noScore";break;case 1:f=
" ignoredScore";break;case 2:case 3:f=" moderateScore";break;case 4:case 5:case 6:case 7:f=" severeScore";break;case 8:case 9:case 10:f=" criticalScore"}return'\x3cdiv class\x3d"'+f+'"\x3e'+(0<g(a,b,c,d,e).length?Insight.util.encodeHtml(c):"")+"\x3c/div\x3e"}},$.extend({},p,{styleFn:function(a,b,c,d,e){return e.modified||"Manual"===e.identificationSource?"modified":""},toolTipFn:function(a){var b="";a.modified&&(b+="\x3cli\x3ebeen manually edited.  See the audit log for details.\x3c/li\x3e");"Manual"===
a.identificationSource&&(b+="\x3cli\x3ebeen claimed from an unknown or similar component.  View the Component Information Panel (CIP) for more details.\x3c/li\x3e");a.waived&&(b+="\x3cli\x3ebeen waived.\x3c/li\x3e");a.grandfathered&&(b+="\x3cli\x3ebeen marked as a legacy violation.\x3c/li\x3e");if(0<b.length)return"This record has...\x3cbr\x3e\x3cbr\x3e\x3cul\x3e"+b+"\x3c/ul\x3e"},formatter:function(a,b,c,d,e){var f="",f=e.waived?'\x3cimg src\x3d"flag_white.png" style\x3d"margin-right:4px" title\x3d"Violation has been waived"\x3e':
'\x3cspan style\x3d"padding-right:20px"\x3e\x3c/span\x3e';e.grandfathered?f+='\x3cimg src\x3d"history.png" style\x3d"margin-right:4px" title\x3d"Legacy Violation"\x3e':void 0!==e.grandfathered&&(f+='\x3cspan style\x3d"padding-right:20px"\x3e\x3c/span\x3e');return f+p.formatter(a,b,c,d,e)}}),{id:"filename",name:"Filename",field:"filename",width:110,sortable:!0,filterable:!0},{id:"versions",name:"Popularity",field:"relativePopularity",sortable:!0,filterable:!1,width:45,sortFn:function(a,b){return a.matchState===
c[0]?b.matchState===c[0]?0:-1:b.matchState===c[0]?1:"Manual"===a.identificationSource?a.identificationSource===b.identificationSource?0:-1:"Manual"===b.identificationSource?1:a.relativePopularity<b.relativePopularity?-1:a.relativePopularity>b.relativePopularity?1:0},formatter:function(a,b,d,e,f){if(f.matchState===c[0]||"Manual"===f.identificationSource)return"";var g;d=Math.round(100*d);79<d?g="popularity-100":59<d?g="popularity-80":39<d?g="popularity-60":19<d?g="popularity-40":0<=d&&(g="popularity-20");
return g?'\x3cdiv class\x3d"'+g+'"\x3e\x3c/div\x3e':""}},{id:"age",name:"Age",field:"age",sortable:!0,filterable:!1,width:40,sortFn:function(a,b){var c=a.age,d=b.age;if(void 0!==c||void 0!==d){if(void 0===c)return-1;if(void 0===d)return 1;if(c<d)return-1;if(c>d)return 1}return 0},formatter:function(a,b,c,d,e){return void 0===c||null===c?"":359<c?(c/365).toFixed(1)+" y":30<c?Math.floor(c/30)+" m":Math.floor(c)+" d"}},{id:"releasehistory",name:"Release History",field:"componentIdentifier",sortable:!1,
filterable:!1,resizable:!1,width:211,header:'\x3cdiv class\x3d"release-header"\x3e\x3ci class\x3d"icon-question-sign" title\x3d"\x3cdiv style\x3d\'background:url(release-tooltip.png);width:241px;height:78px\'\x3e\x3c/div\x3e"\x3e\x3c/i\x3e\x3cspan\x3e'+f+"\x3c/span\x3e\x3c/div\x3e",formatter:function(a,b,c,d,e){if(null===c||"Manual"===e.identificationSource)return"No Popularity Data";a={componentIdentifier:JSON.stringify(e.componentIdentifier),groupId:e.groupId,artifactId:e.artifactId,version:e.version};
var f="";$.each(a,function(a,b){f+="\x26"+encodeURIComponent(a)+"\x3d"+encodeURIComponent(b)});return'\x3cimg src\x3d"../brain/rest/report/'+applicationId+"/"+reportId+"/releaseGraph?"+f.substring(1)+'" alt\x3d"Release Popularity"\x3e'}}],d=[d,new Insight.InformationPanel({byHash:!0})];hideFilename&&f.splice(2,1);Brain.hasFeature("release-graph")||(f[1].width+=f.pop().width);u=new Insight.Table("component",{get:function(){var a=$.Deferred(),b=[$.getJSON("policythreats.json"),$.getJSON("bom.json")];
window.parent&&-1!==window.parent.location.search.indexOf("unknownjs\x3dtrue")&&b.push($.getJSON("unknownjs.json"));$.when.apply($,b).done(function(b,c,d){function e(a){return a.hash||"error: "+(a.pathnames||[]).join("\t")}if(null===b[0]||null===c[0])a.reject([]);else{var f={},g={},k={},h={},n=[];$.each(c[0].aaData,function(a,b){var c=e(b);f[c]=b;g[c]=!1;k[c]=!1;h[c]=!1});d&&$.each(d[0].aaData,function(a,b){var c=e(b);f[c]=b;g[c]=!1;k[c]=!1;h[c]=!1});3<=b[0].version?($("#policy-violation-filter").show(),
$("#policy-violations-grandfathered").show(),$.each(b[0].aaData,function(a,b){var c=e(b);if(!b.hash||"null"===b.hash)return!0;b.allViolations.sort(function(a,b){var c=(b.grandfathered|0)-(a.grandfathered|0),d=(b.waived|0)-(a.waived|0);return 0!==c?c:0!==d?d:b.policyThreatLevel-a.policyThreatLevel});var d=!0;$.each(b.allViolations,function(a,e){var A=!e.waived&&!e.grandfathered;g[c]=A;k[c]=e.waived;h[c]=e.grandfathered;n.push($.extend({policyThreatLevel:e.policyThreatLevel,policyName:e.policyName,
groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,componentIdentifier:b.componentIdentifier,summary:A&&d,waived:e.waived,grandfathered:e.grandfathered,all:!0},f[c]));A&&(d=!1)})})):b[0].version?($("#policy-violation-filter").show(),$.each(b[0].aaData,function(a,b){var c=e(b);if(!b.hash||"null"===b.hash)return!0;b.activeViolations.length&&(g[c]=!0,b.activeViolations.sort(function(a,b){return b.policyThreatLevel-a.policyThreatLevel}),$.each(b.activeViolations,function(a,d){n.push($.extend({policyThreatLevel:d.policyThreatLevel,
policyName:d.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,componentIdentifier:b.componentIdentifier,summary:0===a,waived:!1,all:!0},f[c]))}));b.waivedViolations.length&&(k[c]=!0,$.each(b.waivedViolations,function(a,d){n.push($.extend({policyThreatLevel:d.policyThreatLevel,policyName:d.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,componentIdentifier:b.componentIdentifier,summary:!1,waived:!0,all:!0},f[c]))}))})):$.each(b[0].aaData,
function(a,b){var c=e(b);if(!b.hash||"null"===b.hash)return!0;g[c]=!0;n.push($.extend({policyThreatLevel:b.policyThreatLevel,policyName:b.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,summary:!0,waived:!1,all:!0},f[c]))});$.each(g,function(a,b){b||n.push($.extend(!0,{policyThreatLevel:0,policyName:"None",summary:!0,waived:!1,grandfathered:!1,all:!1===k[a]&&!1===h[a]},f[a]))});a.resolve({aaData:n})}}).fail(function(b){a.reject(b)});return a}},{columns:f,config:a,
multiColumnSort:!0,selectable:!0,plugins:d,defaultSort:[{columnId:"policyName",sortAsc:!1},{columnId:"coordinates",sortAsc:!0}],externalFilters:[function(a,b){var c=!0;b&&$.each(b,function(b,d){return c=a[b]===d});return c}],dataProcessor:function(a){a=a||[];$.each(a,function(a,b){b.id=a;b.createTime&&(b.age=Math.floor(((new Date).getTime()-b.createTime)/864E5));b.filename=(b.filenames||[]).slice().sort().pop()||""});w(a);return a}});$("#policy-match-state-filter").unbind("click");$("#policy-match-state-filter li a").click(b);
$("#policy-violation-filter li a").click(b);$("#policy-match-state-filter li.active a").trigger("click");u.addLoadListener(function(){$(".release-header \x3e .icon-question-sign").tipsy({gravity:"e",html:!0,title:"title",opacity:1})})},createLicenseTable:function(a){var c=[{id:"_formattedEffectiveLicenseThreat",name:"License Threat",shortName:"Licenses",field:"_formattedEffectiveLicenseThreat",sortable:!0,width:200,styleFn:function(){return"nopad"},sortFn:b,formatter:v,toolTipGravity:"w",toolTipFn:function(a){var b=
d(a.declaredLicenses),c=d(a.observedLicenses),e=d(a.overriddenLicenses),b="\x3ctable class\x3d'license-tooltip'\x3e"+("\x3ctr\x3e\x3ctd\x3eDeclared:\x3c/td\x3e\x3ctd\x3e"+b+"\x3c/td\x3e\x3c/tr\x3e")+("\x3ctr\x3e\x3ctd\x3eObserved:\x3c/td\x3e\x3ctd\x3e"+c+"\x3c/td\x3e\x3c/tr\x3e"),b=b+("\x3ctr\x3e\x3ctd\x3eOverridden:\x3c/td\x3e\x3ctd\x3e"+("Overridden"===a.status?e:"-")+"\x3c/td\x3e\x3c/tr\x3e"),b=b+("\x3ctr\x3e\x3ctd\x3eSelected:\x3c/td\x3e\x3ctd\x3e"+("Selected"===a.status?e:"-")+"\x3c/td\x3e\x3c/tr\x3e");
return b+="\x3c/table\x3e"}},p,{id:"status",name:"Status",field:"status",sortable:!0,width:150}],e=[new Insight.InformationPanel];q=new Insight.Table("license","licenses.json",{columns:c,config:a,plugins:e,defaultSort:{columnId:"_formattedEffectiveLicenseThreat",sortAsc:!1},dataProcessor:function(a){var b;for(b=0;b<a.length;b++)a[b].id=b,a[b].status=Insight.util.isNullOrUndefined(a[b].status)?"Open":a[b].status;w(a);return a}});q.addLoadListener(function(){q.table.setSelectionModel(new Slick.RowSelectionModel);
q.table.getData().syncGridSelection(q.table,!0);q.table.getData().onRowsChanged.subscribe(function(a,b){var c,d;b=b.rows;for(d=0;d<b.length;d++)c=q.table.getData().getItem(b[d]),c._formattedEffectiveLicenseThreat=x(c.overriddenLicenses,c.declaredLicenses,c.observedLicenses)})});return q},createSecurityTable:function(a){var b=new Slick.ColumnGrouping({columnId:"_score",style:"scoreCol"}),c=b.getCellStyler(),d=b.getCellRenderer(),e=[{id:"_score",name:"Threat Level",shortName:"Level",field:"_score",
sortable:!0,width:120,toolTip:"'Threat Level' highlights the CVSS (Common Vulnerability Scoring System, version 2) base score for each listed vulnerability.",styleFn:function(a,b,d,e,f){return"nopad "+c(a,b,d,e,f)},sortFn:function(a,b){var c=a._score,d=b._score;return isNaN(c)||isNaN(d)?d<c?-1:d>c?1:0:parseInt(c,10)-parseInt(d,10)},formatter:function(a,b,c,e,f){return'\x3cdiv class\x3d"'+(7<=c?" criticalScore":4<=c?" severeScore":" moderateScore")+'"\x3e'+(d(a,b,c,e,f)||"\x26nbsp;")+"\x3c/div\x3e"}},
{id:"problemCode",name:"Problem Code",shortName:"Code",field:"_reference",sortable:!0,width:105,formatter:function(a,b,c,d,e){a=e._reference;return Insight.util.isNullOrUndefined(a)?"":Insight.util.showVulnerabilityDetail()?'\x3ca href\x3d"javascript:void(0);" class\x3d"vulnerability-info-link"\x3e'+a+"\x3c/a\x3e":'\x3ca href\x3d"'+e.url+'" target\x3d"_blank"\x3e'+a+"\x3c/a\x3e"}},p,{id:"filename",name:"Filename",field:"filename",width:150,sortable:!0,filterable:!0},{id:"status",name:"Status",field:"status",
sortable:!0,width:150}],b=[b,new Insight.InformationPanel];hideFilename&&e.splice(3,1);var f=[];Insight.util.showVulnerabilityDetail()&&f.push({event:"onClick",handler:function(a,b){if($(a.target).hasClass("vulnerability-info-link")){a.stopPropagation();var c=b.grid.getDataItem(b.row);Insight.util.showSvModal(c.source,c.reference,c.componentIdentifier,c.hash);return!1}return!0}});return y=new Insight.Table("security",{get:function(){return $.when($.get("security.json"),$.get("bom.json")).pipe(function(a,
b){var c={};b[0].aaData.forEach(function(a){c[a.hash]=a.filenames});a[0].aaData.forEach(function(a){a.filename=(c[a.hash]||[]).slice().sort().pop()||""});return a[0]})}},{columns:e,config:a,defaultSort:{columnId:"_score",sortAsc:!1},dataProcessor:function(a){for(var b=0;b<a.length;b++)a[b].id=b,a[b]._score=Insight.util.isNullOrUndefined(a[b].score)?"Unscored":String(Math.floor(a[b].score)),a[b]._reference=Insight.util.toSvReference(a[b].source,a[b].reference),a[b].status=Insight.util.isNullOrUndefined(a[b].status)?
"Open":a[b].status;w(a);return a},plugins:b,handlers:f})},createSimilarityTable:function(a){var c=[{id:"_formattedEffectiveLicenseThreat",name:"License Threat",field:"_formattedEffectiveLicenseThreat",sortable:!0,width:65,sortFn:b,formatter:v},{id:"securityCounters",name:"Security",field:"securityCounters",sortable:!0,width:50,sortFn:function(a,b){var c=a.securityCounters.Critical-b.securityCounters.Critical;0===c&&(c=a.securityCounters.Severe-b.securityCounters.Severe);0===c&&(c=a.securityCounters.Moderate-
b.securityCounters.Moderate);return c},formatter:function(a,b,c,d,e){a=e.securityCounters;var f="",g,k,h=0;b=d.width-10;c=function(a,b){var c;for(c=0;c<a&&!(h>=k);c++)f+='\x3cspan class\x3d"arrow '+b+'_arrow" style\x3d"left:'+h++*g+'px"\x3e\x3c/span\x3e'};if(a){d=a.Critical+a.Severe+a.Moderate;for(g=0;-9<g&&(d-1)*(10+g)+10>b;g--);k=(b-10)/(10+g)+1;a.Critical&&c(a.Critical,"red");a.Severe&&c(a.Severe,"orange");a.Moderate&&c(a.Moderate,"yellow")}return'\x3cdiv style\x3d"white-space:nowrap;width:'+(0<
h?10+(h-1)*(10+g):0)+'px"\x3e'+f+"\x3c/div\x3e"}},$.extend({},p,{width:210})];t=new Insight.Table("similarity",a,{selectable:!0,disablePager:!0,disableFilter:!0,height:250,columns:c,dataProcessor:function(a){a||(a=[]);$.each(a,function(a,b){b.id=a;b._formattedEffectiveLicenseThreat=x(b.overriddenLicenses,b.declaredLicenses,b.observedLicenses)});w(a);return a}});t.table.render();t.table.columnsResizedFn=function(){var a;for(a=0;a<t.getDataLength();a++)t.updateCell(a,t.getColumnIndex("securityCounters"))};
t.table.onColumnsResized.subscribe(t.table.columnsResizedFn);$("#similarityTable").click(function(a){a.stopPropagation()})},destroyActiveTable:function(){var a=r();a&&a.destroy();u=q=y=null},getActiveTable:r,loadLicenseThreats:c,getLicenseThreatLevelFromArray:g,getLicenseThreatClass:k,removeAuditTable:function(){Insight.util.isNotNullOrUndefined(z)&&(l("audit",z),z=null)},removeComponentTable:function(){Insight.util.isNotNullOrUndefined(u)&&(l("component",u),$("#componentcontainer ul.nav a").unbind("click"),
u=null)},removeLicenseTable:function(){Insight.util.isNotNullOrUndefined(q)&&(l("license",q),q=null)},removeSecurityTable:function(){Insight.util.isNotNullOrUndefined(y)&&(l("security",y),y=null)},removeSimilarityTable:function(){Insight.util.isNotNullOrUndefined(t)&&(l("similarity",t),t=null)}}})})();
(function(c){function g(a,d,e,g,r,l){var m=[],p=[],w=Brain.getCsrfHeaders?Brain.getCsrfHeaders():{};c.each(d,function(a,b){var d=c.extend({},b);c.each(e,function(a,b){d[a]=b});d.modified=!0;m.push(d)});c.merge(p,g);c.each(e,function(a,b){p.push(a)});c.ajax({type:"POST",url:"../augmentData/bom.json",data:h(m,c.merge(["modified"],f)),headers:w});c.ajax({type:"POST",url:"../augmentData/"+r,data:h(m,p),headers:w}).success(function(){a.beginUpdate();c.each(m,function(c,d){a.updateItem(d.id,d)});a.endUpdate();
Insight.updateSummary();l()}).error(function(a,b,c){c=Insight.util.getErrorMessage(a);l(c)})}function h(a,c){for(var d=[],e=0;e<a.length;e++){var f=a[e],g={componentIdentifier:f.componentIdentifier};Insight.util.isNotNullOrUndefined(f.componentIdentifier)&&"maven"===f.componentIdentifier.format&&(g.groupId=f.componentIdentifier.coordinates.groupId,g.artifactId=f.componentIdentifier.coordinates.artifactId,g.version=f.componentIdentifier.coordinates.version);for(var h=0;h<c.length;h++)g[c[h]]=f[c[h]];
d.push(g)}return JSON.stringify(d)}function a(a){a=c.extend({dataView:null,items:[],mask:{},callback:c.noop},a);c.isArray(a.items)||(a.items=[a.items]);g(a.dataView,a.items,a.mask,e,"security.json",a.callback)}var e=["source","reference"],f=["hash"],d;c(document).ready(function(){d=Hogan.compile(c("#svEditorTemplate").html())});c.extend(!0,window,{InsightDatatable:{addSecurityTableEditor:function(a){a=a.table;var c=a.getColumns();a.setSelectionModel(new Slick.RowSelectionModel);a.getData().syncGridSelection(a,
!0);a.setColumns(c)},SecurityEditor:function(b){function e(){0===h.length?c("button[data-type\x3dupdate]",l).attr("disabled","disabled"):c("button[data-type\x3dupdate]",l).removeAttr("disabled")}function f(){h=[];c.each(b.grid.getSelectedRows(),function(a,c){h.push(b.grid.getData().getItem(c))});e()}function g(d){var e={};d.preventDefault();e.status=c("select",l).val();e.comment=c("textarea",l).val();a({mask:e,dataView:b.dataViews[0],items:h,callback:function(a){if(!Insight.util.isNotNullOrUndefined(a))for(var d=
1;d<b.dataViews.length;d++)b.dataViews[d].beginUpdate(),c.each(h,function(a,f){c.each(b.dataViews[d].getItems(),function(a,g){if(f.source===g.source&&f.reference===g.reference&&f.componentIdentifier.format===g.componentIdentifier.format){for(var h in f.componentIdentifier.coordinates)if(f.componentIdentifier.coordinates.hasOwnProperty(h)&&f.componentIdentifier.coordinates[h]!==g.componentIdentifier.coordinates[h])return;b.dataViews[d].updateItem(g.id,c.extend({},g,e));return!1}})}),b.dataViews[d].endUpdate();
Insight.util.isNotNullOrUndefined(b.callback)&&b.callback.apply(this,arguments)}})}b=c.extend({timestamp:(new Date).getTime()},b);var h=b.artifacts,l;b.grid&&b.grid.onSelectedRowsChanged.subscribe(f);c.extend(this,{destroy:function(){b.grid&&b.grid.onSelectedRowsChanged.unsubscribe(f)},show:function(a){l=a;c(l).html(d.render(b));c("button[data-type\x3dupdate]",l).click(g);c("button[data-type\x3dcancel]",l).click(function(a){a.preventDefault();b.cancelCallback&&b.cancelCallback.apply(this)});c("#svStatus"+
b.timestamp,l).css("width",b.width);e()}})},updateSecurity:a}})})(jQuery);