/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */

export const USER_SET_FIRST_NAME = 'USER_SET_FIRST_NAME';
export const USER_SET_LAST_NAME = 'USER_SET_LAST_NAME';
export const USER_SET_EMAIL = 'USER_SET_EMAIL';
export const USER_SET_USERNAME = 'USER_SET_USERNAME';
export const USER_SET_PASSWORD = 'USER_SET_PASSWORD';
export const USER_SET_MATCH_PASSWORD = 'USER_SET_MATCH_PASSWORD';

export const USER_RESET_FORM = 'USER_RESET_FORM';

export const CREATE_USER_LOAD_REQUESTED = 'CREATE_USER_LOAD_REQUESTED';
export const CREATE_USER_LOAD_FAILED = 'CREATE_USER_LOAD_FAILED';
export const CREATE_USER_LOAD_FULFILLED = 'CREATE_USER_LOAD_FULFILLED';

export const CREATE_USER_SAVE_REQUESTED = 'CREATE_USER_SAVE_REQUESTED';
export const CREATE_USER_SAVE_FULFILLED = 'CREATE_USER_SAVE_FULFILLED';
export const CREATE_USER_SAVE_FAILED = 'CREATE_USER_SAVE_FAILED';

export const USER_FORM_SUBMIT_MASK_TIMER_DONE = 'USER_FORM_SUBMIT_MASK_TIMER_DONE';
export const USER_FORM_DELETE_MASK_TIMER_DONE = 'USER_FORM_DELETE_MASK_TIMER_DONE';

export const EDIT_USER_LOAD_REQUESTED = 'EDIT_USER_LOAD_REQUESTED';
export const EDIT_USER_LOAD_FAILED = 'EDIT_USER_LOAD_FAILED';
export const EDIT_USER_LOAD_FULFILLED = 'EDIT_USER_LOAD_FULFILLED';

export const EDIT_USER_UPDATE_REQUESTED = 'EDIT_USER_UPDATE_REQUESTED';
export const EDIT_USER_UPDATE_FULFILLED = 'EDIT_USER_UPDATE_FULFILLED';
export const EDIT_USER_UPDATE_FAILED = 'EDIT_USER_UPDATE_FAILED';

export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED';
export const DELETE_USER_FULFILLED = 'DELETE_USER_FULFILLED';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const RESET_USER_PASSWORD_REQUESTED = 'RESET_USER_PASSWORD_REQUESTED';
export const RESET_USER_PASSWORD_FULFILLED = 'RESET_USER_PASSWORD_FULFILLED';
export const RESET_USER_PASSWORD_FAILED = 'RESET_USER_PASSWORD_FAILED';

export const RESET_USER_PASSWORD_RESET_VALUE = 'RESET_USER_PASSWORD_RESET_VALUE';

export const USER_LIST_LOAD_REQUESTED = 'USER_LIST_LOAD_REQUESTED';
export const USER_LIST_LOAD_FAILED = 'USER_LIST_LOAD_FAILED';
export const USER_LIST_LOAD_FULFILLED = 'USER_LIST_LOAD_FULFILLED';
