/*
 * Copyright (c) 2011-present Sonatype, Inc. All rights reserved.
 * Includes the third-party code listed at http://links.sonatype.com/products/clm/attributions.
 * "Sonatype" is a trademark of Sonatype, Inc.
 */
export const mockData = {
  dashboardMetadata: [
    {
      accessButtonText: 'View Success Metrics',
      category: 'enterprise',
      dashboardId: 'success-metrics',
      dashboardPath: 'dashboards/success_metrics::success_metrics',
      description: 'Review your applications and vulnerabilities in this foundational dashboard',
      features: ['Discover high-level trends', 'Explore team performance', 'See your risk ratio'],
      groupId: '',
      previewImage: 'SuccessMetricsIcon.svg',
      previewImageIcon: 'faThumbsUp',
      priorityOrder: 100,
      sinceIQVersion: '184',
      spotlight: true,
      spotlightColor: null,
      spotlightText: '',
      title: 'Success Metrics',
    },
    {
      accessButtonText: 'View Security Trends',
      category: 'enterprise',
      dashboardId: 'security_risk_trends',
      dashboardPath: 'dashboards/security_risk_trends::security_risk_trends',
      description: 'Explore your security trends and mitigate risk with this foundational dashboard',
      features: ['Follow violation activity', 'See fix rates', 'Find your MTTR'],
      groupId: 'security-risk',
      previewImage: 'sr_trends.svg',
      previewImageIcon: 'faShieldHalved',
      priorityOrder: 201,
      sinceIQVersion: '199',
      spotlight: false,
      spotlightColor: null,
      spotlightText: '',
      title: 'Security Risk Trends',
    },
    {
      accessButtonText: 'View Security Breakdown',
      category: 'enterprise',
      dashboardId: 'security_risk_breakdown',
      dashboardPath: 'dashboards/security_risk_breakdown::security_risk_breakdown',
      description: 'Dive deeper into your risk and violation data with this foundational dashboard',
      features: ['Explore top violation fixes', 'Prioritize risk mitigation', 'See violation status details'],
      groupId: 'security-risk',
      previewImage: 'sr_breakdown.svg',
      previewImageIcon: 'faShieldQuartered',
      priorityOrder: 250,
      sinceIQVersion: '188',
      spotlight: false,
      spotlightColor: null,
      spotlightText: '',
      title: 'Security Risk Breakdown',
    },
    {
      accessButtonText: 'View AI: Models',
      category: 'dataInsight',
      dashboardId: 'ai-models',
      dashboardPath: 'dashboards/ai_models::ai_models',
      description: 'Learn about the AI models in your code and the relationships between them.',
      features: ['Identify models in use', 'Inspect model ancestry', 'Explore model attributes'],
      groupId: 'ai-group',
      previewImage: 'AIModels.svg',
      previewImageIcon: 'faBrain',
      priorityOrder: 300,
      sinceIQVersion: '180',
      spotlight: false,
      title: 'AI: Models',
    },
    {
      accessButtonText: 'View AI: ML',
      category: 'dataInsight',
      dashboardId: 'ai-consumption',
      dashboardPath: 'dashboards/ai_consumption::ml_ai',
      description: 'Observe Machine Learning (ML) components and integrations in your software.',
      features: ['Sort by AI type', 'Monitor AI adoption', 'Compare apps vs. trends'],
      groupId: 'ai-group',
      previewImage: 'MLAI2.svg',
      previewImageIcon: 'faRobot',
      priorityOrder: 400,
      sinceIQVersion: '180',
      spotlight: false,
      spotlightColor: null,
      spotlightText: '',
      title: 'AI: Machine Learning',
    },
    {
      accessButtonText: 'View Rolling Recap',
      category: 'dataInsight',
      dashboardId: 'rolling-recap',
      dashboardPath: 'dashboards/rolling_recap::rolling_recap',
      description: 'Unlock trends by comparing your usage with the rest of the industry, over the past year.',
      features: ['Analyze performance', 'Compare scans', "View experts' ratings"],
      groupId: '',
      previewImage: 'RollingRecap2.svg',
      previewImageIcon: 'faCalendarCheck',
      priorityOrder: 500,
      sinceIQVersion: '',
      spotlight: false,
      spotlightColor: null,
      spotlightText: '',
      title: 'Rolling Recap Dashboard',
    },
    {
      accessButtonText: 'View Component EOL',
      category: 'dataInsight',
      dashboardId: 'component-eol',
      dashboardPath: 'dashboards/eol_components::eol_components',
      description: 'Learn the specifics about the components that have the status of End of Life (EOL)',
      features: ['Note ratings by version', 'Find apps using versions', 'Sort lists by type'],
      groupId: '',
      previewImage: 'ComponentEOL2.svg',
      previewImageIcon: 'faFlagCheckered',
      priorityOrder: 600,
      sinceIQVersion: '',
      spotlight: false,
      spotlightColor: 'purple',
      spotlightText: '',
      title: 'Component End-of-Life',
    },
    {
      accessButtonText: 'View Mythos Readiness',
      category: 'rapidResponse',
      dashboardId: 'mythos_report',
      dashboardPath: 'dashboards/mythos::mythos_readiness',
      description: 'Cross-reference your open source component inventory with Mythos vulnerability data in a single exportable view.',
      features: ['App component version & Golden fix version in one table', 'Filter by app/stage/component name & version', 'Sortable and downloadable table data'],
      groupId: '',
      previewImage: 'mythosReportIcon.svg',
      previewImageIcon: 'faCodeCompare',
      priorityOrder: 99,
      sinceIQVersion: '204',
      spotlight: true,
      spotlightColor: 'teal',
      spotlightText: '',
      title: 'Mythos Readiness',
    },
  ],
  dashboardGroupMetadata: [
    {
      description: 'test this',
      features: ['See violation *Trends*', 'Explore the *Breakdown*'],
      groupId: 'security-risk',
      previewImageIcon: 'faShieldHalved',
      sinceIQVersion: '',
      spotlight: false,
      spotlightColor: '',
      spotlightText: '',
      title: 'Security Risk',
    },
    {
      description: 'test that',
      features: ['Compare AI *Models*', 'Reveal *Machine Learning*'],
      groupId: 'ai-group',
      previewImageIcon: 'faBrain',
      sinceIQVersion: '',
      spotlight: false,
      spotlightColor: '',
      spotlightText: '',
      title: 'AI Group',
    },
  ],
};
