on: pull_request_review
name: Label approved pull requests
jobs:
  visualTestLabelWhenApproved:
    if: ${{  github.event.pull_request.base.ref == 'main' ||  github.event.pull_request.base.ref == 'master' }}
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - name: Apply Label when 2 approvals are met
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "2"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "Ready for Visual testing"
