/*
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2012 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2011-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2012-2013 Sonatype, Inc. All rights reserved.
 Includes the third-party code listed at http://links.sonatype.com/products/rhc/pro/attributions.
 "Sonatype" is a trademark of Sonatype, Inc.
 Copyright (c) 2013 Sonatype, Inc. All rights reserved. Includes the
 third-party code listed at
 http://links.sonatype.com/products/clm/attributions. "Sonatype" is a
 trademark of Sonatype, Inc.
*/
(function(){function a(a){var b=this;this.options=$.extend(!0,{},d,a);this.node=$("\x3cdiv id\x3d'informationPanel' class\x3d'informationPanel fullBorderedTable'\x3e\x3cdiv style\x3d'width:99%; padding-top: 5px; padding-left: 0.5%; padding-right: 0.5%;'\x3e\x3ca class\x3d'close'\x3e\x26times;\x3c/a\x3e\x3cul class\x3d'nav nav-tabs' style\x3d'margin-bottom:0px; !important'\x3e\x3c/ul\x3e\x3cdiv class\x3d'tab-content' style\x3d'overflow:hidden'\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");$(".close",this.node).click(function(){b.hide()});
this.plugins=[];Insight.InformationPanelPlugins.sort(function(a,c){return a.prototype.priority-c.prototype.priority});$.each(Insight.InformationPanelPlugins,function(a,c){var d=$('\x3cli data-info-plugin\x3d"'+a+'"\x3e\x3ca data-target\x3d"infoPanel'+a+'" data-toggle\x3d"tab"\x3e\x3c/a\x3e\x3c/li\x3e'),f=$('\x3cdiv class\x3d"tab-pane" id\x3d"infoPanel'+a+'"\x3e\x3c/div\x3e');$("ul.nav",b.node).append(d);$("div.tab-content",b.node).append(f);b.plugins.push(new c(f,b.options))});$('a[data-toggle\x3d"tab"]',
this.node).on("show",function(a){var c;null!==a.relatedTarget&&(c=$(a.relatedTarget.parentNode).data("info-plugin"),b.plugins[c].destroy(),$("#"+$(a.relatedTarget).data("target"),b.node).hide());null!==a.target&&(c=$(a.target.parentNode).data("info-plugin"),a=$("#"+$(a.target).data("target"),b.node),a.show(),b.plugins[c].create(a,b.node))})}function b(a){a=a||{};this.priority=a.priority||512}var d={byHash:!1};a.prototype.destroy=function(){this.cleanPlugins()};a.prototype.hide=function(){this.node.detach();
this.grid.removeCellCssStyles("popout");this.cleanPlugins()};a.prototype.init=function(a){var b=this;this.grid=a;a.onClick.subscribe(function(){b.gridClickedFn.apply(b,arguments)});a.getData().onRowCountChanged.subscribe(function(){b.hide()});a.getData().onRowsChanged.subscribe(function(){b.rowChangedFn.apply(b,arguments)});$.each(this.plugins,function(b,g){g.setGrid(a)})};a.prototype.cleanPlugins=function(){$.each(this.plugins,function(a,b){b.destroy()})};a.prototype.gridClickedFn=function(a,b){var p=
this;"INPUT"!==a.target.tagName&&0===$(a.target).children("input:first").length&&(Insight.util.isNotNullOrUndefined(p.timer)?(clearTimeout(p.timer),p.timer=null):p.timer=setTimeout(function(){p.timer=null;$.each(p.plugins,function(a,c){c.setItem(p.grid.getDataItem(b.row))});p.toggle(a,b)},250))};a.prototype.getItem=function(){return this.grid.getDataItem(this.currentRow)};a.prototype.updatePanel=function(){var a=this,b=null;$.each(this.plugins,function(b,g){var d=$("li[data-info-plugin\x3d"+b+"]",
a.node);g.isVisible()?(d.show(),$("a",d).text(g.getTitle())):(d.hide(),$("#infoPanel"+b,a.node).hide(),d.hasClass("active")&&(d.removeClass("active"),$("ul.nav \x3e li:first",a.node).addClass("active")))});0===$("li.active",a.node).length&&$("li",a.node).each(function(a,c){c=$(c);if("none"!==c.css("display"))return c.addClass("active"),!1});b=$("li.active",a.node).data("info-plugin");a.plugins[b].create();$("#infoPanel"+b,a.node).show()};a.prototype.rowChangedFn=function(a,b){var p=this.currentRow,
d=this;setTimeout(function(){var a=d.grid.getSelectedRows(),c=null;Insight.util.isNotNullOrUndefined(p)&&1===a.length?p!==a[0]?(d.hide(),Insight.util.isNotNullOrUndefined(this.currentItemId)&&d.show({row:a[0],cell:1},d.grid.getCanvasNode())):(d.position(p),c=d.getItem(),$.each(d.plugins,function(a,b){b.setItem(c)}),d.updatePanel()):d.hide()},10)};a.prototype.toggle=function(a,b){this.grid.removeCellCssStyles("popout");$(this.node).is(":hidden")||this.currentRow!==b.row?this.show(this.grid.getCellFromEvent(a),
$(a.currentTarget)):this.hide()};a.prototype.show=function(a,b){var d={},g=this.grid.getCellNode(a.row,a.cell),t=$(this.grid.getCanvasNode()).parent();t.offset();t.height();var f=this;Insight.util.isNullOrUndefined(g)&&(this.grid.scrollRowIntoView(a.row),g=this.grid.getCellNode(a.row,a.cell));this.node.css("top",g.offsetParent.offsetTop+g.offsetParent.clientHeight);this.node.addClass("shadowBottom");this.node.removeClass("shadowTop");f.node.appendTo(b);this.updatePanel();f.position(a.row);f.node.show();
this.currentRow=a.row;d[this.currentRow]={};$.each(f.grid.getColumns(),function(a,c){d[f.currentRow][c.id]="popout"});f.grid.setCellCssStyles("popout",d)};a.prototype.position=function(a){var b=this.node.offset().top,d=b+this.node.height(),g=$(this.grid.getCanvasNode()).parent(),t=g.offset().top,f=t+g.height(),m=this.grid.getCellNode(a,1);Insight.util.isNullOrUndefined(m)&&(this.grid.scrollRowIntoView(a),m=this.grid.getCellNode(a,1));(d>f||b<t)&&g.scrollTop(g.scrollTop()+(this.node.offset().top-m.offsetParent.clientHeight)-
g.offset().top);this.node.css("width",g.width()-(g.get(0).scrollHeight>g.height()?this.grid.getScrollbarDimensions().width:0)-2+"px")};b.prototype.getErrorFn=function(a,b,d){return function(){var g=$(a);g.html(Insight.templates.error.render());$(".btn",g).click(function(){b.apply(d,[])})}};b.prototype.isVisible=function(){return!0};b.prototype.getTitle=function(){return""};b.prototype.setItem=function(a){this.gav=a};b.prototype.message=function(a){$(".alert",this.node).remove();a=$('\x3cdiv class\x3d"alert" style\x3d"width:92.5%"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3e\x3c/div\x3e');
$("div:first",this.node).prepend(a);return a};b.prototype.addErrorMessage=function(a){this.message(a).addClass("alert-error").append("\x3cstrong\x3eError: \x3c/strong\x3e",$("\x3cspan\x3e\x3c/span\x3e").text(a))};b.prototype.addSuccessMessage=function(a){var b=this.message(a).addClass("alert-success").append($("\x3cspan\x3e\x3c/span\x3e").text(a));setTimeout(function(){b.fadeOut("fast",function(){b.remove()})},8E3);return b};b.prototype.setGrid=function(a){this.grid=a};b.prototype.create=$.noop;b.prototype.destroy=
$.noop;$.extend(!0,window,{Insight:{InformationPanel:a,InformationPanelPlugin:b,InformationPanelPlugins:[]}})})();
(function(){function a(a){var b="../artifactDetails/";demoMode&&(b=demoArtifactUrl);return b+reportId+"?groupId\x3d"+a.groupId+"\x26artifactId\x3d"+a.artifactId+"\x26version\x3d"+a.version}function b(a,b){var c=[],d=$("\x3cdiv\x3e\x3c/div\x3e");return Insight.util.isNotNullOrUndefined(a)&&0<a.length?("object"===typeof a[0]?$.each(a,function(a,b){c.push(d.text(b.licenseName).html())}):$.each(a,function(a,b){c.push(d.text(b).html())}),'\x3cspan class\x3d"license"\x3e'+c.join(',\x3c/span\x3e \x3cspan class\x3d"license"\x3e')+
"\x3c/span\x3e"):b||""}function d(a,c,d){var f="artifactInfoSecurity",m=Math.floor(a.securityThreatLevel);$(c).is(":hidden")||(0>=a.securityThreatCount?(m="NA",f+=" artifactInfoSecurityUnspecified"):8<=m?f+=" artifactInfoSecurityCritical":4<=m?f+=" artifactInfoSecuritySevere":(0<=m||(m="Unscored"),f+=" artifactInfoSecurityModerate"),a=$.extend(a,{partial:!1,overriddenLicenses:b(a.overriddenLicenses,"-"),declaredLicenses:b(a.declaredLicenses,"-"),observedLicenses:b(a.observedLicenses,"-"),currentMatchState:d.matchState,
proprietary:d.proprietary,colorCls:f,lvl:m,cataloged:a.catalogDate?HealthCheck.getAge(new Date(a.catalogDate)):null,multipleSecurity:1<a.securityThreatCount,isManual:"Manual"===a.identificationSource}),c.html(h.render(a)),$.event.trigger("artifactInfoPanelLoading",{data:a,node:c,partialDisplay:!1,gav:d}),Insight.ComponentInformation({data:a,partialDisplay:!1}))}function c(a,b){this.node=a;this.options=b}var h;$(document).ready(function(){h=Hogan.compile($("#infoPanelComponentTemplate").html())});
c.prototype=new Insight.InformationPanelPlugin({priority:1});c.prototype.create=Brain.ci&&Brain.ci.getArtifactVersionInfoUrl?function(){var a=this,b=a.gav,c=null,f=null,m=null,h=null,y=function(){null!==f&&(null!==c&&b===a.gav)&&(f.securityThreatCount=0,f.securityThreatLevel=null,$.each(f.securityVulnerabilities,function(a,b){"Not Applicable"!==b.status&&(f.securityThreatCount++,Insight.util.isNotNullOrUndefined(b.severity)&&(f.securityThreatLevel=Math.max(f.securityThreatLevel,b.severity)))}),f.versions=
c,d(f,a.node,b))};Insight.util.isNullOrUndefined(this.gav.groupId)||Insight.util.isNullOrUndefined(this.gav.artifactId)||Insight.util.isNullOrUndefined(this.gav.version)?this.node.html("\x3cdiv class\x3d'infoPanelText'\x3eUnknown Component\x3c/div\x3e"):($(this.node).html('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e'),m=$.extend({},this.gav,{appId:applicationId,instanceId:instanceId}),h=Brain.ci.getComponentDetailsListUrl?
Brain.ci.getComponentDetailsListUrl(m):Brain.ci.getArtifactVersionInfoUrl(m),$.getJSON(Insight.toBrain(Brain.ci.getArtifactInfoUrl(m)),function(a){f=a;y()}).error(this.getErrorFn(this.node,this.create,this)),$.getJSON(Insight.toBrain(h),function(a){c=a.list?a.list:a;y()}).error(this.getErrorFn(this.node,this.create,this)))}:function(){var b=this,c=b.gav;Insight.util.isNullOrUndefined(this.gav.groupId)||Insight.util.isNullOrUndefined(this.gav.artifactId)||Insight.util.isNullOrUndefined(this.gav.version)?
this.node.html("\x3cdiv class\x3d'infoPanelText'\x3eUnknown Artifact\x3c/div\x3e"):($(this.node).html('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e'),$.getJSON(a(this.gav),function(a){b.gav===c&&d(a,$(b.node),c)}).error(this.getErrorFn(this.node,this.create,this)))};c.prototype.destroy=function(){this.node.empty()};c.prototype.getTitle=function(){return"Component Info"};Insight.InformationPanelPlugins.push(c)})();
(function(){function a(a,d){this.node=a;this.options=d}a.prototype=new Insight.InformationPanelPlugin({priority:48});a.prototype.isVisible=function(){return!0};a.prototype.create=function(){var a=this;this.destroy();this.gav.hash?$.getJSON("partialmatched.json",function(d){var c=null,h;for(h=0;h<d.aaData.length;h++)if(d.aaData[h].hash===a.gav.hash){c=d.aaData[h].matchDetails;break}c?($(a.node).html("\x3cdiv id\x3d'similarityTable' class\x3d'borderedTable'\x3e\x3c/div\x3e"),InsightDatatable.createSimilarityTable(c)):
$(a.node).html("\x3cdiv class\x3d'infoPanelText'\x3eNo similar matches were found for this component.\x3c/div\x3e")},this.getErrorFn(a.node,a.create,a)):$(a.node).html("\x3cdiv class\x3d'infoPanelText'\x3eNo similar matches were found for this component.\x3c/div\x3e")};a.prototype.destroy=function(){InsightDatatable.removeSimilarityTable();this.node.empty()};a.prototype.getTitle=function(){return"Similar"};Insight.InformationPanelPlugins.push(a)})();
(function(){function a(a){var b,h;if(0===a.indexOf("dependency:/"))return a=a.substring(12),b=a.lastIndexOf("/"),0>b?["Dependency "+a,""]:["Dependency "+a.substring(b+1),"Module "+a.substring(0,b)];b=a.lastIndexOf("/");if(-1===b)return[a,""];h=a.substring(b+1);a=a.substring(0,b);return[h,a]}function b(a,b){this.node=a;this.options=b}b.prototype=new Insight.InformationPanelPlugin({priority:64});b.prototype.buildView=function(b){if(0<b.length){b.sort();var c="\x3cdiv class\x3d'infoPanelText fileDetail'\x3e",
h=!1;$.each(b,function(b,d){$.each(d.pathnames,function(b,d){var g=a(d);c+="\x3cb\x3e"+g[0]+"\x3c/b\x3e";0<g[1].length&&(c+=" \x3ci\x3elocated at\x3c/i\x3e "+g[1]);c+="\x3cbr\x3e\x3cbr\x3e"});0>=d.pathnames.length&&(h=!0)});h&&(c+="Occurrences of this component cannot be listed because pathnames have been anonymized. To see all occurrences, please disable anonymization in the options of your CLM enforcement points and perform a new scan.");c+="\x3c/div\x3e";$(this.node).html(c)}else $(this.node).html("\x3cdiv class\x3d'infoPanelText'\x3eInvalid data encountered, no files are associated with this component.\x3c/div\x3e")};
b.prototype.create=function(){var a=this;a.options.byHash?this.buildView([a.gav]):$.getJSON("bom.json",function(b){var h=[];$.each(b.aaData,function(b,c){c.groupId===a.gav.groupId&&(c.artifactId===a.gav.artifactId&&c.version===a.gav.version)&&h.push(c)});a.buildView(h)},this.getErrorFn(a.node,a.create,a))};b.prototype.destroy=function(){};b.prototype.getTitle=function(){return"Occurrences"};Insight.InformationPanelPlugins.push(b)})();(function(){})();
(function(){$.extend(!0,window,{Insight:{toBrain:function(a){return"/"===a.charAt(0)?"../brain"+a:"../brain/"+a}}})})();
(function(){function a(a){return null===a||"undefined"===typeof a}$.extend(!0,window,{Insight:{util:{enableTooltip:function(a){$(a).each(function(){var a=$(this).attr("data-gravity-offset")||0;a&&(a=parseInt(a,10));$(this).tipsy({fade:!0,gravity:$(this).attr("data-gravity"),offset:a,html:!0,opacity:1,delayOut:0,title:"data-tooltip"})})},getErrorMessage:function(a){var d="";return d=0===a.status||1E3<=a.status?"Network error while contacting server":a.responseText&&0<=(a.getResponseHeader("Content-Type")||
"").indexOf("text/plain")?a.responseText:a.statusText?a.statusText:"Error "+a.status},getQueryParameter:function(a){var d=0<window.location.search.length?window.location.search.substring(1).split("\x26"):[],c=null,h=null;a=a.toLowerCase();for(h=0;h<d.length;h++)if(c=d[h].split("\x3d"),c[0].toLowerCase()===a)return c[1]},isNullOrUndefined:a,isNotNullOrUndefined:function(b){return!a(b)}}}})})();
(function(){var a={};Insight.util.isNullOrUndefined(window.Brain)&&($.getJSON("../brain/rest/features").success(function(b){$.each(b,function(b,c){a[c.toLowerCase()]=!0})}),$.extend(!0,window,{Brain:{hasFeature:function(b){return!0===a[b.toLowerCase()]},getVersion:function(){return!1}}}))})();
(function(){window.demoMode=!1;$(document).ready(function(){InsightDatatable.updateSummary();$("button[data-containerid]").click(function(a){if(!$(this).hasClass("active"))switch(a=$(this).data("containerid"),$("[data-container]").css("display","none"),$("#"+a).css("display",""),InsightDatatable.destroyActiveTable(),a){case "securitycontainer":InsightDatatable.createSecurityTable();break;case "licensecontainer":InsightDatatable.createLicenseTable();break;case "componentcontainer":InsightDatatable.createComponentTable()}});
Insight.util.enableTooltip($("[data-tooltip]"));var a=$('[data-action\x3d"reevaluatePolicy"]');Brain.hasFeature("reevaluate-policy")?a.click(function(){a.find("i").attr("class","icon-white icon-time");$.getJSON("../reevaluatePolicy").success(function(){a.find("i").attr("class","icon-white icon-refresh");location.reload()}).error(function(){$(".btn-group:eq(1)").after('\x3cdiv class\x3d"alert alert-error" style\x3d"margin:5px 0"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3eThere has been an error reevaluating policy. Try running the report again.\x3c/div\x3e')})}):
a.hide();$.browser.msie&&9>$.browser.version&&$(".btn-group:eq(1)").after('\x3cdiv class\x3d"alert alert-error" style\x3d"margin:5px 0"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3eYou are using older version of Internet Explorer (IE). You may notice degraded performance and/or functionality. To address this, download and install the latest version of IE, or other modern browser (e.g. Chrome, Firefox)\x3c/div\x3e')})})();
(function(){function a(a){var b=$(window).innerHeight(),c=$(a).offset().top;a=$("#"+a.attr("id")+"Pager").height();return Math.max(150,b-c-h-a)}function b(a){$("#"+a+"container .message").remove()}function d(a,c){var d=$("#"+a+"container"),f=$("#"+a+"Table").position(),m;null!==f&&(b(a),d.append('\x3cdiv class\x3d"message" style\x3d"top:'+(f.top+70)+'px"\x3e'+c+"\x3c/div\x3e"),m=$(".message",d),m.css("left",f.left+d.outerWidth()/2-m.outerWidth()/2+"px"))}function c(b,c,d){function f(c){r.destroyed||
(r.table=new Slick.Grid("#"+b+"Table",r.dataView,d.columns,u),d.selectable&&(r.table.setSelectionModel(new Slick.RowSelectionModel),r.dataView.syncGridSelection(r.table,!0)),y.init(r.table),s.css("height",d.height||a($("#"+b+"Table"))+"px"),r.processData(c),r.initialize())}function m(a){return function(b,c,d){b=s.empty().append(Insight.templates.error.render({message:d}));$("button",b).click(a)}}function h(a){s.empty().append('\x3cdiv class\x3d"alert alert-info fade in" style\x3d"width:50%;margin:20px auto;padding:5px"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e');
a.get().done(function(b){null!=b?f(b):m(function(){h(a)})()}).fail(m(function(){h(a)}))}var y=new Slick.Data.GroupItemMetadataProvider,u=$.extend({editable:!1,enableAddRow:!1,enableCellNavigation:d.enableCellNavigation,enableColumnReorder:!1,enableTextSelectionOnCells:!0,fullWidthRows:!0,forceFitColumns:!0,rowHeight:31,explicitInitialization:!0,showHeaderRow:!d.disableFilter,multiSelect:!1,autoHeight:d.autoHeight,multiColumnSort:d.multiColumnSort},d.config||{}),r=this,s=$("#"+b+"Table");this.options=
d;this.id=b;this.dataView=new Slick.Data.DataView({groupItemMetadataProvider:y});this.filter=new Slick.Filter;$.isArray(c)?f({aaData:c}):"string"===typeof c?h({get:function(){return $.getJSON(c)}}):"object"===typeof c?h(c):console.log("Unable to load: "+c)}var h=null;$.browser&&($.browser.mozilla&&4>parseFloat($.browser.version)?h=9:$.browser.msie&&9>parseFloat($.browser.version)&&(h=15));null===h&&(h=14);c.prototype.updateHeight=function(){var b=$("#"+this.id+"Table"),c=this;b.css("height",a(b)+
"px");window.clearTimeout(this.resizeTimeout);this.resizeTimeout=window.setTimeout(function(){c.table.resizeCanvas()},50)};c.prototype.destroy=function(){this.destroyed=!0;b(this.id);$(window).unbind("resize");this.table&&(this.table.pager&&(this.table.pager.destroy(),this.table.pager=null),this.table.columnsResizedFn&&(this.table.onColumnsResized.unsubscribe(this.table.columnsResizedFn),this.table.columnsResizedFn=null),this.table.destroy())};c.prototype.initialize=function(){var a=this;this.initialized||
(this.initialized=!0,this.options.defaultSort&&($.isArray(this.options.defaultSort)?this.table.setSortColumns(this.options.defaultSort):this.table.setSortColumns([this.options.defaultSort])),$.isArray(this.options.plugins)&&$.each(this.options.plugins,function(b,c){a.table.registerPlugin(c)}),this.table.registerPlugin(new Slick.Sort),this.table.init(),this.options.disableFilter||this.table.registerPlugin(this.filter),this.table.registerPlugin(new Slick.Tipsy),$(window).resize(this.options.resizeFn||
function(){Insight.util.isNullOrUndefined(a.options.height)&&a.updateHeight()}),this.listeners&&($.each(this.listeners,function(a,b){setTimeout(b,0)}),this.listeners=null))};c.prototype.processData=function(a){var c=this;this.initialize();Insight.util.isNotNullOrUndefined(a)&&(this.options.dataProcessor&&(a.aaData=this.options.dataProcessor.call(null,a.aaData)),this.dataView.beginUpdate(),this.dataView.setItems(a.aaData),this.options.disableFilter||(this.options.externalFilters?this.dataView.setFilter(function(a,
b){var d=!0;$.each(c.options.externalFilters,function(c,h){h(a,b)||(d=!1);return d});return d&&c.filter.getFilter()(a,b)}):this.dataView.setFilter(this.filter.getFilter())),this.options.groupInfo&&this.dataView.groupBy(this.options.groupInfo.field,this.options.groupInfo.groupHeaderFn,this.options.groupInfo.groupingComparer),this.dataView.endUpdate(),this.options.groupInfo&&"collapsed"===this.options.groupInfo.initialState&&(this.dataView.beginUpdate(),$.each(this.dataView.getGroups(),function(a,b){c.dataView.collapseGroup(b.value)}),
this.dataView.endUpdate()));b(this.id);if(Insight.util.isNullOrUndefined(a)||0===a.aaData.length)d(this.id,this.options.emptyText||"None");this.options.disablePager||(this.table.pager=new Slick.Controls.Pager(this.dataView,this.table,$("#"+this.id+"TablePager")))};c.prototype.addMessage=function(a,b,c){var d=this,h=$('\x3cdiv class\x3d"alert"\x3e\x3cbutton class\x3d"close" data-dismiss\x3d"alert"\x3e\x26times;\x3c/button\x3e\x3c/div\x3e');h.addClass(b);h.append("\x3cspan\x3e\x3c/span\x3e").text(a);
h.bind("closed",function(){d.updateHeight()});$("#"+d.id+"container").prepend(h);d.updateHeight();c&&setTimeout(function(){h.fadeOut("fast",function(){h.remove();d.updateHeight()})},1E3*c);return h};c.prototype.addLoadListener=function(a){this.table?setTimeout(a,0):(this.listeners=this.listeners||[],this.listeners.push(a))};c.prototype.addSuccess=function(a,b){this.addMessage(a,"alert-success",b)};c.prototype.addError=function(a,b){this.addMessage(a,"alert-error",b)};$.extend(!0,window,{Insight:{Table:c}})})();
(function(){function a(a){Insight.util.isNotNullOrUndefined(r)?a.apply(null,[r]):$.getJSON("licensethreats.json").success(function(e){r=e.aaData;a.apply(null,[r])}).error(function(e,b,c){a.apply(null,[null,"Loading license categorization: "+Insight.util.getErrorMessage(e)])})}function b(){for(var a=null,e=0;e<arguments.length;e++)for(var b=arguments[e],c=0;c<b.length;c++){var n=r[b[c]];Insight.util.isNotNullOrUndefined(n)&&(a=Math.max(n,a))}return a}function d(a){var e=c(a.effectiveLicenseThreat);
return"undefined"!==typeof e?e:Insight.util.isNotNullOrUndefined(a.overriddenLicenses)?b(a.overriddenLicenses):a.effectiveLicenseThreat}function c(a){if(0<=C.indexOf(a))return h(a)}function h(a){switch(a){case "COPYLEFT":return 10;case "NON-STANDARD":return 7;case "NOT-PROVIDED":return 6;case "WEAKCOPYLEFT":return 3;case "LIBERAL":return 0;default:return null}}function p(a,e){for(var b=[],c=null,c=0;c<e.length;c++)("Not Provided"===e[c]||-1===a.indexOf(e[c]))&&b.push(e[c]);return b}function g(a){return Insight.util.isNotNullOrUndefined(a)&&
0<a.length?a.join(", "):""}function t(a,e){var b=d(a),c=d(e),b=Insight.util.isNullOrUndefined(b)?-1:b,c=Insight.util.isNullOrUndefined(c)?-1:c;return b<c?-1:b>c?1:0}function f(a){var e=c(a);"undefined"!==typeof e&&(a=e);return Insight.util.isNullOrUndefined(a)?"unspecifiedScore":7<a?"criticalScore":3<a?"severeScore":0<a?"moderateScore":"noScore"}function m(a,e,b){if(Insight.util.isNotNullOrUndefined(a))return g(a);a=g(e);e=g(p(e,b));return a+(0<e.length?", "+e:"")}function z(a,e,c,l,n){if(Insight.util.isNotNullOrUndefined(n.overriddenLicenses))return'\x3cdiv class\x3d"'+
f(b(n.overriddenLicenses))+'"\x3e\x3ci\x3e'+g(n.overriddenLicenses)+"\x3c/i\x3e\x3c/div\x3e";a=g(n.declaredLicenses);e=g(p(n.declaredLicenses,n.observedLicenses));return'\x3cdiv class\x3d"'+f(d(n))+'"\x3e \x3cb\x3e'+a+"\x3c/b\x3e"+(0<e.length?", "+e:"")+"\x3c/div\x3e"}function y(){return v||x||w}function u(a,e){$("#"+a+"container .message").remove();$(window).unbind("resize");e.pager&&(e.pager.destroy(),e.pager=null);e.columnsResizedFn&&(e.onColumnsResized.unsubscribe(e.columnsResizedFn),e.columnsResizedFn=
null);e.destroy()}var r,s={preReleaseStrings:["alpha","beta","milestone","rc","snapshot"],isPrerelease:function(a){var e=null;a=a.toLowerCase();if(Insight.util.isNotNullOrUndefined(a)&&(1===a.length||!isNaN(parseFloat(a.charAt(1)))))switch(a.charAt(0)){case "a":case "b":case "m":return!0}for(e=0;e<this.preReleaseStrings.length;e++)if(a.substr(0,this.preReleaseStrings[e].length)==this.preReleaseStrings[e])return!0;return!1},versionItemCompare:function(a,e){if(Insight.util.isNullOrUndefined(a))return-this.versionItemCompare(e,
a);var b=parseInt(a,10),c=parseInt(e,10);return Insight.util.isNullOrUndefined(e)?this.isPrerelease(a)?-1:1:!isNaN(b)&&!isNaN(c)?b===c?0:b>c?1:-1:!isNaN(b)||!isNaN(c)?isNaN(b)?this.isPrerelease(a)?-1:1:this.isPrerelease(e)?1:-1:a<e?-1:a>e?1:0},compare:function(a,e){var b=null,b=/(\w+)/g,c=null,n=null;if(Insight.util.isNullOrUndefined(a))return Insight.util.isNullOrUndefined(e)?0:-1;if(Insight.util.isNullOrUndefined(e))return 1;c=a.match(b);n=e.match(b);for(b=0;b<Math.max(c.length,n.length);b++)switch(this.versionItemCompare(c[b],
n[b])){case 1:return 1;case -1:return-1}return 0}};a($.noop);var C="UNKCAT LIBERAL WEAKCOPYLEFT NOT-PROVIDED NON-STANDARD COPYLEFT".split(" "),v=null,x=null,w=null,q=null,A=null;$.extend(!0,window,{InsightDatatable:{createAuditTable:function(a){A=new Insight.Table("audit",a,{resizeFn:$.noop,selectable:!0,disablePager:!0,disableFilter:!0,height:250,columns:[{id:"date",name:"Date",field:"date",formatter:function(a,b,c,k,d){return dateFormat(c,"mmm d yyyy, h:MM:ss tt")},sortable:!0,width:30},{id:"user",
name:"User",field:"user",toolTipGravity:"n",toolTipFn:function(a){return Insight.util.isNullOrUndefined(a.where)?$("\x3cdiv/\x3e").text("Edited report from "+a.ip).html():$("\x3cdiv/\x3e").text("Edited report in build '"+a.where+"' from "+a.ip).html()},sortable:!0,width:20},{id:"action",name:"Action",field:"action",sortable:!0,width:20},{id:"detail",name:"Detail",field:"detail",sortable:!0,width:40},{id:"comment",name:"Comment",field:"comment",toolTipGravity:"n",toolTipFn:function(a){if(a.comment)return $("\x3cdiv/\x3e").text(a.comment).html()},
sortable:!0,width:80}],defaultSort:{columnId:"date",sortAsc:!1},dataProcessor:function(a){$.each(a,function(a,b){var e=b.status,c="",k;b.id=a;b.date=new Date(b.time);switch(b.status){case "Open":e="Reopened";break;case "Not Applicable":e="Ignored";break;case "Overridden":e="Overrode"}b.action=e;Insight.util.isNullOrUndefined(b.user)&&(b.user="anonymous");switch(b.filename){case "licenses.json":c="License ";e=b.overriddenLicenses;c=Insight.util.isNotNullOrUndefined(e)?c+("as "+g(e)):c+"Analysis";break;
case "security.json":c="Vulnerability ",e=b.source,k=b.reference,Insight.util.isNotNullOrUndefined(e)&&0!==k.toUpperCase().indexOf(e.toUpperCase())&&(c+=e+"-"),c+=k}b.detail=c});return a}});$("#"+A.id+"Table").click(function(a){a.stopPropagation()})},createComponentTable:function(){function a(b){b.preventDefault();$(this).parents("ul").children("li").removeClass("active");$(this).parents("li").addClass("active");b=$("#policy-match-state-filter li.active").text();var c=$("#policy-violation-filter li.active").text(),
e={};"All"!==b&&("Proprietary"===b?e.proprietary=!0:"Error"===b?e.scanError=!0:e.matchState=b.toLowerCase());"Summary"===c?e.summary=!0:"Waived"===c?e.waived=!0:"All"===c&&(e.all=!0);w.addLoadListener(function(){w.table.getData().setFilterArgs(e);w.table.getData().refresh()})}var b=["unknown","similar","exact"],c=new Slick.ColumnGrouping({columnId:"policyName",style:"scoreCol"}),d=c.getCellStyler(),n=c.getCellRenderer(),B=HealthCheck.getAge(earliestReleaseDate,currentDate),D=$("\x3cdiv/\x3e"),B=[{id:"policyName",
name:"Policy Threat",shortName:"Name",field:"policyName",sortable:!0,width:225,styleFn:function(a,b,e,c,k){return"nopad "+d(a,b,e,c,k)},sortFn:function(a,b){var e=a.policyThreatLevel,c=b.policyThreatLevel,k=a.policyName,d=b.policyName;return e<c?-1:e>c||k<d?1:k>d?-1:0},formatter:function(a,b,e,c,k){var d;switch(k.policyThreatLevel){case 0:d=" noScore";break;case 1:d=" ignoredScore";break;case 2:case 3:d=" moderateScore";break;case 4:case 5:case 6:case 7:d=" severeScore";break;case 8:case 9:case 10:d=
" criticalScore"}return'\x3cdiv class\x3d"'+d+'"\x3e'+(0<n(a,b,e,c,k).length?D.text(e).html():"")+"\x3c/div\x3e"}},{id:"coordinates",name:"Coordinates",field:"coordinates",sortable:!0,width:295,toolTipGravity:"se",styleFn:function(a,b,e,c,k){return k.modified||"Manual"===k.identificationSource?"modified":""},toolTipFn:function(a){var b="";a.modified&&(b+="\x3cli\x3ebeen manually edited.  See the audit log for details.\x3c/li\x3e");"Manual"===a.identificationSource&&(b+="\x3cli\x3ebeen claimed from an unknown or similar component.  View the Component Information Panel (CIP) for more details.\x3c/li\x3e");
a.waived&&(b+="\x3cli\x3ebeen waived.\x3c/li\x3e");if(0<b.length)return"This record has...\x3cbr\x3e\x3cbr\x3e\x3cul\x3e"+b+"\x3c/ul\x3e"},formatter:function(a,b,e,c,k){a="";a=k.waived?'\x3cimg src\x3d"flag_white.png" style\x3d"margin-right:4px" title\x3d"Violation has been waived"\x3e':'\x3cspan style\x3d"padding-right:20px"\x3e\x3c/span\x3e';Insight.util.isNotNullOrUndefined(k.groupId)?a+='\x3cimg src\x3d"public/coord-gav.png" alt\x3d"GAV"/\x3e \x3cspan\x3e'+k.groupId+" \x3cstrong\x3e:\x3c/strong\x3e "+
k.artifactId+" \x3cstrong\x3e:\x3c/strong\x3e "+k.version+"\x3c/span\x3e":(a+='\x3cimg src\x3d"public/coord-file.png" alt\x3d"File"/\x3e ',b=k.filenames.join(", "),a+=b?b:"(Anonymized Path) SHA1: "+k.hash);return a}},{id:"versions",name:"Popularity",field:"relativePopularity",sortable:!0,filterable:!1,width:85,sortFn:function(a,c){return a.matchState===b[0]?c.matchState===b[0]?0:-1:c.matchState===b[0]?1:"Manual"===a.identificationSource?a.identificationSource===c.identificationSource?0:-1:"Manual"===
c.identificationSource?1:a.relativePopularity<c.relativePopularity?-1:a.relativePopularity>c.relativePopularity?1:0},formatter:function(a,c,k,d,n){if(n.matchState===b[0]||"Manual"===n.identificationSource)return"";var l;k=Math.round(100*k);79<k?l="popularity-100":59<k?l="popularity-80":39<k?l="popularity-60":19<k?l="popularity-40":0<=k&&(l="popularity-20");return l?'\x3cdiv class\x3d"'+l+'"\x3e\x3c/div\x3e':""}},{id:"age",name:"Age",field:"age",sortable:!0,filterable:!1,width:85,sortFn:function(a,
b){var c=a.age,e=b.age;if(!(void 0===c&&void 0===e)){if(void 0===c)return-1;if(void 0===e)return 1;if(c<e)return-1;if(c>e)return 1}return 0},formatter:function(a,b,c,e,k){return void 0===c||null===c?"":359<c?(c/365).toFixed(1)+" y":30<c?Math.floor(c/30)+" m":Math.floor(c)+" d"}},{id:"releasehistory",name:"Release History",field:"groupId",sortable:!1,filterable:!1,resizable:!1,width:211,header:'\x3cdiv class\x3d"release-header"\x3e\x3ci class\x3d"icon-question-sign" title\x3d"\x3cdiv style\x3d\'background:url(release-tooltip.png);width:241px;height:78px\'\x3e\x3c/div\x3e"\x3e\x3c/i\x3e\x3cspan\x3e'+
B+"\x3c/span\x3e\x3c/div\x3e",formatter:function(a,b,c,e,k){if(null===c||"Manual"===k.identificationSource)return"No Popularity Data";var d="";$.each({groupId:k.groupId,artifactId:k.artifactId,version:k.version},function(a,b){d+="\x26"+encodeURIComponent(a)+"\x3d"+encodeURIComponent(b)});return'\x3cimg src\x3d"../brain/rest/report/'+applicationId+"/"+reportId+"/releaseGraph?"+d.substring(1)+'" alt\x3d"Release Popularity"\x3e'}}],c=[c,new Insight.InformationPanel({byHash:!0})];Brain.hasFeature("release-graph")||
(B[1].width+=B.pop().width);w=new Insight.Table("component",{get:function(){var a=$.Deferred();$.when($.getJSON("policythreats.json"),$.getJSON("bom.json")).done(function(b,c){function e(a){return a.hash||"error: "+(a.pathnames||[]).join("\t")}if(null===b[0]||null===c[0])a.reject([]);else{var k={},d={},n={},l=[];$.each(c[0].aaData,function(a,b){var c=e(b);k[c]=b;d[c]=!1;n[c]=!1});b[0].version?($("#policy-violation-filter").show(),$.each(b[0].aaData,function(a,b){var c=e(b);if(!b.hash||"null"===b.hash)return!0;
b.activeViolations.length&&(d[c]=!0,b.activeViolations.sort(function(a,b){return b.policyThreatLevel-a.policyThreatLevel}),$.each(b.activeViolations,function(a,e){l.push($.extend({policyThreatLevel:e.policyThreatLevel,policyName:e.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,summary:0===a,waived:!1,all:!0},k[c]))}));b.waivedViolations.length&&(n[c]=!0,$.each(b.waivedViolations,function(a,e){l.push($.extend({policyThreatLevel:e.policyThreatLevel,policyName:e.policyName,
groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,summary:!1,waived:!0,all:!0},k[c]))}))})):$.each(b[0].aaData,function(a,b){var c=e(b);if(!b.hash||"null"===b.hash)return!0;d[c]=!0;l.push($.extend({policyThreatLevel:b.policyThreatLevel,policyName:b.policyName,groupId:b.groupId,artifactId:b.artifactId,version:b.version,hash:b.hash,summary:!0,waived:!1,all:!0},k[c]))});$.each(d,function(a,b){b||l.push($.extend(!0,{policyThreatLevel:0,policyName:"None",summary:!0,waived:!1,all:!1===
n[a]},k[a]))});a.resolve({aaData:l})}}).fail(function(b){a.reject(b)});return a}},{columns:B,multiColumnSort:!0,selectable:!0,plugins:c,defaultSort:[{columnId:"policyName",sortAsc:!1},{columnId:"coordinates",sortAsc:!0}],externalFilters:[function(a,b){var c=!0;b&&$.each(b,function(b,e){return c=a[b]===e});return c}],dataProcessor:function(a){a=a||[];$.each(a,function(a,b){b.id=a;b.createTime&&(b.age=Math.floor(((new Date).getTime()-b.createTime)/864E5));Insight.util.isNotNullOrUndefined(b.groupId)?
b.coordinates=b.groupId+":"+b.artifactId+":"+b.version:b.coordinates=b.filenames.join(", ")});return a}});$("#policy-match-state-filter").unbind("click");$("#policy-match-state-filter li a").click(a);$("#policy-violation-filter li a").click(a);$("#policy-match-state-filter li.active a").trigger("click");w.addLoadListener(function(){$(".release-header \x3e .icon-question-sign").tipsy({gravity:"e",html:!0,title:"title",opacity:1})})},createLicenseTable:function(a){var b=[{id:"_formattedEffectiveLicenseThreat",
name:"License Threat",shortName:"Licenses",field:"_formattedEffectiveLicenseThreat",sortable:!0,width:200,styleFn:function(){return"nopad"},sortFn:t,formatter:z},{id:"groupId",name:"Group",field:"groupId",sortable:!0,width:300,cssClass:"gridcell"},{id:"artifactId",name:"Artifact",field:"artifactId",sortable:!0,width:300,cssClass:"gridcell"},{id:"version",name:"Version",field:"version",sortable:!0,width:150,sortFn:function(a,b){return s.compare(a.version,b.version)}},{id:"status",name:"Status",field:"status",
sortable:!0,width:150}],c=[new Insight.InformationPanel];x=new Insight.Table("license","licenses.json",{columns:b,config:a,plugins:c,defaultSort:{columnId:"_formattedEffectiveLicenseThreat",sortAsc:!1},dataProcessor:function(a){var b;for(b=0;b<a.length;b++)a[b].id=b,a[b].status=Insight.util.isNullOrUndefined(a[b].status)?"Open":a[b].status;return a}});x.addLoadListener(function(){x.table.setSelectionModel(new Slick.RowSelectionModel);x.table.getData().onRowsChanged.subscribe(function(a,b){var c,e;
b=b.rows;for(e=0;e<b.length;e++)c=x.table.getData().getItem(b[e]),c._formattedEffectiveLicenseThreat=m(c.overriddenLicenses,c.declaredLicenses,c.observedLicenses)})});return x},createSecurityTable:function(a){var b=new Slick.ColumnGrouping({columnId:"_score",style:"scoreCol"}),c=b.getCellStyler(),d=b.getCellRenderer(),b=[b,new Insight.InformationPanel];v=new Insight.Table("security","security.json",{columns:[{id:"_score",name:"Threat Level",shortName:"Level",field:"_score",sortable:!0,width:120,toolTip:"'Threat Level' highlights the CVSS (Common Vulnerability Scoring System, version 2) base score for each listed vulnerability.",
styleFn:function(a,b,e,k,d){return"nopad "+c(a,b,e,k,d)},sortFn:function(a,b){var c=a._score,e=b._score;return!isNaN(c)&&!isNaN(e)?parseInt(c,10)-parseInt(e,10):e<c?-1:e>c?1:0},formatter:function(a,b,c,e,k){return'\x3cdiv class\x3d"'+(8<=c?" criticalScore":4<=c?" severeScore":" moderateScore")+'"\x3e'+(d(a,b,c,e,k)||"\x26nbsp;")+"\x3c/div\x3e"}},{id:"problemCode",name:"Problem Code",shortName:"Code",field:"_reference",sortable:!0,width:105,formatter:function(a,b,c,e,k){a=k._reference;k=k.url;return Insight.util.isNullOrUndefined(a)?
"":'\x3ca href\x3d"'+k+'" target\x3d"_blank"\x3e'+a+"\x3c/a\x3e"}},{id:"groupId",name:"Group",field:"groupId",sortable:!0,width:255},{id:"artifactId",name:"Artifact",field:"artifactId",sortable:!0,width:250},{id:"version",name:"Version",field:"version",sortable:!0,width:200,sortFn:function(a,b){return s.compare(a.version,b.version)}},{id:"status",name:"Status",field:"status",sortable:!0,width:200}],config:a,defaultSort:{columnId:"_score",sortAsc:!1},dataProcessor:function(a){var b,c,e;for(e=0;e<a.length;e++)a[e].id=
e,a[e]._score=Insight.util.isNullOrUndefined(a[e].score)?"Unscored":String(Math.floor(a[e].score)),b=a[e].source,c=a[e].reference,a[e]._reference=Insight.util.isNullOrUndefined(b)||0===c.toUpperCase().indexOf(b.toUpperCase())?c:b+"-"+c,a[e].status=Insight.util.isNullOrUndefined(a[e].status)?"Open":a[e].status;return a},plugins:b});v.addLoadListener(function(){v.table.setSelectionModel(new Slick.RowSelectionModel)});return v},createSimilarityTable:function(a){q=new Insight.Table("similarity",a,{selectable:!0,
disablePager:!0,disableFilter:!0,height:250,columns:[{id:"_formattedEffectiveLicenseThreat",name:"License Threat",field:"_formattedEffectiveLicenseThreat",sortable:!0,width:65,sortFn:t,formatter:z},{id:"securityCounters",name:"Security",field:"securityCounters",sortable:!0,width:50,sortFn:function(a,b){var c=a.securityCounters.Critical-b.securityCounters.Critical;0===c&&(c=a.securityCounters.Severe-b.securityCounters.Severe);0===c&&(c=a.securityCounters.Moderate-b.securityCounters.Moderate);return c},
formatter:function(a,b,c,k,d){a=d.securityCounters;var h="",f,g,s=0;b=k.width-10;c=function(a,b){var c;for(c=0;c<a&&!(s>=g);c++)h+='\x3cspan class\x3d"arrow '+b+'_arrow" style\x3d"left:'+s++*f+'px"\x3e\x3c/span\x3e'};if(a){k=a.Critical+a.Severe+a.Moderate;for(f=0;-9<f&&(k-1)*(10+f)+10>b;f--);g=(b-10)/(10+f)+1;a.Critical&&c(a.Critical,"red");a.Severe&&c(a.Severe,"orange");a.Moderate&&c(a.Moderate,"yellow")}return'\x3cdiv style\x3d"white-space:nowrap;width:'+(0<s?10+(s-1)*(10+f):0)+'px"\x3e'+h+"\x3c/div\x3e"}},
{id:"groupId",name:"Group",field:"groupId",sortable:!0,width:90},{id:"artifactId",name:"Artifact",field:"artifactId",sortable:!0,width:90},{id:"version",name:"Version",field:"version",sortable:!0,width:30}],dataProcessor:function(a){a||(a=[]);$.each(a,function(a,b){b.id=a;b._formattedEffectiveLicenseThreat=m(b.overriddenLicenses,b.declaredLicenses,b.observedLicenses)});return a}});q.table.render();q.table.columnsResizedFn=function(){var a;for(a=0;a<q.getDataLength();a++)q.updateCell(a,q.getColumnIndex("securityCounters"))};
q.table.onColumnsResized.subscribe(q.table.columnsResizedFn);$("#informationPanelPartialMatch").click(function(a){a.stopPropagation()})},destroyActiveTable:function(){var a=y();a&&a.destroy();w=x=v=null},getActiveTable:y,loadLicenseThreats:a,getLicenseThreatLevelFromArray:b,getLicenseThreatClass:f,removeAuditTable:function(){Insight.util.isNotNullOrUndefined(A)&&(u("audit",A),A=null)},removeComponentTable:function(){Insight.util.isNotNullOrUndefined(w)&&(u("component",w),$("#componentcontainer ul.nav a").unbind("click"),
w=null)},removeLicenseTable:function(){Insight.util.isNotNullOrUndefined(x)&&(u("license",x),x=null)},removeSecurityTable:function(){Insight.util.isNotNullOrUndefined(v)&&(u("security",v),v=null)},removeSimilarityTable:function(){Insight.util.isNotNullOrUndefined(q)&&(u("similarity",q),q=null)}}})})();
(function(a){function b(b){function c(){l=[];a.each(b.grid.getSelectedRows(),function(a,c){l.push(b.grid.getData().getItem(c))});1===l.length?a("input,textarea,select",g).change(q).keyup(q).focusout(q):(a("input,textarea,select",g).unbind("change").unbind("keyup").unbind("focusout"),a("button[data-type\x3dupdate]",g).removeAttr("disabled"))}function d(c){var e=this,f={};c.preventDefault();a(e).attr("disabled","disabled");a("select",g).each(function(b){0===b?f.status=a(this).val():(b=!a(this).prop("disabled"),
f.overriddenLicenses=b?[a(this).val()]:null,f.overriddenLicenseThreat=b?InsightDatatable.getLicenseThreatLevelFromArray(f.overriddenLicenses):null)});f.comment=a("textarea",g).val();m({mask:f,callback:function(c){Insight.util.isNotNullOrUndefined(c)&&a(e).removeAttr("disabled");Insight.util.isNotNullOrUndefined(b.callback)&&b.callback.apply(this,arguments)},dataView:b.dataView,items:l})}b=a.extend({timestamp:(new Date).getTime()},b);var l=b.artifacts,n="#licenseselect"+b.timestamp,f="#license"+b.timestamp,
g=null,v=null,t=a.Deferred(),q=function(){var b=a("option:selected",n).val(),c=a.trim(a("textarea",g).val()),e=a("option:selected",f).val(),k=b!==(l[0].status||"Open"),c=0<c.length,d=e&&(!l[0].overriddenLicenses||l[0].overriddenLicenses[0]!==e);(e&&("Overridden"===b||"Selected"===b)||!e&&!("Overridden"===b||"Selected"===b))&&(c||k||("Overridden"===b||"Selected"===b)&&d)?a("button[data-type\x3dupdate]",g).removeAttr("disabled"):a("button[data-type\x3dupdate]",g).attr("disabled","disabled")};b.single=
Brain.ci.getArtifactLicensesUrl&&b.single;b.grid&&b.grid.onSelectedRowsChanged.subscribe(c);b.single&&a.getJSON(Insight.toBrain(Brain.ci.getArtifactLicensesUrl(a.extend({appId:applicationId},l[0])))).success(function(a){t.resolve(a)}).error(function(){});a.extend(this,{destroy:function(){b.grid&&b.grid.onSelectedRowsChanged.unsubscribe(c)},show:function(c){g=c;a(g).html(s.render(b));a("button[data-type\x3dupdate]",g).click(d);a("button[data-type\x3dcancel]",g).click(function(a){a.preventDefault();
b.cancelCallback&&b.cancelCallback.apply(this)});1===l.length&&(a("button[data-type\x3dupdate]",g).attr("disabled","disabled"),a("input,textarea,select",g).change(q).keyup(q).focusout(q),Insight.util.isNotNullOrUndefined(l[0].status)&&a("[value\x3d"+l[0].status+"]",g).attr("selected",!0));a(n,g).css("width",b.width);a(n,g).change(function(){var b=a(this),c=a(f).val()||l[0].overriddenLicenses&&l[0].overriddenLicenses[0];switch(b.val()){case "Selected":a("option",f).detach();a(f,g).attr("disabled",
!0);t.done(function(e){"Selected"===b.val()&&0<e.length&&InsightDatatable.loadLicenseThreats(function(b){var k={};a.each(e,function(a,c){k[c.licenseName]=b[c.licenseName]});InsightDatatable.populateLicenseCombo(a(f,g),k);Insight.util.isNotNullOrUndefined(c)&&a('option[value\x3d"'+c+'"]',f).attr("selected","selected");a(f,g).removeAttr("disabled")})});break;case "Overridden":a("option",f).detach();v.appendTo(f);a(f,g).removeAttr("disabled");break;default:a("option",f).detach(),a(f,g).attr("disabled",
!0)}Insight.util.isNotNullOrUndefined(c)&&a('option[value\x3d"'+c+'"]',f).attr("selected","selected");q()});h(function(c){var e=a(f,g);InsightDatatable.populateLicenseCombo(e,c);v=a("option",e);1===l.length&&(Insight.util.isNotNullOrUndefined(l[0].overriddenLicenses)&&0<l[0].overriddenLicenses.length&&a("option",e).each(function(){a(this).val()===l[0].overriddenLicenses[0]&&a(this).attr("selected",!0)}),a(n,g).trigger("change"));a(e,g).css("width",b.width)})}})}function d(b){function c(){0===g.length?
a("button[data-type\x3dupdate]",h).attr("disabled","disabled"):a("button[data-type\x3dupdate]",h).removeAttr("disabled")}function d(){g=[];a.each(b.grid.getSelectedRows(),function(a,c){g.push(b.grid.getData().getItem(c))});c()}function f(c){var e={};c.preventDefault();e.status=a("select",h).val();e.comment=a("textarea",h).val();z({mask:e,dataView:b.dataViews[0],items:g,callback:function(c){if(!Insight.util.isNotNullOrUndefined(c))for(var d=1;d<b.dataViews.length;d++)b.dataViews[d].beginUpdate(),a.each(g,
function(c,f){a.each(b.dataViews[d].getItems(),function(c,g){for(var l=0;l<u.length;l++)if(f[u[l]]!==g[u[l]])return;b.dataViews[d].updateItem(g.id,a.extend({},g,e));return!1})}),b.dataViews[d].endUpdate();Insight.util.isNotNullOrUndefined(b.callback)&&b.callback.apply(this,arguments)}})}b=a.extend({timestamp:(new Date).getTime()},b);var g=b.artifacts,h;b.grid&&b.grid.onSelectedRowsChanged.subscribe(d);a.extend(this,{destroy:function(){b.grid&&b.grid.onSelectedRowsChanged.unsubscribe(d)},show:function(d){h=
d;a(h).html(C.render(b));a("button[data-type\x3dupdate]",h).click(f);a("button[data-type\x3dcancel]",h).click(function(a){a.preventDefault();b.cancelCallback&&b.cancelCallback.apply(this)});a("#svStatus"+b.timestamp,h).css("width",b.width);c()}})}function c(b,c,d,f,g,h){var s=[],m=[];a.each(c,function(b,c){var e=a.extend({},c);a.each(d,function(a,b){e[a]=b});e.modified=!0;s.push(e)});a.merge(m,f);a.each(d,function(a,b){m.push(a)});c=function(){b.beginUpdate();a.each(s,function(a,c){b.updateItem(c.id,
c)});b.endUpdate();InsightDatatable.updateSummary();h()};demoMode?c():(a.ajax({type:"POST",url:"../augmentData/bom.json",data:JSON.stringify(s,a.merge(["modified"],r)),beforeSend:parent.beforeSendAugmentedData}),a.ajax({type:"POST",url:"../augmentData/"+g,data:JSON.stringify(s,m),beforeSend:parent.beforeSendAugmentedData}).success(c).error(function(a,b,c){c=Insight.util.getErrorMessage(a);h(c)}))}function h(b,c){Insight.util.isNotNullOrUndefined(w)?b.apply(null,[w]):(A.push(b),q||(q=!0,a.getJSON("licenselist.json").success(function(b){w=
b.aaData;a.each(A,function(a,b){b.apply(null,[w])})}).error(function(a,b,c){b=InsightDatatable.getActiveTable();c=Insight.util.getErrorMessage(a);null!==b?b.addError("Loading known licenses: "+c):console&&console.log("Error loading known licenses: "+c)})))}function p(b){var c={criticalCount:0,severeCount:0,moderateCount:0,noThreatCount:0};"undefined"!==typeof b.effectiveLicenseCounts?a.each(b.effectiveLicenseCounts,function(a,b){7<a?c.criticalCount+=b:3<a?c.severeCount+=b:0<a?c.moderateCount+=b:c.noThreatCount+=
b}):(c.criticalCount=b.copyleftLicenseCount,c.severeCount=b.nonStandardLicenseCount+b.notProvidedLicenseCount,c.moderateCount=b.weakcopyleftLicenseCount,c.noThreatCount=b.liberalLicenseCount);c.count=c.criticalCount+c.severeCount+c.moderateCount+c.noThreatCount;c.licenseAlerts=c.criticalCount+c.severeCount+c.moderateCount;c.multipleLicenseAlerts=1!==c.licenseAlerts;return c}function g(b){var c={criticalCount:0,severeCount:0,moderateCount:0,count:0};a.each(b.securityCounts,function(a,b){6<a?c.moderateCount+=
b:2<a?c.severeCount+=b:c.criticalCount+=b;c.count+=b});c.multiple=1!==c.count;c.insecureArtifactCount=b.insecureArtifactCount;c.multipleComponents=1<c.insecureArtifactCount;return c}function t(b){var c={oldBrain:Insight.util.isNullOrUndefined(b.policyCounts),criticalCount:0,severeCount:0,moderateCount:0};if(c.oldBrain)return c;c.policyComponentCount=b.policyComponentCount;c.multipleComponents=0<c.policyComponentCount;a.each(b.policyCounts,function(a,b){8<=a?c.criticalCount+=b:4<=a?c.severeCount+=
b:1<a&&(c.moderateCount+=b)});c.multipleAlerts=1<c.criticalCount+c.severeCount+c.moderateCount?!0:!1;c.hasPolicyAlerts=0<c.criticalCount+c.severeCount+c.moderateCount?!0:!1;return c}function f(){var b=a("#summary"),c=function(c,e,d){b.empty();b.append(Insight.templates.error.render({message:Insight.util.getErrorMessage(c)}));a("button",b).click(f)};b.html('\x3cdiv class\x3d"alert alert-info"\x3e\x3cstrong\x3eLoading...\x3c/strong\x3e\x3c/div\x3e');a.getJSON("data.json").success(function(d){if(null===
d)c({status:0});else{var f={policy:t(d),sv:g(d),license:p(d)},h=b.is(":visible");b.hide();b.html(v.render(f));HealthCheck.barChart(d.securityCounts,{element:a("#security-chart")[0]});HealthCheck.punchCard(d.securityPunchCard,{element:a("#security-punchcard")[0]});HealthCheck.licenseChart([f.license.criticalCount/f.license.count,f.license.severeCount/f.license.count,f.license.moderateCount/f.license.count,(f.license.count-f.license.licenseAlerts)/f.license.count],{element:a("#license-chart")[0]});
HealthCheck.punchCard(d.licensePunchCard,{element:a("#license-punchcard")[0]});0<d.totalArtifactCount?HealthCheck.artifactsChart(1-d.knownArtifactCount/d.totalArtifactCount,{element:a("#coverage_donut")[0]}):HealthCheck.artifactsChart(0);h&&b.fadeIn();Insight.util.enableTooltip(a("[data-tooltip]",summary))}}).error(c)}function m(b){b=a.extend({dataView:null,items:[],mask:{},callback:a.noop},b);a.isArray(b.items)||(b.items=[b.items]);c(b.dataView,b.items,b.mask,y,"licenses.json",b.callback)}function z(b){b=
a.extend({dataView:null,items:[],mask:{},callback:a.noop},b);a.isArray(b.items)||(b.items=[b.items]);c(b.dataView,b.items,b.mask,u,"security.json",b.callback)}var y=["groupId","artifactId","version"],u=["groupId","artifactId","version","source","reference"],r=["hash","groupId","artifactId","version"],s,C,v,x;a(document).ready(function(){v=Hogan.compile(a("#summaryPageTemplate").html());x=Hogan.compile(a("#errorTemplate").html());s=Hogan.compile(a("#licenseEditorTemplate").html());C=Hogan.compile(a("#svEditorTemplate").html());
a.extend(!0,window,{Insight:{templates:{error:{}}}});Insight.templates.error=x});var w=null,q=!1,A=[];a.extend(!0,window,{InsightDatatable:{addSecurityTableEditor:function(b){var c=b.table,f=c.getColumns(),g=new Slick.BulkEditor({editNode:a("#securityEditor"),editor:new d({width:650,grid:c,cancel:!0,artifacts:[],dataViews:[c.getData()],callback:function(d){Insight.util.isNotNullOrUndefined(d)?b.addError(d):(d=c.getSelectedRows(),InsightDatatable.updateSummary(),1==d.length?b.addSuccess("Updated "+
d.length+" security vulnerability.",60):1<d.length&&b.addSuccess("Updated "+d.length+" security vulnerabilities.",60),a("#securityEditor").slideUp({complete:function(){a(this).empty()},step:function(){b.updateHeight()}}))},cancelCallback:function(c){a("#securityEditor").empty().hide();b.updateHeight()}}),openCallback:function(){b.updateHeight()}}),f=a.merge([g.getColumnDef()],f);f[0].filterable=!1;c.setSelectionModel(new Slick.RowSelectionModel);c.getData().syncGridSelection(c,!0);c.setColumns(f);
c.registerPlugin(g)},addLicenseTableEditor:function(c){var d=c.table,f=d.getColumns(),g=new Slick.BulkEditor({editNode:a("#licenseEditor"),editor:new b({artifacts:[],width:650,cancel:!0,grid:d,dataView:d.getData(),callback:function(b){Insight.util.isNotNullOrUndefined(b)?c.addError(b):(b=d.getSelectedRows(),InsightDatatable.updateSummary(),1==b.length?c.addSuccess("Updated license for "+b.length+" component.",60):1<b.length&&c.addSuccess(d,"license","Updated license for "+b.length+" components.",
60),a("#licenseEditor").slideUp({complete:function(){a(this).empty()},step:function(){c.updateHeight()}}))},cancelCallback:function(b){a("#licenseEditor").empty().hide();c.updateHeight()}}),openCallback:function(){c.updateHeight()}}),f=a.merge([g.getColumnDef()],f);f[0].filterable=!1;d.setSelectionModel(new Slick.RowSelectionModel);d.getData().syncGridSelection(d,!0);d.setColumns(f);d.registerPlugin(g)},populateLicenseCombo:function(b,c,d){a(b).empty();var f=[];a.each(c,function(a,b){f.push(a)});
f.sort(function(a,b){a=a.toUpperCase();b=b.toUpperCase();return a>b?1:a<b?-1:0});a.each(f,function(c,e){var f=a("\x3coption\x3e\x3c/option\x3e").text(e).val(e);e===d&&f.attr("selected","selected");a(b).append(f)})},loadLicenses:h,LicenseEditor:b,SecurityEditor:d,updateLicenses:m,updateSecurity:z,updateBom:function(b){b=a.extend({dataView:null,items:[],mask:{},callback:a.noop},b);a.isArray(b.items)||(b.items=[b.items]);c(b.dataView,b.items,b.mask,r,"bom.json",b.callback)},updateSummary:f}})})(jQuery);
(function(){function a(a,d){this.node=a;this.options=d}(function(){var a=angular.module("PolicyViolations",["CommonServices"]);a.controller("PolicyViolationsController",["$http","$scope","$q","PolicyViolationData","Messages",function(a,b,h,p,g){function t(a){var b={constraintId:a.constraintId,constraintName:a.constraintName,constraintOperator:a.operatorName,conditions:[]};angular.forEach(a.conditionFacts,function(a){b.conditions.push({conditionType:a.conditionTypeId,conditionSummary:a.summary,conditionReason:a.reason})});
return b}function f(a,b){if(b){for(var c=0;c<a.length;c++)if(a[c].actionSummary===b.actionSummary)return;a.push(b)}}function m(a,b){var c=null;$.each(b,function(){if(this.id===a.actionTypeId)return c={actionSummary:this.summary},!1});return c}function z(a){return angular.extend(a,{color:7<a.threatLevel?"red":3<a.threatLevel?"orange":1<a.threatLevel?"yellow":0<a.threatLevel?"darkblue":"blue"})}function y(){b.processedPolicyAlerts.sort(function(a,b){return b.threatLevel-a.threatLevel})}function u(a){b.alerts.push({type:"error",
msg:g.getHttpErrorMessage(a)})}function r(){h.all([a.get(CLM.path+"rest/policy/actionType"),a.get("policyalerts.json")]).then(function(a){var d=a[0].data;a=a[1].data.aaData||[];b.processedPolicyAlerts=[];angular.forEach(a,function(a,g){var h=[];angular.forEach(a.actions,function(a,b){f(h,m(a,d))});angular.forEach(a.trigger.componentFacts,function(d,f){if(d.hash===p.hash){var g=[];angular.forEach(d.constraintFacts,function(a){g.push(t(a))});b.processedPolicyAlerts.push(z({id:a.trigger.policyId,name:a.trigger.policyName,
threatLevel:a.trigger.threatLevel,groupId:d.groupId,artifactId:d.artifactId,version:d.version,hash:d.hash,constraints:g,actions:h}))}})});y()},u)}b.waiveComponent=function(a){$modal.open({templateUrl:"add-waiver-modal-tmpl",controller:"AddWaiverController",backdrop:"static",keyboard:!1,resolve:{policy:function(){return a}}})};b.viewWaivers=function(){$modal.open({templateUrl:"view-waivers-modal-tmpl",controller:"ViewWaiverController",backdrop:"static",keyboard:!1})};b.alerts=[];(function(){a.get("policythreats.json").then(function(a){a.data.version?
(a=a.data.aaData||[],b.processedPolicyAlerts=[],angular.forEach(a,function(a,d){a.hash===p.hash&&angular.forEach(a.activeViolations,function(d,g){var h=[];angular.forEach(d.actions,function(a){f(h,a)});b.processedPolicyAlerts.push(z({id:d.policyId,name:d.policyName,threatLevel:d.policyThreatLevel,groupId:a.groupId,artifactId:a.artifactId,version:a.version,hash:a.hash,constraints:d.constraints,actions:h}))})}),y()):r()},u)})()}]);a.controller("AddWaiverController",["$http","$scope","PolicyViolationData",
"Messages","policy",function(a,b,h,p,g){(function(){b.policy=g;b.component=h;b.waiverLoading=!0;a.get(CLM.path+"rest/policyWaiver/application/"+h.appId+"/applicable/context/"+b.policy.id).success(function(a){function d(a){a.children&&angular.forEach(a.children,function(a){d(a)});b.waiverTargets.push({id:a.id,name:a.name,type:a.type})}b.waiverSelectOwner=a.children&&a.children.length;b.waiverTargets=[];b.waiverLoading=!1;d(a);b.waiver={hash:h.hash,policyId:b.policy.id,ownerId:b.waiverTargets[0].id,
comment:""};b.owner={type:b.waiverTargets[0].type}}).error(function(a,d){b.waiverLoading=!1;b.waiveAssignError=p.getHttpErrorMessage(arguments)})})();b.acceptWaiveComponent=function(){b.waiverSaving=!0;b.waiveAssignError=null;a.post(CLM.path+"rest/policyWaiver/"+b.owner.type+"/"+b.waiver.ownerId,b.waiver).success(function(a){b.waiverSaving=!1;b.$close()}).error(function(a,d,g,h){b.waiverSaving=!1;b.waiveAssignError=p.getHttpErrorMessage(arguments)})}}]);a.controller("ViewWaiverController",["$scope",
"$http","PolicyViolationData","Messages",function(a,b,h,p){function g(b,c,g,h){a.appError=p.getHttpErrorMessage(arguments)}(function(){a.waiversLoading=!0;b.get(CLM.path+"rest/policyWaiver/application/"+h.appId+"/component/"+h.hash).success(function(b){a.waiversLoading=!1;a.waivers=[];angular.forEach(b.waiversByOwner,function(b,c){angular.forEach(b.waivers,function(c,g){c.type=b.ownerType;c.ownerName=b.ownerName;a.waivers.push(c)})})}).error(g)})();a.remove=function(b){a.confirmDelete=b;a.appError=
null};a.removeWaiver=function(){var h=a.confirmDelete;a.confirmDelete=null;a.appError=null;b["delete"](CLM.path+"rest/policyWaiver/"+h.type+"/"+h.ownerId+"/"+h.id).success(function(){a.waivers.splice(a.waivers.indexOf(h),1)}).error(g)}}])})();(function(){a.prototype=new Insight.InformationPanelPlugin({priority:32});a.prototype.isVisible=function(){return!(freemium&&!this.options.sampleData||"unknown"===this.gav.matchState)&&Brain.hasFeature("policy-violations")};a.prototype.create=function(){var a=
(new Date).getTime(),d=$("\x3cdiv ng-include\x3d\"'cip-policy-violations.html'\"\x3e\x3c/div\x3e"),c=this;c.node.empty();d.appendTo(c.node);angular.module("policyViolations"+a,[]).service("PolicyViolationData",function(){return{hash:c.gav.hash,groupId:c.gav.groupId,artifactId:c.gav.artifactId,version:c.gav.version,appId:applicationId}});angular.bootstrap(d[0],["PolicyViolations","policyViolations"+a])};a.prototype.destroy=function(){this.node.empty()};a.prototype.getTitle=function(){return"Policy"};
return a})();Insight.InformationPanelPlugins.push(a);angular.module("CommonServices",[]).service("Messages",function(){return{getHttpErrorMessage:function(a){if(a){if(angular.isArray(a)||"[object Arguments]"===a.toString())a={status:a[1],data:a[0],headers:3<=a.length?a[2]:null};var d="",d=a.headers?a.headers():null;return d=0===a.status||1E3<=a.status?"Unable to reach CLM server":a.data&&(!d||!d["content-type"]||-1===d["content-type"].indexOf("text/html"))?a.data:502===a.status?"Bad Gateway":503===
a.status?"Service Unavailable":504===a.status?"Gateway Timeout":"Error "+a.status}}}})})();